/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LORA_MESH_V1_V1_COMMON_PB_H_INCLUDED
#define PB_LORA_MESH_V1_V1_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Bluetooth connection types */
typedef enum _lora_mesh_v1_BluetoothConnectionType {
    lora_mesh_v1_BluetoothConnectionType_BLUETOOTH_CONNECTION_TYPE_UNSPECIFIED = 0, /* Configuration session */
    lora_mesh_v1_BluetoothConnectionType_BLUETOOTH_CONNECTION_TYPE_CONFIG = 1, /* Configuration session */
    lora_mesh_v1_BluetoothConnectionType_BLUETOOTH_CONNECTION_TYPE_COMMUNICATION = 2 /* Data/communication session */
} lora_mesh_v1_BluetoothConnectionType;

/* Bluetooth configuration command types */
typedef enum _lora_mesh_v1_BluetoothConfigType {
    lora_mesh_v1_BluetoothConfigType_BLUETOOTH_CONFIG_TYPE_UNSPECIFIED = 0, /* Unspecified configuration */
    lora_mesh_v1_BluetoothConfigType_BLUETOOTH_CONFIG_TYPE_SET_PARAMETER = 1, /* Set a configuration parameter */
    lora_mesh_v1_BluetoothConfigType_BLUETOOTH_CONFIG_TYPE_GET_PARAMETER = 2, /* Get a configuration parameter */
    lora_mesh_v1_BluetoothConfigType_BLUETOOTH_CONFIG_TYPE_RESET = 3, /* Reset radio or settings */
    lora_mesh_v1_BluetoothConfigType_BLUETOOTH_CONFIG_TYPE_SAVE = 4, /* Save configuration */
    lora_mesh_v1_BluetoothConfigType_BLUETOOTH_CONFIG_TYPE_LOAD = 5, /* Load configuration */
    lora_mesh_v1_BluetoothConfigType_BLUETOOTH_CONFIG_TYPE_FIRMWARE_UPDATE = 6 /* Initiate firmware update */
} lora_mesh_v1_BluetoothConfigType;

/* Bluetooth data types */
typedef enum _lora_mesh_v1_BluetoothDataType {
    lora_mesh_v1_BluetoothDataType_BLUETOOTH_DATA_TYPE_UNSPECIFIED = 0, /* Unspecified data type */
    lora_mesh_v1_BluetoothDataType_BLUETOOTH_DATA_TYPE_RAW = 1, /* Raw binary data */
    lora_mesh_v1_BluetoothDataType_BLUETOOTH_DATA_TYPE_PROTOBUF = 2, /* Encoded protobuf message */
    lora_mesh_v1_BluetoothDataType_BLUETOOTH_DATA_TYPE_TEXT = 3, /* UTF-8 text */
    lora_mesh_v1_BluetoothDataType_BLUETOOTH_DATA_TYPE_FILE = 4 /* File transfer */
} lora_mesh_v1_BluetoothDataType;

/* Message priority levels */
typedef enum _lora_mesh_v1_MessagePriority {
    lora_mesh_v1_MessagePriority_MESSAGE_PRIORITY_UNSPECIFIED = 0,
    lora_mesh_v1_MessagePriority_MESSAGE_PRIORITY_BEST_EFFORT = 1,
    lora_mesh_v1_MessagePriority_MESSAGE_PRIORITY_LOW = 2,
    lora_mesh_v1_MessagePriority_MESSAGE_PRIORITY_NORMAL = 3,
    lora_mesh_v1_MessagePriority_MESSAGE_PRIORITY_HIGH = 4,
    lora_mesh_v1_MessagePriority_MESSAGE_PRIORITY_CRITICAL = 5
} lora_mesh_v1_MessagePriority;

/* Routing strategy types */
typedef enum _lora_mesh_v1_RoutingStrategy {
    lora_mesh_v1_RoutingStrategy_ROUTING_STRATEGY_UNSPECIFIED = 0,
    lora_mesh_v1_RoutingStrategy_ROUTING_STRATEGY_TOPOLOGY_BASED = 1,
    lora_mesh_v1_RoutingStrategy_ROUTING_STRATEGY_GEOGRAPHIC_BASED = 2,
    lora_mesh_v1_RoutingStrategy_ROUTING_STRATEGY_HYBRID_ROUTING = 3,
    lora_mesh_v1_RoutingStrategy_ROUTING_STRATEGY_MULTICAST_ROUTING = 4,
    lora_mesh_v1_RoutingStrategy_ROUTING_STRATEGY_EMERGENCY_FLOODING = 5
} lora_mesh_v1_RoutingStrategy;

/* Geographic routing modes */
typedef enum _lora_mesh_v1_GeographicRoutingMode {
    lora_mesh_v1_GeographicRoutingMode_GEOGRAPHIC_ROUTING_MODE_UNSPECIFIED = 0,
    lora_mesh_v1_GeographicRoutingMode_GEOGRAPHIC_ROUTING_MODE_GREEDY_FORWARDING = 1,
    lora_mesh_v1_GeographicRoutingMode_GEOGRAPHIC_ROUTING_MODE_PERIMETER_ROUTING = 2,
    lora_mesh_v1_GeographicRoutingMode_GEOGRAPHIC_ROUTING_MODE_PREDICTIVE_ROUTING = 3,
    lora_mesh_v1_GeographicRoutingMode_GEOGRAPHIC_ROUTING_MODE_GEOGRAPHIC_BROADCAST = 4
} lora_mesh_v1_GeographicRoutingMode;

/* Route flags for status indication */
typedef enum _lora_mesh_v1_RouteFlags {
    lora_mesh_v1_RouteFlags_ROUTE_FLAGS_UNSPECIFIED = 0,
    lora_mesh_v1_RouteFlags_ROUTE_FLAGS_ROUTE_VALID = 1,
    lora_mesh_v1_RouteFlags_ROUTE_FLAGS_ROUTE_INVALID = 2,
    lora_mesh_v1_RouteFlags_ROUTE_FLAGS_ROUTE_REPAIRABLE = 3,
    lora_mesh_v1_RouteFlags_ROUTE_FLAGS_REVERSE_ROUTE = 4,
    lora_mesh_v1_RouteFlags_ROUTE_FLAGS_FORWARD_ROUTE = 5,
    lora_mesh_v1_RouteFlags_ROUTE_FLAGS_PROACTIVE_ROUTE = 6,
    lora_mesh_v1_RouteFlags_ROUTE_FLAGS_GEOGRAPHIC_ROUTE = 7
} lora_mesh_v1_RouteFlags;

/* Quality of Service priority levels */
typedef enum _lora_mesh_v1_QoSPriority {
    lora_mesh_v1_QoSPriority_QO_S_PRIORITY_UNSPECIFIED = 0,
    lora_mesh_v1_QoSPriority_QO_S_PRIORITY_QOS_LOW_PRIORITY = 1,
    lora_mesh_v1_QoSPriority_QO_S_PRIORITY_QOS_NORMAL_PRIORITY = 2,
    lora_mesh_v1_QoSPriority_QO_S_PRIORITY_QOS_HIGH_PRIORITY = 3,
    lora_mesh_v1_QoSPriority_QO_S_PRIORITY_QOS_CRITICAL_PRIORITY = 4
} lora_mesh_v1_QoSPriority;

/* Routing protocol types */
typedef enum _lora_mesh_v1_RoutingProtocol {
    lora_mesh_v1_RoutingProtocol_ROUTING_PROTOCOL_UNSPECIFIED = 0,
    lora_mesh_v1_RoutingProtocol_ROUTING_PROTOCOL_AODV = 1, /* Ad hoc On-Demand Distance Vector */
    lora_mesh_v1_RoutingProtocol_ROUTING_PROTOCOL_OLSR = 2, /* Optimized Link State Routing */
    lora_mesh_v1_RoutingProtocol_ROUTING_PROTOCOL_GEOGRAPHIC = 3, /* Geographic/Position-based routing */
    lora_mesh_v1_RoutingProtocol_ROUTING_PROTOCOL_HYBRID = 4, /* Hybrid protocol */
    lora_mesh_v1_RoutingProtocol_ROUTING_PROTOCOL_DSR = 5 /* Dynamic Source Routing */
} lora_mesh_v1_RoutingProtocol;

/* Reliability level requirements */
typedef enum _lora_mesh_v1_ReliabilityLevel {
    lora_mesh_v1_ReliabilityLevel_RELIABILITY_LEVEL_UNSPECIFIED = 0,
    lora_mesh_v1_ReliabilityLevel_RELIABILITY_LEVEL_RELIABILITY_LOW = 1, /* Low reliability requirements */
    lora_mesh_v1_ReliabilityLevel_RELIABILITY_LEVEL_RELIABILITY_MEDIUM = 2, /* Medium reliability */
    lora_mesh_v1_ReliabilityLevel_RELIABILITY_LEVEL_RELIABILITY_HIGH = 3, /* High reliability */
    lora_mesh_v1_ReliabilityLevel_RELIABILITY_LEVEL_RELIABILITY_CRITICAL = 4 /* Critical reliability */
} lora_mesh_v1_ReliabilityLevel;

/* Security levels for message authentication and encryption */
typedef enum _lora_mesh_v1_SecurityLevel {
    lora_mesh_v1_SecurityLevel_SECURITY_LEVEL_UNSPECIFIED = 0, /* No security */
    lora_mesh_v1_SecurityLevel_SECURITY_LEVEL_BASIC = 1, /* Basic authentication */
    lora_mesh_v1_SecurityLevel_SECURITY_LEVEL_STANDARD = 2, /* Standard encryption */
    lora_mesh_v1_SecurityLevel_SECURITY_LEVEL_HIGH_SECURITY = 3, /* High security */
    lora_mesh_v1_SecurityLevel_SECURITY_LEVEL_MILITARY = 4 /* Military-grade security */
} lora_mesh_v1_SecurityLevel;

/* Cryptographic signature algorithms */
typedef enum _lora_mesh_v1_SignatureAlgorithm {
    lora_mesh_v1_SignatureAlgorithm_SIGNATURE_ALGORITHM_UNSPECIFIED = 0,
    lora_mesh_v1_SignatureAlgorithm_SIGNATURE_ALGORITHM_NONE = 1, /* No signature (for debugging/testing) */
    lora_mesh_v1_SignatureAlgorithm_SIGNATURE_ALGORITHM_ED25519 = 2, /* Ed25519 (32-byte keys, 64-byte signatures) */
    lora_mesh_v1_SignatureAlgorithm_SIGNATURE_ALGORITHM_ECDSA_P256 = 3, /* ECDSA P-256 (good balance of security/size) */
    lora_mesh_v1_SignatureAlgorithm_SIGNATURE_ALGORITHM_ECDSA_P384 = 4, /* ECDSA P-384 (higher security) */
    lora_mesh_v1_SignatureAlgorithm_SIGNATURE_ALGORITHM_RSA_2048 = 5, /* RSA-2048 (larger but widely supported) */
    lora_mesh_v1_SignatureAlgorithm_SIGNATURE_ALGORITHM_HMAC_SHA256 = 6 /* HMAC-SHA256 (shared key authentication) */
} lora_mesh_v1_SignatureAlgorithm;

/* Hash algorithms for message integrity */
typedef enum _lora_mesh_v1_HashAlgorithm {
    lora_mesh_v1_HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED = 0,
    lora_mesh_v1_HashAlgorithm_HASH_ALGORITHM_SHA256 = 1, /* SHA-256 (32 bytes) */
    lora_mesh_v1_HashAlgorithm_HASH_ALGORITHM_SHA3_256 = 2, /* SHA3-256 (32 bytes) */
    lora_mesh_v1_HashAlgorithm_HASH_ALGORITHM_BLAKE2B = 3 /* BLAKE2b (configurable size) */
} lora_mesh_v1_HashAlgorithm;

/* Struct definitions */
/* GPS coordinate with timestamp */
typedef struct _lora_mesh_v1_GPSCoordinate {
    double latitude; /* Latitude in decimal degrees */
    double longitude; /* Longitude in decimal degrees */
    float altitude; /* Altitude in meters (optional) */
    uint64_t timestamp; /* Unix timestamp in milliseconds */
    float accuracy; /* GPS accuracy in meters */
    float speed; /* Speed in m/s (optional) */
    float bearing; /* Bearing in degrees (optional) */
} lora_mesh_v1_GPSCoordinate;

/* Node identification and basic info */
typedef struct _lora_mesh_v1_NodeInfo {
    char node_id[16]; /* Unique node identifier */
    bool has_position;
    lora_mesh_v1_GPSCoordinate position; /* Current GPS position */
    uint32_t battery_level; /* Battery level 0-100 */
    int32_t rssi; /* Signal strength (dBm) */
    uint32_t sequence_number; /* Node's sequence number */
    uint64_t last_seen; /* Last communication timestamp */
} lora_mesh_v1_NodeInfo;

/* Link quality metrics */
typedef struct _lora_mesh_v1_LinkQuality {
    float signal_strength; /* Normalized RSSI (0.0-1.0) */
    float packet_loss_rate; /* Packet loss rate (0.0-1.0) */
    float latency_ms; /* Average latency in milliseconds */
    float stability; /* Link stability metric (0.0-1.0) */
    float energy_cost; /* Energy cost factor (0.0-1.0) */
} lora_mesh_v1_LinkQuality;

/* Route quality metrics */
typedef struct _lora_mesh_v1_RouteQualityMetrics {
    float average_rssi; /* Mean signal strength */
    float packet_loss_rate; /* Percentage of lost packets */
    float latency_estimate; /* Expected delivery time */
    float energy_cost; /* Battery consumption estimate */
    float stability_factor; /* Route reliability metric */
} lora_mesh_v1_RouteQualityMetrics;

/* Alternate route information */
typedef struct _lora_mesh_v1_AlternateRoute {
    char next_hop_id[16]; /* Next hop for this alternate path */
    uint32_t hop_count; /* Path length in hops */
    float quality_score; /* Overall path quality rating */
    uint64_t last_used; /* Last time this path was used */
} lora_mesh_v1_AlternateRoute;

/* Neighbor information for link state advertisements */
typedef struct _lora_mesh_v1_NeighborInfo {
    char neighbor_id[16]; /* Neighbor node identifier */
    bool has_link_quality;
    lora_mesh_v1_LinkQuality link_quality; /* Link quality metrics */
    int32_t rssi; /* Signal strength to neighbor */
    float distance_meters; /* Physical distance if known */
} lora_mesh_v1_NeighborInfo;

/* Velocity vector for mobility prediction */
typedef struct _lora_mesh_v1_Velocity {
    float speed; /* Speed in m/s */
    float bearing; /* Direction in degrees (0-360) */
    float acceleration; /* Acceleration in m/s² (optional) */
} lora_mesh_v1_Velocity;

/* Network topology metrics */
typedef struct _lora_mesh_v1_TopologyMetrics {
    float network_density; /* Network density metric */
    float average_path_length; /* Average path length */
    float clustering_coefficient; /* Clustering coefficient */
    uint32_t network_diameter; /* Maximum hop distance */
    uint32_t total_nodes; /* Total nodes in network */
    uint32_t total_links; /* Total links in network */
} lora_mesh_v1_TopologyMetrics;

/* Bluetooth connection request/response */
typedef struct _lora_mesh_v1_BluetoothConnectionRequest {
    char device_name[32]; /* Name of connecting device */
    char device_address[18]; /* Bluetooth MAC address */
    lora_mesh_v1_BluetoothConnectionType connection_type; /* CONFIG or COMMUNICATION */
    char requested_service[32]; /* Service being requested (optional) */
} lora_mesh_v1_BluetoothConnectionRequest;

typedef struct _lora_mesh_v1_BluetoothConnectionResponse {
    bool accepted; /* Whether connection is accepted */
    char reason[64]; /* Reason if rejected */
    pb_callback_t assigned_session_id; /* Session ID for communication */
    pb_callback_t supported_services; /* List of supported services */
} lora_mesh_v1_BluetoothConnectionResponse;

/* Bluetooth configuration command */
typedef struct _lora_mesh_v1_BluetoothConfigCommand {
    lora_mesh_v1_BluetoothConfigType config_type; /* Type of configuration */
    char parameter[32]; /* Parameter name */
    char value[128]; /* Parameter value */
} lora_mesh_v1_BluetoothConfigCommand;

/* Bluetooth configuration response */
typedef struct _lora_mesh_v1_BluetoothConfigResponse {
    bool success; /* Whether config succeeded */
    char message[128]; /* Optional message or error */
} lora_mesh_v1_BluetoothConfigResponse;

typedef PB_BYTES_ARRAY_T(512) lora_mesh_v1_BluetoothDataMessage_payload_t;
/* Bluetooth data message for radio communication */
typedef struct _lora_mesh_v1_BluetoothDataMessage {
    pb_callback_t session_id; /* Session identifier */
    lora_mesh_v1_BluetoothDataMessage_payload_t payload; /* Data payload */
    lora_mesh_v1_BluetoothDataType data_type; /* Type of data (RAW, PROTOBUF, etc.) */
    uint64_t timestamp; /* Timestamp of message */
} lora_mesh_v1_BluetoothDataMessage;

typedef PB_BYTES_ARRAY_T(64) lora_mesh_v1_PublicKey_key_data_t;
/* Public key information for signature verification */
typedef struct _lora_mesh_v1_PublicKey {
    lora_mesh_v1_SignatureAlgorithm algorithm; /* Algorithm this key is for */
    lora_mesh_v1_PublicKey_key_data_t key_data; /* Raw public key bytes */
    char key_id[16]; /* Short key identifier/fingerprint */
    uint64_t creation_time; /* Key creation timestamp */
    uint64_t expiry_time; /* Key expiry (0 = no expiry) */
    char issuer[16]; /* Key issuer/certificate authority */
} lora_mesh_v1_PublicKey;

typedef PB_BYTES_ARRAY_T(64) lora_mesh_v1_CryptographicSignature_signature_data_t;
typedef PB_BYTES_ARRAY_T(32) lora_mesh_v1_CryptographicSignature_message_hash_t;
/* Digital signature structure */
typedef struct _lora_mesh_v1_CryptographicSignature {
    lora_mesh_v1_SignatureAlgorithm algorithm; /* Signature algorithm used */
    lora_mesh_v1_CryptographicSignature_signature_data_t signature_data; /* Raw signature bytes */
    char signer_key_id[16]; /* Key ID used for signing */
    lora_mesh_v1_HashAlgorithm hash_algorithm; /* Hash algorithm used */
    lora_mesh_v1_CryptographicSignature_message_hash_t message_hash; /* Hash of signed data (for verification) */
    uint64_t signature_timestamp; /* When signature was created */
    uint32_t signature_version; /* Signature format version */
} lora_mesh_v1_CryptographicSignature;

/* Key management and trust information */
typedef struct _lora_mesh_v1_KeyMetadata {
    char key_id[16]; /* Unique key identifier */
    char node_id[16]; /* Node this key belongs to */
    lora_mesh_v1_SignatureAlgorithm algorithm; /* Key algorithm */
    uint32_t key_usage_flags; /* Usage permissions (bitfield) */
    uint64_t creation_time; /* Key creation time */
    uint64_t expiry_time; /* Key expiry (0 = no expiry) */
    uint32_t trust_level; /* Trust level (0-100) */
    pb_callback_t issuer_key_id; /* Key that signed this key */
    pb_callback_t revoked_signatures; /* Revoked signature IDs */
} lora_mesh_v1_KeyMetadata;

/* Certificate for public key authentication */
typedef struct _lora_mesh_v1_NodeCertificate {
    char node_id[16]; /* Node identifier */
    bool has_public_key;
    lora_mesh_v1_PublicKey public_key; /* Node's public key */
    pb_callback_t issuer_node_id; /* Certificate issuer */
    uint64_t issued_time; /* Certificate issue time */
    uint64_t expiry_time; /* Certificate expiry */
    uint32_t trust_level; /* Assigned trust level */
    bool has_issuer_signature;
    lora_mesh_v1_CryptographicSignature issuer_signature; /* Issuer's signature on certificate */
    pb_callback_t permissions; /* Granted permissions */
    pb_callback_t certificate_extensions; /* Additional certificate data */
} lora_mesh_v1_NodeCertificate;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _lora_mesh_v1_BluetoothConnectionType_MIN lora_mesh_v1_BluetoothConnectionType_BLUETOOTH_CONNECTION_TYPE_UNSPECIFIED
#define _lora_mesh_v1_BluetoothConnectionType_MAX lora_mesh_v1_BluetoothConnectionType_BLUETOOTH_CONNECTION_TYPE_COMMUNICATION
#define _lora_mesh_v1_BluetoothConnectionType_ARRAYSIZE ((lora_mesh_v1_BluetoothConnectionType)(lora_mesh_v1_BluetoothConnectionType_BLUETOOTH_CONNECTION_TYPE_COMMUNICATION+1))

#define _lora_mesh_v1_BluetoothConfigType_MIN lora_mesh_v1_BluetoothConfigType_BLUETOOTH_CONFIG_TYPE_UNSPECIFIED
#define _lora_mesh_v1_BluetoothConfigType_MAX lora_mesh_v1_BluetoothConfigType_BLUETOOTH_CONFIG_TYPE_FIRMWARE_UPDATE
#define _lora_mesh_v1_BluetoothConfigType_ARRAYSIZE ((lora_mesh_v1_BluetoothConfigType)(lora_mesh_v1_BluetoothConfigType_BLUETOOTH_CONFIG_TYPE_FIRMWARE_UPDATE+1))

#define _lora_mesh_v1_BluetoothDataType_MIN lora_mesh_v1_BluetoothDataType_BLUETOOTH_DATA_TYPE_UNSPECIFIED
#define _lora_mesh_v1_BluetoothDataType_MAX lora_mesh_v1_BluetoothDataType_BLUETOOTH_DATA_TYPE_FILE
#define _lora_mesh_v1_BluetoothDataType_ARRAYSIZE ((lora_mesh_v1_BluetoothDataType)(lora_mesh_v1_BluetoothDataType_BLUETOOTH_DATA_TYPE_FILE+1))

#define _lora_mesh_v1_MessagePriority_MIN lora_mesh_v1_MessagePriority_MESSAGE_PRIORITY_UNSPECIFIED
#define _lora_mesh_v1_MessagePriority_MAX lora_mesh_v1_MessagePriority_MESSAGE_PRIORITY_CRITICAL
#define _lora_mesh_v1_MessagePriority_ARRAYSIZE ((lora_mesh_v1_MessagePriority)(lora_mesh_v1_MessagePriority_MESSAGE_PRIORITY_CRITICAL+1))

#define _lora_mesh_v1_RoutingStrategy_MIN lora_mesh_v1_RoutingStrategy_ROUTING_STRATEGY_UNSPECIFIED
#define _lora_mesh_v1_RoutingStrategy_MAX lora_mesh_v1_RoutingStrategy_ROUTING_STRATEGY_EMERGENCY_FLOODING
#define _lora_mesh_v1_RoutingStrategy_ARRAYSIZE ((lora_mesh_v1_RoutingStrategy)(lora_mesh_v1_RoutingStrategy_ROUTING_STRATEGY_EMERGENCY_FLOODING+1))

#define _lora_mesh_v1_GeographicRoutingMode_MIN lora_mesh_v1_GeographicRoutingMode_GEOGRAPHIC_ROUTING_MODE_UNSPECIFIED
#define _lora_mesh_v1_GeographicRoutingMode_MAX lora_mesh_v1_GeographicRoutingMode_GEOGRAPHIC_ROUTING_MODE_GEOGRAPHIC_BROADCAST
#define _lora_mesh_v1_GeographicRoutingMode_ARRAYSIZE ((lora_mesh_v1_GeographicRoutingMode)(lora_mesh_v1_GeographicRoutingMode_GEOGRAPHIC_ROUTING_MODE_GEOGRAPHIC_BROADCAST+1))

#define _lora_mesh_v1_RouteFlags_MIN lora_mesh_v1_RouteFlags_ROUTE_FLAGS_UNSPECIFIED
#define _lora_mesh_v1_RouteFlags_MAX lora_mesh_v1_RouteFlags_ROUTE_FLAGS_GEOGRAPHIC_ROUTE
#define _lora_mesh_v1_RouteFlags_ARRAYSIZE ((lora_mesh_v1_RouteFlags)(lora_mesh_v1_RouteFlags_ROUTE_FLAGS_GEOGRAPHIC_ROUTE+1))

#define _lora_mesh_v1_QoSPriority_MIN lora_mesh_v1_QoSPriority_QO_S_PRIORITY_UNSPECIFIED
#define _lora_mesh_v1_QoSPriority_MAX lora_mesh_v1_QoSPriority_QO_S_PRIORITY_QOS_CRITICAL_PRIORITY
#define _lora_mesh_v1_QoSPriority_ARRAYSIZE ((lora_mesh_v1_QoSPriority)(lora_mesh_v1_QoSPriority_QO_S_PRIORITY_QOS_CRITICAL_PRIORITY+1))

#define _lora_mesh_v1_RoutingProtocol_MIN lora_mesh_v1_RoutingProtocol_ROUTING_PROTOCOL_UNSPECIFIED
#define _lora_mesh_v1_RoutingProtocol_MAX lora_mesh_v1_RoutingProtocol_ROUTING_PROTOCOL_DSR
#define _lora_mesh_v1_RoutingProtocol_ARRAYSIZE ((lora_mesh_v1_RoutingProtocol)(lora_mesh_v1_RoutingProtocol_ROUTING_PROTOCOL_DSR+1))

#define _lora_mesh_v1_ReliabilityLevel_MIN lora_mesh_v1_ReliabilityLevel_RELIABILITY_LEVEL_UNSPECIFIED
#define _lora_mesh_v1_ReliabilityLevel_MAX lora_mesh_v1_ReliabilityLevel_RELIABILITY_LEVEL_RELIABILITY_CRITICAL
#define _lora_mesh_v1_ReliabilityLevel_ARRAYSIZE ((lora_mesh_v1_ReliabilityLevel)(lora_mesh_v1_ReliabilityLevel_RELIABILITY_LEVEL_RELIABILITY_CRITICAL+1))

#define _lora_mesh_v1_SecurityLevel_MIN lora_mesh_v1_SecurityLevel_SECURITY_LEVEL_UNSPECIFIED
#define _lora_mesh_v1_SecurityLevel_MAX lora_mesh_v1_SecurityLevel_SECURITY_LEVEL_MILITARY
#define _lora_mesh_v1_SecurityLevel_ARRAYSIZE ((lora_mesh_v1_SecurityLevel)(lora_mesh_v1_SecurityLevel_SECURITY_LEVEL_MILITARY+1))

#define _lora_mesh_v1_SignatureAlgorithm_MIN lora_mesh_v1_SignatureAlgorithm_SIGNATURE_ALGORITHM_UNSPECIFIED
#define _lora_mesh_v1_SignatureAlgorithm_MAX lora_mesh_v1_SignatureAlgorithm_SIGNATURE_ALGORITHM_HMAC_SHA256
#define _lora_mesh_v1_SignatureAlgorithm_ARRAYSIZE ((lora_mesh_v1_SignatureAlgorithm)(lora_mesh_v1_SignatureAlgorithm_SIGNATURE_ALGORITHM_HMAC_SHA256+1))

#define _lora_mesh_v1_HashAlgorithm_MIN lora_mesh_v1_HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED
#define _lora_mesh_v1_HashAlgorithm_MAX lora_mesh_v1_HashAlgorithm_HASH_ALGORITHM_BLAKE2B
#define _lora_mesh_v1_HashAlgorithm_ARRAYSIZE ((lora_mesh_v1_HashAlgorithm)(lora_mesh_v1_HashAlgorithm_HASH_ALGORITHM_BLAKE2B+1))









#define lora_mesh_v1_BluetoothConnectionRequest_connection_type_ENUMTYPE lora_mesh_v1_BluetoothConnectionType


#define lora_mesh_v1_BluetoothConfigCommand_config_type_ENUMTYPE lora_mesh_v1_BluetoothConfigType


#define lora_mesh_v1_BluetoothDataMessage_data_type_ENUMTYPE lora_mesh_v1_BluetoothDataType

#define lora_mesh_v1_PublicKey_algorithm_ENUMTYPE lora_mesh_v1_SignatureAlgorithm

#define lora_mesh_v1_CryptographicSignature_algorithm_ENUMTYPE lora_mesh_v1_SignatureAlgorithm
#define lora_mesh_v1_CryptographicSignature_hash_algorithm_ENUMTYPE lora_mesh_v1_HashAlgorithm

#define lora_mesh_v1_KeyMetadata_algorithm_ENUMTYPE lora_mesh_v1_SignatureAlgorithm



/* Initializer values for message structs */
#define lora_mesh_v1_GPSCoordinate_init_default  {0, 0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_NodeInfo_init_default       {"", false, lora_mesh_v1_GPSCoordinate_init_default, 0, 0, 0, 0}
#define lora_mesh_v1_LinkQuality_init_default    {0, 0, 0, 0, 0}
#define lora_mesh_v1_RouteQualityMetrics_init_default {0, 0, 0, 0, 0}
#define lora_mesh_v1_AlternateRoute_init_default {"", 0, 0, 0}
#define lora_mesh_v1_NeighborInfo_init_default   {"", false, lora_mesh_v1_LinkQuality_init_default, 0, 0}
#define lora_mesh_v1_Velocity_init_default       {0, 0, 0}
#define lora_mesh_v1_TopologyMetrics_init_default {0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_BluetoothConnectionRequest_init_default {"", "", _lora_mesh_v1_BluetoothConnectionType_MIN, ""}
#define lora_mesh_v1_BluetoothConnectionResponse_init_default {0, "", {{NULL}, NULL}, {{NULL}, NULL}}
#define lora_mesh_v1_BluetoothConfigCommand_init_default {_lora_mesh_v1_BluetoothConfigType_MIN, "", ""}
#define lora_mesh_v1_BluetoothConfigResponse_init_default {0, ""}
#define lora_mesh_v1_BluetoothDataMessage_init_default {{{NULL}, NULL}, {0, {0}}, _lora_mesh_v1_BluetoothDataType_MIN, 0}
#define lora_mesh_v1_PublicKey_init_default      {_lora_mesh_v1_SignatureAlgorithm_MIN, {0, {0}}, "", 0, 0, ""}
#define lora_mesh_v1_CryptographicSignature_init_default {_lora_mesh_v1_SignatureAlgorithm_MIN, {0, {0}}, "", _lora_mesh_v1_HashAlgorithm_MIN, {0, {0}}, 0, 0}
#define lora_mesh_v1_KeyMetadata_init_default    {"", "", _lora_mesh_v1_SignatureAlgorithm_MIN, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lora_mesh_v1_NodeCertificate_init_default {"", false, lora_mesh_v1_PublicKey_init_default, {{NULL}, NULL}, 0, 0, 0, false, lora_mesh_v1_CryptographicSignature_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define lora_mesh_v1_GPSCoordinate_init_zero     {0, 0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_NodeInfo_init_zero          {"", false, lora_mesh_v1_GPSCoordinate_init_zero, 0, 0, 0, 0}
#define lora_mesh_v1_LinkQuality_init_zero       {0, 0, 0, 0, 0}
#define lora_mesh_v1_RouteQualityMetrics_init_zero {0, 0, 0, 0, 0}
#define lora_mesh_v1_AlternateRoute_init_zero    {"", 0, 0, 0}
#define lora_mesh_v1_NeighborInfo_init_zero      {"", false, lora_mesh_v1_LinkQuality_init_zero, 0, 0}
#define lora_mesh_v1_Velocity_init_zero          {0, 0, 0}
#define lora_mesh_v1_TopologyMetrics_init_zero   {0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_BluetoothConnectionRequest_init_zero {"", "", _lora_mesh_v1_BluetoothConnectionType_MIN, ""}
#define lora_mesh_v1_BluetoothConnectionResponse_init_zero {0, "", {{NULL}, NULL}, {{NULL}, NULL}}
#define lora_mesh_v1_BluetoothConfigCommand_init_zero {_lora_mesh_v1_BluetoothConfigType_MIN, "", ""}
#define lora_mesh_v1_BluetoothConfigResponse_init_zero {0, ""}
#define lora_mesh_v1_BluetoothDataMessage_init_zero {{{NULL}, NULL}, {0, {0}}, _lora_mesh_v1_BluetoothDataType_MIN, 0}
#define lora_mesh_v1_PublicKey_init_zero         {_lora_mesh_v1_SignatureAlgorithm_MIN, {0, {0}}, "", 0, 0, ""}
#define lora_mesh_v1_CryptographicSignature_init_zero {_lora_mesh_v1_SignatureAlgorithm_MIN, {0, {0}}, "", _lora_mesh_v1_HashAlgorithm_MIN, {0, {0}}, 0, 0}
#define lora_mesh_v1_KeyMetadata_init_zero       {"", "", _lora_mesh_v1_SignatureAlgorithm_MIN, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lora_mesh_v1_NodeCertificate_init_zero   {"", false, lora_mesh_v1_PublicKey_init_zero, {{NULL}, NULL}, 0, 0, 0, false, lora_mesh_v1_CryptographicSignature_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define lora_mesh_v1_GPSCoordinate_latitude_tag  1
#define lora_mesh_v1_GPSCoordinate_longitude_tag 2
#define lora_mesh_v1_GPSCoordinate_altitude_tag  3
#define lora_mesh_v1_GPSCoordinate_timestamp_tag 4
#define lora_mesh_v1_GPSCoordinate_accuracy_tag  5
#define lora_mesh_v1_GPSCoordinate_speed_tag     6
#define lora_mesh_v1_GPSCoordinate_bearing_tag   7
#define lora_mesh_v1_NodeInfo_node_id_tag        1
#define lora_mesh_v1_NodeInfo_position_tag       2
#define lora_mesh_v1_NodeInfo_battery_level_tag  3
#define lora_mesh_v1_NodeInfo_rssi_tag           4
#define lora_mesh_v1_NodeInfo_sequence_number_tag 5
#define lora_mesh_v1_NodeInfo_last_seen_tag      6
#define lora_mesh_v1_LinkQuality_signal_strength_tag 1
#define lora_mesh_v1_LinkQuality_packet_loss_rate_tag 2
#define lora_mesh_v1_LinkQuality_latency_ms_tag  3
#define lora_mesh_v1_LinkQuality_stability_tag   4
#define lora_mesh_v1_LinkQuality_energy_cost_tag 5
#define lora_mesh_v1_RouteQualityMetrics_average_rssi_tag 1
#define lora_mesh_v1_RouteQualityMetrics_packet_loss_rate_tag 2
#define lora_mesh_v1_RouteQualityMetrics_latency_estimate_tag 3
#define lora_mesh_v1_RouteQualityMetrics_energy_cost_tag 4
#define lora_mesh_v1_RouteQualityMetrics_stability_factor_tag 5
#define lora_mesh_v1_AlternateRoute_next_hop_id_tag 1
#define lora_mesh_v1_AlternateRoute_hop_count_tag 2
#define lora_mesh_v1_AlternateRoute_quality_score_tag 3
#define lora_mesh_v1_AlternateRoute_last_used_tag 4
#define lora_mesh_v1_NeighborInfo_neighbor_id_tag 1
#define lora_mesh_v1_NeighborInfo_link_quality_tag 2
#define lora_mesh_v1_NeighborInfo_rssi_tag       3
#define lora_mesh_v1_NeighborInfo_distance_meters_tag 4
#define lora_mesh_v1_Velocity_speed_tag          1
#define lora_mesh_v1_Velocity_bearing_tag        2
#define lora_mesh_v1_Velocity_acceleration_tag   3
#define lora_mesh_v1_TopologyMetrics_network_density_tag 1
#define lora_mesh_v1_TopologyMetrics_average_path_length_tag 2
#define lora_mesh_v1_TopologyMetrics_clustering_coefficient_tag 3
#define lora_mesh_v1_TopologyMetrics_network_diameter_tag 4
#define lora_mesh_v1_TopologyMetrics_total_nodes_tag 5
#define lora_mesh_v1_TopologyMetrics_total_links_tag 6
#define lora_mesh_v1_BluetoothConnectionRequest_device_name_tag 1
#define lora_mesh_v1_BluetoothConnectionRequest_device_address_tag 2
#define lora_mesh_v1_BluetoothConnectionRequest_connection_type_tag 3
#define lora_mesh_v1_BluetoothConnectionRequest_requested_service_tag 4
#define lora_mesh_v1_BluetoothConnectionResponse_accepted_tag 1
#define lora_mesh_v1_BluetoothConnectionResponse_reason_tag 2
#define lora_mesh_v1_BluetoothConnectionResponse_assigned_session_id_tag 3
#define lora_mesh_v1_BluetoothConnectionResponse_supported_services_tag 4
#define lora_mesh_v1_BluetoothConfigCommand_config_type_tag 1
#define lora_mesh_v1_BluetoothConfigCommand_parameter_tag 2
#define lora_mesh_v1_BluetoothConfigCommand_value_tag 3
#define lora_mesh_v1_BluetoothConfigResponse_success_tag 1
#define lora_mesh_v1_BluetoothConfigResponse_message_tag 2
#define lora_mesh_v1_BluetoothDataMessage_session_id_tag 1
#define lora_mesh_v1_BluetoothDataMessage_payload_tag 2
#define lora_mesh_v1_BluetoothDataMessage_data_type_tag 3
#define lora_mesh_v1_BluetoothDataMessage_timestamp_tag 4
#define lora_mesh_v1_PublicKey_algorithm_tag     1
#define lora_mesh_v1_PublicKey_key_data_tag      2
#define lora_mesh_v1_PublicKey_key_id_tag        3
#define lora_mesh_v1_PublicKey_creation_time_tag 4
#define lora_mesh_v1_PublicKey_expiry_time_tag   5
#define lora_mesh_v1_PublicKey_issuer_tag        6
#define lora_mesh_v1_CryptographicSignature_algorithm_tag 1
#define lora_mesh_v1_CryptographicSignature_signature_data_tag 2
#define lora_mesh_v1_CryptographicSignature_signer_key_id_tag 3
#define lora_mesh_v1_CryptographicSignature_hash_algorithm_tag 4
#define lora_mesh_v1_CryptographicSignature_message_hash_tag 5
#define lora_mesh_v1_CryptographicSignature_signature_timestamp_tag 6
#define lora_mesh_v1_CryptographicSignature_signature_version_tag 7
#define lora_mesh_v1_KeyMetadata_key_id_tag      1
#define lora_mesh_v1_KeyMetadata_node_id_tag     2
#define lora_mesh_v1_KeyMetadata_algorithm_tag   3
#define lora_mesh_v1_KeyMetadata_key_usage_flags_tag 4
#define lora_mesh_v1_KeyMetadata_creation_time_tag 5
#define lora_mesh_v1_KeyMetadata_expiry_time_tag 6
#define lora_mesh_v1_KeyMetadata_trust_level_tag 7
#define lora_mesh_v1_KeyMetadata_issuer_key_id_tag 8
#define lora_mesh_v1_KeyMetadata_revoked_signatures_tag 9
#define lora_mesh_v1_NodeCertificate_node_id_tag 1
#define lora_mesh_v1_NodeCertificate_public_key_tag 2
#define lora_mesh_v1_NodeCertificate_issuer_node_id_tag 3
#define lora_mesh_v1_NodeCertificate_issued_time_tag 4
#define lora_mesh_v1_NodeCertificate_expiry_time_tag 5
#define lora_mesh_v1_NodeCertificate_trust_level_tag 6
#define lora_mesh_v1_NodeCertificate_issuer_signature_tag 7
#define lora_mesh_v1_NodeCertificate_permissions_tag 8
#define lora_mesh_v1_NodeCertificate_certificate_extensions_tag 9

/* Struct field encoding specification for nanopb */
#define lora_mesh_v1_GPSCoordinate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          1) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude,          3) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         4) \
X(a, STATIC,   SINGULAR, FLOAT,    accuracy,          5) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             6) \
X(a, STATIC,   SINGULAR, FLOAT,    bearing,           7)
#define lora_mesh_v1_GPSCoordinate_CALLBACK NULL
#define lora_mesh_v1_GPSCoordinate_DEFAULT NULL

#define lora_mesh_v1_NodeInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2) \
X(a, STATIC,   SINGULAR, UINT32,   battery_level,     3) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              4) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,   5) \
X(a, STATIC,   SINGULAR, UINT64,   last_seen,         6)
#define lora_mesh_v1_NodeInfo_CALLBACK NULL
#define lora_mesh_v1_NodeInfo_DEFAULT NULL
#define lora_mesh_v1_NodeInfo_position_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_LinkQuality_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    signal_strength,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    packet_loss_rate,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    latency_ms,        3) \
X(a, STATIC,   SINGULAR, FLOAT,    stability,         4) \
X(a, STATIC,   SINGULAR, FLOAT,    energy_cost,       5)
#define lora_mesh_v1_LinkQuality_CALLBACK NULL
#define lora_mesh_v1_LinkQuality_DEFAULT NULL

#define lora_mesh_v1_RouteQualityMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    average_rssi,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    packet_loss_rate,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    latency_estimate,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    energy_cost,       4) \
X(a, STATIC,   SINGULAR, FLOAT,    stability_factor,   5)
#define lora_mesh_v1_RouteQualityMetrics_CALLBACK NULL
#define lora_mesh_v1_RouteQualityMetrics_DEFAULT NULL

#define lora_mesh_v1_AlternateRoute_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   next_hop_id,       1) \
X(a, STATIC,   SINGULAR, UINT32,   hop_count,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    quality_score,     3) \
X(a, STATIC,   SINGULAR, UINT64,   last_used,         4)
#define lora_mesh_v1_AlternateRoute_CALLBACK NULL
#define lora_mesh_v1_AlternateRoute_DEFAULT NULL

#define lora_mesh_v1_NeighborInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   neighbor_id,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  link_quality,      2) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              3) \
X(a, STATIC,   SINGULAR, FLOAT,    distance_meters,   4)
#define lora_mesh_v1_NeighborInfo_CALLBACK NULL
#define lora_mesh_v1_NeighborInfo_DEFAULT NULL
#define lora_mesh_v1_NeighborInfo_link_quality_MSGTYPE lora_mesh_v1_LinkQuality

#define lora_mesh_v1_Velocity_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    bearing,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    acceleration,      3)
#define lora_mesh_v1_Velocity_CALLBACK NULL
#define lora_mesh_v1_Velocity_DEFAULT NULL

#define lora_mesh_v1_TopologyMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    network_density,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    average_path_length,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    clustering_coefficient,   3) \
X(a, STATIC,   SINGULAR, UINT32,   network_diameter,   4) \
X(a, STATIC,   SINGULAR, UINT32,   total_nodes,       5) \
X(a, STATIC,   SINGULAR, UINT32,   total_links,       6)
#define lora_mesh_v1_TopologyMetrics_CALLBACK NULL
#define lora_mesh_v1_TopologyMetrics_DEFAULT NULL

#define lora_mesh_v1_BluetoothConnectionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_name,       1) \
X(a, STATIC,   SINGULAR, STRING,   device_address,    2) \
X(a, STATIC,   SINGULAR, UENUM,    connection_type,   3) \
X(a, STATIC,   SINGULAR, STRING,   requested_service,   4)
#define lora_mesh_v1_BluetoothConnectionRequest_CALLBACK NULL
#define lora_mesh_v1_BluetoothConnectionRequest_DEFAULT NULL

#define lora_mesh_v1_BluetoothConnectionResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     accepted,          1) \
X(a, STATIC,   SINGULAR, STRING,   reason,            2) \
X(a, CALLBACK, SINGULAR, STRING,   assigned_session_id,   3) \
X(a, CALLBACK, REPEATED, STRING,   supported_services,   4)
#define lora_mesh_v1_BluetoothConnectionResponse_CALLBACK pb_default_field_callback
#define lora_mesh_v1_BluetoothConnectionResponse_DEFAULT NULL

#define lora_mesh_v1_BluetoothConfigCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    config_type,       1) \
X(a, STATIC,   SINGULAR, STRING,   parameter,         2) \
X(a, STATIC,   SINGULAR, STRING,   value,             3)
#define lora_mesh_v1_BluetoothConfigCommand_CALLBACK NULL
#define lora_mesh_v1_BluetoothConfigCommand_DEFAULT NULL

#define lora_mesh_v1_BluetoothConfigResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define lora_mesh_v1_BluetoothConfigResponse_CALLBACK NULL
#define lora_mesh_v1_BluetoothConfigResponse_DEFAULT NULL

#define lora_mesh_v1_BluetoothDataMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        1) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           2) \
X(a, STATIC,   SINGULAR, UENUM,    data_type,         3) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         4)
#define lora_mesh_v1_BluetoothDataMessage_CALLBACK pb_default_field_callback
#define lora_mesh_v1_BluetoothDataMessage_DEFAULT NULL

#define lora_mesh_v1_PublicKey_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    algorithm,         1) \
X(a, STATIC,   SINGULAR, BYTES,    key_data,          2) \
X(a, STATIC,   SINGULAR, STRING,   key_id,            3) \
X(a, STATIC,   SINGULAR, UINT64,   creation_time,     4) \
X(a, STATIC,   SINGULAR, UINT64,   expiry_time,       5) \
X(a, STATIC,   SINGULAR, STRING,   issuer,            6)
#define lora_mesh_v1_PublicKey_CALLBACK NULL
#define lora_mesh_v1_PublicKey_DEFAULT NULL

#define lora_mesh_v1_CryptographicSignature_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    algorithm,         1) \
X(a, STATIC,   SINGULAR, BYTES,    signature_data,    2) \
X(a, STATIC,   SINGULAR, STRING,   signer_key_id,     3) \
X(a, STATIC,   SINGULAR, UENUM,    hash_algorithm,    4) \
X(a, STATIC,   SINGULAR, BYTES,    message_hash,      5) \
X(a, STATIC,   SINGULAR, UINT64,   signature_timestamp,   6) \
X(a, STATIC,   SINGULAR, UINT32,   signature_version,   7)
#define lora_mesh_v1_CryptographicSignature_CALLBACK NULL
#define lora_mesh_v1_CryptographicSignature_DEFAULT NULL

#define lora_mesh_v1_KeyMetadata_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key_id,            1) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           2) \
X(a, STATIC,   SINGULAR, UENUM,    algorithm,         3) \
X(a, STATIC,   SINGULAR, UINT32,   key_usage_flags,   4) \
X(a, STATIC,   SINGULAR, UINT64,   creation_time,     5) \
X(a, STATIC,   SINGULAR, UINT64,   expiry_time,       6) \
X(a, STATIC,   SINGULAR, UINT32,   trust_level,       7) \
X(a, CALLBACK, SINGULAR, STRING,   issuer_key_id,     8) \
X(a, CALLBACK, REPEATED, STRING,   revoked_signatures,   9)
#define lora_mesh_v1_KeyMetadata_CALLBACK pb_default_field_callback
#define lora_mesh_v1_KeyMetadata_DEFAULT NULL

#define lora_mesh_v1_NodeCertificate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  public_key,        2) \
X(a, CALLBACK, SINGULAR, STRING,   issuer_node_id,    3) \
X(a, STATIC,   SINGULAR, UINT64,   issued_time,       4) \
X(a, STATIC,   SINGULAR, UINT64,   expiry_time,       5) \
X(a, STATIC,   SINGULAR, UINT32,   trust_level,       6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  issuer_signature,   7) \
X(a, CALLBACK, REPEATED, STRING,   permissions,       8) \
X(a, CALLBACK, SINGULAR, BYTES,    certificate_extensions,   9)
#define lora_mesh_v1_NodeCertificate_CALLBACK pb_default_field_callback
#define lora_mesh_v1_NodeCertificate_DEFAULT NULL
#define lora_mesh_v1_NodeCertificate_public_key_MSGTYPE lora_mesh_v1_PublicKey
#define lora_mesh_v1_NodeCertificate_issuer_signature_MSGTYPE lora_mesh_v1_CryptographicSignature

extern const pb_msgdesc_t lora_mesh_v1_GPSCoordinate_msg;
extern const pb_msgdesc_t lora_mesh_v1_NodeInfo_msg;
extern const pb_msgdesc_t lora_mesh_v1_LinkQuality_msg;
extern const pb_msgdesc_t lora_mesh_v1_RouteQualityMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_AlternateRoute_msg;
extern const pb_msgdesc_t lora_mesh_v1_NeighborInfo_msg;
extern const pb_msgdesc_t lora_mesh_v1_Velocity_msg;
extern const pb_msgdesc_t lora_mesh_v1_TopologyMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_BluetoothConnectionRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_BluetoothConnectionResponse_msg;
extern const pb_msgdesc_t lora_mesh_v1_BluetoothConfigCommand_msg;
extern const pb_msgdesc_t lora_mesh_v1_BluetoothConfigResponse_msg;
extern const pb_msgdesc_t lora_mesh_v1_BluetoothDataMessage_msg;
extern const pb_msgdesc_t lora_mesh_v1_PublicKey_msg;
extern const pb_msgdesc_t lora_mesh_v1_CryptographicSignature_msg;
extern const pb_msgdesc_t lora_mesh_v1_KeyMetadata_msg;
extern const pb_msgdesc_t lora_mesh_v1_NodeCertificate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lora_mesh_v1_GPSCoordinate_fields &lora_mesh_v1_GPSCoordinate_msg
#define lora_mesh_v1_NodeInfo_fields &lora_mesh_v1_NodeInfo_msg
#define lora_mesh_v1_LinkQuality_fields &lora_mesh_v1_LinkQuality_msg
#define lora_mesh_v1_RouteQualityMetrics_fields &lora_mesh_v1_RouteQualityMetrics_msg
#define lora_mesh_v1_AlternateRoute_fields &lora_mesh_v1_AlternateRoute_msg
#define lora_mesh_v1_NeighborInfo_fields &lora_mesh_v1_NeighborInfo_msg
#define lora_mesh_v1_Velocity_fields &lora_mesh_v1_Velocity_msg
#define lora_mesh_v1_TopologyMetrics_fields &lora_mesh_v1_TopologyMetrics_msg
#define lora_mesh_v1_BluetoothConnectionRequest_fields &lora_mesh_v1_BluetoothConnectionRequest_msg
#define lora_mesh_v1_BluetoothConnectionResponse_fields &lora_mesh_v1_BluetoothConnectionResponse_msg
#define lora_mesh_v1_BluetoothConfigCommand_fields &lora_mesh_v1_BluetoothConfigCommand_msg
#define lora_mesh_v1_BluetoothConfigResponse_fields &lora_mesh_v1_BluetoothConfigResponse_msg
#define lora_mesh_v1_BluetoothDataMessage_fields &lora_mesh_v1_BluetoothDataMessage_msg
#define lora_mesh_v1_PublicKey_fields &lora_mesh_v1_PublicKey_msg
#define lora_mesh_v1_CryptographicSignature_fields &lora_mesh_v1_CryptographicSignature_msg
#define lora_mesh_v1_KeyMetadata_fields &lora_mesh_v1_KeyMetadata_msg
#define lora_mesh_v1_NodeCertificate_fields &lora_mesh_v1_NodeCertificate_msg

/* Maximum encoded size of messages (where known) */
/* lora_mesh_v1_BluetoothConnectionResponse_size depends on runtime parameters */
/* lora_mesh_v1_BluetoothDataMessage_size depends on runtime parameters */
/* lora_mesh_v1_KeyMetadata_size depends on runtime parameters */
/* lora_mesh_v1_NodeCertificate_size depends on runtime parameters */
#define LORA_MESH_V1_V1_COMMON_PB_H_MAX_SIZE     lora_mesh_v1_BluetoothConfigCommand_size
#define lora_mesh_v1_AlternateRoute_size         39
#define lora_mesh_v1_BluetoothConfigCommand_size 165
#define lora_mesh_v1_BluetoothConfigResponse_size 132
#define lora_mesh_v1_BluetoothConnectionRequest_size 87
#define lora_mesh_v1_CryptographicSignature_size 138
#define lora_mesh_v1_GPSCoordinate_size          49
#define lora_mesh_v1_LinkQuality_size            25
#define lora_mesh_v1_NeighborInfo_size           60
#define lora_mesh_v1_NodeInfo_size               102
#define lora_mesh_v1_PublicKey_size              124
#define lora_mesh_v1_RouteQualityMetrics_size    25
#define lora_mesh_v1_TopologyMetrics_size        33
#define lora_mesh_v1_Velocity_size               15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
