/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "v1/common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(lora_mesh_v1_GPSCoordinate, lora_mesh_v1_GPSCoordinate, AUTO)


PB_BIND(lora_mesh_v1_NodeInfo, lora_mesh_v1_NodeInfo, AUTO)


PB_BIND(lora_mesh_v1_LinkQuality, lora_mesh_v1_LinkQuality, AUTO)


PB_BIND(lora_mesh_v1_RouteQualityMetrics, lora_mesh_v1_RouteQualityMetrics, AUTO)


PB_BIND(lora_mesh_v1_AlternateRoute, lora_mesh_v1_AlternateRoute, AUTO)


PB_BIND(lora_mesh_v1_NeighborInfo, lora_mesh_v1_NeighborInfo, AUTO)


PB_BIND(lora_mesh_v1_Velocity, lora_mesh_v1_Velocity, AUTO)


PB_BIND(lora_mesh_v1_TopologyMetrics, lora_mesh_v1_TopologyMetrics, AUTO)


PB_BIND(lora_mesh_v1_BluetoothConnectionRequest, lora_mesh_v1_BluetoothConnectionRequest, AUTO)


PB_BIND(lora_mesh_v1_BluetoothConnectionResponse, lora_mesh_v1_BluetoothConnectionResponse, AUTO)


PB_BIND(lora_mesh_v1_BluetoothConfigCommand, lora_mesh_v1_BluetoothConfigCommand, AUTO)


PB_BIND(lora_mesh_v1_BluetoothConfigResponse, lora_mesh_v1_BluetoothConfigResponse, AUTO)


PB_BIND(lora_mesh_v1_BluetoothDataMessage, lora_mesh_v1_BluetoothDataMessage, 2)


PB_BIND(lora_mesh_v1_PublicKey, lora_mesh_v1_PublicKey, AUTO)


PB_BIND(lora_mesh_v1_CryptographicSignature, lora_mesh_v1_CryptographicSignature, AUTO)


PB_BIND(lora_mesh_v1_KeyMetadata, lora_mesh_v1_KeyMetadata, AUTO)


PB_BIND(lora_mesh_v1_NodeCertificate, lora_mesh_v1_NodeCertificate, 2)





























#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

