/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "v1/config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(lora_mesh_v1_MeshNetworkConfig, lora_mesh_v1_MeshNetworkConfig, 2)


PB_BIND(lora_mesh_v1_CryptoConfig, lora_mesh_v1_CryptoConfig, AUTO)


PB_BIND(lora_mesh_v1_KeyRotationPolicy, lora_mesh_v1_KeyRotationPolicy, AUTO)


PB_BIND(lora_mesh_v1_TopologyConfig, lora_mesh_v1_TopologyConfig, AUTO)


PB_BIND(lora_mesh_v1_RedundancyConfig, lora_mesh_v1_RedundancyConfig, AUTO)


PB_BIND(lora_mesh_v1_RoutingConfig, lora_mesh_v1_RoutingConfig, AUTO)


PB_BIND(lora_mesh_v1_ProtocolSwitchingPolicy, lora_mesh_v1_ProtocolSwitchingPolicy, AUTO)


PB_BIND(lora_mesh_v1_RouteMaintenanceConfig, lora_mesh_v1_RouteMaintenanceConfig, AUTO)


PB_BIND(lora_mesh_v1_PerformanceConfig, lora_mesh_v1_PerformanceConfig, AUTO)


PB_BIND(lora_mesh_v1_CompressionConfig, lora_mesh_v1_CompressionConfig, AUTO)


PB_BIND(lora_mesh_v1_QoSConfig, lora_mesh_v1_QoSConfig, 2)


PB_BIND(lora_mesh_v1_ServiceClass, lora_mesh_v1_ServiceClass, AUTO)


PB_BIND(lora_mesh_v1_BandwidthAllocation, lora_mesh_v1_BandwidthAllocation, AUTO)


PB_BIND(lora_mesh_v1_LatencyRequirements, lora_mesh_v1_LatencyRequirements, AUTO)


PB_BIND(lora_mesh_v1_ReliabilityRequirements, lora_mesh_v1_ReliabilityRequirements, AUTO)


PB_BIND(lora_mesh_v1_PriorityScheduling, lora_mesh_v1_PriorityScheduling, AUTO)


PB_BIND(lora_mesh_v1_QueueConfig, lora_mesh_v1_QueueConfig, AUTO)


PB_BIND(lora_mesh_v1_TrafficShaping, lora_mesh_v1_TrafficShaping, AUTO)


PB_BIND(lora_mesh_v1_ShaperConfig, lora_mesh_v1_ShaperConfig, AUTO)


PB_BIND(lora_mesh_v1_TokenBucketConfig, lora_mesh_v1_TokenBucketConfig, AUTO)


PB_BIND(lora_mesh_v1_PoliceConfig, lora_mesh_v1_PoliceConfig, AUTO)


PB_BIND(lora_mesh_v1_AdmissionControl, lora_mesh_v1_AdmissionControl, AUTO)


PB_BIND(lora_mesh_v1_ResourceReservation, lora_mesh_v1_ResourceReservation, AUTO)



































