/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LORA_MESH_V1_V1_CONFIG_PB_H_INCLUDED
#define PB_LORA_MESH_V1_V1_CONFIG_PB_H_INCLUDED
#include <pb.h>
#include "v1/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _lora_mesh_v1_EncryptionAlgorithm {
    lora_mesh_v1_EncryptionAlgorithm_ENCRYPTION_ALGORITHM_UNSPECIFIED = 0, /* No encryption */
    lora_mesh_v1_EncryptionAlgorithm_ENCRYPTION_ALGORITHM_AES_128 = 1, /* AES 128-bit */
    lora_mesh_v1_EncryptionAlgorithm_ENCRYPTION_ALGORITHM_AES_256 = 2, /* AES 256-bit */
    lora_mesh_v1_EncryptionAlgorithm_ENCRYPTION_ALGORITHM_CHACHA20 = 3, /* ChaCha20 */
    lora_mesh_v1_EncryptionAlgorithm_ENCRYPTION_ALGORITHM_SALSA20 = 4 /* Salsa20 */
} lora_mesh_v1_EncryptionAlgorithm;

typedef enum _lora_mesh_v1_AuthenticationMethod {
    lora_mesh_v1_AuthenticationMethod_AUTHENTICATION_METHOD_UNSPECIFIED = 0, /* No authentication */
    lora_mesh_v1_AuthenticationMethod_AUTHENTICATION_METHOD_PRE_SHARED_KEY = 1, /* Pre-shared key */
    lora_mesh_v1_AuthenticationMethod_AUTHENTICATION_METHOD_CERTIFICATE = 2, /* Certificate-based */
    lora_mesh_v1_AuthenticationMethod_AUTHENTICATION_METHOD_BIOMETRIC = 3 /* Biometric authentication */
} lora_mesh_v1_AuthenticationMethod;

typedef enum _lora_mesh_v1_TopologyType {
    lora_mesh_v1_TopologyType_TOPOLOGY_TYPE_UNSPECIFIED = 0, /* No topology specified */
    lora_mesh_v1_TopologyType_TOPOLOGY_TYPE_MESH = 1, /* Full mesh */
    lora_mesh_v1_TopologyType_TOPOLOGY_TYPE_STAR = 2, /* Star topology */
    lora_mesh_v1_TopologyType_TOPOLOGY_TYPE_TREE = 3, /* Tree topology */
    lora_mesh_v1_TopologyType_TOPOLOGY_TYPE_HYBRID_TOPOLOGY = 4 /* Hybrid topology */
} lora_mesh_v1_TopologyType;

typedef enum _lora_mesh_v1_BackupStrategy {
    lora_mesh_v1_BackupStrategy_BACKUP_STRATEGY_UNSPECIFIED = 0, /* No strategy specified */
    lora_mesh_v1_BackupStrategy_BACKUP_STRATEGY_PROACTIVE = 1, /* Proactive backup paths */
    lora_mesh_v1_BackupStrategy_BACKUP_STRATEGY_REACTIVE = 2, /* Reactive backup creation */
    lora_mesh_v1_BackupStrategy_BACKUP_STRATEGY_HYBRID_BACKUP = 3 /* Hybrid approach */
} lora_mesh_v1_BackupStrategy;

typedef enum _lora_mesh_v1_SwitchingTrigger {
    lora_mesh_v1_SwitchingTrigger_SWITCHING_TRIGGER_UNSPECIFIED = 0, /* No trigger specified */
    lora_mesh_v1_SwitchingTrigger_SWITCHING_TRIGGER_LOAD_BASED = 1, /* Load-triggered switching */
    lora_mesh_v1_SwitchingTrigger_SWITCHING_TRIGGER_MOBILITY_BASED = 2, /* Mobility-triggered switching */
    lora_mesh_v1_SwitchingTrigger_SWITCHING_TRIGGER_QOS_BASED = 3, /* QoS-triggered switching */
    lora_mesh_v1_SwitchingTrigger_SWITCHING_TRIGGER_MANUAL = 4 /* Manual switching */
} lora_mesh_v1_SwitchingTrigger;

typedef enum _lora_mesh_v1_PowerManagementMode {
    lora_mesh_v1_PowerManagementMode_POWER_MANAGEMENT_MODE_UNSPECIFIED = 0, /* No mode specified */
    lora_mesh_v1_PowerManagementMode_POWER_MANAGEMENT_MODE_ALWAYS_ON = 1, /* Always powered */
    lora_mesh_v1_PowerManagementMode_POWER_MANAGEMENT_MODE_DUTY_CYCLE = 2, /* Duty cycling */
    lora_mesh_v1_PowerManagementMode_POWER_MANAGEMENT_MODE_ADAPTIVE_POWER = 3, /* Adaptive power management */
    lora_mesh_v1_PowerManagementMode_POWER_MANAGEMENT_MODE_ULTRA_LOW_POWER = 4 /* Ultra-low power mode */
} lora_mesh_v1_PowerManagementMode;

typedef enum _lora_mesh_v1_CompressionAlgorithm {
    lora_mesh_v1_CompressionAlgorithm_COMPRESSION_ALGORITHM_UNSPECIFIED = 0, /* No compression */
    lora_mesh_v1_CompressionAlgorithm_COMPRESSION_ALGORITHM_LZ4 = 1, /* LZ4 compression */
    lora_mesh_v1_CompressionAlgorithm_COMPRESSION_ALGORITHM_ZLIB = 2, /* Zlib compression */
    lora_mesh_v1_CompressionAlgorithm_COMPRESSION_ALGORITHM_BROTLI = 3 /* Brotli compression */
} lora_mesh_v1_CompressionAlgorithm;

typedef enum _lora_mesh_v1_CompressionLevel {
    lora_mesh_v1_CompressionLevel_COMPRESSION_LEVEL_UNSPECIFIED = 0, /* No compression level specified */
    lora_mesh_v1_CompressionLevel_COMPRESSION_LEVEL_LOW_COMPRESSION = 1, /* Low compression */
    lora_mesh_v1_CompressionLevel_COMPRESSION_LEVEL_MEDIUM_COMPRESSION = 2, /* Medium compression */
    lora_mesh_v1_CompressionLevel_COMPRESSION_LEVEL_HIGH_COMPRESSION = 3, /* High compression */
    lora_mesh_v1_CompressionLevel_COMPRESSION_LEVEL_MAX_COMPRESSION = 4 /* Maximum compression */
} lora_mesh_v1_CompressionLevel;

typedef enum _lora_mesh_v1_SchedulingAlgorithm {
    lora_mesh_v1_SchedulingAlgorithm_SCHEDULING_ALGORITHM_UNSPECIFIED = 0, /* No algorithm specified */
    lora_mesh_v1_SchedulingAlgorithm_SCHEDULING_ALGORITHM_STRICT_PRIORITY = 1, /* Strict priority scheduling */
    lora_mesh_v1_SchedulingAlgorithm_SCHEDULING_ALGORITHM_WEIGHTED_FAIR_QUEUE = 2, /* Weighted fair queuing */
    lora_mesh_v1_SchedulingAlgorithm_SCHEDULING_ALGORITHM_DEFICIT_ROUND_ROBIN = 3, /* Deficit round robin */
    lora_mesh_v1_SchedulingAlgorithm_SCHEDULING_ALGORITHM_CLASS_BASED_QUEUE = 4 /* Class-based queuing */
} lora_mesh_v1_SchedulingAlgorithm;

typedef enum _lora_mesh_v1_QueueDiscipline {
    lora_mesh_v1_QueueDiscipline_QUEUE_DISCIPLINE_UNSPECIFIED = 0, /* No discipline specified */
    lora_mesh_v1_QueueDiscipline_QUEUE_DISCIPLINE_FIFO = 1, /* First in, first out */
    lora_mesh_v1_QueueDiscipline_QUEUE_DISCIPLINE_LIFO = 2, /* Last in, first out */
    lora_mesh_v1_QueueDiscipline_QUEUE_DISCIPLINE_RANDOM = 3, /* Random selection */
    lora_mesh_v1_QueueDiscipline_QUEUE_DISCIPLINE_PRIORITY_QUEUE = 4 /* Priority-based */
} lora_mesh_v1_QueueDiscipline;

typedef enum _lora_mesh_v1_DropPolicy {
    lora_mesh_v1_DropPolicy_DROP_POLICY_UNSPECIFIED = 0, /* No policy specified */
    lora_mesh_v1_DropPolicy_DROP_POLICY_TAIL_DROP = 1, /* Drop from tail */
    lora_mesh_v1_DropPolicy_DROP_POLICY_HEAD_DROP = 2, /* Drop from head */
    lora_mesh_v1_DropPolicy_DROP_POLICY_RANDOM_DROP = 3, /* Random drop */
    lora_mesh_v1_DropPolicy_DROP_POLICY_PRIORITY_DROP = 4 /* Priority-based drop */
} lora_mesh_v1_DropPolicy;

typedef enum _lora_mesh_v1_PreemptionPolicy {
    lora_mesh_v1_PreemptionPolicy_PREEMPTION_POLICY_UNSPECIFIED = 0, /* No preemption specified */
    lora_mesh_v1_PreemptionPolicy_PREEMPTION_POLICY_NO_PREEMPTION = 1, /* No preemption */
    lora_mesh_v1_PreemptionPolicy_PREEMPTION_POLICY_PRIORITY_PREEMPTION = 2, /* Priority-based preemption */
    lora_mesh_v1_PreemptionPolicy_PREEMPTION_POLICY_DEADLINE_PREEMPTION = 3 /* Deadline-based preemption */
} lora_mesh_v1_PreemptionPolicy;

typedef enum _lora_mesh_v1_FairnessPolicy {
    lora_mesh_v1_FairnessPolicy_FAIRNESS_POLICY_UNSPECIFIED = 0, /* No fairness policy specified */
    lora_mesh_v1_FairnessPolicy_FAIRNESS_POLICY_STRICT_FAIRNESS = 1, /* Strict fairness */
    lora_mesh_v1_FairnessPolicy_FAIRNESS_POLICY_PROPORTIONAL_FAIR = 2, /* Proportional fairness */
    lora_mesh_v1_FairnessPolicy_FAIRNESS_POLICY_MAX_MIN_FAIR = 3 /* Max-min fairness */
} lora_mesh_v1_FairnessPolicy;

typedef enum _lora_mesh_v1_PoliceAction {
    lora_mesh_v1_PoliceAction_POLICE_ACTION_UNSPECIFIED = 0, /* No action specified */
    lora_mesh_v1_PoliceAction_POLICE_ACTION_DROP = 1, /* Drop packet */
    lora_mesh_v1_PoliceAction_POLICE_ACTION_MARK = 2, /* Mark packet */
    lora_mesh_v1_PoliceAction_POLICE_ACTION_REMARK = 3, /* Remark packet */
    lora_mesh_v1_PoliceAction_POLICE_ACTION_TRANSMIT = 4 /* Allow transmission */
} lora_mesh_v1_PoliceAction;

typedef enum _lora_mesh_v1_AdmissionPolicy {
    lora_mesh_v1_AdmissionPolicy_ADMISSION_POLICY_UNSPECIFIED = 0, /* No policy specified */
    lora_mesh_v1_AdmissionPolicy_ADMISSION_POLICY_FIRST_COME_FIRST_SERVE = 1, /* FCFS admission */
    lora_mesh_v1_AdmissionPolicy_ADMISSION_POLICY_PRIORITY_BASED_ADM = 2, /* Priority-based admission */
    lora_mesh_v1_AdmissionPolicy_ADMISSION_POLICY_RESOURCE_BASED_ADM = 3, /* Resource-based admission */
    lora_mesh_v1_AdmissionPolicy_ADMISSION_POLICY_LOTTERY_BASED = 4 /* Lottery-based admission */
} lora_mesh_v1_AdmissionPolicy;

typedef enum _lora_mesh_v1_ReservationType {
    lora_mesh_v1_ReservationType_RESERVATION_TYPE_UNSPECIFIED = 0, /* No reservation type specified */
    lora_mesh_v1_ReservationType_RESERVATION_TYPE_GUARANTEED = 1, /* Guaranteed reservation */
    lora_mesh_v1_ReservationType_RESERVATION_TYPE_CONTROLLED_LOAD = 2, /* Controlled load */
    lora_mesh_v1_ReservationType_RESERVATION_TYPE_RESV_BEST_EFFORT = 3 /* Best effort */
} lora_mesh_v1_ReservationType;

/* Struct definitions */
/* Key rotation policy */
typedef struct _lora_mesh_v1_KeyRotationPolicy {
    uint32_t rotation_interval_hours; /* Hours between key changes */
    uint32_t key_lifetime_hours; /* Maximum key lifetime */
    uint32_t overlap_period_minutes; /* Old/new key overlap time */
    bool auto_rotation_enabled; /* Enable automatic rotation */
} lora_mesh_v1_KeyRotationPolicy;

typedef PB_BYTES_ARRAY_T(32) lora_mesh_v1_CryptoConfig_network_key_t;
/* Cryptographic configuration */
typedef struct _lora_mesh_v1_CryptoConfig {
    lora_mesh_v1_EncryptionAlgorithm algorithm; /* Encryption algorithm */
    uint32_t key_size_bits; /* Key size in bits */
    lora_mesh_v1_CryptoConfig_network_key_t network_key; /* Shared network key (encrypted) */
    bool has_key_rotation;
    lora_mesh_v1_KeyRotationPolicy key_rotation; /* Key rotation settings */
    lora_mesh_v1_AuthenticationMethod auth_method; /* Authentication method */
    uint32_t message_sequence_window; /* Replay protection window */
} lora_mesh_v1_CryptoConfig;

/* Redundancy configuration */
typedef struct _lora_mesh_v1_RedundancyConfig {
    uint32_t backup_path_count; /* Number of backup paths */
    float path_diversity_threshold; /* Minimum path diversity */
    bool geographic_diversity; /* Enable geographic diversity */
    uint32_t checkpoint_interval; /* Checkpoint frequency */
    lora_mesh_v1_BackupStrategy backup_strategy; /* Backup path strategy */
} lora_mesh_v1_RedundancyConfig;

/* Topology configuration */
typedef struct _lora_mesh_v1_TopologyConfig {
    lora_mesh_v1_TopologyType topology_type; /* Network topology type */
    uint32_t max_hop_count; /* Maximum hops in network */
    uint32_t node_capacity; /* Maximum nodes supported */
    float node_density_threshold; /* Density threshold */
    lora_mesh_v1_ReliabilityLevel reliability_level; /* Required reliability */
    bool has_redundancy_config;
    lora_mesh_v1_RedundancyConfig redundancy_config; /* Redundancy settings */
} lora_mesh_v1_TopologyConfig;

/* Protocol switching policy */
typedef struct _lora_mesh_v1_ProtocolSwitchingPolicy {
    float load_threshold; /* Load threshold for switching */
    float mobility_threshold; /* Mobility threshold */
    uint32_t switch_hysteresis_ms; /* Switching delay to prevent flapping */
    bool adaptive_switching; /* Enable adaptive switching */
    lora_mesh_v1_SwitchingTrigger switching_triggers; /* What triggers protocol changes */
} lora_mesh_v1_ProtocolSwitchingPolicy;

/* Route maintenance configuration */
typedef struct _lora_mesh_v1_RouteMaintenanceConfig {
    uint32_t hello_interval_ms; /* Hello message interval */
    uint32_t route_timeout_ms; /* Route expiration timeout */
    uint32_t active_route_timeout_ms; /* Active route timeout */
    uint32_t allowed_hello_loss; /* Allowed missed hello messages */
    float link_break_threshold; /* RSSI threshold for link break */
    bool preemptive_repair; /* Enable preemptive route repair */
} lora_mesh_v1_RouteMaintenanceConfig;

/* Compression configuration */
typedef struct _lora_mesh_v1_CompressionConfig {
    lora_mesh_v1_CompressionAlgorithm algorithm; /* Compression algorithm */
    uint32_t compression_threshold; /* Minimum size to compress */
    lora_mesh_v1_CompressionLevel level; /* Compression level */
    bool header_compression; /* Compress message headers */
    bool adaptive_compression; /* Adapt compression to conditions */
} lora_mesh_v1_CompressionConfig;

/* Performance configuration */
typedef struct _lora_mesh_v1_PerformanceConfig {
    uint32_t route_cache_size; /* Maximum cached routes */
    uint32_t neighbor_cache_size; /* Maximum cached neighbors */
    uint32_t request_rate_limit; /* Max requests per second */
    uint32_t forwarding_queue_size; /* Forwarding buffer size */
    lora_mesh_v1_PowerManagementMode power_mode; /* Power management mode */
    bool has_compression;
    lora_mesh_v1_CompressionConfig compression; /* Message compression settings */
} lora_mesh_v1_PerformanceConfig;

/* Routing protocol configuration */
typedef struct _lora_mesh_v1_RoutingConfig {
    pb_size_t enabled_protocols_count;
    lora_mesh_v1_RoutingProtocol enabled_protocols[4]; /* Active protocols */
    bool has_switching_policy;
    lora_mesh_v1_ProtocolSwitchingPolicy switching_policy; /* Protocol switching rules */
    bool has_maintenance_config;
    lora_mesh_v1_RouteMaintenanceConfig maintenance_config; /* Route maintenance */
    bool has_performance_config;
    lora_mesh_v1_PerformanceConfig performance_config; /* Performance tuning */
} lora_mesh_v1_RoutingConfig;

/* Bandwidth allocation */
typedef struct _lora_mesh_v1_BandwidthAllocation {
    uint32_t guaranteed_bps; /* Guaranteed bandwidth */
    uint32_t maximum_bps; /* Maximum bandwidth */
    uint32_t burst_size; /* Burst buffer size */
    float sharing_weight; /* Weight for bandwidth sharing */
} lora_mesh_v1_BandwidthAllocation;

/* Latency requirements */
typedef struct _lora_mesh_v1_LatencyRequirements {
    uint32_t maximum_latency_ms; /* Maximum acceptable latency */
    uint32_t target_latency_ms; /* Target latency */
    uint32_t jitter_tolerance_ms; /* Jitter tolerance */
    bool strict_deadline; /* Strict deadline enforcement */
} lora_mesh_v1_LatencyRequirements;

/* Reliability requirements */
typedef struct _lora_mesh_v1_ReliabilityRequirements {
    float minimum_delivery_ratio; /* Minimum delivery success ratio */
    uint32_t maximum_retransmissions; /* Maximum retransmission attempts */
    uint32_t acknowledgment_timeout_ms; /* ACK timeout */
    bool duplicate_detection; /* Enable duplicate detection */
} lora_mesh_v1_ReliabilityRequirements;

/* Service class definition */
typedef struct _lora_mesh_v1_ServiceClass {
    char class_name[32]; /* Service class name */
    lora_mesh_v1_QoSPriority priority; /* Traffic priority */
    bool has_bandwidth;
    lora_mesh_v1_BandwidthAllocation bandwidth; /* Bandwidth allocation */
    bool has_latency;
    lora_mesh_v1_LatencyRequirements latency; /* Latency requirements */
    bool has_reliability;
    lora_mesh_v1_ReliabilityRequirements reliability; /* Reliability requirements */
} lora_mesh_v1_ServiceClass;

/* Queue configuration */
typedef struct _lora_mesh_v1_QueueConfig {
    lora_mesh_v1_QoSPriority priority; /* Queue priority */
    uint32_t queue_size; /* Maximum queue size */
    lora_mesh_v1_QueueDiscipline discipline; /* Queue discipline */
    lora_mesh_v1_DropPolicy drop_policy; /* Drop policy when full */
} lora_mesh_v1_QueueConfig;

/* Priority scheduling */
typedef struct _lora_mesh_v1_PriorityScheduling {
    lora_mesh_v1_SchedulingAlgorithm algorithm; /* Scheduling algorithm */
    pb_size_t queues_count;
    lora_mesh_v1_QueueConfig queues[4]; /* Priority queues */
    lora_mesh_v1_PreemptionPolicy preemption; /* Preemption policy */
    lora_mesh_v1_FairnessPolicy fairness; /* Fairness policy */
} lora_mesh_v1_PriorityScheduling;

/* Token bucket configuration */
typedef struct _lora_mesh_v1_TokenBucketConfig {
    uint32_t bucket_size; /* Token bucket size */
    uint32_t token_rate; /* Token generation rate */
    uint32_t initial_tokens; /* Initial token count */
    bool fair_queuing; /* Fair queuing enabled */
} lora_mesh_v1_TokenBucketConfig;

/* Shaper configuration */
typedef struct _lora_mesh_v1_ShaperConfig {
    char shaper_id[16]; /* Shaper identifier */
    uint32_t rate_limit_bps; /* Rate limit in bps */
    uint32_t burst_size; /* Burst size */
    bool has_token_bucket;
    lora_mesh_v1_TokenBucketConfig token_bucket; /* Token bucket parameters */
} lora_mesh_v1_ShaperConfig;

/* Policing configuration */
typedef struct _lora_mesh_v1_PoliceConfig {
    uint32_t rate_limit_bps; /* Rate limit for policing */
    lora_mesh_v1_PoliceAction exceed_action; /* Action when rate exceeded */
    lora_mesh_v1_PoliceAction violate_action; /* Action when violations occur */
    uint32_t measurement_interval_ms; /* Measurement window */
} lora_mesh_v1_PoliceConfig;

/* Traffic shaping */
typedef struct _lora_mesh_v1_TrafficShaping {
    pb_size_t shapers_count;
    lora_mesh_v1_ShaperConfig shapers[4]; /* Traffic shapers */
    bool has_policing;
    lora_mesh_v1_PoliceConfig policing; /* Traffic policing */
    bool adaptive_shaping; /* Adaptive traffic shaping */
} lora_mesh_v1_TrafficShaping;

/* Resource reservation */
typedef struct _lora_mesh_v1_ResourceReservation {
    uint32_t reserved_bandwidth_bps; /* Reserved bandwidth */
    uint32_t reserved_buffer_size; /* Reserved buffer space */
    float cpu_reservation_percent; /* Reserved CPU percentage */
    lora_mesh_v1_ReservationType reservation_type; /* Type of reservation */
} lora_mesh_v1_ResourceReservation;

/* Admission control */
typedef struct _lora_mesh_v1_AdmissionControl {
    bool admission_control_enabled; /* Enable admission control */
    uint32_t connection_limit; /* Maximum concurrent connections */
    lora_mesh_v1_AdmissionPolicy policy; /* Admission control policy */
    bool has_reservation;
    lora_mesh_v1_ResourceReservation reservation; /* Resource reservation settings */
} lora_mesh_v1_AdmissionControl;

/* Quality of Service configuration */
typedef struct _lora_mesh_v1_QoSConfig {
    pb_size_t service_classes_count;
    lora_mesh_v1_ServiceClass service_classes[4]; /* Defined service classes */
    bool has_scheduling;
    lora_mesh_v1_PriorityScheduling scheduling; /* Priority scheduling policy */
    bool has_shaping;
    lora_mesh_v1_TrafficShaping shaping; /* Traffic shaping rules */
    bool has_admission;
    lora_mesh_v1_AdmissionControl admission; /* Admission control policy */
} lora_mesh_v1_QoSConfig;

/* Comprehensive mesh network configuration */
typedef struct _lora_mesh_v1_MeshNetworkConfig {
    char network_name[32]; /* Network identifier */
    uint32_t network_id; /* Numeric network ID */
    lora_mesh_v1_SecurityLevel security_level; /* Security requirements */
    bool has_crypto_config;
    lora_mesh_v1_CryptoConfig crypto_config; /* Cryptographic settings */
    bool has_topology_config;
    lora_mesh_v1_TopologyConfig topology_config; /* Network topology settings */
    bool has_routing_config;
    lora_mesh_v1_RoutingConfig routing_config; /* Routing protocol configuration */
    bool has_qos_config;
    lora_mesh_v1_QoSConfig qos_config; /* Quality of Service settings */
} lora_mesh_v1_MeshNetworkConfig;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _lora_mesh_v1_EncryptionAlgorithm_MIN lora_mesh_v1_EncryptionAlgorithm_ENCRYPTION_ALGORITHM_UNSPECIFIED
#define _lora_mesh_v1_EncryptionAlgorithm_MAX lora_mesh_v1_EncryptionAlgorithm_ENCRYPTION_ALGORITHM_SALSA20
#define _lora_mesh_v1_EncryptionAlgorithm_ARRAYSIZE ((lora_mesh_v1_EncryptionAlgorithm)(lora_mesh_v1_EncryptionAlgorithm_ENCRYPTION_ALGORITHM_SALSA20+1))

#define _lora_mesh_v1_AuthenticationMethod_MIN lora_mesh_v1_AuthenticationMethod_AUTHENTICATION_METHOD_UNSPECIFIED
#define _lora_mesh_v1_AuthenticationMethod_MAX lora_mesh_v1_AuthenticationMethod_AUTHENTICATION_METHOD_BIOMETRIC
#define _lora_mesh_v1_AuthenticationMethod_ARRAYSIZE ((lora_mesh_v1_AuthenticationMethod)(lora_mesh_v1_AuthenticationMethod_AUTHENTICATION_METHOD_BIOMETRIC+1))

#define _lora_mesh_v1_TopologyType_MIN lora_mesh_v1_TopologyType_TOPOLOGY_TYPE_UNSPECIFIED
#define _lora_mesh_v1_TopologyType_MAX lora_mesh_v1_TopologyType_TOPOLOGY_TYPE_HYBRID_TOPOLOGY
#define _lora_mesh_v1_TopologyType_ARRAYSIZE ((lora_mesh_v1_TopologyType)(lora_mesh_v1_TopologyType_TOPOLOGY_TYPE_HYBRID_TOPOLOGY+1))

#define _lora_mesh_v1_BackupStrategy_MIN lora_mesh_v1_BackupStrategy_BACKUP_STRATEGY_UNSPECIFIED
#define _lora_mesh_v1_BackupStrategy_MAX lora_mesh_v1_BackupStrategy_BACKUP_STRATEGY_HYBRID_BACKUP
#define _lora_mesh_v1_BackupStrategy_ARRAYSIZE ((lora_mesh_v1_BackupStrategy)(lora_mesh_v1_BackupStrategy_BACKUP_STRATEGY_HYBRID_BACKUP+1))

#define _lora_mesh_v1_SwitchingTrigger_MIN lora_mesh_v1_SwitchingTrigger_SWITCHING_TRIGGER_UNSPECIFIED
#define _lora_mesh_v1_SwitchingTrigger_MAX lora_mesh_v1_SwitchingTrigger_SWITCHING_TRIGGER_MANUAL
#define _lora_mesh_v1_SwitchingTrigger_ARRAYSIZE ((lora_mesh_v1_SwitchingTrigger)(lora_mesh_v1_SwitchingTrigger_SWITCHING_TRIGGER_MANUAL+1))

#define _lora_mesh_v1_PowerManagementMode_MIN lora_mesh_v1_PowerManagementMode_POWER_MANAGEMENT_MODE_UNSPECIFIED
#define _lora_mesh_v1_PowerManagementMode_MAX lora_mesh_v1_PowerManagementMode_POWER_MANAGEMENT_MODE_ULTRA_LOW_POWER
#define _lora_mesh_v1_PowerManagementMode_ARRAYSIZE ((lora_mesh_v1_PowerManagementMode)(lora_mesh_v1_PowerManagementMode_POWER_MANAGEMENT_MODE_ULTRA_LOW_POWER+1))

#define _lora_mesh_v1_CompressionAlgorithm_MIN lora_mesh_v1_CompressionAlgorithm_COMPRESSION_ALGORITHM_UNSPECIFIED
#define _lora_mesh_v1_CompressionAlgorithm_MAX lora_mesh_v1_CompressionAlgorithm_COMPRESSION_ALGORITHM_BROTLI
#define _lora_mesh_v1_CompressionAlgorithm_ARRAYSIZE ((lora_mesh_v1_CompressionAlgorithm)(lora_mesh_v1_CompressionAlgorithm_COMPRESSION_ALGORITHM_BROTLI+1))

#define _lora_mesh_v1_CompressionLevel_MIN lora_mesh_v1_CompressionLevel_COMPRESSION_LEVEL_UNSPECIFIED
#define _lora_mesh_v1_CompressionLevel_MAX lora_mesh_v1_CompressionLevel_COMPRESSION_LEVEL_MAX_COMPRESSION
#define _lora_mesh_v1_CompressionLevel_ARRAYSIZE ((lora_mesh_v1_CompressionLevel)(lora_mesh_v1_CompressionLevel_COMPRESSION_LEVEL_MAX_COMPRESSION+1))

#define _lora_mesh_v1_SchedulingAlgorithm_MIN lora_mesh_v1_SchedulingAlgorithm_SCHEDULING_ALGORITHM_UNSPECIFIED
#define _lora_mesh_v1_SchedulingAlgorithm_MAX lora_mesh_v1_SchedulingAlgorithm_SCHEDULING_ALGORITHM_CLASS_BASED_QUEUE
#define _lora_mesh_v1_SchedulingAlgorithm_ARRAYSIZE ((lora_mesh_v1_SchedulingAlgorithm)(lora_mesh_v1_SchedulingAlgorithm_SCHEDULING_ALGORITHM_CLASS_BASED_QUEUE+1))

#define _lora_mesh_v1_QueueDiscipline_MIN lora_mesh_v1_QueueDiscipline_QUEUE_DISCIPLINE_UNSPECIFIED
#define _lora_mesh_v1_QueueDiscipline_MAX lora_mesh_v1_QueueDiscipline_QUEUE_DISCIPLINE_PRIORITY_QUEUE
#define _lora_mesh_v1_QueueDiscipline_ARRAYSIZE ((lora_mesh_v1_QueueDiscipline)(lora_mesh_v1_QueueDiscipline_QUEUE_DISCIPLINE_PRIORITY_QUEUE+1))

#define _lora_mesh_v1_DropPolicy_MIN lora_mesh_v1_DropPolicy_DROP_POLICY_UNSPECIFIED
#define _lora_mesh_v1_DropPolicy_MAX lora_mesh_v1_DropPolicy_DROP_POLICY_PRIORITY_DROP
#define _lora_mesh_v1_DropPolicy_ARRAYSIZE ((lora_mesh_v1_DropPolicy)(lora_mesh_v1_DropPolicy_DROP_POLICY_PRIORITY_DROP+1))

#define _lora_mesh_v1_PreemptionPolicy_MIN lora_mesh_v1_PreemptionPolicy_PREEMPTION_POLICY_UNSPECIFIED
#define _lora_mesh_v1_PreemptionPolicy_MAX lora_mesh_v1_PreemptionPolicy_PREEMPTION_POLICY_DEADLINE_PREEMPTION
#define _lora_mesh_v1_PreemptionPolicy_ARRAYSIZE ((lora_mesh_v1_PreemptionPolicy)(lora_mesh_v1_PreemptionPolicy_PREEMPTION_POLICY_DEADLINE_PREEMPTION+1))

#define _lora_mesh_v1_FairnessPolicy_MIN lora_mesh_v1_FairnessPolicy_FAIRNESS_POLICY_UNSPECIFIED
#define _lora_mesh_v1_FairnessPolicy_MAX lora_mesh_v1_FairnessPolicy_FAIRNESS_POLICY_MAX_MIN_FAIR
#define _lora_mesh_v1_FairnessPolicy_ARRAYSIZE ((lora_mesh_v1_FairnessPolicy)(lora_mesh_v1_FairnessPolicy_FAIRNESS_POLICY_MAX_MIN_FAIR+1))

#define _lora_mesh_v1_PoliceAction_MIN lora_mesh_v1_PoliceAction_POLICE_ACTION_UNSPECIFIED
#define _lora_mesh_v1_PoliceAction_MAX lora_mesh_v1_PoliceAction_POLICE_ACTION_TRANSMIT
#define _lora_mesh_v1_PoliceAction_ARRAYSIZE ((lora_mesh_v1_PoliceAction)(lora_mesh_v1_PoliceAction_POLICE_ACTION_TRANSMIT+1))

#define _lora_mesh_v1_AdmissionPolicy_MIN lora_mesh_v1_AdmissionPolicy_ADMISSION_POLICY_UNSPECIFIED
#define _lora_mesh_v1_AdmissionPolicy_MAX lora_mesh_v1_AdmissionPolicy_ADMISSION_POLICY_LOTTERY_BASED
#define _lora_mesh_v1_AdmissionPolicy_ARRAYSIZE ((lora_mesh_v1_AdmissionPolicy)(lora_mesh_v1_AdmissionPolicy_ADMISSION_POLICY_LOTTERY_BASED+1))

#define _lora_mesh_v1_ReservationType_MIN lora_mesh_v1_ReservationType_RESERVATION_TYPE_UNSPECIFIED
#define _lora_mesh_v1_ReservationType_MAX lora_mesh_v1_ReservationType_RESERVATION_TYPE_RESV_BEST_EFFORT
#define _lora_mesh_v1_ReservationType_ARRAYSIZE ((lora_mesh_v1_ReservationType)(lora_mesh_v1_ReservationType_RESERVATION_TYPE_RESV_BEST_EFFORT+1))

#define lora_mesh_v1_MeshNetworkConfig_security_level_ENUMTYPE lora_mesh_v1_SecurityLevel

#define lora_mesh_v1_CryptoConfig_algorithm_ENUMTYPE lora_mesh_v1_EncryptionAlgorithm
#define lora_mesh_v1_CryptoConfig_auth_method_ENUMTYPE lora_mesh_v1_AuthenticationMethod


#define lora_mesh_v1_TopologyConfig_topology_type_ENUMTYPE lora_mesh_v1_TopologyType
#define lora_mesh_v1_TopologyConfig_reliability_level_ENUMTYPE lora_mesh_v1_ReliabilityLevel

#define lora_mesh_v1_RedundancyConfig_backup_strategy_ENUMTYPE lora_mesh_v1_BackupStrategy

#define lora_mesh_v1_RoutingConfig_enabled_protocols_ENUMTYPE lora_mesh_v1_RoutingProtocol

#define lora_mesh_v1_ProtocolSwitchingPolicy_switching_triggers_ENUMTYPE lora_mesh_v1_SwitchingTrigger


#define lora_mesh_v1_PerformanceConfig_power_mode_ENUMTYPE lora_mesh_v1_PowerManagementMode

#define lora_mesh_v1_CompressionConfig_algorithm_ENUMTYPE lora_mesh_v1_CompressionAlgorithm
#define lora_mesh_v1_CompressionConfig_level_ENUMTYPE lora_mesh_v1_CompressionLevel


#define lora_mesh_v1_ServiceClass_priority_ENUMTYPE lora_mesh_v1_QoSPriority




#define lora_mesh_v1_PriorityScheduling_algorithm_ENUMTYPE lora_mesh_v1_SchedulingAlgorithm
#define lora_mesh_v1_PriorityScheduling_preemption_ENUMTYPE lora_mesh_v1_PreemptionPolicy
#define lora_mesh_v1_PriorityScheduling_fairness_ENUMTYPE lora_mesh_v1_FairnessPolicy

#define lora_mesh_v1_QueueConfig_priority_ENUMTYPE lora_mesh_v1_QoSPriority
#define lora_mesh_v1_QueueConfig_discipline_ENUMTYPE lora_mesh_v1_QueueDiscipline
#define lora_mesh_v1_QueueConfig_drop_policy_ENUMTYPE lora_mesh_v1_DropPolicy




#define lora_mesh_v1_PoliceConfig_exceed_action_ENUMTYPE lora_mesh_v1_PoliceAction
#define lora_mesh_v1_PoliceConfig_violate_action_ENUMTYPE lora_mesh_v1_PoliceAction

#define lora_mesh_v1_AdmissionControl_policy_ENUMTYPE lora_mesh_v1_AdmissionPolicy

#define lora_mesh_v1_ResourceReservation_reservation_type_ENUMTYPE lora_mesh_v1_ReservationType


/* Initializer values for message structs */
#define lora_mesh_v1_MeshNetworkConfig_init_default {"", 0, _lora_mesh_v1_SecurityLevel_MIN, false, lora_mesh_v1_CryptoConfig_init_default, false, lora_mesh_v1_TopologyConfig_init_default, false, lora_mesh_v1_RoutingConfig_init_default, false, lora_mesh_v1_QoSConfig_init_default}
#define lora_mesh_v1_CryptoConfig_init_default   {_lora_mesh_v1_EncryptionAlgorithm_MIN, 0, {0, {0}}, false, lora_mesh_v1_KeyRotationPolicy_init_default, _lora_mesh_v1_AuthenticationMethod_MIN, 0}
#define lora_mesh_v1_KeyRotationPolicy_init_default {0, 0, 0, 0}
#define lora_mesh_v1_TopologyConfig_init_default {_lora_mesh_v1_TopologyType_MIN, 0, 0, 0, _lora_mesh_v1_ReliabilityLevel_MIN, false, lora_mesh_v1_RedundancyConfig_init_default}
#define lora_mesh_v1_RedundancyConfig_init_default {0, 0, 0, 0, _lora_mesh_v1_BackupStrategy_MIN}
#define lora_mesh_v1_RoutingConfig_init_default  {0, {_lora_mesh_v1_RoutingProtocol_MIN, _lora_mesh_v1_RoutingProtocol_MIN, _lora_mesh_v1_RoutingProtocol_MIN, _lora_mesh_v1_RoutingProtocol_MIN}, false, lora_mesh_v1_ProtocolSwitchingPolicy_init_default, false, lora_mesh_v1_RouteMaintenanceConfig_init_default, false, lora_mesh_v1_PerformanceConfig_init_default}
#define lora_mesh_v1_ProtocolSwitchingPolicy_init_default {0, 0, 0, 0, _lora_mesh_v1_SwitchingTrigger_MIN}
#define lora_mesh_v1_RouteMaintenanceConfig_init_default {0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_PerformanceConfig_init_default {0, 0, 0, 0, _lora_mesh_v1_PowerManagementMode_MIN, false, lora_mesh_v1_CompressionConfig_init_default}
#define lora_mesh_v1_CompressionConfig_init_default {_lora_mesh_v1_CompressionAlgorithm_MIN, 0, _lora_mesh_v1_CompressionLevel_MIN, 0, 0}
#define lora_mesh_v1_QoSConfig_init_default      {0, {lora_mesh_v1_ServiceClass_init_default, lora_mesh_v1_ServiceClass_init_default, lora_mesh_v1_ServiceClass_init_default, lora_mesh_v1_ServiceClass_init_default}, false, lora_mesh_v1_PriorityScheduling_init_default, false, lora_mesh_v1_TrafficShaping_init_default, false, lora_mesh_v1_AdmissionControl_init_default}
#define lora_mesh_v1_ServiceClass_init_default   {"", _lora_mesh_v1_QoSPriority_MIN, false, lora_mesh_v1_BandwidthAllocation_init_default, false, lora_mesh_v1_LatencyRequirements_init_default, false, lora_mesh_v1_ReliabilityRequirements_init_default}
#define lora_mesh_v1_BandwidthAllocation_init_default {0, 0, 0, 0}
#define lora_mesh_v1_LatencyRequirements_init_default {0, 0, 0, 0}
#define lora_mesh_v1_ReliabilityRequirements_init_default {0, 0, 0, 0}
#define lora_mesh_v1_PriorityScheduling_init_default {_lora_mesh_v1_SchedulingAlgorithm_MIN, 0, {lora_mesh_v1_QueueConfig_init_default, lora_mesh_v1_QueueConfig_init_default, lora_mesh_v1_QueueConfig_init_default, lora_mesh_v1_QueueConfig_init_default}, _lora_mesh_v1_PreemptionPolicy_MIN, _lora_mesh_v1_FairnessPolicy_MIN}
#define lora_mesh_v1_QueueConfig_init_default    {_lora_mesh_v1_QoSPriority_MIN, 0, _lora_mesh_v1_QueueDiscipline_MIN, _lora_mesh_v1_DropPolicy_MIN}
#define lora_mesh_v1_TrafficShaping_init_default {0, {lora_mesh_v1_ShaperConfig_init_default, lora_mesh_v1_ShaperConfig_init_default, lora_mesh_v1_ShaperConfig_init_default, lora_mesh_v1_ShaperConfig_init_default}, false, lora_mesh_v1_PoliceConfig_init_default, 0}
#define lora_mesh_v1_ShaperConfig_init_default   {"", 0, 0, false, lora_mesh_v1_TokenBucketConfig_init_default}
#define lora_mesh_v1_TokenBucketConfig_init_default {0, 0, 0, 0}
#define lora_mesh_v1_PoliceConfig_init_default   {0, _lora_mesh_v1_PoliceAction_MIN, _lora_mesh_v1_PoliceAction_MIN, 0}
#define lora_mesh_v1_AdmissionControl_init_default {0, 0, _lora_mesh_v1_AdmissionPolicy_MIN, false, lora_mesh_v1_ResourceReservation_init_default}
#define lora_mesh_v1_ResourceReservation_init_default {0, 0, 0, _lora_mesh_v1_ReservationType_MIN}
#define lora_mesh_v1_MeshNetworkConfig_init_zero {"", 0, _lora_mesh_v1_SecurityLevel_MIN, false, lora_mesh_v1_CryptoConfig_init_zero, false, lora_mesh_v1_TopologyConfig_init_zero, false, lora_mesh_v1_RoutingConfig_init_zero, false, lora_mesh_v1_QoSConfig_init_zero}
#define lora_mesh_v1_CryptoConfig_init_zero      {_lora_mesh_v1_EncryptionAlgorithm_MIN, 0, {0, {0}}, false, lora_mesh_v1_KeyRotationPolicy_init_zero, _lora_mesh_v1_AuthenticationMethod_MIN, 0}
#define lora_mesh_v1_KeyRotationPolicy_init_zero {0, 0, 0, 0}
#define lora_mesh_v1_TopologyConfig_init_zero    {_lora_mesh_v1_TopologyType_MIN, 0, 0, 0, _lora_mesh_v1_ReliabilityLevel_MIN, false, lora_mesh_v1_RedundancyConfig_init_zero}
#define lora_mesh_v1_RedundancyConfig_init_zero  {0, 0, 0, 0, _lora_mesh_v1_BackupStrategy_MIN}
#define lora_mesh_v1_RoutingConfig_init_zero     {0, {_lora_mesh_v1_RoutingProtocol_MIN, _lora_mesh_v1_RoutingProtocol_MIN, _lora_mesh_v1_RoutingProtocol_MIN, _lora_mesh_v1_RoutingProtocol_MIN}, false, lora_mesh_v1_ProtocolSwitchingPolicy_init_zero, false, lora_mesh_v1_RouteMaintenanceConfig_init_zero, false, lora_mesh_v1_PerformanceConfig_init_zero}
#define lora_mesh_v1_ProtocolSwitchingPolicy_init_zero {0, 0, 0, 0, _lora_mesh_v1_SwitchingTrigger_MIN}
#define lora_mesh_v1_RouteMaintenanceConfig_init_zero {0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_PerformanceConfig_init_zero {0, 0, 0, 0, _lora_mesh_v1_PowerManagementMode_MIN, false, lora_mesh_v1_CompressionConfig_init_zero}
#define lora_mesh_v1_CompressionConfig_init_zero {_lora_mesh_v1_CompressionAlgorithm_MIN, 0, _lora_mesh_v1_CompressionLevel_MIN, 0, 0}
#define lora_mesh_v1_QoSConfig_init_zero         {0, {lora_mesh_v1_ServiceClass_init_zero, lora_mesh_v1_ServiceClass_init_zero, lora_mesh_v1_ServiceClass_init_zero, lora_mesh_v1_ServiceClass_init_zero}, false, lora_mesh_v1_PriorityScheduling_init_zero, false, lora_mesh_v1_TrafficShaping_init_zero, false, lora_mesh_v1_AdmissionControl_init_zero}
#define lora_mesh_v1_ServiceClass_init_zero      {"", _lora_mesh_v1_QoSPriority_MIN, false, lora_mesh_v1_BandwidthAllocation_init_zero, false, lora_mesh_v1_LatencyRequirements_init_zero, false, lora_mesh_v1_ReliabilityRequirements_init_zero}
#define lora_mesh_v1_BandwidthAllocation_init_zero {0, 0, 0, 0}
#define lora_mesh_v1_LatencyRequirements_init_zero {0, 0, 0, 0}
#define lora_mesh_v1_ReliabilityRequirements_init_zero {0, 0, 0, 0}
#define lora_mesh_v1_PriorityScheduling_init_zero {_lora_mesh_v1_SchedulingAlgorithm_MIN, 0, {lora_mesh_v1_QueueConfig_init_zero, lora_mesh_v1_QueueConfig_init_zero, lora_mesh_v1_QueueConfig_init_zero, lora_mesh_v1_QueueConfig_init_zero}, _lora_mesh_v1_PreemptionPolicy_MIN, _lora_mesh_v1_FairnessPolicy_MIN}
#define lora_mesh_v1_QueueConfig_init_zero       {_lora_mesh_v1_QoSPriority_MIN, 0, _lora_mesh_v1_QueueDiscipline_MIN, _lora_mesh_v1_DropPolicy_MIN}
#define lora_mesh_v1_TrafficShaping_init_zero    {0, {lora_mesh_v1_ShaperConfig_init_zero, lora_mesh_v1_ShaperConfig_init_zero, lora_mesh_v1_ShaperConfig_init_zero, lora_mesh_v1_ShaperConfig_init_zero}, false, lora_mesh_v1_PoliceConfig_init_zero, 0}
#define lora_mesh_v1_ShaperConfig_init_zero      {"", 0, 0, false, lora_mesh_v1_TokenBucketConfig_init_zero}
#define lora_mesh_v1_TokenBucketConfig_init_zero {0, 0, 0, 0}
#define lora_mesh_v1_PoliceConfig_init_zero      {0, _lora_mesh_v1_PoliceAction_MIN, _lora_mesh_v1_PoliceAction_MIN, 0}
#define lora_mesh_v1_AdmissionControl_init_zero  {0, 0, _lora_mesh_v1_AdmissionPolicy_MIN, false, lora_mesh_v1_ResourceReservation_init_zero}
#define lora_mesh_v1_ResourceReservation_init_zero {0, 0, 0, _lora_mesh_v1_ReservationType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define lora_mesh_v1_KeyRotationPolicy_rotation_interval_hours_tag 1
#define lora_mesh_v1_KeyRotationPolicy_key_lifetime_hours_tag 2
#define lora_mesh_v1_KeyRotationPolicy_overlap_period_minutes_tag 3
#define lora_mesh_v1_KeyRotationPolicy_auto_rotation_enabled_tag 4
#define lora_mesh_v1_CryptoConfig_algorithm_tag  1
#define lora_mesh_v1_CryptoConfig_key_size_bits_tag 2
#define lora_mesh_v1_CryptoConfig_network_key_tag 3
#define lora_mesh_v1_CryptoConfig_key_rotation_tag 4
#define lora_mesh_v1_CryptoConfig_auth_method_tag 5
#define lora_mesh_v1_CryptoConfig_message_sequence_window_tag 6
#define lora_mesh_v1_RedundancyConfig_backup_path_count_tag 1
#define lora_mesh_v1_RedundancyConfig_path_diversity_threshold_tag 2
#define lora_mesh_v1_RedundancyConfig_geographic_diversity_tag 3
#define lora_mesh_v1_RedundancyConfig_checkpoint_interval_tag 4
#define lora_mesh_v1_RedundancyConfig_backup_strategy_tag 5
#define lora_mesh_v1_TopologyConfig_topology_type_tag 1
#define lora_mesh_v1_TopologyConfig_max_hop_count_tag 2
#define lora_mesh_v1_TopologyConfig_node_capacity_tag 3
#define lora_mesh_v1_TopologyConfig_node_density_threshold_tag 4
#define lora_mesh_v1_TopologyConfig_reliability_level_tag 5
#define lora_mesh_v1_TopologyConfig_redundancy_config_tag 6
#define lora_mesh_v1_ProtocolSwitchingPolicy_load_threshold_tag 1
#define lora_mesh_v1_ProtocolSwitchingPolicy_mobility_threshold_tag 2
#define lora_mesh_v1_ProtocolSwitchingPolicy_switch_hysteresis_ms_tag 3
#define lora_mesh_v1_ProtocolSwitchingPolicy_adaptive_switching_tag 4
#define lora_mesh_v1_ProtocolSwitchingPolicy_switching_triggers_tag 5
#define lora_mesh_v1_RouteMaintenanceConfig_hello_interval_ms_tag 1
#define lora_mesh_v1_RouteMaintenanceConfig_route_timeout_ms_tag 2
#define lora_mesh_v1_RouteMaintenanceConfig_active_route_timeout_ms_tag 3
#define lora_mesh_v1_RouteMaintenanceConfig_allowed_hello_loss_tag 4
#define lora_mesh_v1_RouteMaintenanceConfig_link_break_threshold_tag 5
#define lora_mesh_v1_RouteMaintenanceConfig_preemptive_repair_tag 6
#define lora_mesh_v1_CompressionConfig_algorithm_tag 1
#define lora_mesh_v1_CompressionConfig_compression_threshold_tag 2
#define lora_mesh_v1_CompressionConfig_level_tag 3
#define lora_mesh_v1_CompressionConfig_header_compression_tag 4
#define lora_mesh_v1_CompressionConfig_adaptive_compression_tag 5
#define lora_mesh_v1_PerformanceConfig_route_cache_size_tag 1
#define lora_mesh_v1_PerformanceConfig_neighbor_cache_size_tag 2
#define lora_mesh_v1_PerformanceConfig_request_rate_limit_tag 3
#define lora_mesh_v1_PerformanceConfig_forwarding_queue_size_tag 4
#define lora_mesh_v1_PerformanceConfig_power_mode_tag 5
#define lora_mesh_v1_PerformanceConfig_compression_tag 6
#define lora_mesh_v1_RoutingConfig_enabled_protocols_tag 1
#define lora_mesh_v1_RoutingConfig_switching_policy_tag 2
#define lora_mesh_v1_RoutingConfig_maintenance_config_tag 3
#define lora_mesh_v1_RoutingConfig_performance_config_tag 4
#define lora_mesh_v1_BandwidthAllocation_guaranteed_bps_tag 1
#define lora_mesh_v1_BandwidthAllocation_maximum_bps_tag 2
#define lora_mesh_v1_BandwidthAllocation_burst_size_tag 3
#define lora_mesh_v1_BandwidthAllocation_sharing_weight_tag 4
#define lora_mesh_v1_LatencyRequirements_maximum_latency_ms_tag 1
#define lora_mesh_v1_LatencyRequirements_target_latency_ms_tag 2
#define lora_mesh_v1_LatencyRequirements_jitter_tolerance_ms_tag 3
#define lora_mesh_v1_LatencyRequirements_strict_deadline_tag 4
#define lora_mesh_v1_ReliabilityRequirements_minimum_delivery_ratio_tag 1
#define lora_mesh_v1_ReliabilityRequirements_maximum_retransmissions_tag 2
#define lora_mesh_v1_ReliabilityRequirements_acknowledgment_timeout_ms_tag 3
#define lora_mesh_v1_ReliabilityRequirements_duplicate_detection_tag 4
#define lora_mesh_v1_ServiceClass_class_name_tag 1
#define lora_mesh_v1_ServiceClass_priority_tag   2
#define lora_mesh_v1_ServiceClass_bandwidth_tag  3
#define lora_mesh_v1_ServiceClass_latency_tag    4
#define lora_mesh_v1_ServiceClass_reliability_tag 5
#define lora_mesh_v1_QueueConfig_priority_tag    1
#define lora_mesh_v1_QueueConfig_queue_size_tag  2
#define lora_mesh_v1_QueueConfig_discipline_tag  3
#define lora_mesh_v1_QueueConfig_drop_policy_tag 4
#define lora_mesh_v1_PriorityScheduling_algorithm_tag 1
#define lora_mesh_v1_PriorityScheduling_queues_tag 2
#define lora_mesh_v1_PriorityScheduling_preemption_tag 3
#define lora_mesh_v1_PriorityScheduling_fairness_tag 4
#define lora_mesh_v1_TokenBucketConfig_bucket_size_tag 1
#define lora_mesh_v1_TokenBucketConfig_token_rate_tag 2
#define lora_mesh_v1_TokenBucketConfig_initial_tokens_tag 3
#define lora_mesh_v1_TokenBucketConfig_fair_queuing_tag 4
#define lora_mesh_v1_ShaperConfig_shaper_id_tag  1
#define lora_mesh_v1_ShaperConfig_rate_limit_bps_tag 2
#define lora_mesh_v1_ShaperConfig_burst_size_tag 3
#define lora_mesh_v1_ShaperConfig_token_bucket_tag 4
#define lora_mesh_v1_PoliceConfig_rate_limit_bps_tag 1
#define lora_mesh_v1_PoliceConfig_exceed_action_tag 2
#define lora_mesh_v1_PoliceConfig_violate_action_tag 3
#define lora_mesh_v1_PoliceConfig_measurement_interval_ms_tag 4
#define lora_mesh_v1_TrafficShaping_shapers_tag  1
#define lora_mesh_v1_TrafficShaping_policing_tag 2
#define lora_mesh_v1_TrafficShaping_adaptive_shaping_tag 3
#define lora_mesh_v1_ResourceReservation_reserved_bandwidth_bps_tag 1
#define lora_mesh_v1_ResourceReservation_reserved_buffer_size_tag 2
#define lora_mesh_v1_ResourceReservation_cpu_reservation_percent_tag 3
#define lora_mesh_v1_ResourceReservation_reservation_type_tag 4
#define lora_mesh_v1_AdmissionControl_admission_control_enabled_tag 1
#define lora_mesh_v1_AdmissionControl_connection_limit_tag 2
#define lora_mesh_v1_AdmissionControl_policy_tag 3
#define lora_mesh_v1_AdmissionControl_reservation_tag 4
#define lora_mesh_v1_QoSConfig_service_classes_tag 1
#define lora_mesh_v1_QoSConfig_scheduling_tag    2
#define lora_mesh_v1_QoSConfig_shaping_tag       3
#define lora_mesh_v1_QoSConfig_admission_tag     4
#define lora_mesh_v1_MeshNetworkConfig_network_name_tag 1
#define lora_mesh_v1_MeshNetworkConfig_network_id_tag 2
#define lora_mesh_v1_MeshNetworkConfig_security_level_tag 3
#define lora_mesh_v1_MeshNetworkConfig_crypto_config_tag 4
#define lora_mesh_v1_MeshNetworkConfig_topology_config_tag 5
#define lora_mesh_v1_MeshNetworkConfig_routing_config_tag 6
#define lora_mesh_v1_MeshNetworkConfig_qos_config_tag 7

/* Struct field encoding specification for nanopb */
#define lora_mesh_v1_MeshNetworkConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   network_name,      1) \
X(a, STATIC,   SINGULAR, UINT32,   network_id,        2) \
X(a, STATIC,   SINGULAR, UENUM,    security_level,    3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  crypto_config,     4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  topology_config,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  routing_config,    6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  qos_config,        7)
#define lora_mesh_v1_MeshNetworkConfig_CALLBACK NULL
#define lora_mesh_v1_MeshNetworkConfig_DEFAULT NULL
#define lora_mesh_v1_MeshNetworkConfig_crypto_config_MSGTYPE lora_mesh_v1_CryptoConfig
#define lora_mesh_v1_MeshNetworkConfig_topology_config_MSGTYPE lora_mesh_v1_TopologyConfig
#define lora_mesh_v1_MeshNetworkConfig_routing_config_MSGTYPE lora_mesh_v1_RoutingConfig
#define lora_mesh_v1_MeshNetworkConfig_qos_config_MSGTYPE lora_mesh_v1_QoSConfig

#define lora_mesh_v1_CryptoConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    algorithm,         1) \
X(a, STATIC,   SINGULAR, UINT32,   key_size_bits,     2) \
X(a, STATIC,   SINGULAR, BYTES,    network_key,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  key_rotation,      4) \
X(a, STATIC,   SINGULAR, UENUM,    auth_method,       5) \
X(a, STATIC,   SINGULAR, UINT32,   message_sequence_window,   6)
#define lora_mesh_v1_CryptoConfig_CALLBACK NULL
#define lora_mesh_v1_CryptoConfig_DEFAULT NULL
#define lora_mesh_v1_CryptoConfig_key_rotation_MSGTYPE lora_mesh_v1_KeyRotationPolicy

#define lora_mesh_v1_KeyRotationPolicy_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   rotation_interval_hours,   1) \
X(a, STATIC,   SINGULAR, UINT32,   key_lifetime_hours,   2) \
X(a, STATIC,   SINGULAR, UINT32,   overlap_period_minutes,   3) \
X(a, STATIC,   SINGULAR, BOOL,     auto_rotation_enabled,   4)
#define lora_mesh_v1_KeyRotationPolicy_CALLBACK NULL
#define lora_mesh_v1_KeyRotationPolicy_DEFAULT NULL

#define lora_mesh_v1_TopologyConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    topology_type,     1) \
X(a, STATIC,   SINGULAR, UINT32,   max_hop_count,     2) \
X(a, STATIC,   SINGULAR, UINT32,   node_capacity,     3) \
X(a, STATIC,   SINGULAR, FLOAT,    node_density_threshold,   4) \
X(a, STATIC,   SINGULAR, UENUM,    reliability_level,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  redundancy_config,   6)
#define lora_mesh_v1_TopologyConfig_CALLBACK NULL
#define lora_mesh_v1_TopologyConfig_DEFAULT NULL
#define lora_mesh_v1_TopologyConfig_redundancy_config_MSGTYPE lora_mesh_v1_RedundancyConfig

#define lora_mesh_v1_RedundancyConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   backup_path_count,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    path_diversity_threshold,   2) \
X(a, STATIC,   SINGULAR, BOOL,     geographic_diversity,   3) \
X(a, STATIC,   SINGULAR, UINT32,   checkpoint_interval,   4) \
X(a, STATIC,   SINGULAR, UENUM,    backup_strategy,   5)
#define lora_mesh_v1_RedundancyConfig_CALLBACK NULL
#define lora_mesh_v1_RedundancyConfig_DEFAULT NULL

#define lora_mesh_v1_RoutingConfig_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UENUM,    enabled_protocols,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  switching_policy,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  maintenance_config,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  performance_config,   4)
#define lora_mesh_v1_RoutingConfig_CALLBACK NULL
#define lora_mesh_v1_RoutingConfig_DEFAULT NULL
#define lora_mesh_v1_RoutingConfig_switching_policy_MSGTYPE lora_mesh_v1_ProtocolSwitchingPolicy
#define lora_mesh_v1_RoutingConfig_maintenance_config_MSGTYPE lora_mesh_v1_RouteMaintenanceConfig
#define lora_mesh_v1_RoutingConfig_performance_config_MSGTYPE lora_mesh_v1_PerformanceConfig

#define lora_mesh_v1_ProtocolSwitchingPolicy_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    load_threshold,    1) \
X(a, STATIC,   SINGULAR, FLOAT,    mobility_threshold,   2) \
X(a, STATIC,   SINGULAR, UINT32,   switch_hysteresis_ms,   3) \
X(a, STATIC,   SINGULAR, BOOL,     adaptive_switching,   4) \
X(a, STATIC,   SINGULAR, UENUM,    switching_triggers,   5)
#define lora_mesh_v1_ProtocolSwitchingPolicy_CALLBACK NULL
#define lora_mesh_v1_ProtocolSwitchingPolicy_DEFAULT NULL

#define lora_mesh_v1_RouteMaintenanceConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   hello_interval_ms,   1) \
X(a, STATIC,   SINGULAR, UINT32,   route_timeout_ms,   2) \
X(a, STATIC,   SINGULAR, UINT32,   active_route_timeout_ms,   3) \
X(a, STATIC,   SINGULAR, UINT32,   allowed_hello_loss,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    link_break_threshold,   5) \
X(a, STATIC,   SINGULAR, BOOL,     preemptive_repair,   6)
#define lora_mesh_v1_RouteMaintenanceConfig_CALLBACK NULL
#define lora_mesh_v1_RouteMaintenanceConfig_DEFAULT NULL

#define lora_mesh_v1_PerformanceConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   route_cache_size,   1) \
X(a, STATIC,   SINGULAR, UINT32,   neighbor_cache_size,   2) \
X(a, STATIC,   SINGULAR, UINT32,   request_rate_limit,   3) \
X(a, STATIC,   SINGULAR, UINT32,   forwarding_queue_size,   4) \
X(a, STATIC,   SINGULAR, UENUM,    power_mode,        5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  compression,       6)
#define lora_mesh_v1_PerformanceConfig_CALLBACK NULL
#define lora_mesh_v1_PerformanceConfig_DEFAULT NULL
#define lora_mesh_v1_PerformanceConfig_compression_MSGTYPE lora_mesh_v1_CompressionConfig

#define lora_mesh_v1_CompressionConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    algorithm,         1) \
X(a, STATIC,   SINGULAR, UINT32,   compression_threshold,   2) \
X(a, STATIC,   SINGULAR, UENUM,    level,             3) \
X(a, STATIC,   SINGULAR, BOOL,     header_compression,   4) \
X(a, STATIC,   SINGULAR, BOOL,     adaptive_compression,   5)
#define lora_mesh_v1_CompressionConfig_CALLBACK NULL
#define lora_mesh_v1_CompressionConfig_DEFAULT NULL

#define lora_mesh_v1_QoSConfig_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  service_classes,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scheduling,        2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  shaping,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  admission,         4)
#define lora_mesh_v1_QoSConfig_CALLBACK NULL
#define lora_mesh_v1_QoSConfig_DEFAULT NULL
#define lora_mesh_v1_QoSConfig_service_classes_MSGTYPE lora_mesh_v1_ServiceClass
#define lora_mesh_v1_QoSConfig_scheduling_MSGTYPE lora_mesh_v1_PriorityScheduling
#define lora_mesh_v1_QoSConfig_shaping_MSGTYPE lora_mesh_v1_TrafficShaping
#define lora_mesh_v1_QoSConfig_admission_MSGTYPE lora_mesh_v1_AdmissionControl

#define lora_mesh_v1_ServiceClass_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   class_name,        1) \
X(a, STATIC,   SINGULAR, UENUM,    priority,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bandwidth,         3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  latency,           4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  reliability,       5)
#define lora_mesh_v1_ServiceClass_CALLBACK NULL
#define lora_mesh_v1_ServiceClass_DEFAULT NULL
#define lora_mesh_v1_ServiceClass_bandwidth_MSGTYPE lora_mesh_v1_BandwidthAllocation
#define lora_mesh_v1_ServiceClass_latency_MSGTYPE lora_mesh_v1_LatencyRequirements
#define lora_mesh_v1_ServiceClass_reliability_MSGTYPE lora_mesh_v1_ReliabilityRequirements

#define lora_mesh_v1_BandwidthAllocation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   guaranteed_bps,    1) \
X(a, STATIC,   SINGULAR, UINT32,   maximum_bps,       2) \
X(a, STATIC,   SINGULAR, UINT32,   burst_size,        3) \
X(a, STATIC,   SINGULAR, FLOAT,    sharing_weight,    4)
#define lora_mesh_v1_BandwidthAllocation_CALLBACK NULL
#define lora_mesh_v1_BandwidthAllocation_DEFAULT NULL

#define lora_mesh_v1_LatencyRequirements_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   maximum_latency_ms,   1) \
X(a, STATIC,   SINGULAR, UINT32,   target_latency_ms,   2) \
X(a, STATIC,   SINGULAR, UINT32,   jitter_tolerance_ms,   3) \
X(a, STATIC,   SINGULAR, BOOL,     strict_deadline,   4)
#define lora_mesh_v1_LatencyRequirements_CALLBACK NULL
#define lora_mesh_v1_LatencyRequirements_DEFAULT NULL

#define lora_mesh_v1_ReliabilityRequirements_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    minimum_delivery_ratio,   1) \
X(a, STATIC,   SINGULAR, UINT32,   maximum_retransmissions,   2) \
X(a, STATIC,   SINGULAR, UINT32,   acknowledgment_timeout_ms,   3) \
X(a, STATIC,   SINGULAR, BOOL,     duplicate_detection,   4)
#define lora_mesh_v1_ReliabilityRequirements_CALLBACK NULL
#define lora_mesh_v1_ReliabilityRequirements_DEFAULT NULL

#define lora_mesh_v1_PriorityScheduling_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    algorithm,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  queues,            2) \
X(a, STATIC,   SINGULAR, UENUM,    preemption,        3) \
X(a, STATIC,   SINGULAR, UENUM,    fairness,          4)
#define lora_mesh_v1_PriorityScheduling_CALLBACK NULL
#define lora_mesh_v1_PriorityScheduling_DEFAULT NULL
#define lora_mesh_v1_PriorityScheduling_queues_MSGTYPE lora_mesh_v1_QueueConfig

#define lora_mesh_v1_QueueConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    priority,          1) \
X(a, STATIC,   SINGULAR, UINT32,   queue_size,        2) \
X(a, STATIC,   SINGULAR, UENUM,    discipline,        3) \
X(a, STATIC,   SINGULAR, UENUM,    drop_policy,       4)
#define lora_mesh_v1_QueueConfig_CALLBACK NULL
#define lora_mesh_v1_QueueConfig_DEFAULT NULL

#define lora_mesh_v1_TrafficShaping_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  shapers,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  policing,          2) \
X(a, STATIC,   SINGULAR, BOOL,     adaptive_shaping,   3)
#define lora_mesh_v1_TrafficShaping_CALLBACK NULL
#define lora_mesh_v1_TrafficShaping_DEFAULT NULL
#define lora_mesh_v1_TrafficShaping_shapers_MSGTYPE lora_mesh_v1_ShaperConfig
#define lora_mesh_v1_TrafficShaping_policing_MSGTYPE lora_mesh_v1_PoliceConfig

#define lora_mesh_v1_ShaperConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   shaper_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   rate_limit_bps,    2) \
X(a, STATIC,   SINGULAR, UINT32,   burst_size,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  token_bucket,      4)
#define lora_mesh_v1_ShaperConfig_CALLBACK NULL
#define lora_mesh_v1_ShaperConfig_DEFAULT NULL
#define lora_mesh_v1_ShaperConfig_token_bucket_MSGTYPE lora_mesh_v1_TokenBucketConfig

#define lora_mesh_v1_TokenBucketConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   bucket_size,       1) \
X(a, STATIC,   SINGULAR, UINT32,   token_rate,        2) \
X(a, STATIC,   SINGULAR, UINT32,   initial_tokens,    3) \
X(a, STATIC,   SINGULAR, BOOL,     fair_queuing,      4)
#define lora_mesh_v1_TokenBucketConfig_CALLBACK NULL
#define lora_mesh_v1_TokenBucketConfig_DEFAULT NULL

#define lora_mesh_v1_PoliceConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   rate_limit_bps,    1) \
X(a, STATIC,   SINGULAR, UENUM,    exceed_action,     2) \
X(a, STATIC,   SINGULAR, UENUM,    violate_action,    3) \
X(a, STATIC,   SINGULAR, UINT32,   measurement_interval_ms,   4)
#define lora_mesh_v1_PoliceConfig_CALLBACK NULL
#define lora_mesh_v1_PoliceConfig_DEFAULT NULL

#define lora_mesh_v1_AdmissionControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     admission_control_enabled,   1) \
X(a, STATIC,   SINGULAR, UINT32,   connection_limit,   2) \
X(a, STATIC,   SINGULAR, UENUM,    policy,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  reservation,       4)
#define lora_mesh_v1_AdmissionControl_CALLBACK NULL
#define lora_mesh_v1_AdmissionControl_DEFAULT NULL
#define lora_mesh_v1_AdmissionControl_reservation_MSGTYPE lora_mesh_v1_ResourceReservation

#define lora_mesh_v1_ResourceReservation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   reserved_bandwidth_bps,   1) \
X(a, STATIC,   SINGULAR, UINT32,   reserved_buffer_size,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    cpu_reservation_percent,   3) \
X(a, STATIC,   SINGULAR, UENUM,    reservation_type,   4)
#define lora_mesh_v1_ResourceReservation_CALLBACK NULL
#define lora_mesh_v1_ResourceReservation_DEFAULT NULL

extern const pb_msgdesc_t lora_mesh_v1_MeshNetworkConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_CryptoConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_KeyRotationPolicy_msg;
extern const pb_msgdesc_t lora_mesh_v1_TopologyConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_RedundancyConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_RoutingConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_ProtocolSwitchingPolicy_msg;
extern const pb_msgdesc_t lora_mesh_v1_RouteMaintenanceConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_PerformanceConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_CompressionConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_QoSConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_ServiceClass_msg;
extern const pb_msgdesc_t lora_mesh_v1_BandwidthAllocation_msg;
extern const pb_msgdesc_t lora_mesh_v1_LatencyRequirements_msg;
extern const pb_msgdesc_t lora_mesh_v1_ReliabilityRequirements_msg;
extern const pb_msgdesc_t lora_mesh_v1_PriorityScheduling_msg;
extern const pb_msgdesc_t lora_mesh_v1_QueueConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_TrafficShaping_msg;
extern const pb_msgdesc_t lora_mesh_v1_ShaperConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_TokenBucketConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_PoliceConfig_msg;
extern const pb_msgdesc_t lora_mesh_v1_AdmissionControl_msg;
extern const pb_msgdesc_t lora_mesh_v1_ResourceReservation_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lora_mesh_v1_MeshNetworkConfig_fields &lora_mesh_v1_MeshNetworkConfig_msg
#define lora_mesh_v1_CryptoConfig_fields &lora_mesh_v1_CryptoConfig_msg
#define lora_mesh_v1_KeyRotationPolicy_fields &lora_mesh_v1_KeyRotationPolicy_msg
#define lora_mesh_v1_TopologyConfig_fields &lora_mesh_v1_TopologyConfig_msg
#define lora_mesh_v1_RedundancyConfig_fields &lora_mesh_v1_RedundancyConfig_msg
#define lora_mesh_v1_RoutingConfig_fields &lora_mesh_v1_RoutingConfig_msg
#define lora_mesh_v1_ProtocolSwitchingPolicy_fields &lora_mesh_v1_ProtocolSwitchingPolicy_msg
#define lora_mesh_v1_RouteMaintenanceConfig_fields &lora_mesh_v1_RouteMaintenanceConfig_msg
#define lora_mesh_v1_PerformanceConfig_fields &lora_mesh_v1_PerformanceConfig_msg
#define lora_mesh_v1_CompressionConfig_fields &lora_mesh_v1_CompressionConfig_msg
#define lora_mesh_v1_QoSConfig_fields &lora_mesh_v1_QoSConfig_msg
#define lora_mesh_v1_ServiceClass_fields &lora_mesh_v1_ServiceClass_msg
#define lora_mesh_v1_BandwidthAllocation_fields &lora_mesh_v1_BandwidthAllocation_msg
#define lora_mesh_v1_LatencyRequirements_fields &lora_mesh_v1_LatencyRequirements_msg
#define lora_mesh_v1_ReliabilityRequirements_fields &lora_mesh_v1_ReliabilityRequirements_msg
#define lora_mesh_v1_PriorityScheduling_fields &lora_mesh_v1_PriorityScheduling_msg
#define lora_mesh_v1_QueueConfig_fields &lora_mesh_v1_QueueConfig_msg
#define lora_mesh_v1_TrafficShaping_fields &lora_mesh_v1_TrafficShaping_msg
#define lora_mesh_v1_ShaperConfig_fields &lora_mesh_v1_ShaperConfig_msg
#define lora_mesh_v1_TokenBucketConfig_fields &lora_mesh_v1_TokenBucketConfig_msg
#define lora_mesh_v1_PoliceConfig_fields &lora_mesh_v1_PoliceConfig_msg
#define lora_mesh_v1_AdmissionControl_fields &lora_mesh_v1_AdmissionControl_msg
#define lora_mesh_v1_ResourceReservation_fields &lora_mesh_v1_ResourceReservation_msg

/* Maximum encoded size of messages (where known) */
#define LORA_MESH_V1_V1_CONFIG_PB_H_MAX_SIZE     lora_mesh_v1_MeshNetworkConfig_size
#define lora_mesh_v1_AdmissionControl_size       31
#define lora_mesh_v1_BandwidthAllocation_size    23
#define lora_mesh_v1_CompressionConfig_size      14
#define lora_mesh_v1_CryptoConfig_size           72
#define lora_mesh_v1_KeyRotationPolicy_size      20
#define lora_mesh_v1_LatencyRequirements_size    20
#define lora_mesh_v1_MeshNetworkConfig_size      1025
#define lora_mesh_v1_PerformanceConfig_size      42
#define lora_mesh_v1_PoliceConfig_size           16
#define lora_mesh_v1_PriorityScheduling_size     62
#define lora_mesh_v1_ProtocolSwitchingPolicy_size 20
#define lora_mesh_v1_QoSConfig_size              752
#define lora_mesh_v1_QueueConfig_size            12
#define lora_mesh_v1_RedundancyConfig_size       21
#define lora_mesh_v1_ReliabilityRequirements_size 19
#define lora_mesh_v1_ResourceReservation_size    19
#define lora_mesh_v1_RouteMaintenanceConfig_size 31
#define lora_mesh_v1_RoutingConfig_size          107
#define lora_mesh_v1_ServiceClass_size           103
#define lora_mesh_v1_ShaperConfig_size           51
#define lora_mesh_v1_TokenBucketConfig_size      20
#define lora_mesh_v1_TopologyConfig_size         44
#define lora_mesh_v1_TrafficShaping_size         232

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
