/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "v1/geographic.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(lora_mesh_v1_GeographicBeaconPayload, lora_mesh_v1_GeographicBeaconPayload, 2)


PB_BIND(lora_mesh_v1_PositionUpdatePayload, lora_mesh_v1_PositionUpdatePayload, 2)


PB_BIND(lora_mesh_v1_PredictedPosition, lora_mesh_v1_PredictedPosition, AUTO)


PB_BIND(lora_mesh_v1_MovementPattern, lora_mesh_v1_MovementPattern, 2)


PB_BIND(lora_mesh_v1_GeographicRegion, lora_mesh_v1_GeographicRegion, 2)


PB_BIND(lora_mesh_v1_PerimeterRoutingPayload, lora_mesh_v1_PerimeterRoutingPayload, AUTO)


PB_BIND(lora_mesh_v1_GeographicMulticastPayload, lora_mesh_v1_GeographicMulticastPayload, AUTO)


PB_BIND(lora_mesh_v1_MulticastRegion, lora_mesh_v1_MulticastRegion, AUTO)


PB_BIND(lora_mesh_v1_GeographicRouteDiscoveryPayload, lora_mesh_v1_GeographicRouteDiscoveryPayload, AUTO)


PB_BIND(lora_mesh_v1_GeographicRouteCandidate, lora_mesh_v1_GeographicRouteCandidate, AUTO)


PB_BIND(lora_mesh_v1_LocationServicePayload, lora_mesh_v1_LocationServicePayload, AUTO)


PB_BIND(lora_mesh_v1_LocationServiceResponse, lora_mesh_v1_LocationServiceResponse, AUTO)


PB_BIND(lora_mesh_v1_LocationServiceNode, lora_mesh_v1_LocationServiceNode, AUTO)

















