/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LORA_MESH_V1_V1_GEOGRAPHIC_PB_H_INCLUDED
#define PB_LORA_MESH_V1_V1_GEOGRAPHIC_PB_H_INCLUDED
#include <pb.h>
#include "v1/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _lora_mesh_v1_MovementType {
    lora_mesh_v1_MovementType_MOVEMENT_TYPE_UNSPECIFIED = 0, /* Not specified */
    lora_mesh_v1_MovementType_MOVEMENT_TYPE_STATIONARY = 1, /* Not moving */
    lora_mesh_v1_MovementType_MOVEMENT_TYPE_LINEAR = 2, /* Moving in straight line */
    lora_mesh_v1_MovementType_MOVEMENT_TYPE_CIRCULAR = 3, /* Moving in circle/loop */
    lora_mesh_v1_MovementType_MOVEMENT_TYPE_RANDOM_WALK = 4, /* Random movement */
    lora_mesh_v1_MovementType_MOVEMENT_TYPE_WAYPOINT = 5, /* Following waypoints */
    lora_mesh_v1_MovementType_MOVEMENT_TYPE_VEHICULAR = 6, /* Vehicle-like movement */
    lora_mesh_v1_MovementType_MOVEMENT_TYPE_PEDESTRIAN = 7 /* Walking movement */
} lora_mesh_v1_MovementType;

typedef enum _lora_mesh_v1_PredictionMethod {
    lora_mesh_v1_PredictionMethod_PREDICTION_METHOD_UNSPECIFIED = 0, /* Method not specified */
    lora_mesh_v1_PredictionMethod_PREDICTION_METHOD_LINEAR_EXTRAPOLATION = 1, /* Simple linear prediction */
    lora_mesh_v1_PredictionMethod_PREDICTION_METHOD_KALMAN_FILTER = 2, /* Kalman filter prediction */
    lora_mesh_v1_PredictionMethod_PREDICTION_METHOD_NEURAL_NETWORK = 3, /* AI-based prediction */
    lora_mesh_v1_PredictionMethod_PREDICTION_METHOD_PATTERN_MATCHING = 4, /* Pattern-based prediction */
    lora_mesh_v1_PredictionMethod_PREDICTION_METHOD_WEIGHTED_AVERAGE = 5 /* Moving average prediction */
} lora_mesh_v1_PredictionMethod;

typedef enum _lora_mesh_v1_GeographicShape {
    lora_mesh_v1_GeographicShape_GEOGRAPHIC_SHAPE_UNSPECIFIED = 0, /* Shape not specified */
    lora_mesh_v1_GeographicShape_GEOGRAPHIC_SHAPE_CIRCLE = 1, /* Circular region */
    lora_mesh_v1_GeographicShape_GEOGRAPHIC_SHAPE_RECTANGLE = 2, /* Rectangular region */
    lora_mesh_v1_GeographicShape_GEOGRAPHIC_SHAPE_POLYGON = 3, /* Arbitrary polygon */
    lora_mesh_v1_GeographicShape_GEOGRAPHIC_SHAPE_ELLIPSE = 4 /* Elliptical region */
} lora_mesh_v1_GeographicShape;

typedef enum _lora_mesh_v1_PerimeterDirection {
    lora_mesh_v1_PerimeterDirection_PERIMETER_DIRECTION_UNSPECIFIED = 0, /* Direction not specified */
    lora_mesh_v1_PerimeterDirection_PERIMETER_DIRECTION_CLOCKWISE = 1, /* Right-hand rule */
    lora_mesh_v1_PerimeterDirection_PERIMETER_DIRECTION_COUNTER_CLOCKWISE = 2 /* Left-hand rule */
} lora_mesh_v1_PerimeterDirection;

typedef enum _lora_mesh_v1_MulticastStrategy {
    lora_mesh_v1_MulticastStrategy_MULTICAST_STRATEGY_UNSPECIFIED = 0, /* Strategy not specified */
    lora_mesh_v1_MulticastStrategy_MULTICAST_STRATEGY_GEOGRAPHIC_FLOODING = 1, /* Flood within geographic region */
    lora_mesh_v1_MulticastStrategy_MULTICAST_STRATEGY_DENSITY_AWARE = 2, /* Adapt to node density */
    lora_mesh_v1_MulticastStrategy_MULTICAST_STRATEGY_ENERGY_EFFICIENT = 3, /* Minimize energy consumption */
    lora_mesh_v1_MulticastStrategy_MULTICAST_STRATEGY_RELIABILITY_FIRST = 4 /* Maximize delivery reliability */
} lora_mesh_v1_MulticastStrategy;

typedef enum _lora_mesh_v1_LocationServiceType {
    lora_mesh_v1_LocationServiceType_LOCATION_SERVICE_TYPE_UNSPECIFIED = 0, /* Service type not specified */
    lora_mesh_v1_LocationServiceType_LOCATION_SERVICE_TYPE_POSITION_QUERY = 1, /* Query for node position */
    lora_mesh_v1_LocationServiceType_LOCATION_SERVICE_TYPE_POSITION_UPDATE = 2, /* Update node position */
    lora_mesh_v1_LocationServiceType_LOCATION_SERVICE_TYPE_CACHE_REFRESH = 3, /* Refresh cached positions */
    lora_mesh_v1_LocationServiceType_LOCATION_SERVICE_TYPE_SERVICE_DISCOVERY = 4 /* Find location services */
} lora_mesh_v1_LocationServiceType;

typedef enum _lora_mesh_v1_RegionPriority {
    lora_mesh_v1_RegionPriority_REGION_PRIORITY_UNSPECIFIED = 0,
    lora_mesh_v1_RegionPriority_REGION_PRIORITY_LOW_PRIORITY = 1,
    lora_mesh_v1_RegionPriority_REGION_PRIORITY_NORMAL_PRIORITY = 2,
    lora_mesh_v1_RegionPriority_REGION_PRIORITY_HIGH_PRIORITY = 3,
    lora_mesh_v1_RegionPriority_REGION_PRIORITY_CRITICAL_PRIORITY = 4
} lora_mesh_v1_RegionPriority;

/* Struct definitions */
/* Predicted future position */
typedef struct _lora_mesh_v1_PredictedPosition {
    bool has_predicted_position;
    lora_mesh_v1_GPSCoordinate predicted_position; /* Predicted coordinate */
    uint64_t prediction_time; /* When node will be at position */
    float confidence; /* Prediction confidence 0.0-1.0 */
    lora_mesh_v1_PredictionMethod method; /* Method used for prediction */
} lora_mesh_v1_PredictedPosition;

/* Movement pattern detection */
typedef struct _lora_mesh_v1_MovementPattern {
    lora_mesh_v1_MovementType pattern_type; /* Type of movement detected */
    float pattern_confidence; /* Confidence in pattern 0.0-1.0 */
    pb_size_t waypoints_count;
    lora_mesh_v1_GPSCoordinate waypoints[8]; /* Key points in movement */
    uint32_t pattern_period_seconds; /* Period of cyclic patterns */
    float average_speed; /* Average movement speed */
    pb_callback_t pattern_description; /* Human-readable description */
} lora_mesh_v1_MovementPattern;

/* Position update for predictive routing */
typedef struct _lora_mesh_v1_PositionUpdatePayload {
    pb_callback_t node_id; /* Node reporting position */
    bool has_position;
    lora_mesh_v1_GPSCoordinate position; /* Current position */
    bool has_velocity;
    lora_mesh_v1_Velocity velocity; /* Current velocity */
    float position_confidence; /* Position accuracy 0.0-1.0 */
    uint64_t update_timestamp; /* When position was recorded */
    /* Predictive information */
    pb_size_t predictions_count;
    lora_mesh_v1_PredictedPosition predictions[4]; /* Future position predictions */
    bool has_movement_pattern;
    lora_mesh_v1_MovementPattern movement_pattern; /* Detected movement pattern */
    uint32_t prediction_horizon_seconds; /* How far ahead predictions valid */
} lora_mesh_v1_PositionUpdatePayload;

/* Geographic region definition */
typedef struct _lora_mesh_v1_GeographicRegion {
    pb_callback_t region_id; /* Unique region identifier */
    lora_mesh_v1_GeographicShape shape; /* Shape of the region */
    pb_size_t boundary_points_count;
    lora_mesh_v1_GPSCoordinate boundary_points[8]; /* Region boundary */
    float coverage_radius; /* Coverage radius in meters */
    lora_mesh_v1_RegionPriority priority; /* Region importance */
    pb_callback_t region_name; /* Human-readable name */
} lora_mesh_v1_GeographicRegion;

/* Geographic routing beacon message */
typedef struct _lora_mesh_v1_GeographicBeaconPayload {
    bool has_beacon_node;
    lora_mesh_v1_NodeInfo beacon_node; /* Node sending beacon */
    pb_size_t geographic_neighbors_count;
    lora_mesh_v1_NeighborInfo geographic_neighbors[8]; /* Neighbors with positions */
    bool has_current_position;
    lora_mesh_v1_GPSCoordinate current_position; /* Current GPS position */
    bool has_current_velocity;
    lora_mesh_v1_Velocity current_velocity; /* Current movement vector */
    /* Geographic routing specific information */
    lora_mesh_v1_GeographicRoutingMode supported_modes; /* Supported routing modes */
    float forwarding_radius; /* Effective forwarding radius */
    uint32_t position_update_interval; /* GPS update frequency */
    bool is_mobile; /* Mobility indicator */
    pb_size_t coverage_areas_count;
    lora_mesh_v1_GeographicRegion coverage_areas[4]; /* Areas this node covers */
} lora_mesh_v1_GeographicBeaconPayload;

/* Perimeter routing message */
typedef struct _lora_mesh_v1_PerimeterRoutingPayload {
    pb_callback_t originator_id; /* Node starting perimeter routing */
    bool has_destination_position;
    lora_mesh_v1_GPSCoordinate destination_position; /* Target position */
    bool has_void_entry_point;
    lora_mesh_v1_GPSCoordinate void_entry_point; /* Where perimeter routing started */
    lora_mesh_v1_PerimeterDirection direction; /* Direction around perimeter */
    pb_callback_t perimeter_path; /* Path taken so far */
    uint32_t max_perimeter_hops; /* Maximum hops in perimeter mode */
    bool return_to_greedy; /* Try to return to greedy forwarding */
} lora_mesh_v1_PerimeterRoutingPayload;

/* Multicast region specification */
typedef struct _lora_mesh_v1_MulticastRegion {
    bool has_center;
    lora_mesh_v1_GPSCoordinate center; /* Center of multicast region */
    float radius; /* Radius in meters */
    lora_mesh_v1_GeographicShape shape; /* Shape of region */
    pb_callback_t polygon_points; /* For polygon regions */
    lora_mesh_v1_RegionPriority priority; /* Delivery priority */
} lora_mesh_v1_MulticastRegion;

/* Geographic multicast message */
typedef struct _lora_mesh_v1_GeographicMulticastPayload {
    bool has_target_region;
    lora_mesh_v1_MulticastRegion target_region; /* Target geographic region */
    pb_callback_t originator_id; /* Node initiating multicast */
    pb_callback_t multicast_payload; /* Actual multicast data */
    lora_mesh_v1_MulticastStrategy strategy; /* Multicast forwarding strategy */
    uint32_t hop_limit; /* Maximum forwarding hops */
    pb_callback_t reached_nodes; /* Nodes that received message */
} lora_mesh_v1_GeographicMulticastPayload;

/* Geographic route discovery message */
typedef struct _lora_mesh_v1_GeographicRouteDiscoveryPayload {
    pb_callback_t originator_id; /* Node initiating discovery */
    bool has_destination_position;
    lora_mesh_v1_GPSCoordinate destination_position; /* Target position (approximate) */
    float destination_radius; /* Acceptable proximity to target */
    lora_mesh_v1_GeographicRoutingMode preferred_mode; /* Preferred routing mode */
    uint32_t discovery_timeout; /* Discovery timeout */
    pb_callback_t candidates; /* Route candidates found */
} lora_mesh_v1_GeographicRouteDiscoveryPayload;

/* Geographic route candidate */
typedef struct _lora_mesh_v1_GeographicRouteCandidate {
    pb_callback_t candidate_id; /* Candidate node ID */
    bool has_candidate_position;
    lora_mesh_v1_GPSCoordinate candidate_position; /* Candidate position */
    float distance_to_target; /* Distance to target */
    float route_quality; /* Quality score 0.0-1.0 */
    uint32_t hop_count; /* Hops to reach candidate */
    bool has_link_quality;
    lora_mesh_v1_LinkQuality link_quality; /* Link quality to candidate */
} lora_mesh_v1_GeographicRouteCandidate;

/* Location service response */
typedef struct _lora_mesh_v1_LocationServiceResponse {
    bool position_found; /* Whether position was found */
    bool has_current_position;
    lora_mesh_v1_GPSCoordinate current_position; /* Current position if known */
    float position_age_seconds; /* Age of position data */
    pb_callback_t location_servers; /* Alternative servers */
    pb_callback_t error_message; /* Error description if failed */
} lora_mesh_v1_LocationServiceResponse;

/* Location service message for position queries */
typedef struct _lora_mesh_v1_LocationServicePayload {
    lora_mesh_v1_LocationServiceType service_type; /* Type of location service */
    pb_callback_t target_node_id; /* Node being queried */
    pb_callback_t requesting_node_id; /* Node making request */
    bool has_last_known_position;
    lora_mesh_v1_GPSCoordinate last_known_position; /* Last known position of target */
    uint64_t last_update_time; /* When position was last updated */
    bool has_response;
    lora_mesh_v1_LocationServiceResponse response; /* Response data */
} lora_mesh_v1_LocationServicePayload;

/* Location service node information */
typedef struct _lora_mesh_v1_LocationServiceNode {
    pb_callback_t node_id; /* Location server node ID */
    bool has_server_position;
    lora_mesh_v1_GPSCoordinate server_position; /* Server position */
    pb_callback_t cached_nodes; /* Nodes with cached positions */
    uint32_t cache_size; /* Number of cached positions */
    float coverage_radius; /* Service coverage radius */
} lora_mesh_v1_LocationServiceNode;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _lora_mesh_v1_MovementType_MIN lora_mesh_v1_MovementType_MOVEMENT_TYPE_UNSPECIFIED
#define _lora_mesh_v1_MovementType_MAX lora_mesh_v1_MovementType_MOVEMENT_TYPE_PEDESTRIAN
#define _lora_mesh_v1_MovementType_ARRAYSIZE ((lora_mesh_v1_MovementType)(lora_mesh_v1_MovementType_MOVEMENT_TYPE_PEDESTRIAN+1))

#define _lora_mesh_v1_PredictionMethod_MIN lora_mesh_v1_PredictionMethod_PREDICTION_METHOD_UNSPECIFIED
#define _lora_mesh_v1_PredictionMethod_MAX lora_mesh_v1_PredictionMethod_PREDICTION_METHOD_WEIGHTED_AVERAGE
#define _lora_mesh_v1_PredictionMethod_ARRAYSIZE ((lora_mesh_v1_PredictionMethod)(lora_mesh_v1_PredictionMethod_PREDICTION_METHOD_WEIGHTED_AVERAGE+1))

#define _lora_mesh_v1_GeographicShape_MIN lora_mesh_v1_GeographicShape_GEOGRAPHIC_SHAPE_UNSPECIFIED
#define _lora_mesh_v1_GeographicShape_MAX lora_mesh_v1_GeographicShape_GEOGRAPHIC_SHAPE_ELLIPSE
#define _lora_mesh_v1_GeographicShape_ARRAYSIZE ((lora_mesh_v1_GeographicShape)(lora_mesh_v1_GeographicShape_GEOGRAPHIC_SHAPE_ELLIPSE+1))

#define _lora_mesh_v1_PerimeterDirection_MIN lora_mesh_v1_PerimeterDirection_PERIMETER_DIRECTION_UNSPECIFIED
#define _lora_mesh_v1_PerimeterDirection_MAX lora_mesh_v1_PerimeterDirection_PERIMETER_DIRECTION_COUNTER_CLOCKWISE
#define _lora_mesh_v1_PerimeterDirection_ARRAYSIZE ((lora_mesh_v1_PerimeterDirection)(lora_mesh_v1_PerimeterDirection_PERIMETER_DIRECTION_COUNTER_CLOCKWISE+1))

#define _lora_mesh_v1_MulticastStrategy_MIN lora_mesh_v1_MulticastStrategy_MULTICAST_STRATEGY_UNSPECIFIED
#define _lora_mesh_v1_MulticastStrategy_MAX lora_mesh_v1_MulticastStrategy_MULTICAST_STRATEGY_RELIABILITY_FIRST
#define _lora_mesh_v1_MulticastStrategy_ARRAYSIZE ((lora_mesh_v1_MulticastStrategy)(lora_mesh_v1_MulticastStrategy_MULTICAST_STRATEGY_RELIABILITY_FIRST+1))

#define _lora_mesh_v1_LocationServiceType_MIN lora_mesh_v1_LocationServiceType_LOCATION_SERVICE_TYPE_UNSPECIFIED
#define _lora_mesh_v1_LocationServiceType_MAX lora_mesh_v1_LocationServiceType_LOCATION_SERVICE_TYPE_SERVICE_DISCOVERY
#define _lora_mesh_v1_LocationServiceType_ARRAYSIZE ((lora_mesh_v1_LocationServiceType)(lora_mesh_v1_LocationServiceType_LOCATION_SERVICE_TYPE_SERVICE_DISCOVERY+1))

#define _lora_mesh_v1_RegionPriority_MIN lora_mesh_v1_RegionPriority_REGION_PRIORITY_UNSPECIFIED
#define _lora_mesh_v1_RegionPriority_MAX lora_mesh_v1_RegionPriority_REGION_PRIORITY_CRITICAL_PRIORITY
#define _lora_mesh_v1_RegionPriority_ARRAYSIZE ((lora_mesh_v1_RegionPriority)(lora_mesh_v1_RegionPriority_REGION_PRIORITY_CRITICAL_PRIORITY+1))

#define lora_mesh_v1_GeographicBeaconPayload_supported_modes_ENUMTYPE lora_mesh_v1_GeographicRoutingMode


#define lora_mesh_v1_PredictedPosition_method_ENUMTYPE lora_mesh_v1_PredictionMethod

#define lora_mesh_v1_MovementPattern_pattern_type_ENUMTYPE lora_mesh_v1_MovementType

#define lora_mesh_v1_GeographicRegion_shape_ENUMTYPE lora_mesh_v1_GeographicShape
#define lora_mesh_v1_GeographicRegion_priority_ENUMTYPE lora_mesh_v1_RegionPriority

#define lora_mesh_v1_PerimeterRoutingPayload_direction_ENUMTYPE lora_mesh_v1_PerimeterDirection

#define lora_mesh_v1_GeographicMulticastPayload_strategy_ENUMTYPE lora_mesh_v1_MulticastStrategy

#define lora_mesh_v1_MulticastRegion_shape_ENUMTYPE lora_mesh_v1_GeographicShape
#define lora_mesh_v1_MulticastRegion_priority_ENUMTYPE lora_mesh_v1_RegionPriority

#define lora_mesh_v1_GeographicRouteDiscoveryPayload_preferred_mode_ENUMTYPE lora_mesh_v1_GeographicRoutingMode


#define lora_mesh_v1_LocationServicePayload_service_type_ENUMTYPE lora_mesh_v1_LocationServiceType




/* Initializer values for message structs */
#define lora_mesh_v1_GeographicBeaconPayload_init_default {false, lora_mesh_v1_NodeInfo_init_default, 0, {lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default}, false, lora_mesh_v1_GPSCoordinate_init_default, false, lora_mesh_v1_Velocity_init_default, _lora_mesh_v1_GeographicRoutingMode_MIN, 0, 0, 0, 0, {lora_mesh_v1_GeographicRegion_init_default, lora_mesh_v1_GeographicRegion_init_default, lora_mesh_v1_GeographicRegion_init_default, lora_mesh_v1_GeographicRegion_init_default}}
#define lora_mesh_v1_PositionUpdatePayload_init_default {{{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_default, false, lora_mesh_v1_Velocity_init_default, 0, 0, 0, {lora_mesh_v1_PredictedPosition_init_default, lora_mesh_v1_PredictedPosition_init_default, lora_mesh_v1_PredictedPosition_init_default, lora_mesh_v1_PredictedPosition_init_default}, false, lora_mesh_v1_MovementPattern_init_default, 0}
#define lora_mesh_v1_PredictedPosition_init_default {false, lora_mesh_v1_GPSCoordinate_init_default, 0, 0, _lora_mesh_v1_PredictionMethod_MIN}
#define lora_mesh_v1_MovementPattern_init_default {_lora_mesh_v1_MovementType_MIN, 0, 0, {lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default}, 0, 0, {{NULL}, NULL}}
#define lora_mesh_v1_GeographicRegion_init_default {{{NULL}, NULL}, _lora_mesh_v1_GeographicShape_MIN, 0, {lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default, lora_mesh_v1_GPSCoordinate_init_default}, 0, _lora_mesh_v1_RegionPriority_MIN, {{NULL}, NULL}}
#define lora_mesh_v1_PerimeterRoutingPayload_init_default {{{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_default, false, lora_mesh_v1_GPSCoordinate_init_default, _lora_mesh_v1_PerimeterDirection_MIN, {{NULL}, NULL}, 0, 0}
#define lora_mesh_v1_GeographicMulticastPayload_init_default {false, lora_mesh_v1_MulticastRegion_init_default, {{NULL}, NULL}, {{NULL}, NULL}, _lora_mesh_v1_MulticastStrategy_MIN, 0, {{NULL}, NULL}}
#define lora_mesh_v1_MulticastRegion_init_default {false, lora_mesh_v1_GPSCoordinate_init_default, 0, _lora_mesh_v1_GeographicShape_MIN, {{NULL}, NULL}, _lora_mesh_v1_RegionPriority_MIN}
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_init_default {{{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_default, 0, _lora_mesh_v1_GeographicRoutingMode_MIN, 0, {{NULL}, NULL}}
#define lora_mesh_v1_GeographicRouteCandidate_init_default {{{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_default, 0, 0, 0, false, lora_mesh_v1_LinkQuality_init_default}
#define lora_mesh_v1_LocationServicePayload_init_default {_lora_mesh_v1_LocationServiceType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_default, 0, false, lora_mesh_v1_LocationServiceResponse_init_default}
#define lora_mesh_v1_LocationServiceResponse_init_default {0, false, lora_mesh_v1_GPSCoordinate_init_default, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lora_mesh_v1_LocationServiceNode_init_default {{{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_default, {{NULL}, NULL}, 0, 0}
#define lora_mesh_v1_GeographicBeaconPayload_init_zero {false, lora_mesh_v1_NodeInfo_init_zero, 0, {lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero}, false, lora_mesh_v1_GPSCoordinate_init_zero, false, lora_mesh_v1_Velocity_init_zero, _lora_mesh_v1_GeographicRoutingMode_MIN, 0, 0, 0, 0, {lora_mesh_v1_GeographicRegion_init_zero, lora_mesh_v1_GeographicRegion_init_zero, lora_mesh_v1_GeographicRegion_init_zero, lora_mesh_v1_GeographicRegion_init_zero}}
#define lora_mesh_v1_PositionUpdatePayload_init_zero {{{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_zero, false, lora_mesh_v1_Velocity_init_zero, 0, 0, 0, {lora_mesh_v1_PredictedPosition_init_zero, lora_mesh_v1_PredictedPosition_init_zero, lora_mesh_v1_PredictedPosition_init_zero, lora_mesh_v1_PredictedPosition_init_zero}, false, lora_mesh_v1_MovementPattern_init_zero, 0}
#define lora_mesh_v1_PredictedPosition_init_zero {false, lora_mesh_v1_GPSCoordinate_init_zero, 0, 0, _lora_mesh_v1_PredictionMethod_MIN}
#define lora_mesh_v1_MovementPattern_init_zero   {_lora_mesh_v1_MovementType_MIN, 0, 0, {lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero}, 0, 0, {{NULL}, NULL}}
#define lora_mesh_v1_GeographicRegion_init_zero  {{{NULL}, NULL}, _lora_mesh_v1_GeographicShape_MIN, 0, {lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero, lora_mesh_v1_GPSCoordinate_init_zero}, 0, _lora_mesh_v1_RegionPriority_MIN, {{NULL}, NULL}}
#define lora_mesh_v1_PerimeterRoutingPayload_init_zero {{{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_zero, false, lora_mesh_v1_GPSCoordinate_init_zero, _lora_mesh_v1_PerimeterDirection_MIN, {{NULL}, NULL}, 0, 0}
#define lora_mesh_v1_GeographicMulticastPayload_init_zero {false, lora_mesh_v1_MulticastRegion_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, _lora_mesh_v1_MulticastStrategy_MIN, 0, {{NULL}, NULL}}
#define lora_mesh_v1_MulticastRegion_init_zero   {false, lora_mesh_v1_GPSCoordinate_init_zero, 0, _lora_mesh_v1_GeographicShape_MIN, {{NULL}, NULL}, _lora_mesh_v1_RegionPriority_MIN}
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_init_zero {{{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_zero, 0, _lora_mesh_v1_GeographicRoutingMode_MIN, 0, {{NULL}, NULL}}
#define lora_mesh_v1_GeographicRouteCandidate_init_zero {{{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_zero, 0, 0, 0, false, lora_mesh_v1_LinkQuality_init_zero}
#define lora_mesh_v1_LocationServicePayload_init_zero {_lora_mesh_v1_LocationServiceType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_zero, 0, false, lora_mesh_v1_LocationServiceResponse_init_zero}
#define lora_mesh_v1_LocationServiceResponse_init_zero {0, false, lora_mesh_v1_GPSCoordinate_init_zero, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lora_mesh_v1_LocationServiceNode_init_zero {{{NULL}, NULL}, false, lora_mesh_v1_GPSCoordinate_init_zero, {{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define lora_mesh_v1_PredictedPosition_predicted_position_tag 1
#define lora_mesh_v1_PredictedPosition_prediction_time_tag 2
#define lora_mesh_v1_PredictedPosition_confidence_tag 3
#define lora_mesh_v1_PredictedPosition_method_tag 4
#define lora_mesh_v1_MovementPattern_pattern_type_tag 1
#define lora_mesh_v1_MovementPattern_pattern_confidence_tag 2
#define lora_mesh_v1_MovementPattern_waypoints_tag 3
#define lora_mesh_v1_MovementPattern_pattern_period_seconds_tag 4
#define lora_mesh_v1_MovementPattern_average_speed_tag 5
#define lora_mesh_v1_MovementPattern_pattern_description_tag 6
#define lora_mesh_v1_PositionUpdatePayload_node_id_tag 1
#define lora_mesh_v1_PositionUpdatePayload_position_tag 2
#define lora_mesh_v1_PositionUpdatePayload_velocity_tag 3
#define lora_mesh_v1_PositionUpdatePayload_position_confidence_tag 4
#define lora_mesh_v1_PositionUpdatePayload_update_timestamp_tag 5
#define lora_mesh_v1_PositionUpdatePayload_predictions_tag 6
#define lora_mesh_v1_PositionUpdatePayload_movement_pattern_tag 7
#define lora_mesh_v1_PositionUpdatePayload_prediction_horizon_seconds_tag 8
#define lora_mesh_v1_GeographicRegion_region_id_tag 1
#define lora_mesh_v1_GeographicRegion_shape_tag  2
#define lora_mesh_v1_GeographicRegion_boundary_points_tag 3
#define lora_mesh_v1_GeographicRegion_coverage_radius_tag 4
#define lora_mesh_v1_GeographicRegion_priority_tag 5
#define lora_mesh_v1_GeographicRegion_region_name_tag 6
#define lora_mesh_v1_GeographicBeaconPayload_beacon_node_tag 1
#define lora_mesh_v1_GeographicBeaconPayload_geographic_neighbors_tag 2
#define lora_mesh_v1_GeographicBeaconPayload_current_position_tag 3
#define lora_mesh_v1_GeographicBeaconPayload_current_velocity_tag 4
#define lora_mesh_v1_GeographicBeaconPayload_supported_modes_tag 5
#define lora_mesh_v1_GeographicBeaconPayload_forwarding_radius_tag 6
#define lora_mesh_v1_GeographicBeaconPayload_position_update_interval_tag 7
#define lora_mesh_v1_GeographicBeaconPayload_is_mobile_tag 8
#define lora_mesh_v1_GeographicBeaconPayload_coverage_areas_tag 9
#define lora_mesh_v1_PerimeterRoutingPayload_originator_id_tag 1
#define lora_mesh_v1_PerimeterRoutingPayload_destination_position_tag 2
#define lora_mesh_v1_PerimeterRoutingPayload_void_entry_point_tag 3
#define lora_mesh_v1_PerimeterRoutingPayload_direction_tag 4
#define lora_mesh_v1_PerimeterRoutingPayload_perimeter_path_tag 5
#define lora_mesh_v1_PerimeterRoutingPayload_max_perimeter_hops_tag 6
#define lora_mesh_v1_PerimeterRoutingPayload_return_to_greedy_tag 7
#define lora_mesh_v1_MulticastRegion_center_tag  1
#define lora_mesh_v1_MulticastRegion_radius_tag  2
#define lora_mesh_v1_MulticastRegion_shape_tag   3
#define lora_mesh_v1_MulticastRegion_polygon_points_tag 4
#define lora_mesh_v1_MulticastRegion_priority_tag 5
#define lora_mesh_v1_GeographicMulticastPayload_target_region_tag 1
#define lora_mesh_v1_GeographicMulticastPayload_originator_id_tag 2
#define lora_mesh_v1_GeographicMulticastPayload_multicast_payload_tag 3
#define lora_mesh_v1_GeographicMulticastPayload_strategy_tag 4
#define lora_mesh_v1_GeographicMulticastPayload_hop_limit_tag 5
#define lora_mesh_v1_GeographicMulticastPayload_reached_nodes_tag 6
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_originator_id_tag 1
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_destination_position_tag 2
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_destination_radius_tag 3
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_preferred_mode_tag 4
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_discovery_timeout_tag 5
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_candidates_tag 6
#define lora_mesh_v1_GeographicRouteCandidate_candidate_id_tag 1
#define lora_mesh_v1_GeographicRouteCandidate_candidate_position_tag 2
#define lora_mesh_v1_GeographicRouteCandidate_distance_to_target_tag 3
#define lora_mesh_v1_GeographicRouteCandidate_route_quality_tag 4
#define lora_mesh_v1_GeographicRouteCandidate_hop_count_tag 5
#define lora_mesh_v1_GeographicRouteCandidate_link_quality_tag 6
#define lora_mesh_v1_LocationServiceResponse_position_found_tag 1
#define lora_mesh_v1_LocationServiceResponse_current_position_tag 2
#define lora_mesh_v1_LocationServiceResponse_position_age_seconds_tag 3
#define lora_mesh_v1_LocationServiceResponse_location_servers_tag 4
#define lora_mesh_v1_LocationServiceResponse_error_message_tag 5
#define lora_mesh_v1_LocationServicePayload_service_type_tag 1
#define lora_mesh_v1_LocationServicePayload_target_node_id_tag 2
#define lora_mesh_v1_LocationServicePayload_requesting_node_id_tag 3
#define lora_mesh_v1_LocationServicePayload_last_known_position_tag 4
#define lora_mesh_v1_LocationServicePayload_last_update_time_tag 5
#define lora_mesh_v1_LocationServicePayload_response_tag 6
#define lora_mesh_v1_LocationServiceNode_node_id_tag 1
#define lora_mesh_v1_LocationServiceNode_server_position_tag 2
#define lora_mesh_v1_LocationServiceNode_cached_nodes_tag 3
#define lora_mesh_v1_LocationServiceNode_cache_size_tag 4
#define lora_mesh_v1_LocationServiceNode_coverage_radius_tag 5

/* Struct field encoding specification for nanopb */
#define lora_mesh_v1_GeographicBeaconPayload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  beacon_node,       1) \
X(a, STATIC,   REPEATED, MESSAGE,  geographic_neighbors,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  current_position,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  current_velocity,   4) \
X(a, STATIC,   SINGULAR, UENUM,    supported_modes,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    forwarding_radius,   6) \
X(a, STATIC,   SINGULAR, UINT32,   position_update_interval,   7) \
X(a, STATIC,   SINGULAR, BOOL,     is_mobile,         8) \
X(a, STATIC,   REPEATED, MESSAGE,  coverage_areas,    9)
#define lora_mesh_v1_GeographicBeaconPayload_CALLBACK NULL
#define lora_mesh_v1_GeographicBeaconPayload_DEFAULT NULL
#define lora_mesh_v1_GeographicBeaconPayload_beacon_node_MSGTYPE lora_mesh_v1_NodeInfo
#define lora_mesh_v1_GeographicBeaconPayload_geographic_neighbors_MSGTYPE lora_mesh_v1_NeighborInfo
#define lora_mesh_v1_GeographicBeaconPayload_current_position_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_GeographicBeaconPayload_current_velocity_MSGTYPE lora_mesh_v1_Velocity
#define lora_mesh_v1_GeographicBeaconPayload_coverage_areas_MSGTYPE lora_mesh_v1_GeographicRegion

#define lora_mesh_v1_PositionUpdatePayload_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  velocity,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    position_confidence,   4) \
X(a, STATIC,   SINGULAR, UINT64,   update_timestamp,   5) \
X(a, STATIC,   REPEATED, MESSAGE,  predictions,       6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  movement_pattern,   7) \
X(a, STATIC,   SINGULAR, UINT32,   prediction_horizon_seconds,   8)
#define lora_mesh_v1_PositionUpdatePayload_CALLBACK pb_default_field_callback
#define lora_mesh_v1_PositionUpdatePayload_DEFAULT NULL
#define lora_mesh_v1_PositionUpdatePayload_position_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_PositionUpdatePayload_velocity_MSGTYPE lora_mesh_v1_Velocity
#define lora_mesh_v1_PositionUpdatePayload_predictions_MSGTYPE lora_mesh_v1_PredictedPosition
#define lora_mesh_v1_PositionUpdatePayload_movement_pattern_MSGTYPE lora_mesh_v1_MovementPattern

#define lora_mesh_v1_PredictedPosition_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  predicted_position,   1) \
X(a, STATIC,   SINGULAR, UINT64,   prediction_time,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    confidence,        3) \
X(a, STATIC,   SINGULAR, UENUM,    method,            4)
#define lora_mesh_v1_PredictedPosition_CALLBACK NULL
#define lora_mesh_v1_PredictedPosition_DEFAULT NULL
#define lora_mesh_v1_PredictedPosition_predicted_position_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_MovementPattern_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    pattern_type,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    pattern_confidence,   2) \
X(a, STATIC,   REPEATED, MESSAGE,  waypoints,         3) \
X(a, STATIC,   SINGULAR, UINT32,   pattern_period_seconds,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    average_speed,     5) \
X(a, CALLBACK, SINGULAR, STRING,   pattern_description,   6)
#define lora_mesh_v1_MovementPattern_CALLBACK pb_default_field_callback
#define lora_mesh_v1_MovementPattern_DEFAULT NULL
#define lora_mesh_v1_MovementPattern_waypoints_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_GeographicRegion_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   region_id,         1) \
X(a, STATIC,   SINGULAR, UENUM,    shape,             2) \
X(a, STATIC,   REPEATED, MESSAGE,  boundary_points,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    coverage_radius,   4) \
X(a, STATIC,   SINGULAR, UENUM,    priority,          5) \
X(a, CALLBACK, SINGULAR, STRING,   region_name,       6)
#define lora_mesh_v1_GeographicRegion_CALLBACK pb_default_field_callback
#define lora_mesh_v1_GeographicRegion_DEFAULT NULL
#define lora_mesh_v1_GeographicRegion_boundary_points_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_PerimeterRoutingPayload_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   originator_id,     1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  destination_position,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  void_entry_point,   3) \
X(a, STATIC,   SINGULAR, UENUM,    direction,         4) \
X(a, CALLBACK, REPEATED, MESSAGE,  perimeter_path,    5) \
X(a, STATIC,   SINGULAR, UINT32,   max_perimeter_hops,   6) \
X(a, STATIC,   SINGULAR, BOOL,     return_to_greedy,   7)
#define lora_mesh_v1_PerimeterRoutingPayload_CALLBACK pb_default_field_callback
#define lora_mesh_v1_PerimeterRoutingPayload_DEFAULT NULL
#define lora_mesh_v1_PerimeterRoutingPayload_destination_position_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_PerimeterRoutingPayload_void_entry_point_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_PerimeterRoutingPayload_perimeter_path_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_GeographicMulticastPayload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  target_region,     1) \
X(a, CALLBACK, SINGULAR, STRING,   originator_id,     2) \
X(a, CALLBACK, SINGULAR, BYTES,    multicast_payload,   3) \
X(a, STATIC,   SINGULAR, UENUM,    strategy,          4) \
X(a, STATIC,   SINGULAR, UINT32,   hop_limit,         5) \
X(a, CALLBACK, REPEATED, STRING,   reached_nodes,     6)
#define lora_mesh_v1_GeographicMulticastPayload_CALLBACK pb_default_field_callback
#define lora_mesh_v1_GeographicMulticastPayload_DEFAULT NULL
#define lora_mesh_v1_GeographicMulticastPayload_target_region_MSGTYPE lora_mesh_v1_MulticastRegion

#define lora_mesh_v1_MulticastRegion_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  center,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    radius,            2) \
X(a, STATIC,   SINGULAR, UENUM,    shape,             3) \
X(a, CALLBACK, REPEATED, MESSAGE,  polygon_points,    4) \
X(a, STATIC,   SINGULAR, UENUM,    priority,          5)
#define lora_mesh_v1_MulticastRegion_CALLBACK pb_default_field_callback
#define lora_mesh_v1_MulticastRegion_DEFAULT NULL
#define lora_mesh_v1_MulticastRegion_center_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_MulticastRegion_polygon_points_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_GeographicRouteDiscoveryPayload_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   originator_id,     1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  destination_position,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    destination_radius,   3) \
X(a, STATIC,   SINGULAR, UENUM,    preferred_mode,    4) \
X(a, STATIC,   SINGULAR, UINT32,   discovery_timeout,   5) \
X(a, CALLBACK, REPEATED, MESSAGE,  candidates,        6)
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_CALLBACK pb_default_field_callback
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_DEFAULT NULL
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_destination_position_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_candidates_MSGTYPE lora_mesh_v1_GeographicRouteCandidate

#define lora_mesh_v1_GeographicRouteCandidate_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   candidate_id,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  candidate_position,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    distance_to_target,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    route_quality,     4) \
X(a, STATIC,   SINGULAR, UINT32,   hop_count,         5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  link_quality,      6)
#define lora_mesh_v1_GeographicRouteCandidate_CALLBACK pb_default_field_callback
#define lora_mesh_v1_GeographicRouteCandidate_DEFAULT NULL
#define lora_mesh_v1_GeographicRouteCandidate_candidate_position_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_GeographicRouteCandidate_link_quality_MSGTYPE lora_mesh_v1_LinkQuality

#define lora_mesh_v1_LocationServicePayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    service_type,      1) \
X(a, CALLBACK, SINGULAR, STRING,   target_node_id,    2) \
X(a, CALLBACK, SINGULAR, STRING,   requesting_node_id,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  last_known_position,   4) \
X(a, STATIC,   SINGULAR, UINT64,   last_update_time,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  response,          6)
#define lora_mesh_v1_LocationServicePayload_CALLBACK pb_default_field_callback
#define lora_mesh_v1_LocationServicePayload_DEFAULT NULL
#define lora_mesh_v1_LocationServicePayload_last_known_position_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_LocationServicePayload_response_MSGTYPE lora_mesh_v1_LocationServiceResponse

#define lora_mesh_v1_LocationServiceResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     position_found,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  current_position,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    position_age_seconds,   3) \
X(a, CALLBACK, REPEATED, MESSAGE,  location_servers,   4) \
X(a, CALLBACK, SINGULAR, STRING,   error_message,     5)
#define lora_mesh_v1_LocationServiceResponse_CALLBACK pb_default_field_callback
#define lora_mesh_v1_LocationServiceResponse_DEFAULT NULL
#define lora_mesh_v1_LocationServiceResponse_current_position_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_LocationServiceResponse_location_servers_MSGTYPE lora_mesh_v1_LocationServiceNode

#define lora_mesh_v1_LocationServiceNode_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  server_position,   2) \
X(a, CALLBACK, REPEATED, STRING,   cached_nodes,      3) \
X(a, STATIC,   SINGULAR, UINT32,   cache_size,        4) \
X(a, STATIC,   SINGULAR, FLOAT,    coverage_radius,   5)
#define lora_mesh_v1_LocationServiceNode_CALLBACK pb_default_field_callback
#define lora_mesh_v1_LocationServiceNode_DEFAULT NULL
#define lora_mesh_v1_LocationServiceNode_server_position_MSGTYPE lora_mesh_v1_GPSCoordinate

extern const pb_msgdesc_t lora_mesh_v1_GeographicBeaconPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_PositionUpdatePayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_PredictedPosition_msg;
extern const pb_msgdesc_t lora_mesh_v1_MovementPattern_msg;
extern const pb_msgdesc_t lora_mesh_v1_GeographicRegion_msg;
extern const pb_msgdesc_t lora_mesh_v1_PerimeterRoutingPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_GeographicMulticastPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_MulticastRegion_msg;
extern const pb_msgdesc_t lora_mesh_v1_GeographicRouteDiscoveryPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_GeographicRouteCandidate_msg;
extern const pb_msgdesc_t lora_mesh_v1_LocationServicePayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_LocationServiceResponse_msg;
extern const pb_msgdesc_t lora_mesh_v1_LocationServiceNode_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lora_mesh_v1_GeographicBeaconPayload_fields &lora_mesh_v1_GeographicBeaconPayload_msg
#define lora_mesh_v1_PositionUpdatePayload_fields &lora_mesh_v1_PositionUpdatePayload_msg
#define lora_mesh_v1_PredictedPosition_fields &lora_mesh_v1_PredictedPosition_msg
#define lora_mesh_v1_MovementPattern_fields &lora_mesh_v1_MovementPattern_msg
#define lora_mesh_v1_GeographicRegion_fields &lora_mesh_v1_GeographicRegion_msg
#define lora_mesh_v1_PerimeterRoutingPayload_fields &lora_mesh_v1_PerimeterRoutingPayload_msg
#define lora_mesh_v1_GeographicMulticastPayload_fields &lora_mesh_v1_GeographicMulticastPayload_msg
#define lora_mesh_v1_MulticastRegion_fields &lora_mesh_v1_MulticastRegion_msg
#define lora_mesh_v1_GeographicRouteDiscoveryPayload_fields &lora_mesh_v1_GeographicRouteDiscoveryPayload_msg
#define lora_mesh_v1_GeographicRouteCandidate_fields &lora_mesh_v1_GeographicRouteCandidate_msg
#define lora_mesh_v1_LocationServicePayload_fields &lora_mesh_v1_LocationServicePayload_msg
#define lora_mesh_v1_LocationServiceResponse_fields &lora_mesh_v1_LocationServiceResponse_msg
#define lora_mesh_v1_LocationServiceNode_fields &lora_mesh_v1_LocationServiceNode_msg

/* Maximum encoded size of messages (where known) */
/* lora_mesh_v1_GeographicBeaconPayload_size depends on runtime parameters */
/* lora_mesh_v1_PositionUpdatePayload_size depends on runtime parameters */
/* lora_mesh_v1_MovementPattern_size depends on runtime parameters */
/* lora_mesh_v1_GeographicRegion_size depends on runtime parameters */
/* lora_mesh_v1_PerimeterRoutingPayload_size depends on runtime parameters */
/* lora_mesh_v1_GeographicMulticastPayload_size depends on runtime parameters */
/* lora_mesh_v1_MulticastRegion_size depends on runtime parameters */
/* lora_mesh_v1_GeographicRouteDiscoveryPayload_size depends on runtime parameters */
/* lora_mesh_v1_GeographicRouteCandidate_size depends on runtime parameters */
/* lora_mesh_v1_LocationServicePayload_size depends on runtime parameters */
/* lora_mesh_v1_LocationServiceResponse_size depends on runtime parameters */
/* lora_mesh_v1_LocationServiceNode_size depends on runtime parameters */
#define LORA_MESH_V1_V1_GEOGRAPHIC_PB_H_MAX_SIZE lora_mesh_v1_PredictedPosition_size
#define lora_mesh_v1_PredictedPosition_size      69

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
