/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "v1/messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(lora_mesh_v1_LoRaMessage, lora_mesh_v1_LoRaMessage, 2)


PB_BIND(lora_mesh_v1_GPSUpdatePayload, lora_mesh_v1_GPSUpdatePayload, AUTO)


PB_BIND(lora_mesh_v1_HelloPayload, lora_mesh_v1_HelloPayload, AUTO)


PB_BIND(lora_mesh_v1_TextMessagePayload, lora_mesh_v1_TextMessagePayload, 2)


PB_BIND(lora_mesh_v1_ControlMessagePayload, lora_mesh_v1_ControlMessagePayload, AUTO)


PB_BIND(lora_mesh_v1_NetworkDiscoveryPayload, lora_mesh_v1_NetworkDiscoveryPayload, 2)


PB_BIND(lora_mesh_v1_AckPayload, lora_mesh_v1_AckPayload, AUTO)


PB_BIND(lora_mesh_v1_EmergencyPayload, lora_mesh_v1_EmergencyPayload, 2)


PB_BIND(lora_mesh_v1_KeyExchangePayload, lora_mesh_v1_KeyExchangePayload, 2)


PB_BIND(lora_mesh_v1_CertificateRequestPayload, lora_mesh_v1_CertificateRequestPayload, 2)


PB_BIND(lora_mesh_v1_CertificateResponsePayload, lora_mesh_v1_CertificateResponsePayload, 2)


PB_BIND(lora_mesh_v1_KeyRevocationPayload, lora_mesh_v1_KeyRevocationPayload, AUTO)


PB_BIND(lora_mesh_v1_SignatureVerificationRequestPayload, lora_mesh_v1_SignatureVerificationRequestPayload, AUTO)


PB_BIND(lora_mesh_v1_SignatureVerificationResponsePayload, lora_mesh_v1_SignatureVerificationResponsePayload, AUTO)















