/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LORA_MESH_V1_V1_MESSAGES_PB_H_INCLUDED
#define PB_LORA_MESH_V1_V1_MESSAGES_PB_H_INCLUDED
#include <pb.h>
#include "v1/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Message types supported by the system */
typedef enum _lora_mesh_v1_MessageType {
    lora_mesh_v1_MessageType_MESSAGE_TYPE_UNSPECIFIED = 0,
    /* Basic application messages */
    lora_mesh_v1_MessageType_MESSAGE_TYPE_GPS_UPDATE = 1,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_TEXT_MESSAGE = 2,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_HELLO = 3,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_CONTROL_MESSAGE = 4,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_ACKNOWLEDGMENT = 5,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_EMERGENCY = 6,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_NETWORK_DISCOVERY = 7,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_CONTENT_SYNC = 8, /* Bundled state sync (positions + messages) */
    /* Routing protocol messages (handled in routing.proto) */
    lora_mesh_v1_MessageType_MESSAGE_TYPE_ROUTE_REQUEST = 10,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_ROUTE_REPLY = 11,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_ROUTE_ERROR = 12,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_LINK_STATE_ADVERTISEMENT = 13,
    /* Geographic routing messages (handled in geographic.proto) */
    lora_mesh_v1_MessageType_MESSAGE_TYPE_GEOGRAPHIC_BEACON = 20,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_POSITION_UPDATE = 21,
    /* Security and key management messages */
    lora_mesh_v1_MessageType_MESSAGE_TYPE_KEY_EXCHANGE = 30,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_CERTIFICATE_REQUEST = 31,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_CERTIFICATE_RESPONSE = 32,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_KEY_REVOCATION = 33,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_SIGNATURE_VERIFICATION_REQUEST = 34,
    lora_mesh_v1_MessageType_MESSAGE_TYPE_SIGNATURE_VERIFICATION_RESPONSE = 35,
    /* Fragmentation and streaming */
    lora_mesh_v1_MessageType_MESSAGE_TYPE_FRAGMENT = 40, /* Fragmented payload (part of larger message) */
    lora_mesh_v1_MessageType_MESSAGE_TYPE_VOICE = 41 /* Voice/audio data (Codec2) */
} lora_mesh_v1_MessageType;

/* Control commands */
typedef enum _lora_mesh_v1_ControlCommand {
    lora_mesh_v1_ControlCommand_CONTROL_COMMAND_UNSPECIFIED = 0,
    lora_mesh_v1_ControlCommand_CONTROL_COMMAND_PING = 1,
    lora_mesh_v1_ControlCommand_CONTROL_COMMAND_REBOOT = 2,
    lora_mesh_v1_ControlCommand_CONTROL_COMMAND_CONFIG_UPDATE = 3,
    lora_mesh_v1_ControlCommand_CONTROL_COMMAND_ROUTE_FLUSH = 4,
    lora_mesh_v1_ControlCommand_CONTROL_COMMAND_POWER_ADJUST = 5,
    lora_mesh_v1_ControlCommand_CONTROL_COMMAND_FREQUENCY_CHANGE = 6,
    lora_mesh_v1_ControlCommand_CONTROL_COMMAND_EMERGENCY_SHUTDOWN = 7
} lora_mesh_v1_ControlCommand;

/* Emergency types */
typedef enum _lora_mesh_v1_EmergencyType {
    lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_UNSPECIFIED = 0,
    lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_MEDICAL = 1,
    lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_FIRE = 2,
    lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_ACCIDENT = 3,
    lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_NATURAL_DISASTER = 4,
    lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_SECURITY_THREAT = 5,
    lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_EQUIPMENT_FAILURE = 6,
    lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_COMMUNICATION_FAILURE = 7,
    lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_OTHER = 99
} lora_mesh_v1_EmergencyType;

/* Certificate status enumeration */
typedef enum _lora_mesh_v1_CertificateStatus {
    lora_mesh_v1_CertificateStatus_CERTIFICATE_STATUS_UNSPECIFIED = 0,
    lora_mesh_v1_CertificateStatus_CERTIFICATE_STATUS_APPROVED = 1, /* Certificate issued successfully */
    lora_mesh_v1_CertificateStatus_CERTIFICATE_STATUS_REJECTED = 2, /* Certificate request rejected */
    lora_mesh_v1_CertificateStatus_CERTIFICATE_STATUS_PENDING = 3, /* Request under review */
    lora_mesh_v1_CertificateStatus_CERTIFICATE_STATUS_REVOKED = 4 /* Certificate has been revoked */
} lora_mesh_v1_CertificateStatus;

/* Revocation reasons */
typedef enum _lora_mesh_v1_RevocationReason {
    lora_mesh_v1_RevocationReason_REVOCATION_REASON_UNSPECIFIED = 0,
    lora_mesh_v1_RevocationReason_REVOCATION_REASON_KEY_COMPROMISE = 1, /* Private key was compromised */
    lora_mesh_v1_RevocationReason_REVOCATION_REASON_NODE_COMPROMISE = 2, /* Node was compromised */
    lora_mesh_v1_RevocationReason_REVOCATION_REASON_ADMINISTRATIVE = 3, /* Administrative revocation */
    lora_mesh_v1_RevocationReason_REVOCATION_REASON_SUPERSEDED = 4, /* Key replaced with new key */
    lora_mesh_v1_RevocationReason_REVOCATION_REASON_CESSATION = 5 /* Node leaving network */
} lora_mesh_v1_RevocationReason;

/* Verification result enumeration */
typedef enum _lora_mesh_v1_VerificationResult {
    lora_mesh_v1_VerificationResult_VERIFICATION_RESULT_UNSPECIFIED = 0,
    lora_mesh_v1_VerificationResult_VERIFICATION_RESULT_VALID = 1, /* Signature is valid */
    lora_mesh_v1_VerificationResult_VERIFICATION_RESULT_INVALID = 2, /* Signature is invalid */
    lora_mesh_v1_VerificationResult_VERIFICATION_RESULT_KEY_NOT_FOUND = 3, /* Signer's public key not available */
    lora_mesh_v1_VerificationResult_VERIFICATION_RESULT_KEY_EXPIRED = 4, /* Signer's key has expired */
    lora_mesh_v1_VerificationResult_VERIFICATION_RESULT_KEY_REVOKED = 5, /* Signer's key has been revoked */
    lora_mesh_v1_VerificationResult_VERIFICATION_RESULT_ALGORITHM_UNSUPPORTED = 6 /* Signature algorithm not supported */
} lora_mesh_v1_VerificationResult;

/* Flags for fragment state */
typedef enum _lora_mesh_v1_FragmentFlags {
    lora_mesh_v1_FragmentFlags_FRAGMENT_FLAG_NONE = 0,
    lora_mesh_v1_FragmentFlags_FRAGMENT_FLAG_FIRST = 1, /* First fragment of stream */
    lora_mesh_v1_FragmentFlags_FRAGMENT_FLAG_MORE = 2, /* More fragments follow */
    lora_mesh_v1_FragmentFlags_FRAGMENT_FLAG_LAST = 4 /* Last fragment, rebroadcast now */
} lora_mesh_v1_FragmentFlags;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(256) lora_mesh_v1_LoRaMessage_payload_t;
/* Main message wrapper for all network communications */
typedef struct _lora_mesh_v1_LoRaMessage {
    char message_id[32]; /* Globally unique message identifier */
    char source_id[16]; /* Original sender node ID */
    char destination_id[16]; /* Final recipient node ID ("BROADCAST" for broadcasts) */
    uint32_t source_port; /* Logical source port (service/application) */
    uint32_t destination_port; /* Logical destination port */
    lora_mesh_v1_MessageType message_type; /* Type of message */
    lora_mesh_v1_LoRaMessage_payload_t payload; /* Serialized message content */
    uint64_t timestamp; /* Message creation timestamp */
    uint32_t ttl; /* Time to live (hop count) */
    uint32_t hop_count; /* Hops from originator */
    uint32_t sequence_number; /* Message sequence number */
    bool has_signature;
    lora_mesh_v1_CryptographicSignature signature; /* Cryptographic signature for authentication */
    lora_mesh_v1_MessagePriority priority; /* Message priority level */
    lora_mesh_v1_RoutingStrategy routing_hint; /* Suggested routing strategy */
    lora_mesh_v1_SecurityLevel security_level; /* Required security level for this message */
    bool signature_required; /* Whether signature verification is mandatory */
} lora_mesh_v1_LoRaMessage;

/* GPS position update message */
typedef struct _lora_mesh_v1_GPSUpdatePayload {
    bool has_position;
    lora_mesh_v1_GPSCoordinate position; /* Current GPS position */
    bool has_velocity;
    lora_mesh_v1_Velocity velocity; /* Current velocity vector */
    uint32_t satellites_used; /* Number of satellites in fix */
    bool is_differential; /* Differential GPS flag */
    uint64_t timestamp; /* GPS timestamp */
    float accuracy; /* Position accuracy in meters */
} lora_mesh_v1_GPSUpdatePayload;

/* Node position entry for content sync (compact format) */
typedef struct _lora_mesh_v1_SyncPosition {
    char node_id[16]; /* Node this position belongs to */
    bool has_position;
    lora_mesh_v1_GPSCoordinate position; /* GPS position */
    uint64_t timestamp; /* Position timestamp */
} lora_mesh_v1_SyncPosition;

/* Text message entry for content sync (compact format) */
typedef struct _lora_mesh_v1_SyncTextMessage {
    char message_id[32]; /* Original message ID */
    char source_id[16]; /* Original sender */
    char text[128]; /* Message text */
    uint64_t timestamp; /* Message timestamp */
} lora_mesh_v1_SyncTextMessage;

/* Bundled content sync payload - positions + messages in one fragmented stream */
typedef struct _lora_mesh_v1_ContentSyncPayload {
    uint64_t mesh_version; /* Sender's mesh version */
    pb_size_t positions_count;
    lora_mesh_v1_SyncPosition positions[10]; /* GPS positions to sync */
    pb_size_t messages_count;
    lora_mesh_v1_SyncTextMessage messages[5]; /* Text messages to sync */
    pb_size_t roster_count;
    char roster[16][16]; /* Known active node IDs (for nodes without GPS) */
} lora_mesh_v1_ContentSyncPayload;

/* Hello message for neighbor discovery */
typedef struct _lora_mesh_v1_HelloPayload {
    bool has_node_info;
    lora_mesh_v1_NodeInfo node_info; /* Sender's node information */
    pb_callback_t known_neighbors; /* List of known neighbor IDs */
    uint32_t neighbor_count; /* Direct neighbor count */
    float battery_level; /* Battery level 0.0-1.0 */
    uint32_t uptime_seconds; /* Node uptime in seconds */
    bool has_local_metrics;
    lora_mesh_v1_TopologyMetrics local_metrics; /* Local network metrics */
    uint64_t hello_timestamp; /* When hello was created */
    uint32_t hello_sequence; /* Hello sequence number */
    uint64_t mesh_version; /* Mesh-wide state version for sync detection */
} lora_mesh_v1_HelloPayload;

/* Text message payload */
typedef struct _lora_mesh_v1_TextMessagePayload {
    char text[256]; /* Message text content */
    char sender_callsign[16]; /* Human-readable sender ID */
    lora_mesh_v1_MessagePriority priority; /* Message priority */
    bool requires_ack; /* Acknowledgment required */
    uint32_t message_sequence; /* Sequence number for this sender */
} lora_mesh_v1_TextMessagePayload;

typedef PB_BYTES_ARRAY_T(128) lora_mesh_v1_ControlMessagePayload_command_data_t;
/* Control message for network management */
typedef struct _lora_mesh_v1_ControlMessagePayload {
    lora_mesh_v1_ControlCommand command; /* Control command type */
    char target_node[16]; /* Target node (empty for broadcast) */
    lora_mesh_v1_ControlMessagePayload_command_data_t command_data; /* Command-specific data */
    uint64_t command_id; /* Unique command identifier */
    uint64_t expiry_time; /* Command expiry timestamp */
} lora_mesh_v1_ControlMessagePayload;

/* Network discovery message */
typedef struct _lora_mesh_v1_NetworkDiscoveryPayload {
    bool has_originator;
    lora_mesh_v1_NodeInfo originator; /* Node initiating discovery */
    uint32_t discovery_radius; /* Maximum hops for discovery */
    pb_size_t discovered_nodes_count;
    lora_mesh_v1_NodeInfo discovered_nodes[16]; /* Nodes discovered so far */
    uint64_t discovery_start_time; /* When discovery started */
    bool include_routing_info; /* Include routing table info */
} lora_mesh_v1_NetworkDiscoveryPayload;

typedef PB_BYTES_ARRAY_T(64) lora_mesh_v1_AckPayload_additional_data_t;
/* Acknowledgment message payload */
typedef struct _lora_mesh_v1_AckPayload {
    char original_message_id[32]; /* ID of message being acknowledged */
    bool success; /* Whether operation succeeded */
    char error_message[128]; /* Error description if failed */
    uint64_t ack_timestamp; /* When ACK was generated */
    lora_mesh_v1_AckPayload_additional_data_t additional_data; /* Optional additional response data */
} lora_mesh_v1_AckPayload;

/* Emergency message for critical situations */
typedef struct _lora_mesh_v1_EmergencyPayload {
    lora_mesh_v1_EmergencyType emergency_type; /* Type of emergency */
    char description[128]; /* Human-readable description */
    bool has_location;
    lora_mesh_v1_GPSCoordinate location; /* Location of emergency */
    uint32_t severity_level; /* Severity 1-10 */
    char contact_info[64]; /* Contact information */
    uint64_t emergency_time; /* When emergency occurred */
    bool requires_response; /* Response required flag */
} lora_mesh_v1_EmergencyPayload;

typedef PB_BYTES_ARRAY_T(64) lora_mesh_v1_KeyExchangePayload_challenge_data_t;
/* Key exchange message payload */
typedef struct _lora_mesh_v1_KeyExchangePayload {
    char requesting_node_id[16]; /* Node requesting key exchange */
    bool has_offered_public_key;
    lora_mesh_v1_PublicKey offered_public_key; /* Public key being offered */
    lora_mesh_v1_SignatureAlgorithm preferred_algorithm; /* Preferred signature algorithm */
    lora_mesh_v1_KeyExchangePayload_challenge_data_t challenge_data; /* Challenge for proof of possession */
    bool has_proof_signature;
    lora_mesh_v1_CryptographicSignature proof_signature; /* Signature proving key ownership */
    uint32_t key_exchange_version; /* Key exchange protocol version */
    pb_size_t supported_algorithms_count;
    lora_mesh_v1_SignatureAlgorithm supported_algorithms[8]; /* Supported algorithms */
} lora_mesh_v1_KeyExchangePayload;

/* Certificate request payload */
typedef struct _lora_mesh_v1_CertificateRequestPayload {
    char requesting_node_id[16]; /* Node requesting certificate */
    bool has_public_key_to_certify;
    lora_mesh_v1_PublicKey public_key_to_certify; /* Key that needs certification */
    char issuer_node_id[16]; /* Requested certificate issuer */
    pb_callback_t requested_permissions; /* Requested permissions */
    uint32_t requested_validity_days; /* Requested certificate validity period */
    bool has_request_signature;
    lora_mesh_v1_CryptographicSignature request_signature; /* Signature on the request */
} lora_mesh_v1_CertificateRequestPayload;

/* Certificate response payload */
typedef struct _lora_mesh_v1_CertificateResponsePayload {
    char requesting_node_id[16]; /* Original requester */
    char issuer_node_id[16]; /* Certificate issuer */
    bool has_certificate;
    lora_mesh_v1_NodeCertificate certificate; /* Issued certificate (if approved) */
    lora_mesh_v1_CertificateStatus status; /* Request status */
    char rejection_reason[128]; /* Reason for rejection (if applicable) */
    uint64_t response_timestamp; /* Response creation time */
} lora_mesh_v1_CertificateResponsePayload;

/* Key revocation payload */
typedef struct _lora_mesh_v1_KeyRevocationPayload {
    char revoked_key_id[16]; /* Key being revoked */
    char revoking_node_id[16]; /* Node issuing revocation */
    lora_mesh_v1_RevocationReason reason; /* Reason for revocation */
    uint64_t revocation_timestamp; /* When revocation was issued */
    bool has_revocation_signature;
    lora_mesh_v1_CryptographicSignature revocation_signature; /* Signature on revocation */
    pb_callback_t affected_certificates; /* Certificates that are now invalid */
} lora_mesh_v1_KeyRevocationPayload;

typedef PB_BYTES_ARRAY_T(256) lora_mesh_v1_SignatureVerificationRequestPayload_message_data_t;
/* Signature verification request payload */
typedef struct _lora_mesh_v1_SignatureVerificationRequestPayload {
    char message_id_to_verify[32]; /* Message ID being verified */
    char signer_node_id[16]; /* Claimed signer of the message */
    char verifier_node_id[16]; /* Node requesting verification */
    lora_mesh_v1_SignatureVerificationRequestPayload_message_data_t message_data; /* Original message data */
    bool has_signature_to_verify;
    lora_mesh_v1_CryptographicSignature signature_to_verify; /* Signature being verified */
} lora_mesh_v1_SignatureVerificationRequestPayload;

/* Signature verification response payload */
typedef struct _lora_mesh_v1_SignatureVerificationResponsePayload {
    char original_message_id[32]; /* Message that was verified */
    char verifier_node_id[16]; /* Node that performed verification */
    lora_mesh_v1_VerificationResult result; /* Verification result */
    char verification_details[128]; /* Additional verification information */
    uint64_t verification_timestamp; /* When verification was performed */
    bool has_verifier_signature;
    lora_mesh_v1_CryptographicSignature verifier_signature; /* Verifier's signature on result */
} lora_mesh_v1_SignatureVerificationResponsePayload;

typedef PB_BYTES_ARRAY_T(120) lora_mesh_v1_FragmentPayload_data_t;
/* Fragment header for multi-packet messages */
typedef struct _lora_mesh_v1_FragmentPayload {
    uint32_t stream_id; /* Unique ID for this fragmented message */
    uint32_t fragment_index; /* 0, 1, 2, ... (order in stream) */
    uint32_t total_fragments; /* Total expected fragment count */
    uint32_t flags; /* FragmentFlags bitmask */
    lora_mesh_v1_MessageType original_type; /* Original message type being fragmented */
    lora_mesh_v1_FragmentPayload_data_t data; /* Fragment data */
} lora_mesh_v1_FragmentPayload;

typedef PB_BYTES_ARRAY_T(128) lora_mesh_v1_VoicePayload_frames_t;
/* Voice packet for PTT audio */
typedef struct _lora_mesh_v1_VoicePayload {
    uint32_t stream_id; /* Unique ID for this PTT session */
    uint32_t sequence; /* Packet order within stream */
    uint32_t codec_mode; /* Codec2 mode: 700, 1300, 1600, 2400, 3200 */
    uint32_t flags; /* FragmentFlags (START, MORE, LAST) */
    uint32_t total_packets; /* Expected packets (hint for buffering) */
    lora_mesh_v1_VoicePayload_frames_t frames; /* Packed Codec2 frames */
    uint32_t frame_count; /* Number of Codec2 frames in this packet */
} lora_mesh_v1_VoicePayload;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _lora_mesh_v1_MessageType_MIN lora_mesh_v1_MessageType_MESSAGE_TYPE_UNSPECIFIED
#define _lora_mesh_v1_MessageType_MAX lora_mesh_v1_MessageType_MESSAGE_TYPE_VOICE
#define _lora_mesh_v1_MessageType_ARRAYSIZE ((lora_mesh_v1_MessageType)(lora_mesh_v1_MessageType_MESSAGE_TYPE_VOICE+1))

#define _lora_mesh_v1_ControlCommand_MIN lora_mesh_v1_ControlCommand_CONTROL_COMMAND_UNSPECIFIED
#define _lora_mesh_v1_ControlCommand_MAX lora_mesh_v1_ControlCommand_CONTROL_COMMAND_EMERGENCY_SHUTDOWN
#define _lora_mesh_v1_ControlCommand_ARRAYSIZE ((lora_mesh_v1_ControlCommand)(lora_mesh_v1_ControlCommand_CONTROL_COMMAND_EMERGENCY_SHUTDOWN+1))

#define _lora_mesh_v1_EmergencyType_MIN lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_UNSPECIFIED
#define _lora_mesh_v1_EmergencyType_MAX lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_OTHER
#define _lora_mesh_v1_EmergencyType_ARRAYSIZE ((lora_mesh_v1_EmergencyType)(lora_mesh_v1_EmergencyType_EMERGENCY_TYPE_OTHER+1))

#define _lora_mesh_v1_CertificateStatus_MIN lora_mesh_v1_CertificateStatus_CERTIFICATE_STATUS_UNSPECIFIED
#define _lora_mesh_v1_CertificateStatus_MAX lora_mesh_v1_CertificateStatus_CERTIFICATE_STATUS_REVOKED
#define _lora_mesh_v1_CertificateStatus_ARRAYSIZE ((lora_mesh_v1_CertificateStatus)(lora_mesh_v1_CertificateStatus_CERTIFICATE_STATUS_REVOKED+1))

#define _lora_mesh_v1_RevocationReason_MIN lora_mesh_v1_RevocationReason_REVOCATION_REASON_UNSPECIFIED
#define _lora_mesh_v1_RevocationReason_MAX lora_mesh_v1_RevocationReason_REVOCATION_REASON_CESSATION
#define _lora_mesh_v1_RevocationReason_ARRAYSIZE ((lora_mesh_v1_RevocationReason)(lora_mesh_v1_RevocationReason_REVOCATION_REASON_CESSATION+1))

#define _lora_mesh_v1_VerificationResult_MIN lora_mesh_v1_VerificationResult_VERIFICATION_RESULT_UNSPECIFIED
#define _lora_mesh_v1_VerificationResult_MAX lora_mesh_v1_VerificationResult_VERIFICATION_RESULT_ALGORITHM_UNSUPPORTED
#define _lora_mesh_v1_VerificationResult_ARRAYSIZE ((lora_mesh_v1_VerificationResult)(lora_mesh_v1_VerificationResult_VERIFICATION_RESULT_ALGORITHM_UNSUPPORTED+1))

#define _lora_mesh_v1_FragmentFlags_MIN lora_mesh_v1_FragmentFlags_FRAGMENT_FLAG_NONE
#define _lora_mesh_v1_FragmentFlags_MAX lora_mesh_v1_FragmentFlags_FRAGMENT_FLAG_LAST
#define _lora_mesh_v1_FragmentFlags_ARRAYSIZE ((lora_mesh_v1_FragmentFlags)(lora_mesh_v1_FragmentFlags_FRAGMENT_FLAG_LAST+1))

#define lora_mesh_v1_LoRaMessage_message_type_ENUMTYPE lora_mesh_v1_MessageType
#define lora_mesh_v1_LoRaMessage_priority_ENUMTYPE lora_mesh_v1_MessagePriority
#define lora_mesh_v1_LoRaMessage_routing_hint_ENUMTYPE lora_mesh_v1_RoutingStrategy
#define lora_mesh_v1_LoRaMessage_security_level_ENUMTYPE lora_mesh_v1_SecurityLevel






#define lora_mesh_v1_TextMessagePayload_priority_ENUMTYPE lora_mesh_v1_MessagePriority

#define lora_mesh_v1_ControlMessagePayload_command_ENUMTYPE lora_mesh_v1_ControlCommand



#define lora_mesh_v1_EmergencyPayload_emergency_type_ENUMTYPE lora_mesh_v1_EmergencyType

#define lora_mesh_v1_KeyExchangePayload_preferred_algorithm_ENUMTYPE lora_mesh_v1_SignatureAlgorithm
#define lora_mesh_v1_KeyExchangePayload_supported_algorithms_ENUMTYPE lora_mesh_v1_SignatureAlgorithm


#define lora_mesh_v1_CertificateResponsePayload_status_ENUMTYPE lora_mesh_v1_CertificateStatus

#define lora_mesh_v1_KeyRevocationPayload_reason_ENUMTYPE lora_mesh_v1_RevocationReason


#define lora_mesh_v1_SignatureVerificationResponsePayload_result_ENUMTYPE lora_mesh_v1_VerificationResult

#define lora_mesh_v1_FragmentPayload_original_type_ENUMTYPE lora_mesh_v1_MessageType



/* Initializer values for message structs */
#define lora_mesh_v1_LoRaMessage_init_default    {"", "", "", 0, 0, _lora_mesh_v1_MessageType_MIN, {0, {0}}, 0, 0, 0, 0, false, lora_mesh_v1_CryptographicSignature_init_default, _lora_mesh_v1_MessagePriority_MIN, _lora_mesh_v1_RoutingStrategy_MIN, _lora_mesh_v1_SecurityLevel_MIN, 0}
#define lora_mesh_v1_GPSUpdatePayload_init_default {false, lora_mesh_v1_GPSCoordinate_init_default, false, lora_mesh_v1_Velocity_init_default, 0, 0, 0, 0}
#define lora_mesh_v1_SyncPosition_init_default   {"", false, lora_mesh_v1_GPSCoordinate_init_default, 0}
#define lora_mesh_v1_SyncTextMessage_init_default {"", "", "", 0}
#define lora_mesh_v1_ContentSyncPayload_init_default {0, 0, {lora_mesh_v1_SyncPosition_init_default, lora_mesh_v1_SyncPosition_init_default, lora_mesh_v1_SyncPosition_init_default, lora_mesh_v1_SyncPosition_init_default, lora_mesh_v1_SyncPosition_init_default, lora_mesh_v1_SyncPosition_init_default, lora_mesh_v1_SyncPosition_init_default, lora_mesh_v1_SyncPosition_init_default, lora_mesh_v1_SyncPosition_init_default, lora_mesh_v1_SyncPosition_init_default}, 0, {lora_mesh_v1_SyncTextMessage_init_default, lora_mesh_v1_SyncTextMessage_init_default, lora_mesh_v1_SyncTextMessage_init_default, lora_mesh_v1_SyncTextMessage_init_default, lora_mesh_v1_SyncTextMessage_init_default}, 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define lora_mesh_v1_HelloPayload_init_default   {false, lora_mesh_v1_NodeInfo_init_default, {{NULL}, NULL}, 0, 0, 0, false, lora_mesh_v1_TopologyMetrics_init_default, 0, 0, 0}
#define lora_mesh_v1_TextMessagePayload_init_default {"", "", _lora_mesh_v1_MessagePriority_MIN, 0, 0}
#define lora_mesh_v1_ControlMessagePayload_init_default {_lora_mesh_v1_ControlCommand_MIN, "", {0, {0}}, 0, 0}
#define lora_mesh_v1_NetworkDiscoveryPayload_init_default {false, lora_mesh_v1_NodeInfo_init_default, 0, 0, {lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default}, 0, 0}
#define lora_mesh_v1_AckPayload_init_default     {"", 0, "", 0, {0, {0}}}
#define lora_mesh_v1_EmergencyPayload_init_default {_lora_mesh_v1_EmergencyType_MIN, "", false, lora_mesh_v1_GPSCoordinate_init_default, 0, "", 0, 0}
#define lora_mesh_v1_KeyExchangePayload_init_default {"", false, lora_mesh_v1_PublicKey_init_default, _lora_mesh_v1_SignatureAlgorithm_MIN, {0, {0}}, false, lora_mesh_v1_CryptographicSignature_init_default, 0, 0, {_lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN}}
#define lora_mesh_v1_CertificateRequestPayload_init_default {"", false, lora_mesh_v1_PublicKey_init_default, "", {{NULL}, NULL}, 0, false, lora_mesh_v1_CryptographicSignature_init_default}
#define lora_mesh_v1_CertificateResponsePayload_init_default {"", "", false, lora_mesh_v1_NodeCertificate_init_default, _lora_mesh_v1_CertificateStatus_MIN, "", 0}
#define lora_mesh_v1_KeyRevocationPayload_init_default {"", "", _lora_mesh_v1_RevocationReason_MIN, 0, false, lora_mesh_v1_CryptographicSignature_init_default, {{NULL}, NULL}}
#define lora_mesh_v1_SignatureVerificationRequestPayload_init_default {"", "", "", {0, {0}}, false, lora_mesh_v1_CryptographicSignature_init_default}
#define lora_mesh_v1_SignatureVerificationResponsePayload_init_default {"", "", _lora_mesh_v1_VerificationResult_MIN, "", 0, false, lora_mesh_v1_CryptographicSignature_init_default}
#define lora_mesh_v1_FragmentPayload_init_default {0, 0, 0, 0, _lora_mesh_v1_MessageType_MIN, {0, {0}}}
#define lora_mesh_v1_VoicePayload_init_default   {0, 0, 0, 0, 0, {0, {0}}, 0}
#define lora_mesh_v1_LoRaMessage_init_zero       {"", "", "", 0, 0, _lora_mesh_v1_MessageType_MIN, {0, {0}}, 0, 0, 0, 0, false, lora_mesh_v1_CryptographicSignature_init_zero, _lora_mesh_v1_MessagePriority_MIN, _lora_mesh_v1_RoutingStrategy_MIN, _lora_mesh_v1_SecurityLevel_MIN, 0}
#define lora_mesh_v1_GPSUpdatePayload_init_zero  {false, lora_mesh_v1_GPSCoordinate_init_zero, false, lora_mesh_v1_Velocity_init_zero, 0, 0, 0, 0}
#define lora_mesh_v1_SyncPosition_init_zero      {"", false, lora_mesh_v1_GPSCoordinate_init_zero, 0}
#define lora_mesh_v1_SyncTextMessage_init_zero   {"", "", "", 0}
#define lora_mesh_v1_ContentSyncPayload_init_zero {0, 0, {lora_mesh_v1_SyncPosition_init_zero, lora_mesh_v1_SyncPosition_init_zero, lora_mesh_v1_SyncPosition_init_zero, lora_mesh_v1_SyncPosition_init_zero, lora_mesh_v1_SyncPosition_init_zero, lora_mesh_v1_SyncPosition_init_zero, lora_mesh_v1_SyncPosition_init_zero, lora_mesh_v1_SyncPosition_init_zero, lora_mesh_v1_SyncPosition_init_zero, lora_mesh_v1_SyncPosition_init_zero}, 0, {lora_mesh_v1_SyncTextMessage_init_zero, lora_mesh_v1_SyncTextMessage_init_zero, lora_mesh_v1_SyncTextMessage_init_zero, lora_mesh_v1_SyncTextMessage_init_zero, lora_mesh_v1_SyncTextMessage_init_zero}, 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define lora_mesh_v1_HelloPayload_init_zero      {false, lora_mesh_v1_NodeInfo_init_zero, {{NULL}, NULL}, 0, 0, 0, false, lora_mesh_v1_TopologyMetrics_init_zero, 0, 0, 0}
#define lora_mesh_v1_TextMessagePayload_init_zero {"", "", _lora_mesh_v1_MessagePriority_MIN, 0, 0}
#define lora_mesh_v1_ControlMessagePayload_init_zero {_lora_mesh_v1_ControlCommand_MIN, "", {0, {0}}, 0, 0}
#define lora_mesh_v1_NetworkDiscoveryPayload_init_zero {false, lora_mesh_v1_NodeInfo_init_zero, 0, 0, {lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero}, 0, 0}
#define lora_mesh_v1_AckPayload_init_zero        {"", 0, "", 0, {0, {0}}}
#define lora_mesh_v1_EmergencyPayload_init_zero  {_lora_mesh_v1_EmergencyType_MIN, "", false, lora_mesh_v1_GPSCoordinate_init_zero, 0, "", 0, 0}
#define lora_mesh_v1_KeyExchangePayload_init_zero {"", false, lora_mesh_v1_PublicKey_init_zero, _lora_mesh_v1_SignatureAlgorithm_MIN, {0, {0}}, false, lora_mesh_v1_CryptographicSignature_init_zero, 0, 0, {_lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN, _lora_mesh_v1_SignatureAlgorithm_MIN}}
#define lora_mesh_v1_CertificateRequestPayload_init_zero {"", false, lora_mesh_v1_PublicKey_init_zero, "", {{NULL}, NULL}, 0, false, lora_mesh_v1_CryptographicSignature_init_zero}
#define lora_mesh_v1_CertificateResponsePayload_init_zero {"", "", false, lora_mesh_v1_NodeCertificate_init_zero, _lora_mesh_v1_CertificateStatus_MIN, "", 0}
#define lora_mesh_v1_KeyRevocationPayload_init_zero {"", "", _lora_mesh_v1_RevocationReason_MIN, 0, false, lora_mesh_v1_CryptographicSignature_init_zero, {{NULL}, NULL}}
#define lora_mesh_v1_SignatureVerificationRequestPayload_init_zero {"", "", "", {0, {0}}, false, lora_mesh_v1_CryptographicSignature_init_zero}
#define lora_mesh_v1_SignatureVerificationResponsePayload_init_zero {"", "", _lora_mesh_v1_VerificationResult_MIN, "", 0, false, lora_mesh_v1_CryptographicSignature_init_zero}
#define lora_mesh_v1_FragmentPayload_init_zero   {0, 0, 0, 0, _lora_mesh_v1_MessageType_MIN, {0, {0}}}
#define lora_mesh_v1_VoicePayload_init_zero      {0, 0, 0, 0, 0, {0, {0}}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define lora_mesh_v1_LoRaMessage_message_id_tag  1
#define lora_mesh_v1_LoRaMessage_source_id_tag   2
#define lora_mesh_v1_LoRaMessage_destination_id_tag 3
#define lora_mesh_v1_LoRaMessage_source_port_tag 4
#define lora_mesh_v1_LoRaMessage_destination_port_tag 5
#define lora_mesh_v1_LoRaMessage_message_type_tag 6
#define lora_mesh_v1_LoRaMessage_payload_tag     7
#define lora_mesh_v1_LoRaMessage_timestamp_tag   8
#define lora_mesh_v1_LoRaMessage_ttl_tag         9
#define lora_mesh_v1_LoRaMessage_hop_count_tag   10
#define lora_mesh_v1_LoRaMessage_sequence_number_tag 11
#define lora_mesh_v1_LoRaMessage_signature_tag   12
#define lora_mesh_v1_LoRaMessage_priority_tag    13
#define lora_mesh_v1_LoRaMessage_routing_hint_tag 14
#define lora_mesh_v1_LoRaMessage_security_level_tag 15
#define lora_mesh_v1_LoRaMessage_signature_required_tag 16
#define lora_mesh_v1_GPSUpdatePayload_position_tag 1
#define lora_mesh_v1_GPSUpdatePayload_velocity_tag 2
#define lora_mesh_v1_GPSUpdatePayload_satellites_used_tag 3
#define lora_mesh_v1_GPSUpdatePayload_is_differential_tag 4
#define lora_mesh_v1_GPSUpdatePayload_timestamp_tag 5
#define lora_mesh_v1_GPSUpdatePayload_accuracy_tag 6
#define lora_mesh_v1_SyncPosition_node_id_tag    1
#define lora_mesh_v1_SyncPosition_position_tag   2
#define lora_mesh_v1_SyncPosition_timestamp_tag  3
#define lora_mesh_v1_SyncTextMessage_message_id_tag 1
#define lora_mesh_v1_SyncTextMessage_source_id_tag 2
#define lora_mesh_v1_SyncTextMessage_text_tag    3
#define lora_mesh_v1_SyncTextMessage_timestamp_tag 4
#define lora_mesh_v1_ContentSyncPayload_mesh_version_tag 1
#define lora_mesh_v1_ContentSyncPayload_positions_tag 2
#define lora_mesh_v1_ContentSyncPayload_messages_tag 3
#define lora_mesh_v1_ContentSyncPayload_roster_tag 4
#define lora_mesh_v1_HelloPayload_node_info_tag  1
#define lora_mesh_v1_HelloPayload_known_neighbors_tag 2
#define lora_mesh_v1_HelloPayload_neighbor_count_tag 3
#define lora_mesh_v1_HelloPayload_battery_level_tag 4
#define lora_mesh_v1_HelloPayload_uptime_seconds_tag 5
#define lora_mesh_v1_HelloPayload_local_metrics_tag 6
#define lora_mesh_v1_HelloPayload_hello_timestamp_tag 7
#define lora_mesh_v1_HelloPayload_hello_sequence_tag 8
#define lora_mesh_v1_HelloPayload_mesh_version_tag 9
#define lora_mesh_v1_TextMessagePayload_text_tag 1
#define lora_mesh_v1_TextMessagePayload_sender_callsign_tag 2
#define lora_mesh_v1_TextMessagePayload_priority_tag 3
#define lora_mesh_v1_TextMessagePayload_requires_ack_tag 4
#define lora_mesh_v1_TextMessagePayload_message_sequence_tag 5
#define lora_mesh_v1_ControlMessagePayload_command_tag 1
#define lora_mesh_v1_ControlMessagePayload_target_node_tag 2
#define lora_mesh_v1_ControlMessagePayload_command_data_tag 3
#define lora_mesh_v1_ControlMessagePayload_command_id_tag 4
#define lora_mesh_v1_ControlMessagePayload_expiry_time_tag 5
#define lora_mesh_v1_NetworkDiscoveryPayload_originator_tag 1
#define lora_mesh_v1_NetworkDiscoveryPayload_discovery_radius_tag 2
#define lora_mesh_v1_NetworkDiscoveryPayload_discovered_nodes_tag 3
#define lora_mesh_v1_NetworkDiscoveryPayload_discovery_start_time_tag 4
#define lora_mesh_v1_NetworkDiscoveryPayload_include_routing_info_tag 5
#define lora_mesh_v1_AckPayload_original_message_id_tag 1
#define lora_mesh_v1_AckPayload_success_tag      2
#define lora_mesh_v1_AckPayload_error_message_tag 3
#define lora_mesh_v1_AckPayload_ack_timestamp_tag 4
#define lora_mesh_v1_AckPayload_additional_data_tag 5
#define lora_mesh_v1_EmergencyPayload_emergency_type_tag 1
#define lora_mesh_v1_EmergencyPayload_description_tag 2
#define lora_mesh_v1_EmergencyPayload_location_tag 3
#define lora_mesh_v1_EmergencyPayload_severity_level_tag 4
#define lora_mesh_v1_EmergencyPayload_contact_info_tag 5
#define lora_mesh_v1_EmergencyPayload_emergency_time_tag 6
#define lora_mesh_v1_EmergencyPayload_requires_response_tag 7
#define lora_mesh_v1_KeyExchangePayload_requesting_node_id_tag 1
#define lora_mesh_v1_KeyExchangePayload_offered_public_key_tag 2
#define lora_mesh_v1_KeyExchangePayload_preferred_algorithm_tag 3
#define lora_mesh_v1_KeyExchangePayload_challenge_data_tag 4
#define lora_mesh_v1_KeyExchangePayload_proof_signature_tag 5
#define lora_mesh_v1_KeyExchangePayload_key_exchange_version_tag 6
#define lora_mesh_v1_KeyExchangePayload_supported_algorithms_tag 7
#define lora_mesh_v1_CertificateRequestPayload_requesting_node_id_tag 1
#define lora_mesh_v1_CertificateRequestPayload_public_key_to_certify_tag 2
#define lora_mesh_v1_CertificateRequestPayload_issuer_node_id_tag 3
#define lora_mesh_v1_CertificateRequestPayload_requested_permissions_tag 4
#define lora_mesh_v1_CertificateRequestPayload_requested_validity_days_tag 5
#define lora_mesh_v1_CertificateRequestPayload_request_signature_tag 6
#define lora_mesh_v1_CertificateResponsePayload_requesting_node_id_tag 1
#define lora_mesh_v1_CertificateResponsePayload_issuer_node_id_tag 2
#define lora_mesh_v1_CertificateResponsePayload_certificate_tag 3
#define lora_mesh_v1_CertificateResponsePayload_status_tag 4
#define lora_mesh_v1_CertificateResponsePayload_rejection_reason_tag 5
#define lora_mesh_v1_CertificateResponsePayload_response_timestamp_tag 6
#define lora_mesh_v1_KeyRevocationPayload_revoked_key_id_tag 1
#define lora_mesh_v1_KeyRevocationPayload_revoking_node_id_tag 2
#define lora_mesh_v1_KeyRevocationPayload_reason_tag 3
#define lora_mesh_v1_KeyRevocationPayload_revocation_timestamp_tag 4
#define lora_mesh_v1_KeyRevocationPayload_revocation_signature_tag 5
#define lora_mesh_v1_KeyRevocationPayload_affected_certificates_tag 6
#define lora_mesh_v1_SignatureVerificationRequestPayload_message_id_to_verify_tag 1
#define lora_mesh_v1_SignatureVerificationRequestPayload_signer_node_id_tag 2
#define lora_mesh_v1_SignatureVerificationRequestPayload_verifier_node_id_tag 3
#define lora_mesh_v1_SignatureVerificationRequestPayload_message_data_tag 4
#define lora_mesh_v1_SignatureVerificationRequestPayload_signature_to_verify_tag 5
#define lora_mesh_v1_SignatureVerificationResponsePayload_original_message_id_tag 1
#define lora_mesh_v1_SignatureVerificationResponsePayload_verifier_node_id_tag 2
#define lora_mesh_v1_SignatureVerificationResponsePayload_result_tag 3
#define lora_mesh_v1_SignatureVerificationResponsePayload_verification_details_tag 4
#define lora_mesh_v1_SignatureVerificationResponsePayload_verification_timestamp_tag 5
#define lora_mesh_v1_SignatureVerificationResponsePayload_verifier_signature_tag 6
#define lora_mesh_v1_FragmentPayload_stream_id_tag 1
#define lora_mesh_v1_FragmentPayload_fragment_index_tag 2
#define lora_mesh_v1_FragmentPayload_total_fragments_tag 3
#define lora_mesh_v1_FragmentPayload_flags_tag   4
#define lora_mesh_v1_FragmentPayload_original_type_tag 5
#define lora_mesh_v1_FragmentPayload_data_tag    6
#define lora_mesh_v1_VoicePayload_stream_id_tag  1
#define lora_mesh_v1_VoicePayload_sequence_tag   2
#define lora_mesh_v1_VoicePayload_codec_mode_tag 3
#define lora_mesh_v1_VoicePayload_flags_tag      4
#define lora_mesh_v1_VoicePayload_total_packets_tag 5
#define lora_mesh_v1_VoicePayload_frames_tag     6
#define lora_mesh_v1_VoicePayload_frame_count_tag 7

/* Struct field encoding specification for nanopb */
#define lora_mesh_v1_LoRaMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   source_id,         2) \
X(a, STATIC,   SINGULAR, STRING,   destination_id,    3) \
X(a, STATIC,   SINGULAR, UINT32,   source_port,       4) \
X(a, STATIC,   SINGULAR, UINT32,   destination_port,   5) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      6) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           7) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         8) \
X(a, STATIC,   SINGULAR, UINT32,   ttl,               9) \
X(a, STATIC,   SINGULAR, UINT32,   hop_count,        10) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,  11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  signature,        12) \
X(a, STATIC,   SINGULAR, UENUM,    priority,         13) \
X(a, STATIC,   SINGULAR, UENUM,    routing_hint,     14) \
X(a, STATIC,   SINGULAR, UENUM,    security_level,   15) \
X(a, STATIC,   SINGULAR, BOOL,     signature_required,  16)
#define lora_mesh_v1_LoRaMessage_CALLBACK NULL
#define lora_mesh_v1_LoRaMessage_DEFAULT NULL
#define lora_mesh_v1_LoRaMessage_signature_MSGTYPE lora_mesh_v1_CryptographicSignature

#define lora_mesh_v1_GPSUpdatePayload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  velocity,          2) \
X(a, STATIC,   SINGULAR, UINT32,   satellites_used,   3) \
X(a, STATIC,   SINGULAR, BOOL,     is_differential,   4) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         5) \
X(a, STATIC,   SINGULAR, FLOAT,    accuracy,          6)
#define lora_mesh_v1_GPSUpdatePayload_CALLBACK NULL
#define lora_mesh_v1_GPSUpdatePayload_DEFAULT NULL
#define lora_mesh_v1_GPSUpdatePayload_position_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_GPSUpdatePayload_velocity_MSGTYPE lora_mesh_v1_Velocity

#define lora_mesh_v1_SyncPosition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         3)
#define lora_mesh_v1_SyncPosition_CALLBACK NULL
#define lora_mesh_v1_SyncPosition_DEFAULT NULL
#define lora_mesh_v1_SyncPosition_position_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_SyncTextMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   source_id,         2) \
X(a, STATIC,   SINGULAR, STRING,   text,              3) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         4)
#define lora_mesh_v1_SyncTextMessage_CALLBACK NULL
#define lora_mesh_v1_SyncTextMessage_DEFAULT NULL

#define lora_mesh_v1_ContentSyncPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   mesh_version,      1) \
X(a, STATIC,   REPEATED, MESSAGE,  positions,         2) \
X(a, STATIC,   REPEATED, MESSAGE,  messages,          3) \
X(a, STATIC,   REPEATED, STRING,   roster,            4)
#define lora_mesh_v1_ContentSyncPayload_CALLBACK NULL
#define lora_mesh_v1_ContentSyncPayload_DEFAULT NULL
#define lora_mesh_v1_ContentSyncPayload_positions_MSGTYPE lora_mesh_v1_SyncPosition
#define lora_mesh_v1_ContentSyncPayload_messages_MSGTYPE lora_mesh_v1_SyncTextMessage

#define lora_mesh_v1_HelloPayload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  node_info,         1) \
X(a, CALLBACK, REPEATED, STRING,   known_neighbors,   2) \
X(a, STATIC,   SINGULAR, UINT32,   neighbor_count,    3) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_level,     4) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_seconds,    5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  local_metrics,     6) \
X(a, STATIC,   SINGULAR, UINT64,   hello_timestamp,   7) \
X(a, STATIC,   SINGULAR, UINT32,   hello_sequence,    8) \
X(a, STATIC,   SINGULAR, UINT64,   mesh_version,      9)
#define lora_mesh_v1_HelloPayload_CALLBACK pb_default_field_callback
#define lora_mesh_v1_HelloPayload_DEFAULT NULL
#define lora_mesh_v1_HelloPayload_node_info_MSGTYPE lora_mesh_v1_NodeInfo
#define lora_mesh_v1_HelloPayload_local_metrics_MSGTYPE lora_mesh_v1_TopologyMetrics

#define lora_mesh_v1_TextMessagePayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1) \
X(a, STATIC,   SINGULAR, STRING,   sender_callsign,   2) \
X(a, STATIC,   SINGULAR, UENUM,    priority,          3) \
X(a, STATIC,   SINGULAR, BOOL,     requires_ack,      4) \
X(a, STATIC,   SINGULAR, UINT32,   message_sequence,   5)
#define lora_mesh_v1_TextMessagePayload_CALLBACK NULL
#define lora_mesh_v1_TextMessagePayload_DEFAULT NULL

#define lora_mesh_v1_ControlMessagePayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, STATIC,   SINGULAR, STRING,   target_node,       2) \
X(a, STATIC,   SINGULAR, BYTES,    command_data,      3) \
X(a, STATIC,   SINGULAR, UINT64,   command_id,        4) \
X(a, STATIC,   SINGULAR, UINT64,   expiry_time,       5)
#define lora_mesh_v1_ControlMessagePayload_CALLBACK NULL
#define lora_mesh_v1_ControlMessagePayload_DEFAULT NULL

#define lora_mesh_v1_NetworkDiscoveryPayload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  originator,        1) \
X(a, STATIC,   SINGULAR, UINT32,   discovery_radius,   2) \
X(a, STATIC,   REPEATED, MESSAGE,  discovered_nodes,   3) \
X(a, STATIC,   SINGULAR, UINT64,   discovery_start_time,   4) \
X(a, STATIC,   SINGULAR, BOOL,     include_routing_info,   5)
#define lora_mesh_v1_NetworkDiscoveryPayload_CALLBACK NULL
#define lora_mesh_v1_NetworkDiscoveryPayload_DEFAULT NULL
#define lora_mesh_v1_NetworkDiscoveryPayload_originator_MSGTYPE lora_mesh_v1_NodeInfo
#define lora_mesh_v1_NetworkDiscoveryPayload_discovered_nodes_MSGTYPE lora_mesh_v1_NodeInfo

#define lora_mesh_v1_AckPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   original_message_id,   1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, STRING,   error_message,     3) \
X(a, STATIC,   SINGULAR, UINT64,   ack_timestamp,     4) \
X(a, STATIC,   SINGULAR, BYTES,    additional_data,   5)
#define lora_mesh_v1_AckPayload_CALLBACK NULL
#define lora_mesh_v1_AckPayload_DEFAULT NULL

#define lora_mesh_v1_EmergencyPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    emergency_type,    1) \
X(a, STATIC,   SINGULAR, STRING,   description,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  location,          3) \
X(a, STATIC,   SINGULAR, UINT32,   severity_level,    4) \
X(a, STATIC,   SINGULAR, STRING,   contact_info,      5) \
X(a, STATIC,   SINGULAR, UINT64,   emergency_time,    6) \
X(a, STATIC,   SINGULAR, BOOL,     requires_response,   7)
#define lora_mesh_v1_EmergencyPayload_CALLBACK NULL
#define lora_mesh_v1_EmergencyPayload_DEFAULT NULL
#define lora_mesh_v1_EmergencyPayload_location_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_KeyExchangePayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   requesting_node_id,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  offered_public_key,   2) \
X(a, STATIC,   SINGULAR, UENUM,    preferred_algorithm,   3) \
X(a, STATIC,   SINGULAR, BYTES,    challenge_data,    4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  proof_signature,   5) \
X(a, STATIC,   SINGULAR, UINT32,   key_exchange_version,   6) \
X(a, STATIC,   REPEATED, UENUM,    supported_algorithms,   7)
#define lora_mesh_v1_KeyExchangePayload_CALLBACK NULL
#define lora_mesh_v1_KeyExchangePayload_DEFAULT NULL
#define lora_mesh_v1_KeyExchangePayload_offered_public_key_MSGTYPE lora_mesh_v1_PublicKey
#define lora_mesh_v1_KeyExchangePayload_proof_signature_MSGTYPE lora_mesh_v1_CryptographicSignature

#define lora_mesh_v1_CertificateRequestPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   requesting_node_id,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  public_key_to_certify,   2) \
X(a, STATIC,   SINGULAR, STRING,   issuer_node_id,    3) \
X(a, CALLBACK, REPEATED, STRING,   requested_permissions,   4) \
X(a, STATIC,   SINGULAR, UINT32,   requested_validity_days,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  request_signature,   6)
#define lora_mesh_v1_CertificateRequestPayload_CALLBACK pb_default_field_callback
#define lora_mesh_v1_CertificateRequestPayload_DEFAULT NULL
#define lora_mesh_v1_CertificateRequestPayload_public_key_to_certify_MSGTYPE lora_mesh_v1_PublicKey
#define lora_mesh_v1_CertificateRequestPayload_request_signature_MSGTYPE lora_mesh_v1_CryptographicSignature

#define lora_mesh_v1_CertificateResponsePayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   requesting_node_id,   1) \
X(a, STATIC,   SINGULAR, STRING,   issuer_node_id,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  certificate,       3) \
X(a, STATIC,   SINGULAR, UENUM,    status,            4) \
X(a, STATIC,   SINGULAR, STRING,   rejection_reason,   5) \
X(a, STATIC,   SINGULAR, UINT64,   response_timestamp,   6)
#define lora_mesh_v1_CertificateResponsePayload_CALLBACK NULL
#define lora_mesh_v1_CertificateResponsePayload_DEFAULT NULL
#define lora_mesh_v1_CertificateResponsePayload_certificate_MSGTYPE lora_mesh_v1_NodeCertificate

#define lora_mesh_v1_KeyRevocationPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   revoked_key_id,    1) \
X(a, STATIC,   SINGULAR, STRING,   revoking_node_id,   2) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            3) \
X(a, STATIC,   SINGULAR, UINT64,   revocation_timestamp,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  revocation_signature,   5) \
X(a, CALLBACK, REPEATED, STRING,   affected_certificates,   6)
#define lora_mesh_v1_KeyRevocationPayload_CALLBACK pb_default_field_callback
#define lora_mesh_v1_KeyRevocationPayload_DEFAULT NULL
#define lora_mesh_v1_KeyRevocationPayload_revocation_signature_MSGTYPE lora_mesh_v1_CryptographicSignature

#define lora_mesh_v1_SignatureVerificationRequestPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message_id_to_verify,   1) \
X(a, STATIC,   SINGULAR, STRING,   signer_node_id,    2) \
X(a, STATIC,   SINGULAR, STRING,   verifier_node_id,   3) \
X(a, STATIC,   SINGULAR, BYTES,    message_data,      4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  signature_to_verify,   5)
#define lora_mesh_v1_SignatureVerificationRequestPayload_CALLBACK NULL
#define lora_mesh_v1_SignatureVerificationRequestPayload_DEFAULT NULL
#define lora_mesh_v1_SignatureVerificationRequestPayload_signature_to_verify_MSGTYPE lora_mesh_v1_CryptographicSignature

#define lora_mesh_v1_SignatureVerificationResponsePayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   original_message_id,   1) \
X(a, STATIC,   SINGULAR, STRING,   verifier_node_id,   2) \
X(a, STATIC,   SINGULAR, UENUM,    result,            3) \
X(a, STATIC,   SINGULAR, STRING,   verification_details,   4) \
X(a, STATIC,   SINGULAR, UINT64,   verification_timestamp,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  verifier_signature,   6)
#define lora_mesh_v1_SignatureVerificationResponsePayload_CALLBACK NULL
#define lora_mesh_v1_SignatureVerificationResponsePayload_DEFAULT NULL
#define lora_mesh_v1_SignatureVerificationResponsePayload_verifier_signature_MSGTYPE lora_mesh_v1_CryptographicSignature

#define lora_mesh_v1_FragmentPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   stream_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   fragment_index,    2) \
X(a, STATIC,   SINGULAR, UINT32,   total_fragments,   3) \
X(a, STATIC,   SINGULAR, UINT32,   flags,             4) \
X(a, STATIC,   SINGULAR, UENUM,    original_type,     5) \
X(a, STATIC,   SINGULAR, BYTES,    data,              6)
#define lora_mesh_v1_FragmentPayload_CALLBACK NULL
#define lora_mesh_v1_FragmentPayload_DEFAULT NULL

#define lora_mesh_v1_VoicePayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   stream_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          2) \
X(a, STATIC,   SINGULAR, UINT32,   codec_mode,        3) \
X(a, STATIC,   SINGULAR, UINT32,   flags,             4) \
X(a, STATIC,   SINGULAR, UINT32,   total_packets,     5) \
X(a, STATIC,   SINGULAR, BYTES,    frames,            6) \
X(a, STATIC,   SINGULAR, UINT32,   frame_count,       7)
#define lora_mesh_v1_VoicePayload_CALLBACK NULL
#define lora_mesh_v1_VoicePayload_DEFAULT NULL

extern const pb_msgdesc_t lora_mesh_v1_LoRaMessage_msg;
extern const pb_msgdesc_t lora_mesh_v1_GPSUpdatePayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_SyncPosition_msg;
extern const pb_msgdesc_t lora_mesh_v1_SyncTextMessage_msg;
extern const pb_msgdesc_t lora_mesh_v1_ContentSyncPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_HelloPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_TextMessagePayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_ControlMessagePayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_NetworkDiscoveryPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_AckPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_EmergencyPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_KeyExchangePayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_CertificateRequestPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_CertificateResponsePayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_KeyRevocationPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_SignatureVerificationRequestPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_SignatureVerificationResponsePayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_FragmentPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_VoicePayload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lora_mesh_v1_LoRaMessage_fields &lora_mesh_v1_LoRaMessage_msg
#define lora_mesh_v1_GPSUpdatePayload_fields &lora_mesh_v1_GPSUpdatePayload_msg
#define lora_mesh_v1_SyncPosition_fields &lora_mesh_v1_SyncPosition_msg
#define lora_mesh_v1_SyncTextMessage_fields &lora_mesh_v1_SyncTextMessage_msg
#define lora_mesh_v1_ContentSyncPayload_fields &lora_mesh_v1_ContentSyncPayload_msg
#define lora_mesh_v1_HelloPayload_fields &lora_mesh_v1_HelloPayload_msg
#define lora_mesh_v1_TextMessagePayload_fields &lora_mesh_v1_TextMessagePayload_msg
#define lora_mesh_v1_ControlMessagePayload_fields &lora_mesh_v1_ControlMessagePayload_msg
#define lora_mesh_v1_NetworkDiscoveryPayload_fields &lora_mesh_v1_NetworkDiscoveryPayload_msg
#define lora_mesh_v1_AckPayload_fields &lora_mesh_v1_AckPayload_msg
#define lora_mesh_v1_EmergencyPayload_fields &lora_mesh_v1_EmergencyPayload_msg
#define lora_mesh_v1_KeyExchangePayload_fields &lora_mesh_v1_KeyExchangePayload_msg
#define lora_mesh_v1_CertificateRequestPayload_fields &lora_mesh_v1_CertificateRequestPayload_msg
#define lora_mesh_v1_CertificateResponsePayload_fields &lora_mesh_v1_CertificateResponsePayload_msg
#define lora_mesh_v1_KeyRevocationPayload_fields &lora_mesh_v1_KeyRevocationPayload_msg
#define lora_mesh_v1_SignatureVerificationRequestPayload_fields &lora_mesh_v1_SignatureVerificationRequestPayload_msg
#define lora_mesh_v1_SignatureVerificationResponsePayload_fields &lora_mesh_v1_SignatureVerificationResponsePayload_msg
#define lora_mesh_v1_FragmentPayload_fields &lora_mesh_v1_FragmentPayload_msg
#define lora_mesh_v1_VoicePayload_fields &lora_mesh_v1_VoicePayload_msg

/* Maximum encoded size of messages (where known) */
/* lora_mesh_v1_HelloPayload_size depends on runtime parameters */
/* lora_mesh_v1_CertificateRequestPayload_size depends on runtime parameters */
/* lora_mesh_v1_KeyRevocationPayload_size depends on runtime parameters */
#define LORA_MESH_V1_V1_MESSAGES_PB_H_MAX_SIZE   lora_mesh_v1_ContentSyncPayload_size
#define lora_mesh_v1_AckPayload_size             242
#define lora_mesh_v1_ContentSyncPayload_size     2063
#define lora_mesh_v1_ControlMessagePayload_size  172
#define lora_mesh_v1_EmergencyPayload_size       267
#define lora_mesh_v1_FragmentPayload_size        148
#define lora_mesh_v1_GPSUpdatePayload_size       92
#define lora_mesh_v1_KeyExchangePayload_size     374
#define lora_mesh_v1_LoRaMessage_size            519
#define lora_mesh_v1_NetworkDiscoveryPayload_size 1787
#define lora_mesh_v1_SignatureVerificationRequestPayload_size 467
#define lora_mesh_v1_SignatureVerificationResponsePayload_size 334
#define lora_mesh_v1_SyncPosition_size           79
#define lora_mesh_v1_SyncTextMessage_size        191
#define lora_mesh_v1_TextMessagePayload_size     285
#define lora_mesh_v1_VoicePayload_size           167
#if defined(lora_mesh_v1_NodeCertificate_size)
#define lora_mesh_v1_CertificateResponsePayload_size (183 + lora_mesh_v1_NodeCertificate_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
