/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LORA_MESH_V1_V1_METRICS_PB_H_INCLUDED
#define PB_LORA_MESH_V1_V1_METRICS_PB_H_INCLUDED
#include <pb.h>
#include "v1/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _lora_mesh_v1_NodeStatus {
    lora_mesh_v1_NodeStatus_NODE_STATUS_UNSPECIFIED = 0, /* Status not specified */
    lora_mesh_v1_NodeStatus_NODE_STATUS_ONLINE = 1, /* Node is online and operational */
    lora_mesh_v1_NodeStatus_NODE_STATUS_OFFLINE = 2, /* Node is offline */
    lora_mesh_v1_NodeStatus_NODE_STATUS_DEGRADED = 3, /* Node is operational but degraded */
    lora_mesh_v1_NodeStatus_NODE_STATUS_MAINTENANCE = 4, /* Node is in maintenance mode */
    lora_mesh_v1_NodeStatus_NODE_STATUS_ERROR = 5 /* Node has errors */
} lora_mesh_v1_NodeStatus;

typedef enum _lora_mesh_v1_BatteryStatus {
    lora_mesh_v1_BatteryStatus_BATTERY_STATUS_UNSPECIFIED = 0, /* Status not specified */
    lora_mesh_v1_BatteryStatus_BATTERY_STATUS_CHARGING = 1, /* Battery is charging */
    lora_mesh_v1_BatteryStatus_BATTERY_STATUS_DISCHARGING = 2, /* Battery is discharging */
    lora_mesh_v1_BatteryStatus_BATTERY_STATUS_FULL = 3, /* Battery is full */
    lora_mesh_v1_BatteryStatus_BATTERY_STATUS_LOW_BATTERY = 4, /* Battery is low */
    lora_mesh_v1_BatteryStatus_BATTERY_STATUS_CRITICAL_BATTERY = 5 /* Battery is critically low */
} lora_mesh_v1_BatteryStatus;

typedef enum _lora_mesh_v1_ServiceState {
    lora_mesh_v1_ServiceState_SERVICE_STATE_UNSPECIFIED = 0, /* State not specified */
    lora_mesh_v1_ServiceState_SERVICE_STATE_RUNNING = 1, /* Service is running */
    lora_mesh_v1_ServiceState_SERVICE_STATE_STOPPED = 2, /* Service is stopped */
    lora_mesh_v1_ServiceState_SERVICE_STATE_STARTING = 3, /* Service is starting */
    lora_mesh_v1_ServiceState_SERVICE_STATE_STOPPING = 4, /* Service is stopping */
    lora_mesh_v1_ServiceState_SERVICE_STATE_FAILED = 5 /* Service has failed */
} lora_mesh_v1_ServiceState;

typedef enum _lora_mesh_v1_LinkTrend {
    lora_mesh_v1_LinkTrend_LINK_TREND_UNSPECIFIED = 0, /* Trend not specified */
    lora_mesh_v1_LinkTrend_LINK_TREND_IMPROVING = 1, /* Link quality improving */
    lora_mesh_v1_LinkTrend_LINK_TREND_STABLE = 2, /* Link quality stable */
    lora_mesh_v1_LinkTrend_LINK_TREND_DEGRADING = 3, /* Link quality degrading */
    lora_mesh_v1_LinkTrend_LINK_TREND_UNSTABLE = 4 /* Link quality unstable */
} lora_mesh_v1_LinkTrend;

typedef enum _lora_mesh_v1_FlowState {
    lora_mesh_v1_FlowState_FLOW_STATE_UNSPECIFIED = 0, /* State not specified */
    lora_mesh_v1_FlowState_FLOW_STATE_ACTIVE = 1, /* Flow is active */
    lora_mesh_v1_FlowState_FLOW_STATE_INACTIVE = 2, /* Flow is inactive */
    lora_mesh_v1_FlowState_FLOW_STATE_CONGESTED = 3, /* Flow is congested */
    lora_mesh_v1_FlowState_FLOW_STATE_TERMINATED = 4 /* Flow is terminated */
} lora_mesh_v1_FlowState;

typedef enum _lora_mesh_v1_ThroughputTrend {
    lora_mesh_v1_ThroughputTrend_THROUGHPUT_TREND_UNSPECIFIED = 0, /* Trend not specified */
    lora_mesh_v1_ThroughputTrend_THROUGHPUT_TREND_INCREASING = 1, /* Throughput increasing */
    lora_mesh_v1_ThroughputTrend_THROUGHPUT_TREND_STEADY = 2, /* Throughput steady */
    lora_mesh_v1_ThroughputTrend_THROUGHPUT_TREND_DECREASING = 3, /* Throughput decreasing */
    lora_mesh_v1_ThroughputTrend_THROUGHPUT_TREND_VOLATILE = 4 /* Throughput volatile */
} lora_mesh_v1_ThroughputTrend;

typedef enum _lora_mesh_v1_EfficiencyTrend {
    lora_mesh_v1_EfficiencyTrend_EFFICIENCY_TREND_UNSPECIFIED = 0, /* Trend not specified */
    lora_mesh_v1_EfficiencyTrend_EFFICIENCY_TREND_IMPROVING_EFFICIENCY = 1, /* Efficiency improving */
    lora_mesh_v1_EfficiencyTrend_EFFICIENCY_TREND_STABLE_EFFICIENCY = 2, /* Efficiency stable */
    lora_mesh_v1_EfficiencyTrend_EFFICIENCY_TREND_DECLINING_EFFICIENCY = 3 /* Efficiency declining */
} lora_mesh_v1_EfficiencyTrend;

typedef enum _lora_mesh_v1_BottleneckType {
    lora_mesh_v1_BottleneckType_BOTTLENECK_TYPE_UNSPECIFIED = 0, /* Type not specified */
    lora_mesh_v1_BottleneckType_BOTTLENECK_TYPE_CPU_BOTTLENECK = 1, /* CPU bottleneck */
    lora_mesh_v1_BottleneckType_BOTTLENECK_TYPE_MEMORY_BOTTLENECK = 2, /* Memory bottleneck */
    lora_mesh_v1_BottleneckType_BOTTLENECK_TYPE_BANDWIDTH_BOTTLENECK = 3, /* Bandwidth bottleneck */
    lora_mesh_v1_BottleneckType_BOTTLENECK_TYPE_PROTOCOL_BOTTLENECK = 4, /* Protocol bottleneck */
    lora_mesh_v1_BottleneckType_BOTTLENECK_TYPE_ENERGY_BOTTLENECK = 5 /* Energy bottleneck */
} lora_mesh_v1_BottleneckType;

/* Struct definitions */
/* Battery information */
typedef struct _lora_mesh_v1_BatteryInfo {
    float voltage; /* Battery voltage */
    float current; /* Current draw */
    float charge_percentage; /* Charge level 0-100% */
    uint32_t estimated_life_minutes; /* Estimated remaining life */
    lora_mesh_v1_BatteryStatus status; /* Battery status */
    float temperature; /* Battery temperature */
} lora_mesh_v1_BatteryInfo;

/* Radio performance metrics */
typedef struct _lora_mesh_v1_RadioMetrics {
    float rssi_dbm; /* Received signal strength */
    float snr_db; /* Signal to noise ratio */
    float frequency_error_hz; /* Frequency error */
    uint32_t tx_power_dbm; /* Transmission power */
    uint32_t packets_transmitted; /* Packets transmitted */
    uint32_t packets_received; /* Packets received */
    uint32_t packets_lost; /* Packets lost */
    uint32_t crc_errors; /* CRC error count */
    float packet_error_rate; /* Packet error rate */
    uint32_t channel_utilization; /* Channel busy percentage */
} lora_mesh_v1_RadioMetrics;

/* Service status information */
typedef struct _lora_mesh_v1_ServiceStatus {
    char service_name[32]; /* Service identifier */
    lora_mesh_v1_ServiceState state; /* Current state */
    uint64_t start_time; /* Service start time */
    uint32_t restart_count; /* Number of restarts */
    float cpu_usage; /* Service CPU usage */
    uint32_t memory_usage; /* Service memory usage */
    char last_error[64]; /* Last error message */
} lora_mesh_v1_ServiceStatus;

/* Individual node performance metrics */
typedef struct _lora_mesh_v1_NodeMetrics {
    char node_id[16]; /* Node identifier */
    lora_mesh_v1_NodeStatus status; /* Current node status */
    uint64_t uptime_seconds; /* Node uptime */
    uint32_t neighbor_count; /* Number of neighbors */
    float cpu_utilization; /* CPU usage percentage */
    uint32_t memory_used_bytes; /* Memory usage */
    uint32_t memory_total_bytes; /* Total memory */
    bool has_battery_info;
    lora_mesh_v1_BatteryInfo battery_info; /* Battery information */
    bool has_radio_metrics;
    lora_mesh_v1_RadioMetrics radio_metrics; /* Radio performance */
    pb_size_t services_count;
    lora_mesh_v1_ServiceStatus services[4]; /* Running services */
} lora_mesh_v1_NodeMetrics;

/* Detailed link statistics */
typedef struct _lora_mesh_v1_LinkStatistics {
    uint32_t packets_sent; /* Packets sent over link */
    uint32_t packets_received; /* Packets received */
    uint32_t packets_dropped; /* Packets dropped */
    uint32_t retransmissions; /* Retransmission count */
    float average_delay_ms; /* Average packet delay */
    float jitter_ms; /* Packet jitter */
    uint64_t bytes_transmitted; /* Total bytes transmitted */
    uint64_t bytes_received; /* Total bytes received */
    float throughput_bps; /* Link throughput */
} lora_mesh_v1_LinkStatistics;

/* Link stability assessment */
typedef struct _lora_mesh_v1_LinkStability {
    float stability_score; /* Stability score 0.0-1.0 */
    uint32_t link_breaks; /* Number of link breaks */
    uint32_t reconnection_count; /* Reconnection attempts */
    float average_uptime_minutes; /* Average link uptime */
    float availability_percentage; /* Link availability */
    lora_mesh_v1_LinkTrend trend; /* Link quality trend */
} lora_mesh_v1_LinkStability;

/* Link quality metrics between nodes */
typedef struct _lora_mesh_v1_LinkMetrics {
    char source_node[16]; /* Source node ID */
    char destination_node[16]; /* Destination node ID */
    bool has_quality;
    lora_mesh_v1_LinkQuality quality; /* Link quality assessment */
    float distance_meters; /* Distance between nodes */
    uint32_t hop_count; /* Hops between nodes */
    bool has_statistics;
    lora_mesh_v1_LinkStatistics statistics; /* Link statistics */
    bool has_stability;
    lora_mesh_v1_LinkStability stability; /* Link stability metrics */
} lora_mesh_v1_LinkMetrics;

/* Route discovery performance */
typedef struct _lora_mesh_v1_RouteDiscoveryMetrics {
    uint32_t discovery_requests; /* Discovery requests sent */
    uint32_t discovery_replies; /* Discovery replies received */
    float discovery_success_rate; /* Success rate percentage */
    float average_discovery_time_ms; /* Average discovery time */
    uint32_t discovery_overhead; /* Discovery overhead packets */
    float route_optimality; /* Route optimality score */
} lora_mesh_v1_RouteDiscoveryMetrics;

/* Route maintenance performance */
typedef struct _lora_mesh_v1_RouteMaintenanceMetrics {
    uint32_t route_repairs; /* Route repairs attempted */
    uint32_t successful_repairs; /* Successful repairs */
    uint32_t route_breaks; /* Route break events */
    float repair_time_ms; /* Average repair time */
    uint32_t maintenance_overhead; /* Maintenance overhead */
    float route_lifetime_minutes; /* Average route lifetime */
} lora_mesh_v1_RouteMaintenanceMetrics;

/* Network convergence metrics */
typedef struct _lora_mesh_v1_ConvergenceMetrics {
    float convergence_time_ms; /* Time to converge */
    uint32_t routing_updates; /* Routing table updates */
    float network_diameter; /* Network diameter (hops) */
    uint32_t partitions; /* Network partitions detected */
    float global_connectivity; /* Global connectivity ratio */
} lora_mesh_v1_ConvergenceMetrics;

/* Per-protocol performance metrics */
typedef struct _lora_mesh_v1_ProtocolPerformance {
    lora_mesh_v1_RoutingProtocol protocol; /* Protocol type */
    float efficiency_score; /* Efficiency score 0.0-1.0 */
    uint32_t control_overhead; /* Control message overhead */
    float scalability_factor; /* Scalability assessment */
    uint32_t memory_usage; /* Protocol memory usage */
    float cpu_usage; /* Protocol CPU usage */
} lora_mesh_v1_ProtocolPerformance;

/* Routing protocol performance metrics */
typedef struct _lora_mesh_v1_RoutingMetrics {
    lora_mesh_v1_RoutingProtocol active_protocol; /* Currently active protocol */
    bool has_discovery;
    lora_mesh_v1_RouteDiscoveryMetrics discovery; /* Route discovery performance */
    bool has_maintenance;
    lora_mesh_v1_RouteMaintenanceMetrics maintenance; /* Route maintenance */
    bool has_convergence;
    lora_mesh_v1_ConvergenceMetrics convergence; /* Network convergence */
    pb_size_t protocol_performance_count;
    lora_mesh_v1_ProtocolPerformance protocol_performance[4]; /* Per-protocol metrics */
} lora_mesh_v1_RoutingMetrics;

/* Traffic flow information */
typedef struct _lora_mesh_v1_TrafficFlow {
    char flow_id[16]; /* Flow identifier */
    char source_node[16]; /* Source node */
    char destination_node[16]; /* Destination node */
    uint64_t bytes_per_second; /* Current throughput */
    uint64_t packets_per_second; /* Packet rate */
    float average_packet_size; /* Average packet size */
    lora_mesh_v1_QoSPriority priority; /* Traffic priority */
    lora_mesh_v1_FlowState state; /* Flow state */
} lora_mesh_v1_TrafficFlow;

/* QoS class traffic metrics */
typedef struct _lora_mesh_v1_TrafficClassMetrics {
    lora_mesh_v1_QoSPriority priority_class; /* Priority class */
    uint64_t total_bytes; /* Total bytes for class */
    uint64_t total_packets; /* Total packets for class */
    uint32_t dropped_packets; /* Dropped packets */
    float average_latency_ms; /* Average latency */
    float jitter_ms; /* Jitter for class */
    float delivery_ratio; /* Delivery success ratio */
} lora_mesh_v1_TrafficClassMetrics;

/* Congestion hotspot information */
typedef struct _lora_mesh_v1_CongestionPoint {
    char node_id[16]; /* Congested node */
    float congestion_severity; /* Severity 0.0-1.0 */
    uint32_t queue_depth; /* Current queue depth */
    float drop_rate; /* Packet drop rate */
    pb_size_t affected_flows_count;
    char affected_flows[8][16]; /* Affected traffic flows */
} lora_mesh_v1_CongestionPoint;

/* Network congestion metrics */
typedef struct _lora_mesh_v1_CongestionMetrics {
    float congestion_level; /* Congestion level 0.0-1.0 */
    pb_size_t hotspots_count;
    lora_mesh_v1_CongestionPoint hotspots[4]; /* Congestion hotspots */
    uint32_t queue_overflow_events; /* Queue overflow count */
    float average_queue_depth; /* Average queue depth */
    uint32_t backpressure_events; /* Backpressure events */
} lora_mesh_v1_CongestionMetrics;

/* Load balancing metrics */
typedef struct _lora_mesh_v1_LoadBalancing {
    float load_distribution_score; /* Load distribution quality */
    float max_node_utilization; /* Maximum node utilization */
    float min_node_utilization; /* Minimum node utilization */
    float utilization_variance; /* Utilization variance */
    uint32_t load_balancing_events; /* Load balancing actions */
} lora_mesh_v1_LoadBalancing;

/* Traffic flow metrics */
typedef struct _lora_mesh_v1_TrafficMetrics {
    bool has_total_flow;
    lora_mesh_v1_TrafficFlow total_flow; /* Total network traffic */
    pb_size_t per_node_flow_count;
    lora_mesh_v1_TrafficFlow per_node_flow[16]; /* Per-node traffic */
    pb_size_t qos_metrics_count;
    lora_mesh_v1_TrafficClassMetrics qos_metrics[4]; /* QoS class metrics */
    bool has_congestion;
    lora_mesh_v1_CongestionMetrics congestion; /* Congestion information */
    bool has_load_balancing;
    lora_mesh_v1_LoadBalancing load_balancing; /* Load balancing metrics */
} lora_mesh_v1_TrafficMetrics;

/* Latency histogram bucket */
typedef struct _lora_mesh_v1_LatencyBucket {
    float latency_threshold_ms; /* Bucket threshold */
    uint32_t packet_count; /* Packets in bucket */
    float percentage; /* Percentage of total */
} lora_mesh_v1_LatencyBucket;

/* Latency distribution */
typedef struct _lora_mesh_v1_LatencyDistribution {
    pb_size_t buckets_count;
    lora_mesh_v1_LatencyBucket buckets[8]; /* Latency histogram buckets */
    float standard_deviation; /* Standard deviation */
    float skewness; /* Distribution skewness */
} lora_mesh_v1_LatencyDistribution;

/* Latency performance */
typedef struct _lora_mesh_v1_LatencyMetrics {
    float average_latency_ms; /* Average end-to-end latency */
    float median_latency_ms; /* Median latency */
    float percentile_95_latency_ms; /* 95th percentile latency */
    float max_latency_ms; /* Maximum observed latency */
    float jitter_ms; /* Latency jitter */
    bool has_distribution;
    lora_mesh_v1_LatencyDistribution distribution; /* Latency distribution */
} lora_mesh_v1_LatencyMetrics;

/* Throughput metrics */
typedef struct _lora_mesh_v1_ThroughputMetrics {
    uint64_t aggregate_throughput_bps; /* Total network throughput */
    uint64_t average_node_throughput_bps; /* Average per-node throughput */
    uint64_t peak_throughput_bps; /* Peak observed throughput */
    float throughput_efficiency; /* Throughput efficiency ratio */
    lora_mesh_v1_ThroughputTrend trend; /* Throughput trend */
} lora_mesh_v1_ThroughputMetrics;

/* Reliability metrics */
typedef struct _lora_mesh_v1_ReliabilityMetrics {
    float packet_delivery_ratio; /* Overall delivery ratio */
    float end_to_end_reliability; /* E2E reliability */
    uint32_t total_packet_loss; /* Total packets lost */
    float mean_time_between_failures; /* MTBF in hours */
    float mean_time_to_repair; /* MTTR in minutes */
    float availability_percentage; /* Network availability */
} lora_mesh_v1_ReliabilityMetrics;

/* Efficiency metrics */
typedef struct _lora_mesh_v1_EfficiencyMetrics {
    float protocol_efficiency; /* Protocol overhead efficiency */
    float energy_efficiency; /* Energy per bit transmitted */
    float spectrum_efficiency; /* Bits per Hz utilization */
    float routing_efficiency; /* Routing path efficiency */
    lora_mesh_v1_EfficiencyTrend trend; /* Efficiency trend */
} lora_mesh_v1_EfficiencyMetrics;

/* Scalability bottlenecks */
typedef struct _lora_mesh_v1_ScalabilityBottleneck {
    lora_mesh_v1_BottleneckType type; /* Type of bottleneck */
    float severity; /* Severity 0.0-1.0 */
    char description[128]; /* Description of bottleneck */
    pb_size_t mitigation_strategies_count;
    char mitigation_strategies[4][64]; /* Possible mitigations */
} lora_mesh_v1_ScalabilityBottleneck;

/* Scalability assessment */
typedef struct _lora_mesh_v1_ScalabilityMetrics {
    uint32_t current_node_count; /* Current number of nodes */
    uint32_t maximum_supported_nodes; /* Maximum scalable nodes */
    float scalability_factor; /* Scalability assessment */
    bool has_bottlenecks;
    lora_mesh_v1_ScalabilityBottleneck bottlenecks; /* Scalability bottlenecks */
    float growth_sustainability; /* Growth sustainability */
} lora_mesh_v1_ScalabilityMetrics;

/* System performance metrics */
typedef struct _lora_mesh_v1_PerformanceMetrics {
    bool has_latency;
    lora_mesh_v1_LatencyMetrics latency; /* End-to-end latency */
    bool has_throughput;
    lora_mesh_v1_ThroughputMetrics throughput; /* Network throughput */
    bool has_reliability;
    lora_mesh_v1_ReliabilityMetrics reliability; /* Network reliability */
    bool has_efficiency;
    lora_mesh_v1_EfficiencyMetrics efficiency; /* Network efficiency */
    bool has_scalability;
    lora_mesh_v1_ScalabilityMetrics scalability; /* Scalability assessment */
} lora_mesh_v1_PerformanceMetrics;

/* Energy consumption breakdown */
typedef struct _lora_mesh_v1_EnergyBreakdown {
    float radio_power_watts; /* Radio power consumption */
    float cpu_power_watts; /* CPU power consumption */
    float memory_power_watts; /* Memory power consumption */
    float sensors_power_watts; /* Sensor power consumption */
    float idle_power_watts; /* Idle power consumption */
} lora_mesh_v1_EnergyBreakdown;

/* Battery life projection */
typedef struct _lora_mesh_v1_BatteryProjection {
    uint32_t estimated_life_hours; /* Estimated battery life */
    uint32_t low_battery_nodes; /* Nodes with low battery */
    uint32_t critical_battery_nodes; /* Nodes with critical battery */
    float network_lifetime_hours; /* Estimated network lifetime */
} lora_mesh_v1_BatteryProjection;

/* Energy efficiency assessment */
typedef struct _lora_mesh_v1_EnergyEfficiency {
    float bits_per_joule; /* Energy efficiency ratio */
    float energy_per_packet; /* Energy per packet */
    float transmission_efficiency; /* Transmission energy efficiency */
    float processing_efficiency; /* Processing energy efficiency */
} lora_mesh_v1_EnergyEfficiency;

/* Energy consumption metrics */
typedef struct _lora_mesh_v1_EnergyMetrics {
    float total_power_consumption_watts; /* Total power consumption */
    float average_node_power_watts; /* Average node power */
    bool has_energy_breakdown;
    lora_mesh_v1_EnergyBreakdown energy_breakdown; /* Energy breakdown by component */
    bool has_battery_projection;
    lora_mesh_v1_BatteryProjection battery_projection; /* Battery life projection */
    bool has_energy_efficiency;
    lora_mesh_v1_EnergyEfficiency energy_efficiency; /* Energy efficiency metrics */
} lora_mesh_v1_EnergyMetrics;

/* Comprehensive network monitoring and metrics */
typedef struct _lora_mesh_v1_NetworkMetrics {
    bool has_node_metrics;
    lora_mesh_v1_NodeMetrics node_metrics; /* Individual node metrics */
    bool has_link_metrics;
    lora_mesh_v1_LinkMetrics link_metrics; /* Link quality metrics */
    bool has_routing_metrics;
    lora_mesh_v1_RoutingMetrics routing_metrics; /* Routing performance */
    bool has_traffic_metrics;
    lora_mesh_v1_TrafficMetrics traffic_metrics; /* Traffic statistics */
    bool has_performance_metrics;
    lora_mesh_v1_PerformanceMetrics performance_metrics; /* System performance */
    bool has_energy_metrics;
    lora_mesh_v1_EnergyMetrics energy_metrics; /* Energy consumption */
} lora_mesh_v1_NetworkMetrics;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _lora_mesh_v1_NodeStatus_MIN lora_mesh_v1_NodeStatus_NODE_STATUS_UNSPECIFIED
#define _lora_mesh_v1_NodeStatus_MAX lora_mesh_v1_NodeStatus_NODE_STATUS_ERROR
#define _lora_mesh_v1_NodeStatus_ARRAYSIZE ((lora_mesh_v1_NodeStatus)(lora_mesh_v1_NodeStatus_NODE_STATUS_ERROR+1))

#define _lora_mesh_v1_BatteryStatus_MIN lora_mesh_v1_BatteryStatus_BATTERY_STATUS_UNSPECIFIED
#define _lora_mesh_v1_BatteryStatus_MAX lora_mesh_v1_BatteryStatus_BATTERY_STATUS_CRITICAL_BATTERY
#define _lora_mesh_v1_BatteryStatus_ARRAYSIZE ((lora_mesh_v1_BatteryStatus)(lora_mesh_v1_BatteryStatus_BATTERY_STATUS_CRITICAL_BATTERY+1))

#define _lora_mesh_v1_ServiceState_MIN lora_mesh_v1_ServiceState_SERVICE_STATE_UNSPECIFIED
#define _lora_mesh_v1_ServiceState_MAX lora_mesh_v1_ServiceState_SERVICE_STATE_FAILED
#define _lora_mesh_v1_ServiceState_ARRAYSIZE ((lora_mesh_v1_ServiceState)(lora_mesh_v1_ServiceState_SERVICE_STATE_FAILED+1))

#define _lora_mesh_v1_LinkTrend_MIN lora_mesh_v1_LinkTrend_LINK_TREND_UNSPECIFIED
#define _lora_mesh_v1_LinkTrend_MAX lora_mesh_v1_LinkTrend_LINK_TREND_UNSTABLE
#define _lora_mesh_v1_LinkTrend_ARRAYSIZE ((lora_mesh_v1_LinkTrend)(lora_mesh_v1_LinkTrend_LINK_TREND_UNSTABLE+1))

#define _lora_mesh_v1_FlowState_MIN lora_mesh_v1_FlowState_FLOW_STATE_UNSPECIFIED
#define _lora_mesh_v1_FlowState_MAX lora_mesh_v1_FlowState_FLOW_STATE_TERMINATED
#define _lora_mesh_v1_FlowState_ARRAYSIZE ((lora_mesh_v1_FlowState)(lora_mesh_v1_FlowState_FLOW_STATE_TERMINATED+1))

#define _lora_mesh_v1_ThroughputTrend_MIN lora_mesh_v1_ThroughputTrend_THROUGHPUT_TREND_UNSPECIFIED
#define _lora_mesh_v1_ThroughputTrend_MAX lora_mesh_v1_ThroughputTrend_THROUGHPUT_TREND_VOLATILE
#define _lora_mesh_v1_ThroughputTrend_ARRAYSIZE ((lora_mesh_v1_ThroughputTrend)(lora_mesh_v1_ThroughputTrend_THROUGHPUT_TREND_VOLATILE+1))

#define _lora_mesh_v1_EfficiencyTrend_MIN lora_mesh_v1_EfficiencyTrend_EFFICIENCY_TREND_UNSPECIFIED
#define _lora_mesh_v1_EfficiencyTrend_MAX lora_mesh_v1_EfficiencyTrend_EFFICIENCY_TREND_DECLINING_EFFICIENCY
#define _lora_mesh_v1_EfficiencyTrend_ARRAYSIZE ((lora_mesh_v1_EfficiencyTrend)(lora_mesh_v1_EfficiencyTrend_EFFICIENCY_TREND_DECLINING_EFFICIENCY+1))

#define _lora_mesh_v1_BottleneckType_MIN lora_mesh_v1_BottleneckType_BOTTLENECK_TYPE_UNSPECIFIED
#define _lora_mesh_v1_BottleneckType_MAX lora_mesh_v1_BottleneckType_BOTTLENECK_TYPE_ENERGY_BOTTLENECK
#define _lora_mesh_v1_BottleneckType_ARRAYSIZE ((lora_mesh_v1_BottleneckType)(lora_mesh_v1_BottleneckType_BOTTLENECK_TYPE_ENERGY_BOTTLENECK+1))


#define lora_mesh_v1_NodeMetrics_status_ENUMTYPE lora_mesh_v1_NodeStatus

#define lora_mesh_v1_BatteryInfo_status_ENUMTYPE lora_mesh_v1_BatteryStatus


#define lora_mesh_v1_ServiceStatus_state_ENUMTYPE lora_mesh_v1_ServiceState



#define lora_mesh_v1_LinkStability_trend_ENUMTYPE lora_mesh_v1_LinkTrend

#define lora_mesh_v1_RoutingMetrics_active_protocol_ENUMTYPE lora_mesh_v1_RoutingProtocol




#define lora_mesh_v1_ProtocolPerformance_protocol_ENUMTYPE lora_mesh_v1_RoutingProtocol


#define lora_mesh_v1_TrafficFlow_priority_ENUMTYPE lora_mesh_v1_QoSPriority
#define lora_mesh_v1_TrafficFlow_state_ENUMTYPE lora_mesh_v1_FlowState

#define lora_mesh_v1_TrafficClassMetrics_priority_class_ENUMTYPE lora_mesh_v1_QoSPriority








#define lora_mesh_v1_ThroughputMetrics_trend_ENUMTYPE lora_mesh_v1_ThroughputTrend


#define lora_mesh_v1_EfficiencyMetrics_trend_ENUMTYPE lora_mesh_v1_EfficiencyTrend


#define lora_mesh_v1_ScalabilityBottleneck_type_ENUMTYPE lora_mesh_v1_BottleneckType






/* Initializer values for message structs */
#define lora_mesh_v1_NetworkMetrics_init_default {false, lora_mesh_v1_NodeMetrics_init_default, false, lora_mesh_v1_LinkMetrics_init_default, false, lora_mesh_v1_RoutingMetrics_init_default, false, lora_mesh_v1_TrafficMetrics_init_default, false, lora_mesh_v1_PerformanceMetrics_init_default, false, lora_mesh_v1_EnergyMetrics_init_default}
#define lora_mesh_v1_NodeMetrics_init_default    {"", _lora_mesh_v1_NodeStatus_MIN, 0, 0, 0, 0, 0, false, lora_mesh_v1_BatteryInfo_init_default, false, lora_mesh_v1_RadioMetrics_init_default, 0, {lora_mesh_v1_ServiceStatus_init_default, lora_mesh_v1_ServiceStatus_init_default, lora_mesh_v1_ServiceStatus_init_default, lora_mesh_v1_ServiceStatus_init_default}}
#define lora_mesh_v1_BatteryInfo_init_default    {0, 0, 0, 0, _lora_mesh_v1_BatteryStatus_MIN, 0}
#define lora_mesh_v1_RadioMetrics_init_default   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_ServiceStatus_init_default  {"", _lora_mesh_v1_ServiceState_MIN, 0, 0, 0, 0, ""}
#define lora_mesh_v1_LinkMetrics_init_default    {"", "", false, lora_mesh_v1_LinkQuality_init_default, 0, 0, false, lora_mesh_v1_LinkStatistics_init_default, false, lora_mesh_v1_LinkStability_init_default}
#define lora_mesh_v1_LinkStatistics_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_LinkStability_init_default  {0, 0, 0, 0, 0, _lora_mesh_v1_LinkTrend_MIN}
#define lora_mesh_v1_RoutingMetrics_init_default {_lora_mesh_v1_RoutingProtocol_MIN, false, lora_mesh_v1_RouteDiscoveryMetrics_init_default, false, lora_mesh_v1_RouteMaintenanceMetrics_init_default, false, lora_mesh_v1_ConvergenceMetrics_init_default, 0, {lora_mesh_v1_ProtocolPerformance_init_default, lora_mesh_v1_ProtocolPerformance_init_default, lora_mesh_v1_ProtocolPerformance_init_default, lora_mesh_v1_ProtocolPerformance_init_default}}
#define lora_mesh_v1_RouteDiscoveryMetrics_init_default {0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_RouteMaintenanceMetrics_init_default {0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_ConvergenceMetrics_init_default {0, 0, 0, 0, 0}
#define lora_mesh_v1_ProtocolPerformance_init_default {_lora_mesh_v1_RoutingProtocol_MIN, 0, 0, 0, 0, 0}
#define lora_mesh_v1_TrafficMetrics_init_default {false, lora_mesh_v1_TrafficFlow_init_default, 0, {lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default, lora_mesh_v1_TrafficFlow_init_default}, 0, {lora_mesh_v1_TrafficClassMetrics_init_default, lora_mesh_v1_TrafficClassMetrics_init_default, lora_mesh_v1_TrafficClassMetrics_init_default, lora_mesh_v1_TrafficClassMetrics_init_default}, false, lora_mesh_v1_CongestionMetrics_init_default, false, lora_mesh_v1_LoadBalancing_init_default}
#define lora_mesh_v1_TrafficFlow_init_default    {"", "", "", 0, 0, 0, _lora_mesh_v1_QoSPriority_MIN, _lora_mesh_v1_FlowState_MIN}
#define lora_mesh_v1_TrafficClassMetrics_init_default {_lora_mesh_v1_QoSPriority_MIN, 0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_CongestionMetrics_init_default {0, 0, {lora_mesh_v1_CongestionPoint_init_default, lora_mesh_v1_CongestionPoint_init_default, lora_mesh_v1_CongestionPoint_init_default, lora_mesh_v1_CongestionPoint_init_default}, 0, 0, 0}
#define lora_mesh_v1_CongestionPoint_init_default {"", 0, 0, 0, 0, {"", "", "", "", "", "", "", ""}}
#define lora_mesh_v1_LoadBalancing_init_default  {0, 0, 0, 0, 0}
#define lora_mesh_v1_PerformanceMetrics_init_default {false, lora_mesh_v1_LatencyMetrics_init_default, false, lora_mesh_v1_ThroughputMetrics_init_default, false, lora_mesh_v1_ReliabilityMetrics_init_default, false, lora_mesh_v1_EfficiencyMetrics_init_default, false, lora_mesh_v1_ScalabilityMetrics_init_default}
#define lora_mesh_v1_LatencyMetrics_init_default {0, 0, 0, 0, 0, false, lora_mesh_v1_LatencyDistribution_init_default}
#define lora_mesh_v1_LatencyDistribution_init_default {0, {lora_mesh_v1_LatencyBucket_init_default, lora_mesh_v1_LatencyBucket_init_default, lora_mesh_v1_LatencyBucket_init_default, lora_mesh_v1_LatencyBucket_init_default, lora_mesh_v1_LatencyBucket_init_default, lora_mesh_v1_LatencyBucket_init_default, lora_mesh_v1_LatencyBucket_init_default, lora_mesh_v1_LatencyBucket_init_default}, 0, 0}
#define lora_mesh_v1_LatencyBucket_init_default  {0, 0, 0}
#define lora_mesh_v1_ThroughputMetrics_init_default {0, 0, 0, 0, _lora_mesh_v1_ThroughputTrend_MIN}
#define lora_mesh_v1_ReliabilityMetrics_init_default {0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_EfficiencyMetrics_init_default {0, 0, 0, 0, _lora_mesh_v1_EfficiencyTrend_MIN}
#define lora_mesh_v1_ScalabilityMetrics_init_default {0, 0, 0, false, lora_mesh_v1_ScalabilityBottleneck_init_default, 0}
#define lora_mesh_v1_ScalabilityBottleneck_init_default {_lora_mesh_v1_BottleneckType_MIN, 0, "", 0, {"", "", "", ""}}
#define lora_mesh_v1_EnergyMetrics_init_default  {0, 0, false, lora_mesh_v1_EnergyBreakdown_init_default, false, lora_mesh_v1_BatteryProjection_init_default, false, lora_mesh_v1_EnergyEfficiency_init_default}
#define lora_mesh_v1_EnergyBreakdown_init_default {0, 0, 0, 0, 0}
#define lora_mesh_v1_BatteryProjection_init_default {0, 0, 0, 0}
#define lora_mesh_v1_EnergyEfficiency_init_default {0, 0, 0, 0}
#define lora_mesh_v1_NetworkMetrics_init_zero    {false, lora_mesh_v1_NodeMetrics_init_zero, false, lora_mesh_v1_LinkMetrics_init_zero, false, lora_mesh_v1_RoutingMetrics_init_zero, false, lora_mesh_v1_TrafficMetrics_init_zero, false, lora_mesh_v1_PerformanceMetrics_init_zero, false, lora_mesh_v1_EnergyMetrics_init_zero}
#define lora_mesh_v1_NodeMetrics_init_zero       {"", _lora_mesh_v1_NodeStatus_MIN, 0, 0, 0, 0, 0, false, lora_mesh_v1_BatteryInfo_init_zero, false, lora_mesh_v1_RadioMetrics_init_zero, 0, {lora_mesh_v1_ServiceStatus_init_zero, lora_mesh_v1_ServiceStatus_init_zero, lora_mesh_v1_ServiceStatus_init_zero, lora_mesh_v1_ServiceStatus_init_zero}}
#define lora_mesh_v1_BatteryInfo_init_zero       {0, 0, 0, 0, _lora_mesh_v1_BatteryStatus_MIN, 0}
#define lora_mesh_v1_RadioMetrics_init_zero      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_ServiceStatus_init_zero     {"", _lora_mesh_v1_ServiceState_MIN, 0, 0, 0, 0, ""}
#define lora_mesh_v1_LinkMetrics_init_zero       {"", "", false, lora_mesh_v1_LinkQuality_init_zero, 0, 0, false, lora_mesh_v1_LinkStatistics_init_zero, false, lora_mesh_v1_LinkStability_init_zero}
#define lora_mesh_v1_LinkStatistics_init_zero    {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_LinkStability_init_zero     {0, 0, 0, 0, 0, _lora_mesh_v1_LinkTrend_MIN}
#define lora_mesh_v1_RoutingMetrics_init_zero    {_lora_mesh_v1_RoutingProtocol_MIN, false, lora_mesh_v1_RouteDiscoveryMetrics_init_zero, false, lora_mesh_v1_RouteMaintenanceMetrics_init_zero, false, lora_mesh_v1_ConvergenceMetrics_init_zero, 0, {lora_mesh_v1_ProtocolPerformance_init_zero, lora_mesh_v1_ProtocolPerformance_init_zero, lora_mesh_v1_ProtocolPerformance_init_zero, lora_mesh_v1_ProtocolPerformance_init_zero}}
#define lora_mesh_v1_RouteDiscoveryMetrics_init_zero {0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_RouteMaintenanceMetrics_init_zero {0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_ConvergenceMetrics_init_zero {0, 0, 0, 0, 0}
#define lora_mesh_v1_ProtocolPerformance_init_zero {_lora_mesh_v1_RoutingProtocol_MIN, 0, 0, 0, 0, 0}
#define lora_mesh_v1_TrafficMetrics_init_zero    {false, lora_mesh_v1_TrafficFlow_init_zero, 0, {lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero, lora_mesh_v1_TrafficFlow_init_zero}, 0, {lora_mesh_v1_TrafficClassMetrics_init_zero, lora_mesh_v1_TrafficClassMetrics_init_zero, lora_mesh_v1_TrafficClassMetrics_init_zero, lora_mesh_v1_TrafficClassMetrics_init_zero}, false, lora_mesh_v1_CongestionMetrics_init_zero, false, lora_mesh_v1_LoadBalancing_init_zero}
#define lora_mesh_v1_TrafficFlow_init_zero       {"", "", "", 0, 0, 0, _lora_mesh_v1_QoSPriority_MIN, _lora_mesh_v1_FlowState_MIN}
#define lora_mesh_v1_TrafficClassMetrics_init_zero {_lora_mesh_v1_QoSPriority_MIN, 0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_CongestionMetrics_init_zero {0, 0, {lora_mesh_v1_CongestionPoint_init_zero, lora_mesh_v1_CongestionPoint_init_zero, lora_mesh_v1_CongestionPoint_init_zero, lora_mesh_v1_CongestionPoint_init_zero}, 0, 0, 0}
#define lora_mesh_v1_CongestionPoint_init_zero   {"", 0, 0, 0, 0, {"", "", "", "", "", "", "", ""}}
#define lora_mesh_v1_LoadBalancing_init_zero     {0, 0, 0, 0, 0}
#define lora_mesh_v1_PerformanceMetrics_init_zero {false, lora_mesh_v1_LatencyMetrics_init_zero, false, lora_mesh_v1_ThroughputMetrics_init_zero, false, lora_mesh_v1_ReliabilityMetrics_init_zero, false, lora_mesh_v1_EfficiencyMetrics_init_zero, false, lora_mesh_v1_ScalabilityMetrics_init_zero}
#define lora_mesh_v1_LatencyMetrics_init_zero    {0, 0, 0, 0, 0, false, lora_mesh_v1_LatencyDistribution_init_zero}
#define lora_mesh_v1_LatencyDistribution_init_zero {0, {lora_mesh_v1_LatencyBucket_init_zero, lora_mesh_v1_LatencyBucket_init_zero, lora_mesh_v1_LatencyBucket_init_zero, lora_mesh_v1_LatencyBucket_init_zero, lora_mesh_v1_LatencyBucket_init_zero, lora_mesh_v1_LatencyBucket_init_zero, lora_mesh_v1_LatencyBucket_init_zero, lora_mesh_v1_LatencyBucket_init_zero}, 0, 0}
#define lora_mesh_v1_LatencyBucket_init_zero     {0, 0, 0}
#define lora_mesh_v1_ThroughputMetrics_init_zero {0, 0, 0, 0, _lora_mesh_v1_ThroughputTrend_MIN}
#define lora_mesh_v1_ReliabilityMetrics_init_zero {0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_EfficiencyMetrics_init_zero {0, 0, 0, 0, _lora_mesh_v1_EfficiencyTrend_MIN}
#define lora_mesh_v1_ScalabilityMetrics_init_zero {0, 0, 0, false, lora_mesh_v1_ScalabilityBottleneck_init_zero, 0}
#define lora_mesh_v1_ScalabilityBottleneck_init_zero {_lora_mesh_v1_BottleneckType_MIN, 0, "", 0, {"", "", "", ""}}
#define lora_mesh_v1_EnergyMetrics_init_zero     {0, 0, false, lora_mesh_v1_EnergyBreakdown_init_zero, false, lora_mesh_v1_BatteryProjection_init_zero, false, lora_mesh_v1_EnergyEfficiency_init_zero}
#define lora_mesh_v1_EnergyBreakdown_init_zero   {0, 0, 0, 0, 0}
#define lora_mesh_v1_BatteryProjection_init_zero {0, 0, 0, 0}
#define lora_mesh_v1_EnergyEfficiency_init_zero  {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define lora_mesh_v1_BatteryInfo_voltage_tag     1
#define lora_mesh_v1_BatteryInfo_current_tag     2
#define lora_mesh_v1_BatteryInfo_charge_percentage_tag 3
#define lora_mesh_v1_BatteryInfo_estimated_life_minutes_tag 4
#define lora_mesh_v1_BatteryInfo_status_tag      5
#define lora_mesh_v1_BatteryInfo_temperature_tag 6
#define lora_mesh_v1_RadioMetrics_rssi_dbm_tag   1
#define lora_mesh_v1_RadioMetrics_snr_db_tag     2
#define lora_mesh_v1_RadioMetrics_frequency_error_hz_tag 3
#define lora_mesh_v1_RadioMetrics_tx_power_dbm_tag 4
#define lora_mesh_v1_RadioMetrics_packets_transmitted_tag 5
#define lora_mesh_v1_RadioMetrics_packets_received_tag 6
#define lora_mesh_v1_RadioMetrics_packets_lost_tag 7
#define lora_mesh_v1_RadioMetrics_crc_errors_tag 8
#define lora_mesh_v1_RadioMetrics_packet_error_rate_tag 9
#define lora_mesh_v1_RadioMetrics_channel_utilization_tag 10
#define lora_mesh_v1_ServiceStatus_service_name_tag 1
#define lora_mesh_v1_ServiceStatus_state_tag     2
#define lora_mesh_v1_ServiceStatus_start_time_tag 3
#define lora_mesh_v1_ServiceStatus_restart_count_tag 4
#define lora_mesh_v1_ServiceStatus_cpu_usage_tag 5
#define lora_mesh_v1_ServiceStatus_memory_usage_tag 6
#define lora_mesh_v1_ServiceStatus_last_error_tag 7
#define lora_mesh_v1_NodeMetrics_node_id_tag     1
#define lora_mesh_v1_NodeMetrics_status_tag      2
#define lora_mesh_v1_NodeMetrics_uptime_seconds_tag 3
#define lora_mesh_v1_NodeMetrics_neighbor_count_tag 4
#define lora_mesh_v1_NodeMetrics_cpu_utilization_tag 5
#define lora_mesh_v1_NodeMetrics_memory_used_bytes_tag 6
#define lora_mesh_v1_NodeMetrics_memory_total_bytes_tag 7
#define lora_mesh_v1_NodeMetrics_battery_info_tag 8
#define lora_mesh_v1_NodeMetrics_radio_metrics_tag 9
#define lora_mesh_v1_NodeMetrics_services_tag    10
#define lora_mesh_v1_LinkStatistics_packets_sent_tag 1
#define lora_mesh_v1_LinkStatistics_packets_received_tag 2
#define lora_mesh_v1_LinkStatistics_packets_dropped_tag 3
#define lora_mesh_v1_LinkStatistics_retransmissions_tag 4
#define lora_mesh_v1_LinkStatistics_average_delay_ms_tag 5
#define lora_mesh_v1_LinkStatistics_jitter_ms_tag 6
#define lora_mesh_v1_LinkStatistics_bytes_transmitted_tag 7
#define lora_mesh_v1_LinkStatistics_bytes_received_tag 8
#define lora_mesh_v1_LinkStatistics_throughput_bps_tag 9
#define lora_mesh_v1_LinkStability_stability_score_tag 1
#define lora_mesh_v1_LinkStability_link_breaks_tag 2
#define lora_mesh_v1_LinkStability_reconnection_count_tag 3
#define lora_mesh_v1_LinkStability_average_uptime_minutes_tag 4
#define lora_mesh_v1_LinkStability_availability_percentage_tag 5
#define lora_mesh_v1_LinkStability_trend_tag     6
#define lora_mesh_v1_LinkMetrics_source_node_tag 1
#define lora_mesh_v1_LinkMetrics_destination_node_tag 2
#define lora_mesh_v1_LinkMetrics_quality_tag     3
#define lora_mesh_v1_LinkMetrics_distance_meters_tag 4
#define lora_mesh_v1_LinkMetrics_hop_count_tag   5
#define lora_mesh_v1_LinkMetrics_statistics_tag  6
#define lora_mesh_v1_LinkMetrics_stability_tag   7
#define lora_mesh_v1_RouteDiscoveryMetrics_discovery_requests_tag 1
#define lora_mesh_v1_RouteDiscoveryMetrics_discovery_replies_tag 2
#define lora_mesh_v1_RouteDiscoveryMetrics_discovery_success_rate_tag 3
#define lora_mesh_v1_RouteDiscoveryMetrics_average_discovery_time_ms_tag 4
#define lora_mesh_v1_RouteDiscoveryMetrics_discovery_overhead_tag 5
#define lora_mesh_v1_RouteDiscoveryMetrics_route_optimality_tag 6
#define lora_mesh_v1_RouteMaintenanceMetrics_route_repairs_tag 1
#define lora_mesh_v1_RouteMaintenanceMetrics_successful_repairs_tag 2
#define lora_mesh_v1_RouteMaintenanceMetrics_route_breaks_tag 3
#define lora_mesh_v1_RouteMaintenanceMetrics_repair_time_ms_tag 4
#define lora_mesh_v1_RouteMaintenanceMetrics_maintenance_overhead_tag 5
#define lora_mesh_v1_RouteMaintenanceMetrics_route_lifetime_minutes_tag 6
#define lora_mesh_v1_ConvergenceMetrics_convergence_time_ms_tag 1
#define lora_mesh_v1_ConvergenceMetrics_routing_updates_tag 2
#define lora_mesh_v1_ConvergenceMetrics_network_diameter_tag 3
#define lora_mesh_v1_ConvergenceMetrics_partitions_tag 4
#define lora_mesh_v1_ConvergenceMetrics_global_connectivity_tag 5
#define lora_mesh_v1_ProtocolPerformance_protocol_tag 1
#define lora_mesh_v1_ProtocolPerformance_efficiency_score_tag 2
#define lora_mesh_v1_ProtocolPerformance_control_overhead_tag 3
#define lora_mesh_v1_ProtocolPerformance_scalability_factor_tag 4
#define lora_mesh_v1_ProtocolPerformance_memory_usage_tag 5
#define lora_mesh_v1_ProtocolPerformance_cpu_usage_tag 6
#define lora_mesh_v1_RoutingMetrics_active_protocol_tag 1
#define lora_mesh_v1_RoutingMetrics_discovery_tag 2
#define lora_mesh_v1_RoutingMetrics_maintenance_tag 3
#define lora_mesh_v1_RoutingMetrics_convergence_tag 4
#define lora_mesh_v1_RoutingMetrics_protocol_performance_tag 5
#define lora_mesh_v1_TrafficFlow_flow_id_tag     1
#define lora_mesh_v1_TrafficFlow_source_node_tag 2
#define lora_mesh_v1_TrafficFlow_destination_node_tag 3
#define lora_mesh_v1_TrafficFlow_bytes_per_second_tag 4
#define lora_mesh_v1_TrafficFlow_packets_per_second_tag 5
#define lora_mesh_v1_TrafficFlow_average_packet_size_tag 6
#define lora_mesh_v1_TrafficFlow_priority_tag    7
#define lora_mesh_v1_TrafficFlow_state_tag       8
#define lora_mesh_v1_TrafficClassMetrics_priority_class_tag 1
#define lora_mesh_v1_TrafficClassMetrics_total_bytes_tag 2
#define lora_mesh_v1_TrafficClassMetrics_total_packets_tag 3
#define lora_mesh_v1_TrafficClassMetrics_dropped_packets_tag 4
#define lora_mesh_v1_TrafficClassMetrics_average_latency_ms_tag 5
#define lora_mesh_v1_TrafficClassMetrics_jitter_ms_tag 6
#define lora_mesh_v1_TrafficClassMetrics_delivery_ratio_tag 7
#define lora_mesh_v1_CongestionPoint_node_id_tag 1
#define lora_mesh_v1_CongestionPoint_congestion_severity_tag 2
#define lora_mesh_v1_CongestionPoint_queue_depth_tag 3
#define lora_mesh_v1_CongestionPoint_drop_rate_tag 4
#define lora_mesh_v1_CongestionPoint_affected_flows_tag 5
#define lora_mesh_v1_CongestionMetrics_congestion_level_tag 1
#define lora_mesh_v1_CongestionMetrics_hotspots_tag 2
#define lora_mesh_v1_CongestionMetrics_queue_overflow_events_tag 3
#define lora_mesh_v1_CongestionMetrics_average_queue_depth_tag 4
#define lora_mesh_v1_CongestionMetrics_backpressure_events_tag 5
#define lora_mesh_v1_LoadBalancing_load_distribution_score_tag 1
#define lora_mesh_v1_LoadBalancing_max_node_utilization_tag 2
#define lora_mesh_v1_LoadBalancing_min_node_utilization_tag 3
#define lora_mesh_v1_LoadBalancing_utilization_variance_tag 4
#define lora_mesh_v1_LoadBalancing_load_balancing_events_tag 5
#define lora_mesh_v1_TrafficMetrics_total_flow_tag 1
#define lora_mesh_v1_TrafficMetrics_per_node_flow_tag 2
#define lora_mesh_v1_TrafficMetrics_qos_metrics_tag 3
#define lora_mesh_v1_TrafficMetrics_congestion_tag 4
#define lora_mesh_v1_TrafficMetrics_load_balancing_tag 5
#define lora_mesh_v1_LatencyBucket_latency_threshold_ms_tag 1
#define lora_mesh_v1_LatencyBucket_packet_count_tag 2
#define lora_mesh_v1_LatencyBucket_percentage_tag 3
#define lora_mesh_v1_LatencyDistribution_buckets_tag 1
#define lora_mesh_v1_LatencyDistribution_standard_deviation_tag 2
#define lora_mesh_v1_LatencyDistribution_skewness_tag 3
#define lora_mesh_v1_LatencyMetrics_average_latency_ms_tag 1
#define lora_mesh_v1_LatencyMetrics_median_latency_ms_tag 2
#define lora_mesh_v1_LatencyMetrics_percentile_95_latency_ms_tag 3
#define lora_mesh_v1_LatencyMetrics_max_latency_ms_tag 4
#define lora_mesh_v1_LatencyMetrics_jitter_ms_tag 5
#define lora_mesh_v1_LatencyMetrics_distribution_tag 6
#define lora_mesh_v1_ThroughputMetrics_aggregate_throughput_bps_tag 1
#define lora_mesh_v1_ThroughputMetrics_average_node_throughput_bps_tag 2
#define lora_mesh_v1_ThroughputMetrics_peak_throughput_bps_tag 3
#define lora_mesh_v1_ThroughputMetrics_throughput_efficiency_tag 4
#define lora_mesh_v1_ThroughputMetrics_trend_tag 5
#define lora_mesh_v1_ReliabilityMetrics_packet_delivery_ratio_tag 1
#define lora_mesh_v1_ReliabilityMetrics_end_to_end_reliability_tag 2
#define lora_mesh_v1_ReliabilityMetrics_total_packet_loss_tag 3
#define lora_mesh_v1_ReliabilityMetrics_mean_time_between_failures_tag 4
#define lora_mesh_v1_ReliabilityMetrics_mean_time_to_repair_tag 5
#define lora_mesh_v1_ReliabilityMetrics_availability_percentage_tag 6
#define lora_mesh_v1_EfficiencyMetrics_protocol_efficiency_tag 1
#define lora_mesh_v1_EfficiencyMetrics_energy_efficiency_tag 2
#define lora_mesh_v1_EfficiencyMetrics_spectrum_efficiency_tag 3
#define lora_mesh_v1_EfficiencyMetrics_routing_efficiency_tag 4
#define lora_mesh_v1_EfficiencyMetrics_trend_tag 5
#define lora_mesh_v1_ScalabilityBottleneck_type_tag 1
#define lora_mesh_v1_ScalabilityBottleneck_severity_tag 2
#define lora_mesh_v1_ScalabilityBottleneck_description_tag 3
#define lora_mesh_v1_ScalabilityBottleneck_mitigation_strategies_tag 4
#define lora_mesh_v1_ScalabilityMetrics_current_node_count_tag 1
#define lora_mesh_v1_ScalabilityMetrics_maximum_supported_nodes_tag 2
#define lora_mesh_v1_ScalabilityMetrics_scalability_factor_tag 3
#define lora_mesh_v1_ScalabilityMetrics_bottlenecks_tag 4
#define lora_mesh_v1_ScalabilityMetrics_growth_sustainability_tag 5
#define lora_mesh_v1_PerformanceMetrics_latency_tag 1
#define lora_mesh_v1_PerformanceMetrics_throughput_tag 2
#define lora_mesh_v1_PerformanceMetrics_reliability_tag 3
#define lora_mesh_v1_PerformanceMetrics_efficiency_tag 4
#define lora_mesh_v1_PerformanceMetrics_scalability_tag 5
#define lora_mesh_v1_EnergyBreakdown_radio_power_watts_tag 1
#define lora_mesh_v1_EnergyBreakdown_cpu_power_watts_tag 2
#define lora_mesh_v1_EnergyBreakdown_memory_power_watts_tag 3
#define lora_mesh_v1_EnergyBreakdown_sensors_power_watts_tag 4
#define lora_mesh_v1_EnergyBreakdown_idle_power_watts_tag 5
#define lora_mesh_v1_BatteryProjection_estimated_life_hours_tag 1
#define lora_mesh_v1_BatteryProjection_low_battery_nodes_tag 2
#define lora_mesh_v1_BatteryProjection_critical_battery_nodes_tag 3
#define lora_mesh_v1_BatteryProjection_network_lifetime_hours_tag 4
#define lora_mesh_v1_EnergyEfficiency_bits_per_joule_tag 1
#define lora_mesh_v1_EnergyEfficiency_energy_per_packet_tag 2
#define lora_mesh_v1_EnergyEfficiency_transmission_efficiency_tag 3
#define lora_mesh_v1_EnergyEfficiency_processing_efficiency_tag 4
#define lora_mesh_v1_EnergyMetrics_total_power_consumption_watts_tag 1
#define lora_mesh_v1_EnergyMetrics_average_node_power_watts_tag 2
#define lora_mesh_v1_EnergyMetrics_energy_breakdown_tag 3
#define lora_mesh_v1_EnergyMetrics_battery_projection_tag 4
#define lora_mesh_v1_EnergyMetrics_energy_efficiency_tag 5
#define lora_mesh_v1_NetworkMetrics_node_metrics_tag 1
#define lora_mesh_v1_NetworkMetrics_link_metrics_tag 2
#define lora_mesh_v1_NetworkMetrics_routing_metrics_tag 3
#define lora_mesh_v1_NetworkMetrics_traffic_metrics_tag 4
#define lora_mesh_v1_NetworkMetrics_performance_metrics_tag 5
#define lora_mesh_v1_NetworkMetrics_energy_metrics_tag 6

/* Struct field encoding specification for nanopb */
#define lora_mesh_v1_NetworkMetrics_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  node_metrics,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  link_metrics,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  routing_metrics,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  traffic_metrics,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  performance_metrics,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  energy_metrics,    6)
#define lora_mesh_v1_NetworkMetrics_CALLBACK NULL
#define lora_mesh_v1_NetworkMetrics_DEFAULT NULL
#define lora_mesh_v1_NetworkMetrics_node_metrics_MSGTYPE lora_mesh_v1_NodeMetrics
#define lora_mesh_v1_NetworkMetrics_link_metrics_MSGTYPE lora_mesh_v1_LinkMetrics
#define lora_mesh_v1_NetworkMetrics_routing_metrics_MSGTYPE lora_mesh_v1_RoutingMetrics
#define lora_mesh_v1_NetworkMetrics_traffic_metrics_MSGTYPE lora_mesh_v1_TrafficMetrics
#define lora_mesh_v1_NetworkMetrics_performance_metrics_MSGTYPE lora_mesh_v1_PerformanceMetrics
#define lora_mesh_v1_NetworkMetrics_energy_metrics_MSGTYPE lora_mesh_v1_EnergyMetrics

#define lora_mesh_v1_NodeMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, STATIC,   SINGULAR, UINT64,   uptime_seconds,    3) \
X(a, STATIC,   SINGULAR, UINT32,   neighbor_count,    4) \
X(a, STATIC,   SINGULAR, FLOAT,    cpu_utilization,   5) \
X(a, STATIC,   SINGULAR, UINT32,   memory_used_bytes,   6) \
X(a, STATIC,   SINGULAR, UINT32,   memory_total_bytes,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  battery_info,      8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  radio_metrics,     9) \
X(a, STATIC,   REPEATED, MESSAGE,  services,         10)
#define lora_mesh_v1_NodeMetrics_CALLBACK NULL
#define lora_mesh_v1_NodeMetrics_DEFAULT NULL
#define lora_mesh_v1_NodeMetrics_battery_info_MSGTYPE lora_mesh_v1_BatteryInfo
#define lora_mesh_v1_NodeMetrics_radio_metrics_MSGTYPE lora_mesh_v1_RadioMetrics
#define lora_mesh_v1_NodeMetrics_services_MSGTYPE lora_mesh_v1_ServiceStatus

#define lora_mesh_v1_BatteryInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    current,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    charge_percentage,   3) \
X(a, STATIC,   SINGULAR, UINT32,   estimated_life_minutes,   4) \
X(a, STATIC,   SINGULAR, UENUM,    status,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       6)
#define lora_mesh_v1_BatteryInfo_CALLBACK NULL
#define lora_mesh_v1_BatteryInfo_DEFAULT NULL

#define lora_mesh_v1_RadioMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    rssi_dbm,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    snr_db,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    frequency_error_hz,   3) \
X(a, STATIC,   SINGULAR, UINT32,   tx_power_dbm,      4) \
X(a, STATIC,   SINGULAR, UINT32,   packets_transmitted,   5) \
X(a, STATIC,   SINGULAR, UINT32,   packets_received,   6) \
X(a, STATIC,   SINGULAR, UINT32,   packets_lost,      7) \
X(a, STATIC,   SINGULAR, UINT32,   crc_errors,        8) \
X(a, STATIC,   SINGULAR, FLOAT,    packet_error_rate,   9) \
X(a, STATIC,   SINGULAR, UINT32,   channel_utilization,  10)
#define lora_mesh_v1_RadioMetrics_CALLBACK NULL
#define lora_mesh_v1_RadioMetrics_DEFAULT NULL

#define lora_mesh_v1_ServiceStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   service_name,      1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, STATIC,   SINGULAR, UINT64,   start_time,        3) \
X(a, STATIC,   SINGULAR, UINT32,   restart_count,     4) \
X(a, STATIC,   SINGULAR, FLOAT,    cpu_usage,         5) \
X(a, STATIC,   SINGULAR, UINT32,   memory_usage,      6) \
X(a, STATIC,   SINGULAR, STRING,   last_error,        7)
#define lora_mesh_v1_ServiceStatus_CALLBACK NULL
#define lora_mesh_v1_ServiceStatus_DEFAULT NULL

#define lora_mesh_v1_LinkMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   source_node,       1) \
X(a, STATIC,   SINGULAR, STRING,   destination_node,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  quality,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    distance_meters,   4) \
X(a, STATIC,   SINGULAR, UINT32,   hop_count,         5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  statistics,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stability,         7)
#define lora_mesh_v1_LinkMetrics_CALLBACK NULL
#define lora_mesh_v1_LinkMetrics_DEFAULT NULL
#define lora_mesh_v1_LinkMetrics_quality_MSGTYPE lora_mesh_v1_LinkQuality
#define lora_mesh_v1_LinkMetrics_statistics_MSGTYPE lora_mesh_v1_LinkStatistics
#define lora_mesh_v1_LinkMetrics_stability_MSGTYPE lora_mesh_v1_LinkStability

#define lora_mesh_v1_LinkStatistics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   packets_sent,      1) \
X(a, STATIC,   SINGULAR, UINT32,   packets_received,   2) \
X(a, STATIC,   SINGULAR, UINT32,   packets_dropped,   3) \
X(a, STATIC,   SINGULAR, UINT32,   retransmissions,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    average_delay_ms,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    jitter_ms,         6) \
X(a, STATIC,   SINGULAR, UINT64,   bytes_transmitted,   7) \
X(a, STATIC,   SINGULAR, UINT64,   bytes_received,    8) \
X(a, STATIC,   SINGULAR, FLOAT,    throughput_bps,    9)
#define lora_mesh_v1_LinkStatistics_CALLBACK NULL
#define lora_mesh_v1_LinkStatistics_DEFAULT NULL

#define lora_mesh_v1_LinkStability_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    stability_score,   1) \
X(a, STATIC,   SINGULAR, UINT32,   link_breaks,       2) \
X(a, STATIC,   SINGULAR, UINT32,   reconnection_count,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    average_uptime_minutes,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    availability_percentage,   5) \
X(a, STATIC,   SINGULAR, UENUM,    trend,             6)
#define lora_mesh_v1_LinkStability_CALLBACK NULL
#define lora_mesh_v1_LinkStability_DEFAULT NULL

#define lora_mesh_v1_RoutingMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    active_protocol,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  discovery,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  maintenance,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  convergence,       4) \
X(a, STATIC,   REPEATED, MESSAGE,  protocol_performance,   5)
#define lora_mesh_v1_RoutingMetrics_CALLBACK NULL
#define lora_mesh_v1_RoutingMetrics_DEFAULT NULL
#define lora_mesh_v1_RoutingMetrics_discovery_MSGTYPE lora_mesh_v1_RouteDiscoveryMetrics
#define lora_mesh_v1_RoutingMetrics_maintenance_MSGTYPE lora_mesh_v1_RouteMaintenanceMetrics
#define lora_mesh_v1_RoutingMetrics_convergence_MSGTYPE lora_mesh_v1_ConvergenceMetrics
#define lora_mesh_v1_RoutingMetrics_protocol_performance_MSGTYPE lora_mesh_v1_ProtocolPerformance

#define lora_mesh_v1_RouteDiscoveryMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   discovery_requests,   1) \
X(a, STATIC,   SINGULAR, UINT32,   discovery_replies,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    discovery_success_rate,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    average_discovery_time_ms,   4) \
X(a, STATIC,   SINGULAR, UINT32,   discovery_overhead,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    route_optimality,   6)
#define lora_mesh_v1_RouteDiscoveryMetrics_CALLBACK NULL
#define lora_mesh_v1_RouteDiscoveryMetrics_DEFAULT NULL

#define lora_mesh_v1_RouteMaintenanceMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   route_repairs,     1) \
X(a, STATIC,   SINGULAR, UINT32,   successful_repairs,   2) \
X(a, STATIC,   SINGULAR, UINT32,   route_breaks,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    repair_time_ms,    4) \
X(a, STATIC,   SINGULAR, UINT32,   maintenance_overhead,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    route_lifetime_minutes,   6)
#define lora_mesh_v1_RouteMaintenanceMetrics_CALLBACK NULL
#define lora_mesh_v1_RouteMaintenanceMetrics_DEFAULT NULL

#define lora_mesh_v1_ConvergenceMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    convergence_time_ms,   1) \
X(a, STATIC,   SINGULAR, UINT32,   routing_updates,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    network_diameter,   3) \
X(a, STATIC,   SINGULAR, UINT32,   partitions,        4) \
X(a, STATIC,   SINGULAR, FLOAT,    global_connectivity,   5)
#define lora_mesh_v1_ConvergenceMetrics_CALLBACK NULL
#define lora_mesh_v1_ConvergenceMetrics_DEFAULT NULL

#define lora_mesh_v1_ProtocolPerformance_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    protocol,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    efficiency_score,   2) \
X(a, STATIC,   SINGULAR, UINT32,   control_overhead,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    scalability_factor,   4) \
X(a, STATIC,   SINGULAR, UINT32,   memory_usage,      5) \
X(a, STATIC,   SINGULAR, FLOAT,    cpu_usage,         6)
#define lora_mesh_v1_ProtocolPerformance_CALLBACK NULL
#define lora_mesh_v1_ProtocolPerformance_DEFAULT NULL

#define lora_mesh_v1_TrafficMetrics_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  total_flow,        1) \
X(a, STATIC,   REPEATED, MESSAGE,  per_node_flow,     2) \
X(a, STATIC,   REPEATED, MESSAGE,  qos_metrics,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  congestion,        4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  load_balancing,    5)
#define lora_mesh_v1_TrafficMetrics_CALLBACK NULL
#define lora_mesh_v1_TrafficMetrics_DEFAULT NULL
#define lora_mesh_v1_TrafficMetrics_total_flow_MSGTYPE lora_mesh_v1_TrafficFlow
#define lora_mesh_v1_TrafficMetrics_per_node_flow_MSGTYPE lora_mesh_v1_TrafficFlow
#define lora_mesh_v1_TrafficMetrics_qos_metrics_MSGTYPE lora_mesh_v1_TrafficClassMetrics
#define lora_mesh_v1_TrafficMetrics_congestion_MSGTYPE lora_mesh_v1_CongestionMetrics
#define lora_mesh_v1_TrafficMetrics_load_balancing_MSGTYPE lora_mesh_v1_LoadBalancing

#define lora_mesh_v1_TrafficFlow_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   flow_id,           1) \
X(a, STATIC,   SINGULAR, STRING,   source_node,       2) \
X(a, STATIC,   SINGULAR, STRING,   destination_node,   3) \
X(a, STATIC,   SINGULAR, UINT64,   bytes_per_second,   4) \
X(a, STATIC,   SINGULAR, UINT64,   packets_per_second,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    average_packet_size,   6) \
X(a, STATIC,   SINGULAR, UENUM,    priority,          7) \
X(a, STATIC,   SINGULAR, UENUM,    state,             8)
#define lora_mesh_v1_TrafficFlow_CALLBACK NULL
#define lora_mesh_v1_TrafficFlow_DEFAULT NULL

#define lora_mesh_v1_TrafficClassMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    priority_class,    1) \
X(a, STATIC,   SINGULAR, UINT64,   total_bytes,       2) \
X(a, STATIC,   SINGULAR, UINT64,   total_packets,     3) \
X(a, STATIC,   SINGULAR, UINT32,   dropped_packets,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    average_latency_ms,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    jitter_ms,         6) \
X(a, STATIC,   SINGULAR, FLOAT,    delivery_ratio,    7)
#define lora_mesh_v1_TrafficClassMetrics_CALLBACK NULL
#define lora_mesh_v1_TrafficClassMetrics_DEFAULT NULL

#define lora_mesh_v1_CongestionMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    congestion_level,   1) \
X(a, STATIC,   REPEATED, MESSAGE,  hotspots,          2) \
X(a, STATIC,   SINGULAR, UINT32,   queue_overflow_events,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    average_queue_depth,   4) \
X(a, STATIC,   SINGULAR, UINT32,   backpressure_events,   5)
#define lora_mesh_v1_CongestionMetrics_CALLBACK NULL
#define lora_mesh_v1_CongestionMetrics_DEFAULT NULL
#define lora_mesh_v1_CongestionMetrics_hotspots_MSGTYPE lora_mesh_v1_CongestionPoint

#define lora_mesh_v1_CongestionPoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    congestion_severity,   2) \
X(a, STATIC,   SINGULAR, UINT32,   queue_depth,       3) \
X(a, STATIC,   SINGULAR, FLOAT,    drop_rate,         4) \
X(a, STATIC,   REPEATED, STRING,   affected_flows,    5)
#define lora_mesh_v1_CongestionPoint_CALLBACK NULL
#define lora_mesh_v1_CongestionPoint_DEFAULT NULL

#define lora_mesh_v1_LoadBalancing_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    load_distribution_score,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    max_node_utilization,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    min_node_utilization,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    utilization_variance,   4) \
X(a, STATIC,   SINGULAR, UINT32,   load_balancing_events,   5)
#define lora_mesh_v1_LoadBalancing_CALLBACK NULL
#define lora_mesh_v1_LoadBalancing_DEFAULT NULL

#define lora_mesh_v1_PerformanceMetrics_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  latency,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  throughput,        2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  reliability,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  efficiency,        4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scalability,       5)
#define lora_mesh_v1_PerformanceMetrics_CALLBACK NULL
#define lora_mesh_v1_PerformanceMetrics_DEFAULT NULL
#define lora_mesh_v1_PerformanceMetrics_latency_MSGTYPE lora_mesh_v1_LatencyMetrics
#define lora_mesh_v1_PerformanceMetrics_throughput_MSGTYPE lora_mesh_v1_ThroughputMetrics
#define lora_mesh_v1_PerformanceMetrics_reliability_MSGTYPE lora_mesh_v1_ReliabilityMetrics
#define lora_mesh_v1_PerformanceMetrics_efficiency_MSGTYPE lora_mesh_v1_EfficiencyMetrics
#define lora_mesh_v1_PerformanceMetrics_scalability_MSGTYPE lora_mesh_v1_ScalabilityMetrics

#define lora_mesh_v1_LatencyMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    average_latency_ms,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    median_latency_ms,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    percentile_95_latency_ms,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    max_latency_ms,    4) \
X(a, STATIC,   SINGULAR, FLOAT,    jitter_ms,         5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  distribution,      6)
#define lora_mesh_v1_LatencyMetrics_CALLBACK NULL
#define lora_mesh_v1_LatencyMetrics_DEFAULT NULL
#define lora_mesh_v1_LatencyMetrics_distribution_MSGTYPE lora_mesh_v1_LatencyDistribution

#define lora_mesh_v1_LatencyDistribution_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  buckets,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    standard_deviation,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    skewness,          3)
#define lora_mesh_v1_LatencyDistribution_CALLBACK NULL
#define lora_mesh_v1_LatencyDistribution_DEFAULT NULL
#define lora_mesh_v1_LatencyDistribution_buckets_MSGTYPE lora_mesh_v1_LatencyBucket

#define lora_mesh_v1_LatencyBucket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    latency_threshold_ms,   1) \
X(a, STATIC,   SINGULAR, UINT32,   packet_count,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    percentage,        3)
#define lora_mesh_v1_LatencyBucket_CALLBACK NULL
#define lora_mesh_v1_LatencyBucket_DEFAULT NULL

#define lora_mesh_v1_ThroughputMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   aggregate_throughput_bps,   1) \
X(a, STATIC,   SINGULAR, UINT64,   average_node_throughput_bps,   2) \
X(a, STATIC,   SINGULAR, UINT64,   peak_throughput_bps,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    throughput_efficiency,   4) \
X(a, STATIC,   SINGULAR, UENUM,    trend,             5)
#define lora_mesh_v1_ThroughputMetrics_CALLBACK NULL
#define lora_mesh_v1_ThroughputMetrics_DEFAULT NULL

#define lora_mesh_v1_ReliabilityMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    packet_delivery_ratio,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    end_to_end_reliability,   2) \
X(a, STATIC,   SINGULAR, UINT32,   total_packet_loss,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    mean_time_between_failures,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    mean_time_to_repair,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    availability_percentage,   6)
#define lora_mesh_v1_ReliabilityMetrics_CALLBACK NULL
#define lora_mesh_v1_ReliabilityMetrics_DEFAULT NULL

#define lora_mesh_v1_EfficiencyMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    protocol_efficiency,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    energy_efficiency,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    spectrum_efficiency,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    routing_efficiency,   4) \
X(a, STATIC,   SINGULAR, UENUM,    trend,             5)
#define lora_mesh_v1_EfficiencyMetrics_CALLBACK NULL
#define lora_mesh_v1_EfficiencyMetrics_DEFAULT NULL

#define lora_mesh_v1_ScalabilityMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   current_node_count,   1) \
X(a, STATIC,   SINGULAR, UINT32,   maximum_supported_nodes,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    scalability_factor,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bottlenecks,       4) \
X(a, STATIC,   SINGULAR, FLOAT,    growth_sustainability,   5)
#define lora_mesh_v1_ScalabilityMetrics_CALLBACK NULL
#define lora_mesh_v1_ScalabilityMetrics_DEFAULT NULL
#define lora_mesh_v1_ScalabilityMetrics_bottlenecks_MSGTYPE lora_mesh_v1_ScalabilityBottleneck

#define lora_mesh_v1_ScalabilityBottleneck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    severity,          2) \
X(a, STATIC,   SINGULAR, STRING,   description,       3) \
X(a, STATIC,   REPEATED, STRING,   mitigation_strategies,   4)
#define lora_mesh_v1_ScalabilityBottleneck_CALLBACK NULL
#define lora_mesh_v1_ScalabilityBottleneck_DEFAULT NULL

#define lora_mesh_v1_EnergyMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    total_power_consumption_watts,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    average_node_power_watts,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  energy_breakdown,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  battery_projection,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  energy_efficiency,   5)
#define lora_mesh_v1_EnergyMetrics_CALLBACK NULL
#define lora_mesh_v1_EnergyMetrics_DEFAULT NULL
#define lora_mesh_v1_EnergyMetrics_energy_breakdown_MSGTYPE lora_mesh_v1_EnergyBreakdown
#define lora_mesh_v1_EnergyMetrics_battery_projection_MSGTYPE lora_mesh_v1_BatteryProjection
#define lora_mesh_v1_EnergyMetrics_energy_efficiency_MSGTYPE lora_mesh_v1_EnergyEfficiency

#define lora_mesh_v1_EnergyBreakdown_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    radio_power_watts,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    cpu_power_watts,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    memory_power_watts,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    sensors_power_watts,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    idle_power_watts,   5)
#define lora_mesh_v1_EnergyBreakdown_CALLBACK NULL
#define lora_mesh_v1_EnergyBreakdown_DEFAULT NULL

#define lora_mesh_v1_BatteryProjection_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   estimated_life_hours,   1) \
X(a, STATIC,   SINGULAR, UINT32,   low_battery_nodes,   2) \
X(a, STATIC,   SINGULAR, UINT32,   critical_battery_nodes,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    network_lifetime_hours,   4)
#define lora_mesh_v1_BatteryProjection_CALLBACK NULL
#define lora_mesh_v1_BatteryProjection_DEFAULT NULL

#define lora_mesh_v1_EnergyEfficiency_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    bits_per_joule,    1) \
X(a, STATIC,   SINGULAR, FLOAT,    energy_per_packet,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    transmission_efficiency,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    processing_efficiency,   4)
#define lora_mesh_v1_EnergyEfficiency_CALLBACK NULL
#define lora_mesh_v1_EnergyEfficiency_DEFAULT NULL

extern const pb_msgdesc_t lora_mesh_v1_NetworkMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_NodeMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_BatteryInfo_msg;
extern const pb_msgdesc_t lora_mesh_v1_RadioMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_ServiceStatus_msg;
extern const pb_msgdesc_t lora_mesh_v1_LinkMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_LinkStatistics_msg;
extern const pb_msgdesc_t lora_mesh_v1_LinkStability_msg;
extern const pb_msgdesc_t lora_mesh_v1_RoutingMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_RouteDiscoveryMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_RouteMaintenanceMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_ConvergenceMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_ProtocolPerformance_msg;
extern const pb_msgdesc_t lora_mesh_v1_TrafficMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_TrafficFlow_msg;
extern const pb_msgdesc_t lora_mesh_v1_TrafficClassMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_CongestionMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_CongestionPoint_msg;
extern const pb_msgdesc_t lora_mesh_v1_LoadBalancing_msg;
extern const pb_msgdesc_t lora_mesh_v1_PerformanceMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_LatencyMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_LatencyDistribution_msg;
extern const pb_msgdesc_t lora_mesh_v1_LatencyBucket_msg;
extern const pb_msgdesc_t lora_mesh_v1_ThroughputMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_ReliabilityMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_EfficiencyMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_ScalabilityMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_ScalabilityBottleneck_msg;
extern const pb_msgdesc_t lora_mesh_v1_EnergyMetrics_msg;
extern const pb_msgdesc_t lora_mesh_v1_EnergyBreakdown_msg;
extern const pb_msgdesc_t lora_mesh_v1_BatteryProjection_msg;
extern const pb_msgdesc_t lora_mesh_v1_EnergyEfficiency_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lora_mesh_v1_NetworkMetrics_fields &lora_mesh_v1_NetworkMetrics_msg
#define lora_mesh_v1_NodeMetrics_fields &lora_mesh_v1_NodeMetrics_msg
#define lora_mesh_v1_BatteryInfo_fields &lora_mesh_v1_BatteryInfo_msg
#define lora_mesh_v1_RadioMetrics_fields &lora_mesh_v1_RadioMetrics_msg
#define lora_mesh_v1_ServiceStatus_fields &lora_mesh_v1_ServiceStatus_msg
#define lora_mesh_v1_LinkMetrics_fields &lora_mesh_v1_LinkMetrics_msg
#define lora_mesh_v1_LinkStatistics_fields &lora_mesh_v1_LinkStatistics_msg
#define lora_mesh_v1_LinkStability_fields &lora_mesh_v1_LinkStability_msg
#define lora_mesh_v1_RoutingMetrics_fields &lora_mesh_v1_RoutingMetrics_msg
#define lora_mesh_v1_RouteDiscoveryMetrics_fields &lora_mesh_v1_RouteDiscoveryMetrics_msg
#define lora_mesh_v1_RouteMaintenanceMetrics_fields &lora_mesh_v1_RouteMaintenanceMetrics_msg
#define lora_mesh_v1_ConvergenceMetrics_fields &lora_mesh_v1_ConvergenceMetrics_msg
#define lora_mesh_v1_ProtocolPerformance_fields &lora_mesh_v1_ProtocolPerformance_msg
#define lora_mesh_v1_TrafficMetrics_fields &lora_mesh_v1_TrafficMetrics_msg
#define lora_mesh_v1_TrafficFlow_fields &lora_mesh_v1_TrafficFlow_msg
#define lora_mesh_v1_TrafficClassMetrics_fields &lora_mesh_v1_TrafficClassMetrics_msg
#define lora_mesh_v1_CongestionMetrics_fields &lora_mesh_v1_CongestionMetrics_msg
#define lora_mesh_v1_CongestionPoint_fields &lora_mesh_v1_CongestionPoint_msg
#define lora_mesh_v1_LoadBalancing_fields &lora_mesh_v1_LoadBalancing_msg
#define lora_mesh_v1_PerformanceMetrics_fields &lora_mesh_v1_PerformanceMetrics_msg
#define lora_mesh_v1_LatencyMetrics_fields &lora_mesh_v1_LatencyMetrics_msg
#define lora_mesh_v1_LatencyDistribution_fields &lora_mesh_v1_LatencyDistribution_msg
#define lora_mesh_v1_LatencyBucket_fields &lora_mesh_v1_LatencyBucket_msg
#define lora_mesh_v1_ThroughputMetrics_fields &lora_mesh_v1_ThroughputMetrics_msg
#define lora_mesh_v1_ReliabilityMetrics_fields &lora_mesh_v1_ReliabilityMetrics_msg
#define lora_mesh_v1_EfficiencyMetrics_fields &lora_mesh_v1_EfficiencyMetrics_msg
#define lora_mesh_v1_ScalabilityMetrics_fields &lora_mesh_v1_ScalabilityMetrics_msg
#define lora_mesh_v1_ScalabilityBottleneck_fields &lora_mesh_v1_ScalabilityBottleneck_msg
#define lora_mesh_v1_EnergyMetrics_fields &lora_mesh_v1_EnergyMetrics_msg
#define lora_mesh_v1_EnergyBreakdown_fields &lora_mesh_v1_EnergyBreakdown_msg
#define lora_mesh_v1_BatteryProjection_fields &lora_mesh_v1_BatteryProjection_msg
#define lora_mesh_v1_EnergyEfficiency_fields &lora_mesh_v1_EnergyEfficiency_msg

/* Maximum encoded size of messages (where known) */
#define LORA_MESH_V1_V1_METRICS_PB_H_MAX_SIZE    lora_mesh_v1_NetworkMetrics_size
#define lora_mesh_v1_BatteryInfo_size            28
#define lora_mesh_v1_BatteryProjection_size      23
#define lora_mesh_v1_CongestionMetrics_size      710
#define lora_mesh_v1_CongestionPoint_size        169
#define lora_mesh_v1_ConvergenceMetrics_size     27
#define lora_mesh_v1_EfficiencyMetrics_size      22
#define lora_mesh_v1_EnergyBreakdown_size        25
#define lora_mesh_v1_EnergyEfficiency_size       20
#define lora_mesh_v1_EnergyMetrics_size          84
#define lora_mesh_v1_LatencyBucket_size          16
#define lora_mesh_v1_LatencyDistribution_size    154
#define lora_mesh_v1_LatencyMetrics_size         182
#define lora_mesh_v1_LinkMetrics_size            166
#define lora_mesh_v1_LinkStability_size          29
#define lora_mesh_v1_LinkStatistics_size         61
#define lora_mesh_v1_LoadBalancing_size          26
#define lora_mesh_v1_NetworkMetrics_size         4224
#define lora_mesh_v1_NodeMetrics_size            665
#define lora_mesh_v1_PerformanceMetrics_size     709
#define lora_mesh_v1_ProtocolPerformance_size    29
#define lora_mesh_v1_RadioMetrics_size           56
#define lora_mesh_v1_ReliabilityMetrics_size     31
#define lora_mesh_v1_RouteDiscoveryMetrics_size  33
#define lora_mesh_v1_RouteMaintenanceMetrics_size 34
#define lora_mesh_v1_RoutingMetrics_size         226
#define lora_mesh_v1_ScalabilityBottleneck_size  397
#define lora_mesh_v1_ScalabilityMetrics_size     422
#define lora_mesh_v1_ServiceStatus_size          128
#define lora_mesh_v1_ThroughputMetrics_size      40
#define lora_mesh_v1_TrafficClassMetrics_size    45
#define lora_mesh_v1_TrafficFlow_size            82
#define lora_mesh_v1_TrafficMetrics_size         2357

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
