/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "v1/metrics.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(lora_mesh_v1_NetworkMetrics, lora_mesh_v1_NetworkMetrics, 2)


PB_BIND(lora_mesh_v1_NodeMetrics, lora_mesh_v1_NodeMetrics, 2)


PB_BIND(lora_mesh_v1_BatteryInfo, lora_mesh_v1_BatteryInfo, AUTO)


PB_BIND(lora_mesh_v1_RadioMetrics, lora_mesh_v1_RadioMetrics, AUTO)


PB_BIND(lora_mesh_v1_ServiceStatus, lora_mesh_v1_ServiceStatus, AUTO)


PB_BIND(lora_mesh_v1_LinkMetrics, lora_mesh_v1_LinkMetrics, AUTO)


PB_BIND(lora_mesh_v1_LinkStatistics, lora_mesh_v1_LinkStatistics, AUTO)


PB_BIND(lora_mesh_v1_LinkStability, lora_mesh_v1_LinkStability, AUTO)


PB_BIND(lora_mesh_v1_RoutingMetrics, lora_mesh_v1_RoutingMetrics, AUTO)


PB_BIND(lora_mesh_v1_RouteDiscoveryMetrics, lora_mesh_v1_RouteDiscoveryMetrics, AUTO)


PB_BIND(lora_mesh_v1_RouteMaintenanceMetrics, lora_mesh_v1_RouteMaintenanceMetrics, AUTO)


PB_BIND(lora_mesh_v1_ConvergenceMetrics, lora_mesh_v1_ConvergenceMetrics, AUTO)


PB_BIND(lora_mesh_v1_ProtocolPerformance, lora_mesh_v1_ProtocolPerformance, AUTO)


PB_BIND(lora_mesh_v1_TrafficMetrics, lora_mesh_v1_TrafficMetrics, 2)


PB_BIND(lora_mesh_v1_TrafficFlow, lora_mesh_v1_TrafficFlow, AUTO)


PB_BIND(lora_mesh_v1_TrafficClassMetrics, lora_mesh_v1_TrafficClassMetrics, AUTO)


PB_BIND(lora_mesh_v1_CongestionMetrics, lora_mesh_v1_CongestionMetrics, 2)


PB_BIND(lora_mesh_v1_CongestionPoint, lora_mesh_v1_CongestionPoint, AUTO)


PB_BIND(lora_mesh_v1_LoadBalancing, lora_mesh_v1_LoadBalancing, AUTO)


PB_BIND(lora_mesh_v1_PerformanceMetrics, lora_mesh_v1_PerformanceMetrics, 2)


PB_BIND(lora_mesh_v1_LatencyMetrics, lora_mesh_v1_LatencyMetrics, AUTO)


PB_BIND(lora_mesh_v1_LatencyDistribution, lora_mesh_v1_LatencyDistribution, AUTO)


PB_BIND(lora_mesh_v1_LatencyBucket, lora_mesh_v1_LatencyBucket, AUTO)


PB_BIND(lora_mesh_v1_ThroughputMetrics, lora_mesh_v1_ThroughputMetrics, AUTO)


PB_BIND(lora_mesh_v1_ReliabilityMetrics, lora_mesh_v1_ReliabilityMetrics, AUTO)


PB_BIND(lora_mesh_v1_EfficiencyMetrics, lora_mesh_v1_EfficiencyMetrics, AUTO)


PB_BIND(lora_mesh_v1_ScalabilityMetrics, lora_mesh_v1_ScalabilityMetrics, 2)


PB_BIND(lora_mesh_v1_ScalabilityBottleneck, lora_mesh_v1_ScalabilityBottleneck, 2)


PB_BIND(lora_mesh_v1_EnergyMetrics, lora_mesh_v1_EnergyMetrics, AUTO)


PB_BIND(lora_mesh_v1_EnergyBreakdown, lora_mesh_v1_EnergyBreakdown, AUTO)


PB_BIND(lora_mesh_v1_BatteryProjection, lora_mesh_v1_BatteryProjection, AUTO)


PB_BIND(lora_mesh_v1_EnergyEfficiency, lora_mesh_v1_EnergyEfficiency, AUTO)



















