/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "v1/routing.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(lora_mesh_v1_RouteRequestPayload, lora_mesh_v1_RouteRequestPayload, AUTO)


PB_BIND(lora_mesh_v1_RouteReplyPayload, lora_mesh_v1_RouteReplyPayload, AUTO)


PB_BIND(lora_mesh_v1_RouteErrorPayload, lora_mesh_v1_RouteErrorPayload, 2)


PB_BIND(lora_mesh_v1_UnreachableDestination, lora_mesh_v1_UnreachableDestination, AUTO)


PB_BIND(lora_mesh_v1_QoSRequirements, lora_mesh_v1_QoSRequirements, AUTO)


PB_BIND(lora_mesh_v1_LinkStateAdvertisementPayload, lora_mesh_v1_LinkStateAdvertisementPayload, 2)


PB_BIND(lora_mesh_v1_ServiceAdvertisement, lora_mesh_v1_ServiceAdvertisement, AUTO)


PB_BIND(lora_mesh_v1_ServiceQuality, lora_mesh_v1_ServiceQuality, AUTO)


PB_BIND(lora_mesh_v1_NodeCapabilities, lora_mesh_v1_NodeCapabilities, AUTO)















