/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LORA_MESH_V1_V1_ROUTING_PB_H_INCLUDED
#define PB_LORA_MESH_V1_V1_ROUTING_PB_H_INCLUDED
#include <pb.h>
#include "v1/common.pb.h"
#include "v1/messages.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Route request flags */
typedef enum _lora_mesh_v1_RouteRequestFlags {
    lora_mesh_v1_RouteRequestFlags_ROUTE_REQUEST_FLAGS_UNSPECIFIED = 0,
    lora_mesh_v1_RouteRequestFlags_ROUTE_REQUEST_FLAGS_RREQ_JOIN_FLAG = 1, /* New node joining network */
    lora_mesh_v1_RouteRequestFlags_ROUTE_REQUEST_FLAGS_RREQ_REPAIR_FLAG = 2, /* Local route repair */
    lora_mesh_v1_RouteRequestFlags_ROUTE_REQUEST_FLAGS_RREQ_GRATUITOUS_RREP = 3, /* Request gratuitous RREP */
    lora_mesh_v1_RouteRequestFlags_ROUTE_REQUEST_FLAGS_RREQ_DESTINATION_ONLY = 4, /* Only destination can reply */
    lora_mesh_v1_RouteRequestFlags_ROUTE_REQUEST_FLAGS_RREQ_MULTIPATH = 5, /* Multipath route discovery */
    lora_mesh_v1_RouteRequestFlags_ROUTE_REQUEST_FLAGS_RREQ_QOS_AWARE = 6 /* QoS-constrained routing */
} lora_mesh_v1_RouteRequestFlags;

/* Route reply flags */
typedef enum _lora_mesh_v1_RouteReplyFlags {
    lora_mesh_v1_RouteReplyFlags_ROUTE_REPLY_FLAGS_UNSPECIFIED = 0,
    lora_mesh_v1_RouteReplyFlags_ROUTE_REPLY_FLAGS_RREP_REPAIR_FLAG = 1, /* Route repair reply */
    lora_mesh_v1_RouteReplyFlags_ROUTE_REPLY_FLAGS_RREP_ACKNOWLEDGMENT = 2, /* Acknowledgment required */
    lora_mesh_v1_RouteReplyFlags_ROUTE_REPLY_FLAGS_RREP_INTERMEDIATE_REPLY = 3, /* Reply from intermediate node */
    lora_mesh_v1_RouteReplyFlags_ROUTE_REPLY_FLAGS_RREP_MULTIPATH = 4, /* Part of multipath discovery */
    lora_mesh_v1_RouteReplyFlags_ROUTE_REPLY_FLAGS_RREP_QOS_SATISFIED = 5 /* QoS requirements met */
} lora_mesh_v1_RouteReplyFlags;

/* Route error causes */
typedef enum _lora_mesh_v1_RouteErrorCause {
    lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_UNSPECIFIED = 0,
    lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_LINK_FAILURE = 1, /* Next hop unreachable */
    lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_NODE_UNREACHABLE = 2, /* Destination unreachable */
    lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_ROUTE_TIMEOUT = 3, /* Route expired */
    lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_QOS_VIOLATION = 4, /* QoS requirements not met */
    lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_CONGESTION = 5, /* Network congestion */
    lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_ENERGY_DEPLETION = 6, /* Battery too low */
    lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_AUTHENTICATION_FAILURE = 7 /* Security check failed */
} lora_mesh_v1_RouteErrorCause;

/* Route metric preferences for multipath discovery */
typedef enum _lora_mesh_v1_RouteMetricPreference {
    lora_mesh_v1_RouteMetricPreference_ROUTE_METRIC_PREFERENCE_UNSPECIFIED = 0,
    lora_mesh_v1_RouteMetricPreference_ROUTE_METRIC_PREFERENCE_SHORTEST_HOP = 1, /* Minimize hop count */
    lora_mesh_v1_RouteMetricPreference_ROUTE_METRIC_PREFERENCE_HIGHEST_RSSI = 2, /* Best signal quality */
    lora_mesh_v1_RouteMetricPreference_ROUTE_METRIC_PREFERENCE_LOWEST_ENERGY = 3, /* Battery conservation */
    lora_mesh_v1_RouteMetricPreference_ROUTE_METRIC_PREFERENCE_MOST_STABLE = 4, /* Least mobile nodes */
    lora_mesh_v1_RouteMetricPreference_ROUTE_METRIC_PREFERENCE_BEST_QUALITY = 5, /* Overall quality */
    lora_mesh_v1_RouteMetricPreference_ROUTE_METRIC_PREFERENCE_LOWEST_LATENCY = 6 /* Minimize delay */
} lora_mesh_v1_RouteMetricPreference;

/* Service types */
typedef enum _lora_mesh_v1_ServiceType {
    lora_mesh_v1_ServiceType_SERVICE_TYPE_UNSPECIFIED = 0,
    lora_mesh_v1_ServiceType_SERVICE_TYPE_DATA_RELAY = 1, /* Message relaying service */
    lora_mesh_v1_ServiceType_SERVICE_TYPE_GPS_POSITIONING = 2, /* GPS positioning service */
    lora_mesh_v1_ServiceType_SERVICE_TYPE_WEATHER_MONITORING = 3, /* Weather data collection */
    lora_mesh_v1_ServiceType_SERVICE_TYPE_EMERGENCY_COORDINATION = 4, /* Emergency response coordination */
    lora_mesh_v1_ServiceType_SERVICE_TYPE_FILE_TRANSFER = 5, /* File transfer service */
    lora_mesh_v1_ServiceType_SERVICE_TYPE_VOICE_RELAY = 6, /* Voice communication relay */
    lora_mesh_v1_ServiceType_SERVICE_TYPE_SENSOR_DATA = 7, /* Sensor data collection */
    lora_mesh_v1_ServiceType_SERVICE_TYPE_CUSTOM = 99 /* Custom service type */
} lora_mesh_v1_ServiceType;

/* Node capability types */
typedef enum _lora_mesh_v1_NodeCapability {
    lora_mesh_v1_NodeCapability_NODE_CAPABILITY_UNSPECIFIED = 0,
    lora_mesh_v1_NodeCapability_NODE_CAPABILITY_BASIC_ROUTING = 1, /* Basic message routing */
    lora_mesh_v1_NodeCapability_NODE_CAPABILITY_GEOGRAPHIC_ROUTING = 2, /* GPS-based routing */
    lora_mesh_v1_NodeCapability_NODE_CAPABILITY_EMERGENCY_GATEWAY = 3, /* Emergency communication gateway */
    lora_mesh_v1_NodeCapability_NODE_CAPABILITY_INTERNET_GATEWAY = 4, /* Internet connectivity gateway */
    lora_mesh_v1_NodeCapability_NODE_CAPABILITY_WEATHER_STATION = 5, /* Weather monitoring */
    lora_mesh_v1_NodeCapability_NODE_CAPABILITY_REPEATER = 6, /* Signal repeater/amplifier */
    lora_mesh_v1_NodeCapability_NODE_CAPABILITY_COMMAND_CENTER = 7, /* Command and control center */
    lora_mesh_v1_NodeCapability_NODE_CAPABILITY_MOBILE_UNIT = 8 /* Mobile communication unit */
} lora_mesh_v1_NodeCapability;

/* Struct definitions */
/* AODV Route Reply message */
typedef struct _lora_mesh_v1_RouteReplyPayload {
    char destination_id[16]; /* Replying node (destination) */
    uint32_t destination_sequence_number; /* Current sequence number */
    char originator_id[16]; /* Original requester */
    uint32_t hop_count; /* Hops from destination */
    uint32_t lifetime_ms; /* Route validity period */
    uint32_t source_port; /* Logical source port (service/application) */
    uint32_t destination_port; /* Logical destination port */
    /* Extensions for enhanced AODV */
    lora_mesh_v1_RouteReplyFlags flags; /* Reply flags */
    bool has_route_metrics;
    lora_mesh_v1_RouteQualityMetrics route_metrics; /* Route quality information */
    pb_size_t alternate_routes_count;
    lora_mesh_v1_AlternateRoute alternate_routes[4]; /* Additional route options */
    char replying_node[16]; /* Actual replying node (if intermediate) */
    uint64_t reply_timestamp; /* When reply was generated */
} lora_mesh_v1_RouteReplyPayload;

/* Unreachable destination info */
typedef struct _lora_mesh_v1_UnreachableDestination {
    char destination_id[16]; /* Unreachable node */
    uint32_t destination_sequence_number; /* Incremented sequence number */
    char failed_next_hop[16]; /* Next hop that failed */
    lora_mesh_v1_RouteErrorCause failure_reason; /* Specific failure reason */
} lora_mesh_v1_UnreachableDestination;

/* AODV Route Error message */
typedef struct _lora_mesh_v1_RouteErrorPayload {
    pb_size_t unreachable_destinations_count;
    lora_mesh_v1_UnreachableDestination unreachable_destinations[8];
    char reporting_node[16]; /* Node reporting the error */
    lora_mesh_v1_RouteErrorCause error_cause; /* Reason for route failure */
    uint64_t error_timestamp; /* When error occurred */
    uint32_t affected_message_count; /* Messages affected by failure */
    uint32_t source_port; /* Logical source port (service/application) */
    uint32_t destination_port; /* Logical destination port */
} lora_mesh_v1_RouteErrorPayload;

/* Quality of Service requirements */
typedef struct _lora_mesh_v1_QoSRequirements {
    float max_delay_ms; /* Maximum acceptable delay */
    float min_bandwidth_kbps; /* Minimum bandwidth requirement */
    float max_loss_rate; /* Maximum packet loss rate */
    float min_reliability; /* Minimum delivery reliability */
    uint32_t max_energy_cost; /* Maximum energy consumption */
    lora_mesh_v1_MessagePriority priority; /* Message priority level */
} lora_mesh_v1_QoSRequirements;

/* AODV Route Request message */
typedef struct _lora_mesh_v1_RouteRequestPayload {
    uint32_t rreq_id; /* Unique request ID from originator */
    char originator_id[16]; /* Node seeking the route */
    uint32_t originator_sequence_number; /* Freshness of originator's info */
    char destination_id[16]; /* Target node */
    uint32_t destination_sequence_number; /* Last known dest sequence (0 if unknown) */
    uint32_t hop_count; /* Hops from originator */
    uint32_t broadcast_id; /* Prevents broadcast loops */
    uint32_t source_port; /* Logical source port (service/application) */
    uint32_t destination_port; /* Logical destination port */
    /* Extensions for enhanced AODV */
    lora_mesh_v1_RouteRequestFlags flags; /* Request flags */
    lora_mesh_v1_RouteMetricPreference metric_preference; /* Preferred route metric */
    uint32_t max_hop_limit; /* Maximum allowed hops */
    uint64_t discovery_timeout; /* How long to wait for reply */
    pb_callback_t excluded_nodes; /* Nodes to avoid in route */
    bool has_qos_requirements;
    lora_mesh_v1_QoSRequirements qos_requirements; /* Quality of service needs */
} lora_mesh_v1_RouteRequestPayload;

/* Service quality parameters */
typedef struct _lora_mesh_v1_ServiceQuality {
    float availability; /* Service availability 0.0-1.0 */
    float response_time_ms; /* Average response time */
    float throughput_kbps; /* Service throughput */
    uint32_t concurrent_capacity; /* Concurrent user capacity */
    float reliability; /* Service reliability 0.0-1.0 */
} lora_mesh_v1_ServiceQuality;

/* Service advertisement for capability discovery */
typedef struct _lora_mesh_v1_ServiceAdvertisement {
    char service_name[32]; /* Human-readable service name */
    lora_mesh_v1_ServiceType service_type; /* Type of service */
    char service_id[32]; /* Unique service identifier */
    pb_callback_t endpoints; /* Service endpoints/addresses */
    bool has_quality;
    lora_mesh_v1_ServiceQuality quality; /* Service quality parameters */
    uint32_t capacity; /* Maximum concurrent users */
    bool requires_auth; /* Authentication required */
} lora_mesh_v1_ServiceAdvertisement;

/* Node capabilities advertisement */
typedef struct _lora_mesh_v1_NodeCapabilities {
    pb_size_t capabilities_count;
    lora_mesh_v1_NodeCapability capabilities[16]; /* List of capabilities */
    uint32_t max_hop_relay; /* Maximum relay hop count */
    uint32_t max_message_size; /* Maximum message size */
    pb_size_t supported_messages_count;
    lora_mesh_v1_MessageType supported_messages[8]; /* Supported message types */
    pb_size_t supported_routing_count;
    lora_mesh_v1_RoutingStrategy supported_routing[4]; /* Supported routing */
    bool has_gps; /* GPS capability */
    bool has_internet; /* Internet connectivity */
    bool is_mobile; /* Mobility capability */
    float battery_capacity_wh; /* Battery capacity in Wh */
    uint32_t radio_power_dbm; /* Radio transmission power */
} lora_mesh_v1_NodeCapabilities;

/* Link State Advertisement message */
typedef struct _lora_mesh_v1_LinkStateAdvertisementPayload {
    char originator_id[16]; /* Advertising node */
    uint32_t sequence_number; /* LSA freshness indicator */
    pb_size_t neighbors_count;
    lora_mesh_v1_NeighborInfo neighbors[16]; /* Current neighbor list */
    bool has_gps_position;
    lora_mesh_v1_GPSCoordinate gps_position; /* Originator's location */
    /* Extended LSA information */
    bool has_local_metrics;
    lora_mesh_v1_TopologyMetrics local_metrics; /* Local topology metrics */
    uint64_t lsa_timestamp; /* When LSA was generated */
    uint32_t lsa_lifetime_ms; /* How long LSA is valid */
    pb_size_t services_count;
    lora_mesh_v1_ServiceAdvertisement services[8]; /* Services offered by node */
    bool has_capabilities;
    lora_mesh_v1_NodeCapabilities capabilities; /* Node capabilities */
    float mobility_factor; /* Node mobility indicator */
} lora_mesh_v1_LinkStateAdvertisementPayload;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _lora_mesh_v1_RouteRequestFlags_MIN lora_mesh_v1_RouteRequestFlags_ROUTE_REQUEST_FLAGS_UNSPECIFIED
#define _lora_mesh_v1_RouteRequestFlags_MAX lora_mesh_v1_RouteRequestFlags_ROUTE_REQUEST_FLAGS_RREQ_QOS_AWARE
#define _lora_mesh_v1_RouteRequestFlags_ARRAYSIZE ((lora_mesh_v1_RouteRequestFlags)(lora_mesh_v1_RouteRequestFlags_ROUTE_REQUEST_FLAGS_RREQ_QOS_AWARE+1))

#define _lora_mesh_v1_RouteReplyFlags_MIN lora_mesh_v1_RouteReplyFlags_ROUTE_REPLY_FLAGS_UNSPECIFIED
#define _lora_mesh_v1_RouteReplyFlags_MAX lora_mesh_v1_RouteReplyFlags_ROUTE_REPLY_FLAGS_RREP_QOS_SATISFIED
#define _lora_mesh_v1_RouteReplyFlags_ARRAYSIZE ((lora_mesh_v1_RouteReplyFlags)(lora_mesh_v1_RouteReplyFlags_ROUTE_REPLY_FLAGS_RREP_QOS_SATISFIED+1))

#define _lora_mesh_v1_RouteErrorCause_MIN lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_UNSPECIFIED
#define _lora_mesh_v1_RouteErrorCause_MAX lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_AUTHENTICATION_FAILURE
#define _lora_mesh_v1_RouteErrorCause_ARRAYSIZE ((lora_mesh_v1_RouteErrorCause)(lora_mesh_v1_RouteErrorCause_ROUTE_ERROR_CAUSE_AUTHENTICATION_FAILURE+1))

#define _lora_mesh_v1_RouteMetricPreference_MIN lora_mesh_v1_RouteMetricPreference_ROUTE_METRIC_PREFERENCE_UNSPECIFIED
#define _lora_mesh_v1_RouteMetricPreference_MAX lora_mesh_v1_RouteMetricPreference_ROUTE_METRIC_PREFERENCE_LOWEST_LATENCY
#define _lora_mesh_v1_RouteMetricPreference_ARRAYSIZE ((lora_mesh_v1_RouteMetricPreference)(lora_mesh_v1_RouteMetricPreference_ROUTE_METRIC_PREFERENCE_LOWEST_LATENCY+1))

#define _lora_mesh_v1_ServiceType_MIN lora_mesh_v1_ServiceType_SERVICE_TYPE_UNSPECIFIED
#define _lora_mesh_v1_ServiceType_MAX lora_mesh_v1_ServiceType_SERVICE_TYPE_CUSTOM
#define _lora_mesh_v1_ServiceType_ARRAYSIZE ((lora_mesh_v1_ServiceType)(lora_mesh_v1_ServiceType_SERVICE_TYPE_CUSTOM+1))

#define _lora_mesh_v1_NodeCapability_MIN lora_mesh_v1_NodeCapability_NODE_CAPABILITY_UNSPECIFIED
#define _lora_mesh_v1_NodeCapability_MAX lora_mesh_v1_NodeCapability_NODE_CAPABILITY_MOBILE_UNIT
#define _lora_mesh_v1_NodeCapability_ARRAYSIZE ((lora_mesh_v1_NodeCapability)(lora_mesh_v1_NodeCapability_NODE_CAPABILITY_MOBILE_UNIT+1))

#define lora_mesh_v1_RouteRequestPayload_flags_ENUMTYPE lora_mesh_v1_RouteRequestFlags
#define lora_mesh_v1_RouteRequestPayload_metric_preference_ENUMTYPE lora_mesh_v1_RouteMetricPreference

#define lora_mesh_v1_RouteReplyPayload_flags_ENUMTYPE lora_mesh_v1_RouteReplyFlags

#define lora_mesh_v1_RouteErrorPayload_error_cause_ENUMTYPE lora_mesh_v1_RouteErrorCause

#define lora_mesh_v1_UnreachableDestination_failure_reason_ENUMTYPE lora_mesh_v1_RouteErrorCause

#define lora_mesh_v1_QoSRequirements_priority_ENUMTYPE lora_mesh_v1_MessagePriority


#define lora_mesh_v1_ServiceAdvertisement_service_type_ENUMTYPE lora_mesh_v1_ServiceType


#define lora_mesh_v1_NodeCapabilities_capabilities_ENUMTYPE lora_mesh_v1_NodeCapability
#define lora_mesh_v1_NodeCapabilities_supported_messages_ENUMTYPE lora_mesh_v1_MessageType
#define lora_mesh_v1_NodeCapabilities_supported_routing_ENUMTYPE lora_mesh_v1_RoutingStrategy


/* Initializer values for message structs */
#define lora_mesh_v1_RouteRequestPayload_init_default {0, "", 0, "", 0, 0, 0, 0, 0, _lora_mesh_v1_RouteRequestFlags_MIN, _lora_mesh_v1_RouteMetricPreference_MIN, 0, 0, {{NULL}, NULL}, false, lora_mesh_v1_QoSRequirements_init_default}
#define lora_mesh_v1_RouteReplyPayload_init_default {"", 0, "", 0, 0, 0, 0, _lora_mesh_v1_RouteReplyFlags_MIN, false, lora_mesh_v1_RouteQualityMetrics_init_default, 0, {lora_mesh_v1_AlternateRoute_init_default, lora_mesh_v1_AlternateRoute_init_default, lora_mesh_v1_AlternateRoute_init_default, lora_mesh_v1_AlternateRoute_init_default}, "", 0}
#define lora_mesh_v1_RouteErrorPayload_init_default {0, {lora_mesh_v1_UnreachableDestination_init_default, lora_mesh_v1_UnreachableDestination_init_default, lora_mesh_v1_UnreachableDestination_init_default, lora_mesh_v1_UnreachableDestination_init_default, lora_mesh_v1_UnreachableDestination_init_default, lora_mesh_v1_UnreachableDestination_init_default, lora_mesh_v1_UnreachableDestination_init_default, lora_mesh_v1_UnreachableDestination_init_default}, "", _lora_mesh_v1_RouteErrorCause_MIN, 0, 0, 0, 0}
#define lora_mesh_v1_UnreachableDestination_init_default {"", 0, "", _lora_mesh_v1_RouteErrorCause_MIN}
#define lora_mesh_v1_QoSRequirements_init_default {0, 0, 0, 0, 0, _lora_mesh_v1_MessagePriority_MIN}
#define lora_mesh_v1_LinkStateAdvertisementPayload_init_default {"", 0, 0, {lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default, lora_mesh_v1_NeighborInfo_init_default}, false, lora_mesh_v1_GPSCoordinate_init_default, false, lora_mesh_v1_TopologyMetrics_init_default, 0, 0, 0, {lora_mesh_v1_ServiceAdvertisement_init_default, lora_mesh_v1_ServiceAdvertisement_init_default, lora_mesh_v1_ServiceAdvertisement_init_default, lora_mesh_v1_ServiceAdvertisement_init_default, lora_mesh_v1_ServiceAdvertisement_init_default, lora_mesh_v1_ServiceAdvertisement_init_default, lora_mesh_v1_ServiceAdvertisement_init_default, lora_mesh_v1_ServiceAdvertisement_init_default}, false, lora_mesh_v1_NodeCapabilities_init_default, 0}
#define lora_mesh_v1_ServiceAdvertisement_init_default {"", _lora_mesh_v1_ServiceType_MIN, "", {{NULL}, NULL}, false, lora_mesh_v1_ServiceQuality_init_default, 0, 0}
#define lora_mesh_v1_ServiceQuality_init_default {0, 0, 0, 0, 0}
#define lora_mesh_v1_NodeCapabilities_init_default {0, {_lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN}, 0, 0, 0, {_lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN}, 0, {_lora_mesh_v1_RoutingStrategy_MIN, _lora_mesh_v1_RoutingStrategy_MIN, _lora_mesh_v1_RoutingStrategy_MIN, _lora_mesh_v1_RoutingStrategy_MIN}, 0, 0, 0, 0, 0}
#define lora_mesh_v1_RouteRequestPayload_init_zero {0, "", 0, "", 0, 0, 0, 0, 0, _lora_mesh_v1_RouteRequestFlags_MIN, _lora_mesh_v1_RouteMetricPreference_MIN, 0, 0, {{NULL}, NULL}, false, lora_mesh_v1_QoSRequirements_init_zero}
#define lora_mesh_v1_RouteReplyPayload_init_zero {"", 0, "", 0, 0, 0, 0, _lora_mesh_v1_RouteReplyFlags_MIN, false, lora_mesh_v1_RouteQualityMetrics_init_zero, 0, {lora_mesh_v1_AlternateRoute_init_zero, lora_mesh_v1_AlternateRoute_init_zero, lora_mesh_v1_AlternateRoute_init_zero, lora_mesh_v1_AlternateRoute_init_zero}, "", 0}
#define lora_mesh_v1_RouteErrorPayload_init_zero {0, {lora_mesh_v1_UnreachableDestination_init_zero, lora_mesh_v1_UnreachableDestination_init_zero, lora_mesh_v1_UnreachableDestination_init_zero, lora_mesh_v1_UnreachableDestination_init_zero, lora_mesh_v1_UnreachableDestination_init_zero, lora_mesh_v1_UnreachableDestination_init_zero, lora_mesh_v1_UnreachableDestination_init_zero, lora_mesh_v1_UnreachableDestination_init_zero}, "", _lora_mesh_v1_RouteErrorCause_MIN, 0, 0, 0, 0}
#define lora_mesh_v1_UnreachableDestination_init_zero {"", 0, "", _lora_mesh_v1_RouteErrorCause_MIN}
#define lora_mesh_v1_QoSRequirements_init_zero   {0, 0, 0, 0, 0, _lora_mesh_v1_MessagePriority_MIN}
#define lora_mesh_v1_LinkStateAdvertisementPayload_init_zero {"", 0, 0, {lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero, lora_mesh_v1_NeighborInfo_init_zero}, false, lora_mesh_v1_GPSCoordinate_init_zero, false, lora_mesh_v1_TopologyMetrics_init_zero, 0, 0, 0, {lora_mesh_v1_ServiceAdvertisement_init_zero, lora_mesh_v1_ServiceAdvertisement_init_zero, lora_mesh_v1_ServiceAdvertisement_init_zero, lora_mesh_v1_ServiceAdvertisement_init_zero, lora_mesh_v1_ServiceAdvertisement_init_zero, lora_mesh_v1_ServiceAdvertisement_init_zero, lora_mesh_v1_ServiceAdvertisement_init_zero, lora_mesh_v1_ServiceAdvertisement_init_zero}, false, lora_mesh_v1_NodeCapabilities_init_zero, 0}
#define lora_mesh_v1_ServiceAdvertisement_init_zero {"", _lora_mesh_v1_ServiceType_MIN, "", {{NULL}, NULL}, false, lora_mesh_v1_ServiceQuality_init_zero, 0, 0}
#define lora_mesh_v1_ServiceQuality_init_zero    {0, 0, 0, 0, 0}
#define lora_mesh_v1_NodeCapabilities_init_zero  {0, {_lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN, _lora_mesh_v1_NodeCapability_MIN}, 0, 0, 0, {_lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN, _lora_mesh_v1_MessageType_MIN}, 0, {_lora_mesh_v1_RoutingStrategy_MIN, _lora_mesh_v1_RoutingStrategy_MIN, _lora_mesh_v1_RoutingStrategy_MIN, _lora_mesh_v1_RoutingStrategy_MIN}, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define lora_mesh_v1_RouteReplyPayload_destination_id_tag 1
#define lora_mesh_v1_RouteReplyPayload_destination_sequence_number_tag 2
#define lora_mesh_v1_RouteReplyPayload_originator_id_tag 3
#define lora_mesh_v1_RouteReplyPayload_hop_count_tag 4
#define lora_mesh_v1_RouteReplyPayload_lifetime_ms_tag 5
#define lora_mesh_v1_RouteReplyPayload_source_port_tag 6
#define lora_mesh_v1_RouteReplyPayload_destination_port_tag 7
#define lora_mesh_v1_RouteReplyPayload_flags_tag 8
#define lora_mesh_v1_RouteReplyPayload_route_metrics_tag 9
#define lora_mesh_v1_RouteReplyPayload_alternate_routes_tag 10
#define lora_mesh_v1_RouteReplyPayload_replying_node_tag 11
#define lora_mesh_v1_RouteReplyPayload_reply_timestamp_tag 12
#define lora_mesh_v1_UnreachableDestination_destination_id_tag 1
#define lora_mesh_v1_UnreachableDestination_destination_sequence_number_tag 2
#define lora_mesh_v1_UnreachableDestination_failed_next_hop_tag 3
#define lora_mesh_v1_UnreachableDestination_failure_reason_tag 4
#define lora_mesh_v1_RouteErrorPayload_unreachable_destinations_tag 1
#define lora_mesh_v1_RouteErrorPayload_reporting_node_tag 2
#define lora_mesh_v1_RouteErrorPayload_error_cause_tag 3
#define lora_mesh_v1_RouteErrorPayload_error_timestamp_tag 4
#define lora_mesh_v1_RouteErrorPayload_affected_message_count_tag 5
#define lora_mesh_v1_RouteErrorPayload_source_port_tag 6
#define lora_mesh_v1_RouteErrorPayload_destination_port_tag 7
#define lora_mesh_v1_QoSRequirements_max_delay_ms_tag 1
#define lora_mesh_v1_QoSRequirements_min_bandwidth_kbps_tag 2
#define lora_mesh_v1_QoSRequirements_max_loss_rate_tag 3
#define lora_mesh_v1_QoSRequirements_min_reliability_tag 4
#define lora_mesh_v1_QoSRequirements_max_energy_cost_tag 5
#define lora_mesh_v1_QoSRequirements_priority_tag 6
#define lora_mesh_v1_RouteRequestPayload_rreq_id_tag 1
#define lora_mesh_v1_RouteRequestPayload_originator_id_tag 2
#define lora_mesh_v1_RouteRequestPayload_originator_sequence_number_tag 3
#define lora_mesh_v1_RouteRequestPayload_destination_id_tag 4
#define lora_mesh_v1_RouteRequestPayload_destination_sequence_number_tag 5
#define lora_mesh_v1_RouteRequestPayload_hop_count_tag 6
#define lora_mesh_v1_RouteRequestPayload_broadcast_id_tag 7
#define lora_mesh_v1_RouteRequestPayload_source_port_tag 8
#define lora_mesh_v1_RouteRequestPayload_destination_port_tag 9
#define lora_mesh_v1_RouteRequestPayload_flags_tag 10
#define lora_mesh_v1_RouteRequestPayload_metric_preference_tag 11
#define lora_mesh_v1_RouteRequestPayload_max_hop_limit_tag 12
#define lora_mesh_v1_RouteRequestPayload_discovery_timeout_tag 13
#define lora_mesh_v1_RouteRequestPayload_excluded_nodes_tag 14
#define lora_mesh_v1_RouteRequestPayload_qos_requirements_tag 15
#define lora_mesh_v1_ServiceQuality_availability_tag 1
#define lora_mesh_v1_ServiceQuality_response_time_ms_tag 2
#define lora_mesh_v1_ServiceQuality_throughput_kbps_tag 3
#define lora_mesh_v1_ServiceQuality_concurrent_capacity_tag 4
#define lora_mesh_v1_ServiceQuality_reliability_tag 5
#define lora_mesh_v1_ServiceAdvertisement_service_name_tag 1
#define lora_mesh_v1_ServiceAdvertisement_service_type_tag 2
#define lora_mesh_v1_ServiceAdvertisement_service_id_tag 3
#define lora_mesh_v1_ServiceAdvertisement_endpoints_tag 4
#define lora_mesh_v1_ServiceAdvertisement_quality_tag 5
#define lora_mesh_v1_ServiceAdvertisement_capacity_tag 6
#define lora_mesh_v1_ServiceAdvertisement_requires_auth_tag 7
#define lora_mesh_v1_NodeCapabilities_capabilities_tag 1
#define lora_mesh_v1_NodeCapabilities_max_hop_relay_tag 2
#define lora_mesh_v1_NodeCapabilities_max_message_size_tag 3
#define lora_mesh_v1_NodeCapabilities_supported_messages_tag 4
#define lora_mesh_v1_NodeCapabilities_supported_routing_tag 5
#define lora_mesh_v1_NodeCapabilities_has_gps_tag 6
#define lora_mesh_v1_NodeCapabilities_has_internet_tag 7
#define lora_mesh_v1_NodeCapabilities_is_mobile_tag 8
#define lora_mesh_v1_NodeCapabilities_battery_capacity_wh_tag 9
#define lora_mesh_v1_NodeCapabilities_radio_power_dbm_tag 10
#define lora_mesh_v1_LinkStateAdvertisementPayload_originator_id_tag 1
#define lora_mesh_v1_LinkStateAdvertisementPayload_sequence_number_tag 2
#define lora_mesh_v1_LinkStateAdvertisementPayload_neighbors_tag 3
#define lora_mesh_v1_LinkStateAdvertisementPayload_gps_position_tag 4
#define lora_mesh_v1_LinkStateAdvertisementPayload_local_metrics_tag 5
#define lora_mesh_v1_LinkStateAdvertisementPayload_lsa_timestamp_tag 6
#define lora_mesh_v1_LinkStateAdvertisementPayload_lsa_lifetime_ms_tag 7
#define lora_mesh_v1_LinkStateAdvertisementPayload_services_tag 8
#define lora_mesh_v1_LinkStateAdvertisementPayload_capabilities_tag 9
#define lora_mesh_v1_LinkStateAdvertisementPayload_mobility_factor_tag 10

/* Struct field encoding specification for nanopb */
#define lora_mesh_v1_RouteRequestPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   rreq_id,           1) \
X(a, STATIC,   SINGULAR, STRING,   originator_id,     2) \
X(a, STATIC,   SINGULAR, UINT32,   originator_sequence_number,   3) \
X(a, STATIC,   SINGULAR, STRING,   destination_id,    4) \
X(a, STATIC,   SINGULAR, UINT32,   destination_sequence_number,   5) \
X(a, STATIC,   SINGULAR, UINT32,   hop_count,         6) \
X(a, STATIC,   SINGULAR, UINT32,   broadcast_id,      7) \
X(a, STATIC,   SINGULAR, UINT32,   source_port,       8) \
X(a, STATIC,   SINGULAR, UINT32,   destination_port,   9) \
X(a, STATIC,   SINGULAR, UENUM,    flags,            10) \
X(a, STATIC,   SINGULAR, UENUM,    metric_preference,  11) \
X(a, STATIC,   SINGULAR, UINT32,   max_hop_limit,    12) \
X(a, STATIC,   SINGULAR, UINT64,   discovery_timeout,  13) \
X(a, CALLBACK, REPEATED, STRING,   excluded_nodes,   14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  qos_requirements,  15)
#define lora_mesh_v1_RouteRequestPayload_CALLBACK pb_default_field_callback
#define lora_mesh_v1_RouteRequestPayload_DEFAULT NULL
#define lora_mesh_v1_RouteRequestPayload_qos_requirements_MSGTYPE lora_mesh_v1_QoSRequirements

#define lora_mesh_v1_RouteReplyPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   destination_id,    1) \
X(a, STATIC,   SINGULAR, UINT32,   destination_sequence_number,   2) \
X(a, STATIC,   SINGULAR, STRING,   originator_id,     3) \
X(a, STATIC,   SINGULAR, UINT32,   hop_count,         4) \
X(a, STATIC,   SINGULAR, UINT32,   lifetime_ms,       5) \
X(a, STATIC,   SINGULAR, UINT32,   source_port,       6) \
X(a, STATIC,   SINGULAR, UINT32,   destination_port,   7) \
X(a, STATIC,   SINGULAR, UENUM,    flags,             8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  route_metrics,     9) \
X(a, STATIC,   REPEATED, MESSAGE,  alternate_routes,  10) \
X(a, STATIC,   SINGULAR, STRING,   replying_node,    11) \
X(a, STATIC,   SINGULAR, UINT64,   reply_timestamp,  12)
#define lora_mesh_v1_RouteReplyPayload_CALLBACK NULL
#define lora_mesh_v1_RouteReplyPayload_DEFAULT NULL
#define lora_mesh_v1_RouteReplyPayload_route_metrics_MSGTYPE lora_mesh_v1_RouteQualityMetrics
#define lora_mesh_v1_RouteReplyPayload_alternate_routes_MSGTYPE lora_mesh_v1_AlternateRoute

#define lora_mesh_v1_RouteErrorPayload_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  unreachable_destinations,   1) \
X(a, STATIC,   SINGULAR, STRING,   reporting_node,    2) \
X(a, STATIC,   SINGULAR, UENUM,    error_cause,       3) \
X(a, STATIC,   SINGULAR, UINT64,   error_timestamp,   4) \
X(a, STATIC,   SINGULAR, UINT32,   affected_message_count,   5) \
X(a, STATIC,   SINGULAR, UINT32,   source_port,       6) \
X(a, STATIC,   SINGULAR, UINT32,   destination_port,   7)
#define lora_mesh_v1_RouteErrorPayload_CALLBACK NULL
#define lora_mesh_v1_RouteErrorPayload_DEFAULT NULL
#define lora_mesh_v1_RouteErrorPayload_unreachable_destinations_MSGTYPE lora_mesh_v1_UnreachableDestination

#define lora_mesh_v1_UnreachableDestination_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   destination_id,    1) \
X(a, STATIC,   SINGULAR, UINT32,   destination_sequence_number,   2) \
X(a, STATIC,   SINGULAR, STRING,   failed_next_hop,   3) \
X(a, STATIC,   SINGULAR, UENUM,    failure_reason,    4)
#define lora_mesh_v1_UnreachableDestination_CALLBACK NULL
#define lora_mesh_v1_UnreachableDestination_DEFAULT NULL

#define lora_mesh_v1_QoSRequirements_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    max_delay_ms,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    min_bandwidth_kbps,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    max_loss_rate,     3) \
X(a, STATIC,   SINGULAR, FLOAT,    min_reliability,   4) \
X(a, STATIC,   SINGULAR, UINT32,   max_energy_cost,   5) \
X(a, STATIC,   SINGULAR, UENUM,    priority,          6)
#define lora_mesh_v1_QoSRequirements_CALLBACK NULL
#define lora_mesh_v1_QoSRequirements_DEFAULT NULL

#define lora_mesh_v1_LinkStateAdvertisementPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   originator_id,     1) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,   2) \
X(a, STATIC,   REPEATED, MESSAGE,  neighbors,         3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps_position,      4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  local_metrics,     5) \
X(a, STATIC,   SINGULAR, UINT64,   lsa_timestamp,     6) \
X(a, STATIC,   SINGULAR, UINT32,   lsa_lifetime_ms,   7) \
X(a, STATIC,   REPEATED, MESSAGE,  services,          8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  capabilities,      9) \
X(a, STATIC,   SINGULAR, FLOAT,    mobility_factor,  10)
#define lora_mesh_v1_LinkStateAdvertisementPayload_CALLBACK NULL
#define lora_mesh_v1_LinkStateAdvertisementPayload_DEFAULT NULL
#define lora_mesh_v1_LinkStateAdvertisementPayload_neighbors_MSGTYPE lora_mesh_v1_NeighborInfo
#define lora_mesh_v1_LinkStateAdvertisementPayload_gps_position_MSGTYPE lora_mesh_v1_GPSCoordinate
#define lora_mesh_v1_LinkStateAdvertisementPayload_local_metrics_MSGTYPE lora_mesh_v1_TopologyMetrics
#define lora_mesh_v1_LinkStateAdvertisementPayload_services_MSGTYPE lora_mesh_v1_ServiceAdvertisement
#define lora_mesh_v1_LinkStateAdvertisementPayload_capabilities_MSGTYPE lora_mesh_v1_NodeCapabilities

#define lora_mesh_v1_ServiceAdvertisement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   service_name,      1) \
X(a, STATIC,   SINGULAR, UENUM,    service_type,      2) \
X(a, STATIC,   SINGULAR, STRING,   service_id,        3) \
X(a, CALLBACK, REPEATED, STRING,   endpoints,         4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  quality,           5) \
X(a, STATIC,   SINGULAR, UINT32,   capacity,          6) \
X(a, STATIC,   SINGULAR, BOOL,     requires_auth,     7)
#define lora_mesh_v1_ServiceAdvertisement_CALLBACK pb_default_field_callback
#define lora_mesh_v1_ServiceAdvertisement_DEFAULT NULL
#define lora_mesh_v1_ServiceAdvertisement_quality_MSGTYPE lora_mesh_v1_ServiceQuality

#define lora_mesh_v1_ServiceQuality_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    availability,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    response_time_ms,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    throughput_kbps,   3) \
X(a, STATIC,   SINGULAR, UINT32,   concurrent_capacity,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    reliability,       5)
#define lora_mesh_v1_ServiceQuality_CALLBACK NULL
#define lora_mesh_v1_ServiceQuality_DEFAULT NULL

#define lora_mesh_v1_NodeCapabilities_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UENUM,    capabilities,      1) \
X(a, STATIC,   SINGULAR, UINT32,   max_hop_relay,     2) \
X(a, STATIC,   SINGULAR, UINT32,   max_message_size,   3) \
X(a, STATIC,   REPEATED, UENUM,    supported_messages,   4) \
X(a, STATIC,   REPEATED, UENUM,    supported_routing,   5) \
X(a, STATIC,   SINGULAR, BOOL,     has_gps,           6) \
X(a, STATIC,   SINGULAR, BOOL,     has_internet,      7) \
X(a, STATIC,   SINGULAR, BOOL,     is_mobile,         8) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_capacity_wh,   9) \
X(a, STATIC,   SINGULAR, UINT32,   radio_power_dbm,  10)
#define lora_mesh_v1_NodeCapabilities_CALLBACK NULL
#define lora_mesh_v1_NodeCapabilities_DEFAULT NULL

extern const pb_msgdesc_t lora_mesh_v1_RouteRequestPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_RouteReplyPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_RouteErrorPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_UnreachableDestination_msg;
extern const pb_msgdesc_t lora_mesh_v1_QoSRequirements_msg;
extern const pb_msgdesc_t lora_mesh_v1_LinkStateAdvertisementPayload_msg;
extern const pb_msgdesc_t lora_mesh_v1_ServiceAdvertisement_msg;
extern const pb_msgdesc_t lora_mesh_v1_ServiceQuality_msg;
extern const pb_msgdesc_t lora_mesh_v1_NodeCapabilities_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lora_mesh_v1_RouteRequestPayload_fields &lora_mesh_v1_RouteRequestPayload_msg
#define lora_mesh_v1_RouteReplyPayload_fields &lora_mesh_v1_RouteReplyPayload_msg
#define lora_mesh_v1_RouteErrorPayload_fields &lora_mesh_v1_RouteErrorPayload_msg
#define lora_mesh_v1_UnreachableDestination_fields &lora_mesh_v1_UnreachableDestination_msg
#define lora_mesh_v1_QoSRequirements_fields &lora_mesh_v1_QoSRequirements_msg
#define lora_mesh_v1_LinkStateAdvertisementPayload_fields &lora_mesh_v1_LinkStateAdvertisementPayload_msg
#define lora_mesh_v1_ServiceAdvertisement_fields &lora_mesh_v1_ServiceAdvertisement_msg
#define lora_mesh_v1_ServiceQuality_fields &lora_mesh_v1_ServiceQuality_msg
#define lora_mesh_v1_NodeCapabilities_fields &lora_mesh_v1_NodeCapabilities_msg

/* Maximum encoded size of messages (where known) */
/* lora_mesh_v1_RouteRequestPayload_size depends on runtime parameters */
/* lora_mesh_v1_LinkStateAdvertisementPayload_size depends on runtime parameters */
/* lora_mesh_v1_ServiceAdvertisement_size depends on runtime parameters */
#define LORA_MESH_V1_V1_ROUTING_PB_H_MAX_SIZE    lora_mesh_v1_RouteErrorPayload_size
#define lora_mesh_v1_NodeCapabilities_size       85
#define lora_mesh_v1_QoSRequirements_size        28
#define lora_mesh_v1_RouteErrorPayload_size      400
#define lora_mesh_v1_RouteReplyPayload_size      285
#define lora_mesh_v1_ServiceQuality_size         26
#define lora_mesh_v1_UnreachableDestination_size 42

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
