/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "v1/serial.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(lora_mesh_v1_SerialPacket, lora_mesh_v1_SerialPacket, 2)


PB_BIND(lora_mesh_v1_ToDevice, lora_mesh_v1_ToDevice, AUTO)


PB_BIND(lora_mesh_v1_FromDevice, lora_mesh_v1_FromDevice, 2)


PB_BIND(lora_mesh_v1_GetInfoRequest, lora_mesh_v1_GetInfoRequest, AUTO)


PB_BIND(lora_mesh_v1_GetGPSRequest, lora_mesh_v1_GetGPSRequest, AUTO)


PB_BIND(lora_mesh_v1_GetNeighborsRequest, lora_mesh_v1_GetNeighborsRequest, AUTO)


PB_BIND(lora_mesh_v1_GetRoutesRequest, lora_mesh_v1_GetRoutesRequest, AUTO)


PB_BIND(lora_mesh_v1_GetRosterRequest, lora_mesh_v1_GetRosterRequest, AUTO)


PB_BIND(lora_mesh_v1_GetStatsRequest, lora_mesh_v1_GetStatsRequest, AUTO)


PB_BIND(lora_mesh_v1_SetGPSRequest, lora_mesh_v1_SetGPSRequest, AUTO)


PB_BIND(lora_mesh_v1_SetNodeIDRequest, lora_mesh_v1_SetNodeIDRequest, AUTO)


PB_BIND(lora_mesh_v1_SendMessageRequest, lora_mesh_v1_SendMessageRequest, AUTO)


PB_BIND(lora_mesh_v1_SendGPSRequest, lora_mesh_v1_SendGPSRequest, AUTO)


PB_BIND(lora_mesh_v1_SendEmergencyRequest, lora_mesh_v1_SendEmergencyRequest, AUTO)


PB_BIND(lora_mesh_v1_DiscoverRequest, lora_mesh_v1_DiscoverRequest, AUTO)


PB_BIND(lora_mesh_v1_JoinRequest, lora_mesh_v1_JoinRequest, AUTO)


PB_BIND(lora_mesh_v1_PingRequest, lora_mesh_v1_PingRequest, AUTO)


PB_BIND(lora_mesh_v1_GetInfoResponse, lora_mesh_v1_GetInfoResponse, AUTO)


PB_BIND(lora_mesh_v1_GetGPSResponse, lora_mesh_v1_GetGPSResponse, AUTO)


PB_BIND(lora_mesh_v1_GetNeighborsResponse, lora_mesh_v1_GetNeighborsResponse, 2)


PB_BIND(lora_mesh_v1_RouteEntry, lora_mesh_v1_RouteEntry, AUTO)


PB_BIND(lora_mesh_v1_GetRoutesResponse, lora_mesh_v1_GetRoutesResponse, 2)


PB_BIND(lora_mesh_v1_RosterEntry, lora_mesh_v1_RosterEntry, AUTO)


PB_BIND(lora_mesh_v1_GetRosterResponse, lora_mesh_v1_GetRosterResponse, 2)


PB_BIND(lora_mesh_v1_GetStatsResponse, lora_mesh_v1_GetStatsResponse, AUTO)


PB_BIND(lora_mesh_v1_CommandResult, lora_mesh_v1_CommandResult, AUTO)


PB_BIND(lora_mesh_v1_MessageReceivedEvent, lora_mesh_v1_MessageReceivedEvent, 2)


PB_BIND(lora_mesh_v1_GPSReceivedEvent, lora_mesh_v1_GPSReceivedEvent, AUTO)


PB_BIND(lora_mesh_v1_NeighborChangedEvent, lora_mesh_v1_NeighborChangedEvent, AUTO)


PB_BIND(lora_mesh_v1_EmergencyReceivedEvent, lora_mesh_v1_EmergencyReceivedEvent, AUTO)


PB_BIND(lora_mesh_v1_LogEvent, lora_mesh_v1_LogEvent, AUTO)







