/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LORA_MESH_V1_V1_SERIAL_PB_H_INCLUDED
#define PB_LORA_MESH_V1_V1_SERIAL_PB_H_INCLUDED
#include <pb.h>
#include "v1/common.pb.h"
#include "v1/messages.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _lora_mesh_v1_NeighborChangedEvent_ChangeType {
    lora_mesh_v1_NeighborChangedEvent_ChangeType_JOINED = 0,
    lora_mesh_v1_NeighborChangedEvent_ChangeType_LEFT = 1,
    lora_mesh_v1_NeighborChangedEvent_ChangeType_UPDATED = 2
} lora_mesh_v1_NeighborChangedEvent_ChangeType;

typedef enum _lora_mesh_v1_LogEvent_LogLevel {
    lora_mesh_v1_LogEvent_LogLevel_DEBUG = 0,
    lora_mesh_v1_LogEvent_LogLevel_INFO = 1,
    lora_mesh_v1_LogEvent_LogLevel_WARNING = 2,
    lora_mesh_v1_LogEvent_LogLevel_ERROR = 3
} lora_mesh_v1_LogEvent_LogLevel;

/* Struct definitions */
typedef struct _lora_mesh_v1_GetInfoRequest {
    char dummy_field;
} lora_mesh_v1_GetInfoRequest;

typedef struct _lora_mesh_v1_GetGPSRequest {
    char dummy_field;
} lora_mesh_v1_GetGPSRequest;

typedef struct _lora_mesh_v1_GetNeighborsRequest {
    char dummy_field;
} lora_mesh_v1_GetNeighborsRequest;

typedef struct _lora_mesh_v1_GetRoutesRequest {
    char dummy_field;
} lora_mesh_v1_GetRoutesRequest;

typedef struct _lora_mesh_v1_GetRosterRequest {
    char dummy_field;
} lora_mesh_v1_GetRosterRequest;

typedef struct _lora_mesh_v1_GetStatsRequest {
    char dummy_field;
} lora_mesh_v1_GetStatsRequest;

typedef struct _lora_mesh_v1_SetGPSRequest {
    bool has_position;
    lora_mesh_v1_GPSCoordinate position; /* Reuse common.proto GPSCoordinate */
    bool use_static; /* Use as static position */
} lora_mesh_v1_SetGPSRequest;

typedef struct _lora_mesh_v1_SetNodeIDRequest {
    char node_id[16];
} lora_mesh_v1_SetNodeIDRequest;

typedef struct _lora_mesh_v1_SendMessageRequest {
    char destination[16]; /* Node ID or "BROADCAST" */
    char text[200];
} lora_mesh_v1_SendMessageRequest;

typedef struct _lora_mesh_v1_SendGPSRequest {
    char dummy_field;
} lora_mesh_v1_SendGPSRequest;

typedef struct _lora_mesh_v1_SendEmergencyRequest {
    lora_mesh_v1_EmergencyType emergency_type; /* Reuse from messages.proto */
    char description[100];
} lora_mesh_v1_SendEmergencyRequest;

typedef struct _lora_mesh_v1_DiscoverRequest {
    char dummy_field;
} lora_mesh_v1_DiscoverRequest;

typedef struct _lora_mesh_v1_JoinRequest {
    char dummy_field;
} lora_mesh_v1_JoinRequest;

typedef struct _lora_mesh_v1_PingRequest {
    char destination[16];
} lora_mesh_v1_PingRequest;

/* Commands from host to device */
typedef struct _lora_mesh_v1_ToDevice {
    pb_size_t which_command;
    union {
        /* Information queries */
        lora_mesh_v1_GetInfoRequest get_info;
        lora_mesh_v1_GetGPSRequest get_gps;
        lora_mesh_v1_GetNeighborsRequest get_neighbors;
        lora_mesh_v1_GetRoutesRequest get_routes;
        lora_mesh_v1_GetRosterRequest get_roster;
        lora_mesh_v1_GetStatsRequest get_stats;
        /* Configuration */
        lora_mesh_v1_SetGPSRequest set_gps;
        lora_mesh_v1_SetNodeIDRequest set_node_id;
        /* Actions */
        lora_mesh_v1_SendMessageRequest send_message;
        lora_mesh_v1_SendGPSRequest send_gps;
        lora_mesh_v1_SendEmergencyRequest send_emergency;
        lora_mesh_v1_DiscoverRequest discover;
        lora_mesh_v1_JoinRequest join;
        lora_mesh_v1_PingRequest ping;
    } command;
} lora_mesh_v1_ToDevice;

typedef struct _lora_mesh_v1_GetInfoResponse {
    bool has_node_info;
    lora_mesh_v1_NodeInfo node_info; /* Reuse common.proto NodeInfo */
    char firmware_version[16];
    char protocol_version[8];
    uint64_t mesh_version;
    uint32_t neighbor_count;
    uint32_t route_count;
    uint64_t uptime_ms;
} lora_mesh_v1_GetInfoResponse;

typedef struct _lora_mesh_v1_GetGPSResponse {
    bool has_fix;
    bool has_position;
    lora_mesh_v1_GPSCoordinate position; /* Reuse common.proto GPSCoordinate */
    uint32_t satellites;
    float hdop;
} lora_mesh_v1_GetGPSResponse;

typedef struct _lora_mesh_v1_GetNeighborsResponse {
    pb_size_t neighbors_count;
    lora_mesh_v1_NodeInfo neighbors[16]; /* Reuse common.proto NodeInfo */
} lora_mesh_v1_GetNeighborsResponse;

typedef struct _lora_mesh_v1_RouteEntry {
    char destination[16];
    char next_hop[16];
    uint32_t hop_count;
    int32_t rssi;
    uint64_t last_update;
} lora_mesh_v1_RouteEntry;

typedef struct _lora_mesh_v1_GetRoutesResponse {
    pb_size_t routes_count;
    lora_mesh_v1_RouteEntry routes[32];
} lora_mesh_v1_GetRoutesResponse;

typedef struct _lora_mesh_v1_RosterEntry {
    bool has_node;
    lora_mesh_v1_NodeInfo node; /* Reuse common.proto NodeInfo */
    bool is_self;
    bool is_active;
} lora_mesh_v1_RosterEntry;

typedef struct _lora_mesh_v1_GetRosterResponse {
    pb_size_t roster_count;
    lora_mesh_v1_RosterEntry roster[32];
} lora_mesh_v1_GetRosterResponse;

typedef struct _lora_mesh_v1_GetStatsResponse {
    uint64_t messages_sent;
    uint64_t messages_received;
    uint64_t messages_forwarded;
    uint64_t messages_dropped;
    uint64_t route_discoveries;
    uint64_t route_errors;
    uint64_t mesh_version;
    uint64_t uptime_ms;
} lora_mesh_v1_GetStatsResponse;

typedef struct _lora_mesh_v1_CommandResult {
    bool success;
    char error[100];
    char message_id[36]; /* For send operations */
} lora_mesh_v1_CommandResult;

typedef struct _lora_mesh_v1_MessageReceivedEvent {
    char from[16];
    char message_id[36];
    char text[200];
    uint64_t timestamp;
    bool is_broadcast;
} lora_mesh_v1_MessageReceivedEvent;

typedef struct _lora_mesh_v1_GPSReceivedEvent {
    char node_id[16];
    bool has_position;
    lora_mesh_v1_GPSCoordinate position; /* Reuse common.proto GPSCoordinate */
} lora_mesh_v1_GPSReceivedEvent;

typedef struct _lora_mesh_v1_NeighborChangedEvent {
    lora_mesh_v1_NeighborChangedEvent_ChangeType change_type;
    bool has_neighbor;
    lora_mesh_v1_NodeInfo neighbor; /* Reuse common.proto NodeInfo */
} lora_mesh_v1_NeighborChangedEvent;

typedef struct _lora_mesh_v1_EmergencyReceivedEvent {
    char from[16];
    lora_mesh_v1_EmergencyType emergency_type; /* Reuse from messages.proto */
    char description[100];
    bool has_position;
    lora_mesh_v1_GPSCoordinate position; /* Reuse common.proto GPSCoordinate */
} lora_mesh_v1_EmergencyReceivedEvent;

typedef struct _lora_mesh_v1_LogEvent {
    lora_mesh_v1_LogEvent_LogLevel level;
    char message[200];
    uint64_t timestamp;
} lora_mesh_v1_LogEvent;

/* Responses and events from device to host */
typedef struct _lora_mesh_v1_FromDevice {
    pb_size_t which_payload;
    union {
        /* Responses to queries */
        lora_mesh_v1_GetInfoResponse info;
        lora_mesh_v1_GetGPSResponse gps;
        lora_mesh_v1_GetNeighborsResponse neighbors;
        lora_mesh_v1_GetRoutesResponse routes;
        lora_mesh_v1_GetRosterResponse roster;
        lora_mesh_v1_GetStatsResponse stats;
        /* Action results */
        lora_mesh_v1_CommandResult result;
        /* Async events */
        lora_mesh_v1_MessageReceivedEvent message_received;
        lora_mesh_v1_GPSReceivedEvent gps_received;
        lora_mesh_v1_NeighborChangedEvent neighbor_changed;
        lora_mesh_v1_EmergencyReceivedEvent emergency_received;
        lora_mesh_v1_LogEvent log;
    } payload;
    uint32_t request_id; /* Matches packet_id of request (0 for events) */
} lora_mesh_v1_FromDevice;

/* Wrapper for all serial communication */
typedef struct _lora_mesh_v1_SerialPacket {
    uint32_t packet_id; /* For request/response correlation */
    pb_size_t which_payload;
    union {
        lora_mesh_v1_ToDevice to_device; /* Host -> Device commands */
        lora_mesh_v1_FromDevice from_device; /* Device -> Host responses/events */
    } payload;
} lora_mesh_v1_SerialPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _lora_mesh_v1_NeighborChangedEvent_ChangeType_MIN lora_mesh_v1_NeighborChangedEvent_ChangeType_JOINED
#define _lora_mesh_v1_NeighborChangedEvent_ChangeType_MAX lora_mesh_v1_NeighborChangedEvent_ChangeType_UPDATED
#define _lora_mesh_v1_NeighborChangedEvent_ChangeType_ARRAYSIZE ((lora_mesh_v1_NeighborChangedEvent_ChangeType)(lora_mesh_v1_NeighborChangedEvent_ChangeType_UPDATED+1))

#define _lora_mesh_v1_LogEvent_LogLevel_MIN lora_mesh_v1_LogEvent_LogLevel_DEBUG
#define _lora_mesh_v1_LogEvent_LogLevel_MAX lora_mesh_v1_LogEvent_LogLevel_ERROR
#define _lora_mesh_v1_LogEvent_LogLevel_ARRAYSIZE ((lora_mesh_v1_LogEvent_LogLevel)(lora_mesh_v1_LogEvent_LogLevel_ERROR+1))














#define lora_mesh_v1_SendEmergencyRequest_emergency_type_ENUMTYPE lora_mesh_v1_EmergencyType















#define lora_mesh_v1_NeighborChangedEvent_change_type_ENUMTYPE lora_mesh_v1_NeighborChangedEvent_ChangeType

#define lora_mesh_v1_EmergencyReceivedEvent_emergency_type_ENUMTYPE lora_mesh_v1_EmergencyType

#define lora_mesh_v1_LogEvent_level_ENUMTYPE lora_mesh_v1_LogEvent_LogLevel


/* Initializer values for message structs */
#define lora_mesh_v1_SerialPacket_init_default   {0, 0, {lora_mesh_v1_ToDevice_init_default}}
#define lora_mesh_v1_ToDevice_init_default       {0, {lora_mesh_v1_GetInfoRequest_init_default}}
#define lora_mesh_v1_FromDevice_init_default     {0, {lora_mesh_v1_GetInfoResponse_init_default}, 0}
#define lora_mesh_v1_GetInfoRequest_init_default {0}
#define lora_mesh_v1_GetGPSRequest_init_default  {0}
#define lora_mesh_v1_GetNeighborsRequest_init_default {0}
#define lora_mesh_v1_GetRoutesRequest_init_default {0}
#define lora_mesh_v1_GetRosterRequest_init_default {0}
#define lora_mesh_v1_GetStatsRequest_init_default {0}
#define lora_mesh_v1_SetGPSRequest_init_default  {false, lora_mesh_v1_GPSCoordinate_init_default, 0}
#define lora_mesh_v1_SetNodeIDRequest_init_default {""}
#define lora_mesh_v1_SendMessageRequest_init_default {"", ""}
#define lora_mesh_v1_SendGPSRequest_init_default {0}
#define lora_mesh_v1_SendEmergencyRequest_init_default {_lora_mesh_v1_EmergencyType_MIN, ""}
#define lora_mesh_v1_DiscoverRequest_init_default {0}
#define lora_mesh_v1_JoinRequest_init_default    {0}
#define lora_mesh_v1_PingRequest_init_default    {""}
#define lora_mesh_v1_GetInfoResponse_init_default {false, lora_mesh_v1_NodeInfo_init_default, "", "", 0, 0, 0, 0}
#define lora_mesh_v1_GetGPSResponse_init_default {0, false, lora_mesh_v1_GPSCoordinate_init_default, 0, 0}
#define lora_mesh_v1_GetNeighborsResponse_init_default {0, {lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default, lora_mesh_v1_NodeInfo_init_default}}
#define lora_mesh_v1_RouteEntry_init_default     {"", "", 0, 0, 0}
#define lora_mesh_v1_GetRoutesResponse_init_default {0, {lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default, lora_mesh_v1_RouteEntry_init_default}}
#define lora_mesh_v1_RosterEntry_init_default    {false, lora_mesh_v1_NodeInfo_init_default, 0, 0}
#define lora_mesh_v1_GetRosterResponse_init_default {0, {lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default, lora_mesh_v1_RosterEntry_init_default}}
#define lora_mesh_v1_GetStatsResponse_init_default {0, 0, 0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_CommandResult_init_default  {0, "", ""}
#define lora_mesh_v1_MessageReceivedEvent_init_default {"", "", "", 0, 0}
#define lora_mesh_v1_GPSReceivedEvent_init_default {"", false, lora_mesh_v1_GPSCoordinate_init_default}
#define lora_mesh_v1_NeighborChangedEvent_init_default {_lora_mesh_v1_NeighborChangedEvent_ChangeType_MIN, false, lora_mesh_v1_NodeInfo_init_default}
#define lora_mesh_v1_EmergencyReceivedEvent_init_default {"", _lora_mesh_v1_EmergencyType_MIN, "", false, lora_mesh_v1_GPSCoordinate_init_default}
#define lora_mesh_v1_LogEvent_init_default       {_lora_mesh_v1_LogEvent_LogLevel_MIN, "", 0}
#define lora_mesh_v1_SerialPacket_init_zero      {0, 0, {lora_mesh_v1_ToDevice_init_zero}}
#define lora_mesh_v1_ToDevice_init_zero          {0, {lora_mesh_v1_GetInfoRequest_init_zero}}
#define lora_mesh_v1_FromDevice_init_zero        {0, {lora_mesh_v1_GetInfoResponse_init_zero}, 0}
#define lora_mesh_v1_GetInfoRequest_init_zero    {0}
#define lora_mesh_v1_GetGPSRequest_init_zero     {0}
#define lora_mesh_v1_GetNeighborsRequest_init_zero {0}
#define lora_mesh_v1_GetRoutesRequest_init_zero  {0}
#define lora_mesh_v1_GetRosterRequest_init_zero  {0}
#define lora_mesh_v1_GetStatsRequest_init_zero   {0}
#define lora_mesh_v1_SetGPSRequest_init_zero     {false, lora_mesh_v1_GPSCoordinate_init_zero, 0}
#define lora_mesh_v1_SetNodeIDRequest_init_zero  {""}
#define lora_mesh_v1_SendMessageRequest_init_zero {"", ""}
#define lora_mesh_v1_SendGPSRequest_init_zero    {0}
#define lora_mesh_v1_SendEmergencyRequest_init_zero {_lora_mesh_v1_EmergencyType_MIN, ""}
#define lora_mesh_v1_DiscoverRequest_init_zero   {0}
#define lora_mesh_v1_JoinRequest_init_zero       {0}
#define lora_mesh_v1_PingRequest_init_zero       {""}
#define lora_mesh_v1_GetInfoResponse_init_zero   {false, lora_mesh_v1_NodeInfo_init_zero, "", "", 0, 0, 0, 0}
#define lora_mesh_v1_GetGPSResponse_init_zero    {0, false, lora_mesh_v1_GPSCoordinate_init_zero, 0, 0}
#define lora_mesh_v1_GetNeighborsResponse_init_zero {0, {lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero, lora_mesh_v1_NodeInfo_init_zero}}
#define lora_mesh_v1_RouteEntry_init_zero        {"", "", 0, 0, 0}
#define lora_mesh_v1_GetRoutesResponse_init_zero {0, {lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero, lora_mesh_v1_RouteEntry_init_zero}}
#define lora_mesh_v1_RosterEntry_init_zero       {false, lora_mesh_v1_NodeInfo_init_zero, 0, 0}
#define lora_mesh_v1_GetRosterResponse_init_zero {0, {lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero, lora_mesh_v1_RosterEntry_init_zero}}
#define lora_mesh_v1_GetStatsResponse_init_zero  {0, 0, 0, 0, 0, 0, 0, 0}
#define lora_mesh_v1_CommandResult_init_zero     {0, "", ""}
#define lora_mesh_v1_MessageReceivedEvent_init_zero {"", "", "", 0, 0}
#define lora_mesh_v1_GPSReceivedEvent_init_zero  {"", false, lora_mesh_v1_GPSCoordinate_init_zero}
#define lora_mesh_v1_NeighborChangedEvent_init_zero {_lora_mesh_v1_NeighborChangedEvent_ChangeType_MIN, false, lora_mesh_v1_NodeInfo_init_zero}
#define lora_mesh_v1_EmergencyReceivedEvent_init_zero {"", _lora_mesh_v1_EmergencyType_MIN, "", false, lora_mesh_v1_GPSCoordinate_init_zero}
#define lora_mesh_v1_LogEvent_init_zero          {_lora_mesh_v1_LogEvent_LogLevel_MIN, "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define lora_mesh_v1_SetGPSRequest_position_tag  1
#define lora_mesh_v1_SetGPSRequest_use_static_tag 2
#define lora_mesh_v1_SetNodeIDRequest_node_id_tag 1
#define lora_mesh_v1_SendMessageRequest_destination_tag 1
#define lora_mesh_v1_SendMessageRequest_text_tag 2
#define lora_mesh_v1_SendEmergencyRequest_emergency_type_tag 1
#define lora_mesh_v1_SendEmergencyRequest_description_tag 2
#define lora_mesh_v1_PingRequest_destination_tag 1
#define lora_mesh_v1_ToDevice_get_info_tag       1
#define lora_mesh_v1_ToDevice_get_gps_tag        2
#define lora_mesh_v1_ToDevice_get_neighbors_tag  3
#define lora_mesh_v1_ToDevice_get_routes_tag     4
#define lora_mesh_v1_ToDevice_get_roster_tag     5
#define lora_mesh_v1_ToDevice_get_stats_tag      6
#define lora_mesh_v1_ToDevice_set_gps_tag        10
#define lora_mesh_v1_ToDevice_set_node_id_tag    11
#define lora_mesh_v1_ToDevice_send_message_tag   20
#define lora_mesh_v1_ToDevice_send_gps_tag       21
#define lora_mesh_v1_ToDevice_send_emergency_tag 22
#define lora_mesh_v1_ToDevice_discover_tag       23
#define lora_mesh_v1_ToDevice_join_tag           24
#define lora_mesh_v1_ToDevice_ping_tag           25
#define lora_mesh_v1_GetInfoResponse_node_info_tag 1
#define lora_mesh_v1_GetInfoResponse_firmware_version_tag 2
#define lora_mesh_v1_GetInfoResponse_protocol_version_tag 3
#define lora_mesh_v1_GetInfoResponse_mesh_version_tag 4
#define lora_mesh_v1_GetInfoResponse_neighbor_count_tag 5
#define lora_mesh_v1_GetInfoResponse_route_count_tag 6
#define lora_mesh_v1_GetInfoResponse_uptime_ms_tag 7
#define lora_mesh_v1_GetGPSResponse_has_fix_tag  1
#define lora_mesh_v1_GetGPSResponse_position_tag 2
#define lora_mesh_v1_GetGPSResponse_satellites_tag 3
#define lora_mesh_v1_GetGPSResponse_hdop_tag     4
#define lora_mesh_v1_GetNeighborsResponse_neighbors_tag 1
#define lora_mesh_v1_RouteEntry_destination_tag  1
#define lora_mesh_v1_RouteEntry_next_hop_tag     2
#define lora_mesh_v1_RouteEntry_hop_count_tag    3
#define lora_mesh_v1_RouteEntry_rssi_tag         4
#define lora_mesh_v1_RouteEntry_last_update_tag  5
#define lora_mesh_v1_GetRoutesResponse_routes_tag 1
#define lora_mesh_v1_RosterEntry_node_tag        1
#define lora_mesh_v1_RosterEntry_is_self_tag     2
#define lora_mesh_v1_RosterEntry_is_active_tag   3
#define lora_mesh_v1_GetRosterResponse_roster_tag 1
#define lora_mesh_v1_GetStatsResponse_messages_sent_tag 1
#define lora_mesh_v1_GetStatsResponse_messages_received_tag 2
#define lora_mesh_v1_GetStatsResponse_messages_forwarded_tag 3
#define lora_mesh_v1_GetStatsResponse_messages_dropped_tag 4
#define lora_mesh_v1_GetStatsResponse_route_discoveries_tag 5
#define lora_mesh_v1_GetStatsResponse_route_errors_tag 6
#define lora_mesh_v1_GetStatsResponse_mesh_version_tag 7
#define lora_mesh_v1_GetStatsResponse_uptime_ms_tag 8
#define lora_mesh_v1_CommandResult_success_tag   1
#define lora_mesh_v1_CommandResult_error_tag     2
#define lora_mesh_v1_CommandResult_message_id_tag 3
#define lora_mesh_v1_MessageReceivedEvent_from_tag 1
#define lora_mesh_v1_MessageReceivedEvent_message_id_tag 2
#define lora_mesh_v1_MessageReceivedEvent_text_tag 3
#define lora_mesh_v1_MessageReceivedEvent_timestamp_tag 4
#define lora_mesh_v1_MessageReceivedEvent_is_broadcast_tag 5
#define lora_mesh_v1_GPSReceivedEvent_node_id_tag 1
#define lora_mesh_v1_GPSReceivedEvent_position_tag 2
#define lora_mesh_v1_NeighborChangedEvent_change_type_tag 1
#define lora_mesh_v1_NeighborChangedEvent_neighbor_tag 2
#define lora_mesh_v1_EmergencyReceivedEvent_from_tag 1
#define lora_mesh_v1_EmergencyReceivedEvent_emergency_type_tag 2
#define lora_mesh_v1_EmergencyReceivedEvent_description_tag 3
#define lora_mesh_v1_EmergencyReceivedEvent_position_tag 4
#define lora_mesh_v1_LogEvent_level_tag          1
#define lora_mesh_v1_LogEvent_message_tag        2
#define lora_mesh_v1_LogEvent_timestamp_tag      3
#define lora_mesh_v1_FromDevice_info_tag         1
#define lora_mesh_v1_FromDevice_gps_tag          2
#define lora_mesh_v1_FromDevice_neighbors_tag    3
#define lora_mesh_v1_FromDevice_routes_tag       4
#define lora_mesh_v1_FromDevice_roster_tag       5
#define lora_mesh_v1_FromDevice_stats_tag        6
#define lora_mesh_v1_FromDevice_result_tag       10
#define lora_mesh_v1_FromDevice_message_received_tag 20
#define lora_mesh_v1_FromDevice_gps_received_tag 21
#define lora_mesh_v1_FromDevice_neighbor_changed_tag 22
#define lora_mesh_v1_FromDevice_emergency_received_tag 23
#define lora_mesh_v1_FromDevice_log_tag          24
#define lora_mesh_v1_FromDevice_request_id_tag   100
#define lora_mesh_v1_SerialPacket_packet_id_tag  1
#define lora_mesh_v1_SerialPacket_to_device_tag  2
#define lora_mesh_v1_SerialPacket_from_device_tag 3

/* Struct field encoding specification for nanopb */
#define lora_mesh_v1_SerialPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   packet_id,         1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,to_device,payload.to_device),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,from_device,payload.from_device),   3)
#define lora_mesh_v1_SerialPacket_CALLBACK NULL
#define lora_mesh_v1_SerialPacket_DEFAULT NULL
#define lora_mesh_v1_SerialPacket_payload_to_device_MSGTYPE lora_mesh_v1_ToDevice
#define lora_mesh_v1_SerialPacket_payload_from_device_MSGTYPE lora_mesh_v1_FromDevice

#define lora_mesh_v1_ToDevice_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,get_info,command.get_info),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,get_gps,command.get_gps),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,get_neighbors,command.get_neighbors),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,get_routes,command.get_routes),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,get_roster,command.get_roster),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,get_stats,command.get_stats),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_gps,command.set_gps),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_node_id,command.set_node_id),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,send_message,command.send_message),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,send_gps,command.send_gps),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,send_emergency,command.send_emergency),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,discover,command.discover),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,join,command.join),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,ping,command.ping),  25)
#define lora_mesh_v1_ToDevice_CALLBACK NULL
#define lora_mesh_v1_ToDevice_DEFAULT NULL
#define lora_mesh_v1_ToDevice_command_get_info_MSGTYPE lora_mesh_v1_GetInfoRequest
#define lora_mesh_v1_ToDevice_command_get_gps_MSGTYPE lora_mesh_v1_GetGPSRequest
#define lora_mesh_v1_ToDevice_command_get_neighbors_MSGTYPE lora_mesh_v1_GetNeighborsRequest
#define lora_mesh_v1_ToDevice_command_get_routes_MSGTYPE lora_mesh_v1_GetRoutesRequest
#define lora_mesh_v1_ToDevice_command_get_roster_MSGTYPE lora_mesh_v1_GetRosterRequest
#define lora_mesh_v1_ToDevice_command_get_stats_MSGTYPE lora_mesh_v1_GetStatsRequest
#define lora_mesh_v1_ToDevice_command_set_gps_MSGTYPE lora_mesh_v1_SetGPSRequest
#define lora_mesh_v1_ToDevice_command_set_node_id_MSGTYPE lora_mesh_v1_SetNodeIDRequest
#define lora_mesh_v1_ToDevice_command_send_message_MSGTYPE lora_mesh_v1_SendMessageRequest
#define lora_mesh_v1_ToDevice_command_send_gps_MSGTYPE lora_mesh_v1_SendGPSRequest
#define lora_mesh_v1_ToDevice_command_send_emergency_MSGTYPE lora_mesh_v1_SendEmergencyRequest
#define lora_mesh_v1_ToDevice_command_discover_MSGTYPE lora_mesh_v1_DiscoverRequest
#define lora_mesh_v1_ToDevice_command_join_MSGTYPE lora_mesh_v1_JoinRequest
#define lora_mesh_v1_ToDevice_command_ping_MSGTYPE lora_mesh_v1_PingRequest

#define lora_mesh_v1_FromDevice_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,info,payload.info),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gps,payload.gps),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,neighbors,payload.neighbors),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,routes,payload.routes),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,roster,payload.roster),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,stats,payload.stats),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,result,payload.result),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,message_received,payload.message_received),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gps_received,payload.gps_received),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,neighbor_changed,payload.neighbor_changed),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,emergency_received,payload.emergency_received),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,log,payload.log),  24) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,      100)
#define lora_mesh_v1_FromDevice_CALLBACK NULL
#define lora_mesh_v1_FromDevice_DEFAULT NULL
#define lora_mesh_v1_FromDevice_payload_info_MSGTYPE lora_mesh_v1_GetInfoResponse
#define lora_mesh_v1_FromDevice_payload_gps_MSGTYPE lora_mesh_v1_GetGPSResponse
#define lora_mesh_v1_FromDevice_payload_neighbors_MSGTYPE lora_mesh_v1_GetNeighborsResponse
#define lora_mesh_v1_FromDevice_payload_routes_MSGTYPE lora_mesh_v1_GetRoutesResponse
#define lora_mesh_v1_FromDevice_payload_roster_MSGTYPE lora_mesh_v1_GetRosterResponse
#define lora_mesh_v1_FromDevice_payload_stats_MSGTYPE lora_mesh_v1_GetStatsResponse
#define lora_mesh_v1_FromDevice_payload_result_MSGTYPE lora_mesh_v1_CommandResult
#define lora_mesh_v1_FromDevice_payload_message_received_MSGTYPE lora_mesh_v1_MessageReceivedEvent
#define lora_mesh_v1_FromDevice_payload_gps_received_MSGTYPE lora_mesh_v1_GPSReceivedEvent
#define lora_mesh_v1_FromDevice_payload_neighbor_changed_MSGTYPE lora_mesh_v1_NeighborChangedEvent
#define lora_mesh_v1_FromDevice_payload_emergency_received_MSGTYPE lora_mesh_v1_EmergencyReceivedEvent
#define lora_mesh_v1_FromDevice_payload_log_MSGTYPE lora_mesh_v1_LogEvent

#define lora_mesh_v1_GetInfoRequest_FIELDLIST(X, a) \

#define lora_mesh_v1_GetInfoRequest_CALLBACK NULL
#define lora_mesh_v1_GetInfoRequest_DEFAULT NULL

#define lora_mesh_v1_GetGPSRequest_FIELDLIST(X, a) \

#define lora_mesh_v1_GetGPSRequest_CALLBACK NULL
#define lora_mesh_v1_GetGPSRequest_DEFAULT NULL

#define lora_mesh_v1_GetNeighborsRequest_FIELDLIST(X, a) \

#define lora_mesh_v1_GetNeighborsRequest_CALLBACK NULL
#define lora_mesh_v1_GetNeighborsRequest_DEFAULT NULL

#define lora_mesh_v1_GetRoutesRequest_FIELDLIST(X, a) \

#define lora_mesh_v1_GetRoutesRequest_CALLBACK NULL
#define lora_mesh_v1_GetRoutesRequest_DEFAULT NULL

#define lora_mesh_v1_GetRosterRequest_FIELDLIST(X, a) \

#define lora_mesh_v1_GetRosterRequest_CALLBACK NULL
#define lora_mesh_v1_GetRosterRequest_DEFAULT NULL

#define lora_mesh_v1_GetStatsRequest_FIELDLIST(X, a) \

#define lora_mesh_v1_GetStatsRequest_CALLBACK NULL
#define lora_mesh_v1_GetStatsRequest_DEFAULT NULL

#define lora_mesh_v1_SetGPSRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          1) \
X(a, STATIC,   SINGULAR, BOOL,     use_static,        2)
#define lora_mesh_v1_SetGPSRequest_CALLBACK NULL
#define lora_mesh_v1_SetGPSRequest_DEFAULT NULL
#define lora_mesh_v1_SetGPSRequest_position_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_SetNodeIDRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1)
#define lora_mesh_v1_SetNodeIDRequest_CALLBACK NULL
#define lora_mesh_v1_SetNodeIDRequest_DEFAULT NULL

#define lora_mesh_v1_SendMessageRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   destination,       1) \
X(a, STATIC,   SINGULAR, STRING,   text,              2)
#define lora_mesh_v1_SendMessageRequest_CALLBACK NULL
#define lora_mesh_v1_SendMessageRequest_DEFAULT NULL

#define lora_mesh_v1_SendGPSRequest_FIELDLIST(X, a) \

#define lora_mesh_v1_SendGPSRequest_CALLBACK NULL
#define lora_mesh_v1_SendGPSRequest_DEFAULT NULL

#define lora_mesh_v1_SendEmergencyRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    emergency_type,    1) \
X(a, STATIC,   SINGULAR, STRING,   description,       2)
#define lora_mesh_v1_SendEmergencyRequest_CALLBACK NULL
#define lora_mesh_v1_SendEmergencyRequest_DEFAULT NULL

#define lora_mesh_v1_DiscoverRequest_FIELDLIST(X, a) \

#define lora_mesh_v1_DiscoverRequest_CALLBACK NULL
#define lora_mesh_v1_DiscoverRequest_DEFAULT NULL

#define lora_mesh_v1_JoinRequest_FIELDLIST(X, a) \

#define lora_mesh_v1_JoinRequest_CALLBACK NULL
#define lora_mesh_v1_JoinRequest_DEFAULT NULL

#define lora_mesh_v1_PingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   destination,       1)
#define lora_mesh_v1_PingRequest_CALLBACK NULL
#define lora_mesh_v1_PingRequest_DEFAULT NULL

#define lora_mesh_v1_GetInfoResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  node_info,         1) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   2) \
X(a, STATIC,   SINGULAR, STRING,   protocol_version,   3) \
X(a, STATIC,   SINGULAR, UINT64,   mesh_version,      4) \
X(a, STATIC,   SINGULAR, UINT32,   neighbor_count,    5) \
X(a, STATIC,   SINGULAR, UINT32,   route_count,       6) \
X(a, STATIC,   SINGULAR, UINT64,   uptime_ms,         7)
#define lora_mesh_v1_GetInfoResponse_CALLBACK NULL
#define lora_mesh_v1_GetInfoResponse_DEFAULT NULL
#define lora_mesh_v1_GetInfoResponse_node_info_MSGTYPE lora_mesh_v1_NodeInfo

#define lora_mesh_v1_GetGPSResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_fix,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2) \
X(a, STATIC,   SINGULAR, UINT32,   satellites,        3) \
X(a, STATIC,   SINGULAR, FLOAT,    hdop,              4)
#define lora_mesh_v1_GetGPSResponse_CALLBACK NULL
#define lora_mesh_v1_GetGPSResponse_DEFAULT NULL
#define lora_mesh_v1_GetGPSResponse_position_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_GetNeighborsResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  neighbors,         1)
#define lora_mesh_v1_GetNeighborsResponse_CALLBACK NULL
#define lora_mesh_v1_GetNeighborsResponse_DEFAULT NULL
#define lora_mesh_v1_GetNeighborsResponse_neighbors_MSGTYPE lora_mesh_v1_NodeInfo

#define lora_mesh_v1_RouteEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   destination,       1) \
X(a, STATIC,   SINGULAR, STRING,   next_hop,          2) \
X(a, STATIC,   SINGULAR, UINT32,   hop_count,         3) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              4) \
X(a, STATIC,   SINGULAR, UINT64,   last_update,       5)
#define lora_mesh_v1_RouteEntry_CALLBACK NULL
#define lora_mesh_v1_RouteEntry_DEFAULT NULL

#define lora_mesh_v1_GetRoutesResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  routes,            1)
#define lora_mesh_v1_GetRoutesResponse_CALLBACK NULL
#define lora_mesh_v1_GetRoutesResponse_DEFAULT NULL
#define lora_mesh_v1_GetRoutesResponse_routes_MSGTYPE lora_mesh_v1_RouteEntry

#define lora_mesh_v1_RosterEntry_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  node,              1) \
X(a, STATIC,   SINGULAR, BOOL,     is_self,           2) \
X(a, STATIC,   SINGULAR, BOOL,     is_active,         3)
#define lora_mesh_v1_RosterEntry_CALLBACK NULL
#define lora_mesh_v1_RosterEntry_DEFAULT NULL
#define lora_mesh_v1_RosterEntry_node_MSGTYPE lora_mesh_v1_NodeInfo

#define lora_mesh_v1_GetRosterResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  roster,            1)
#define lora_mesh_v1_GetRosterResponse_CALLBACK NULL
#define lora_mesh_v1_GetRosterResponse_DEFAULT NULL
#define lora_mesh_v1_GetRosterResponse_roster_MSGTYPE lora_mesh_v1_RosterEntry

#define lora_mesh_v1_GetStatsResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   messages_sent,     1) \
X(a, STATIC,   SINGULAR, UINT64,   messages_received,   2) \
X(a, STATIC,   SINGULAR, UINT64,   messages_forwarded,   3) \
X(a, STATIC,   SINGULAR, UINT64,   messages_dropped,   4) \
X(a, STATIC,   SINGULAR, UINT64,   route_discoveries,   5) \
X(a, STATIC,   SINGULAR, UINT64,   route_errors,      6) \
X(a, STATIC,   SINGULAR, UINT64,   mesh_version,      7) \
X(a, STATIC,   SINGULAR, UINT64,   uptime_ms,         8)
#define lora_mesh_v1_GetStatsResponse_CALLBACK NULL
#define lora_mesh_v1_GetStatsResponse_DEFAULT NULL

#define lora_mesh_v1_CommandResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, STRING,   message_id,        3)
#define lora_mesh_v1_CommandResult_CALLBACK NULL
#define lora_mesh_v1_CommandResult_DEFAULT NULL

#define lora_mesh_v1_MessageReceivedEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   from,              1) \
X(a, STATIC,   SINGULAR, STRING,   message_id,        2) \
X(a, STATIC,   SINGULAR, STRING,   text,              3) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         4) \
X(a, STATIC,   SINGULAR, BOOL,     is_broadcast,      5)
#define lora_mesh_v1_MessageReceivedEvent_CALLBACK NULL
#define lora_mesh_v1_MessageReceivedEvent_DEFAULT NULL

#define lora_mesh_v1_GPSReceivedEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2)
#define lora_mesh_v1_GPSReceivedEvent_CALLBACK NULL
#define lora_mesh_v1_GPSReceivedEvent_DEFAULT NULL
#define lora_mesh_v1_GPSReceivedEvent_position_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_NeighborChangedEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    change_type,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  neighbor,          2)
#define lora_mesh_v1_NeighborChangedEvent_CALLBACK NULL
#define lora_mesh_v1_NeighborChangedEvent_DEFAULT NULL
#define lora_mesh_v1_NeighborChangedEvent_neighbor_MSGTYPE lora_mesh_v1_NodeInfo

#define lora_mesh_v1_EmergencyReceivedEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   from,              1) \
X(a, STATIC,   SINGULAR, UENUM,    emergency_type,    2) \
X(a, STATIC,   SINGULAR, STRING,   description,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          4)
#define lora_mesh_v1_EmergencyReceivedEvent_CALLBACK NULL
#define lora_mesh_v1_EmergencyReceivedEvent_DEFAULT NULL
#define lora_mesh_v1_EmergencyReceivedEvent_position_MSGTYPE lora_mesh_v1_GPSCoordinate

#define lora_mesh_v1_LogEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    level,             1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         3)
#define lora_mesh_v1_LogEvent_CALLBACK NULL
#define lora_mesh_v1_LogEvent_DEFAULT NULL

extern const pb_msgdesc_t lora_mesh_v1_SerialPacket_msg;
extern const pb_msgdesc_t lora_mesh_v1_ToDevice_msg;
extern const pb_msgdesc_t lora_mesh_v1_FromDevice_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetInfoRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetGPSRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetNeighborsRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetRoutesRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetRosterRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetStatsRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_SetGPSRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_SetNodeIDRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_SendMessageRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_SendGPSRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_SendEmergencyRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_DiscoverRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_JoinRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_PingRequest_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetInfoResponse_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetGPSResponse_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetNeighborsResponse_msg;
extern const pb_msgdesc_t lora_mesh_v1_RouteEntry_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetRoutesResponse_msg;
extern const pb_msgdesc_t lora_mesh_v1_RosterEntry_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetRosterResponse_msg;
extern const pb_msgdesc_t lora_mesh_v1_GetStatsResponse_msg;
extern const pb_msgdesc_t lora_mesh_v1_CommandResult_msg;
extern const pb_msgdesc_t lora_mesh_v1_MessageReceivedEvent_msg;
extern const pb_msgdesc_t lora_mesh_v1_GPSReceivedEvent_msg;
extern const pb_msgdesc_t lora_mesh_v1_NeighborChangedEvent_msg;
extern const pb_msgdesc_t lora_mesh_v1_EmergencyReceivedEvent_msg;
extern const pb_msgdesc_t lora_mesh_v1_LogEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lora_mesh_v1_SerialPacket_fields &lora_mesh_v1_SerialPacket_msg
#define lora_mesh_v1_ToDevice_fields &lora_mesh_v1_ToDevice_msg
#define lora_mesh_v1_FromDevice_fields &lora_mesh_v1_FromDevice_msg
#define lora_mesh_v1_GetInfoRequest_fields &lora_mesh_v1_GetInfoRequest_msg
#define lora_mesh_v1_GetGPSRequest_fields &lora_mesh_v1_GetGPSRequest_msg
#define lora_mesh_v1_GetNeighborsRequest_fields &lora_mesh_v1_GetNeighborsRequest_msg
#define lora_mesh_v1_GetRoutesRequest_fields &lora_mesh_v1_GetRoutesRequest_msg
#define lora_mesh_v1_GetRosterRequest_fields &lora_mesh_v1_GetRosterRequest_msg
#define lora_mesh_v1_GetStatsRequest_fields &lora_mesh_v1_GetStatsRequest_msg
#define lora_mesh_v1_SetGPSRequest_fields &lora_mesh_v1_SetGPSRequest_msg
#define lora_mesh_v1_SetNodeIDRequest_fields &lora_mesh_v1_SetNodeIDRequest_msg
#define lora_mesh_v1_SendMessageRequest_fields &lora_mesh_v1_SendMessageRequest_msg
#define lora_mesh_v1_SendGPSRequest_fields &lora_mesh_v1_SendGPSRequest_msg
#define lora_mesh_v1_SendEmergencyRequest_fields &lora_mesh_v1_SendEmergencyRequest_msg
#define lora_mesh_v1_DiscoverRequest_fields &lora_mesh_v1_DiscoverRequest_msg
#define lora_mesh_v1_JoinRequest_fields &lora_mesh_v1_JoinRequest_msg
#define lora_mesh_v1_PingRequest_fields &lora_mesh_v1_PingRequest_msg
#define lora_mesh_v1_GetInfoResponse_fields &lora_mesh_v1_GetInfoResponse_msg
#define lora_mesh_v1_GetGPSResponse_fields &lora_mesh_v1_GetGPSResponse_msg
#define lora_mesh_v1_GetNeighborsResponse_fields &lora_mesh_v1_GetNeighborsResponse_msg
#define lora_mesh_v1_RouteEntry_fields &lora_mesh_v1_RouteEntry_msg
#define lora_mesh_v1_GetRoutesResponse_fields &lora_mesh_v1_GetRoutesResponse_msg
#define lora_mesh_v1_RosterEntry_fields &lora_mesh_v1_RosterEntry_msg
#define lora_mesh_v1_GetRosterResponse_fields &lora_mesh_v1_GetRosterResponse_msg
#define lora_mesh_v1_GetStatsResponse_fields &lora_mesh_v1_GetStatsResponse_msg
#define lora_mesh_v1_CommandResult_fields &lora_mesh_v1_CommandResult_msg
#define lora_mesh_v1_MessageReceivedEvent_fields &lora_mesh_v1_MessageReceivedEvent_msg
#define lora_mesh_v1_GPSReceivedEvent_fields &lora_mesh_v1_GPSReceivedEvent_msg
#define lora_mesh_v1_NeighborChangedEvent_fields &lora_mesh_v1_NeighborChangedEvent_msg
#define lora_mesh_v1_EmergencyReceivedEvent_fields &lora_mesh_v1_EmergencyReceivedEvent_msg
#define lora_mesh_v1_LogEvent_fields &lora_mesh_v1_LogEvent_msg

/* Maximum encoded size of messages (where known) */
#define LORA_MESH_V1_V1_SERIAL_PB_H_MAX_SIZE     lora_mesh_v1_SerialPacket_size
#define lora_mesh_v1_CommandResult_size          140
#define lora_mesh_v1_DiscoverRequest_size        0
#define lora_mesh_v1_EmergencyReceivedEvent_size 171
#define lora_mesh_v1_FromDevice_size             3530
#define lora_mesh_v1_GPSReceivedEvent_size       68
#define lora_mesh_v1_GetGPSRequest_size          0
#define lora_mesh_v1_GetGPSResponse_size         64
#define lora_mesh_v1_GetInfoRequest_size         0
#define lora_mesh_v1_GetInfoResponse_size        164
#define lora_mesh_v1_GetNeighborsRequest_size    0
#define lora_mesh_v1_GetNeighborsResponse_size   1664
#define lora_mesh_v1_GetRosterRequest_size       0
#define lora_mesh_v1_GetRosterResponse_size      3520
#define lora_mesh_v1_GetRoutesRequest_size       0
#define lora_mesh_v1_GetRoutesResponse_size      2048
#define lora_mesh_v1_GetStatsRequest_size        0
#define lora_mesh_v1_GetStatsResponse_size       88
#define lora_mesh_v1_JoinRequest_size            0
#define lora_mesh_v1_LogEvent_size               215
#define lora_mesh_v1_MessageReceivedEvent_size   269
#define lora_mesh_v1_NeighborChangedEvent_size   106
#define lora_mesh_v1_PingRequest_size            17
#define lora_mesh_v1_RosterEntry_size            108
#define lora_mesh_v1_RouteEntry_size             62
#define lora_mesh_v1_SendEmergencyRequest_size   103
#define lora_mesh_v1_SendGPSRequest_size         0
#define lora_mesh_v1_SendMessageRequest_size     219
#define lora_mesh_v1_SerialPacket_size           3539
#define lora_mesh_v1_SetGPSRequest_size          53
#define lora_mesh_v1_SetNodeIDRequest_size       17
#define lora_mesh_v1_ToDevice_size               223

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
